### PR TITLE
Fix subview of zero-sized arrays

### PR DESCRIPTION
**Pull request by hvy**
A sub-view of a zero-sized array (e.g. a sub-view of shape `(2, 0)` of an array one that has a shape of `(7. 0)`) should always have an offset of 0. Having a non-zero offset would yield an invalid address when for instance creating a new array based on it.

In short, this fix was missing for ChainerX.
https://github.com/cupy/cupy/blob/master/cupy/core/_routines_indexing.pyx#L322-L323

~_TODO: Need to add tests._~ Done.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
