### PR TITLE
Fix regex of protobuf modules warned by Python 3.7

### LINKED ISSUE #5688: Protobuf is still warned after #5514
```
% COLUMNS=80 pytest -m 'not gpu and not ideep' chainer_tests/exporters_tests
============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir: /Users/tos/GitHub/chainer, inifile: setup.cfg
collected 0 items / 2 errors

==================================== ERRORS ====================================
______ ERROR collecting tests/chainer_tests/exporters_tests/test_caffe.py ______
chainer_tests/exporters_tests/test_caffe.py:7: in <module>
    from chainer.exporters import caffe
../chainer/exporters/__init__.py:1: in <module>
    from chainer.exporters import caffe  # NOQA
../chainer/exporters/caffe.py:11: in <module>
    from chainer.links.caffe.protobuf3 import caffe_pb2 as caffe_pb
../chainer/links/caffe/__init__.py:1: in <module>
    from chainer.links.caffe.caffe_function import CaffeFunction  # NOQA
../chainer/links/caffe/caffe_function.py:10: in <module>
    from chainer.links.caffe.protobuf3 import caffe_pb2 as caffe_pb
../chainer/links/caffe/protobuf3/caffe_pb2.py:7: in <module>
    from google.protobuf import descriptor as _descriptor
../../../.pyenv/versions/3.7.1/envs/n/lib/python3.7/site-packages/google/protobuf/descriptor.py:40: in <module>
    from google.protobuf.internal import api_implementation
../../../.pyenv/versions/3.7.1/envs/n/lib/python3.7/site-packages/google/protobuf/internal/api_implementation.py:154: in <module>
    from google.protobuf.pyext import _message
../../../.pyenv/versions/3.7.1/lib/python3.7/collections/__init__.py:52: in __getattr__
    DeprecationWarning, stacklevel=2)
E   DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
______ ERROR collecting tests/chainer_tests/exporters_tests/test_caffe.py ______
chainer_tests/exporters_tests/test_caffe.py:7: in <module>
    from chainer.exporters import caffe
../chainer/exporters/__init__.py:1: in <module>
    from chainer.exporters import caffe  # NOQA
../chainer/exporters/caffe.py:11: in <module>
    from chainer.links.caffe.protobuf3 import caffe_pb2 as caffe_pb
../chainer/links/caffe/protobuf3/caffe_pb2.py:7: in <module>
    from google.protobuf import descriptor as _descriptor
../../../.pyenv/versions/3.7.1/envs/n/lib/python3.7/site-packages/google/protobuf/descriptor.py:40: in <module>
    from google.protobuf.internal import api_implementation
../../../.pyenv/versions/3.7.1/envs/n/lib/python3.7/site-packages/google/protobuf/internal/api_implementation.py:154: in <module>
    from google.protobuf.pyext import _message
../../../.pyenv/versions/3.7.1/lib/python3.7/collections/__init__.py:52: in __getattr__
    DeprecationWarning, stacklevel=2)
E   DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 2 error in 1.02 seconds ============================
```

### PR DESCRIPTION
**Pull request by toslunar**
Close #5688.

### CODE REVIEW

**Comment by okuta** [comment]
Please resolve conflicts.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Comment by toslunar** [comment]
Sorry, @okuta.  I've just merged #5694.

**Pull request merged**
