### PR TITLE
add document for chainer.config.lazy_grad_sum

### PR DESCRIPTION
**Pull request by kmaehashi**
Documentation for #4136.

### CODE REVIEW

**Comment by niboshi** [comment]
Please fix this error:
>chainer/docs/source/reference/configuration.rst:173: ERROR: Malformed table.

**Comment by kmaehashi** [comment]
Thanks, fixed.

**Comment by niboshi** [comment]
Maybe you forgot to push the change?

**Comment by kmaehashi** [comment]
Oh, sorry. Pushed.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
