### PR TITLE
Make `F.average` as accurate as backend

### PR DESCRIPTION
**Pull request by toslunar**
#7681 will be fixed if CPU with NumPy >= 1.12 or GPU.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
```
19:07:24  > git checkout -f d7297aabbb9557f14a284057bd9c12ef6fd07003
19:07:24 FATAL: Could not checkout d7297aabbb9557f14a284057bd9c12ef6fd07003
```
Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Pull request merged**
