### PR TITLE
Add `cached_property` decorator

### PR DESCRIPTION
**Pull request by toslunar**
This PR introduces `cached_property` decorator for `chainer.Distribution`.

The changes from the original implementation (https://pypi.org/project/cached-property/) are the following:
- Caches are stored for each `chainer.config.enable_backprop`.
- Implemented as a data descriptor.
  - Clearing caches by `del obj.attr` is not supported.
- No support for `asyncio`.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by beam2d** [comment]
How about putting `cached_property` at a more general place, e.g. `chainer.utils`? I think this utility is general and not limited to the use in `distributions`.

**Comment by toslunar** [comment]
Moved `cached_property` to `chainer.utils.cache`.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
