### PR TITLE
Revive clang-tidy test in Travis CI

### LINKED ISSUE #8048: Bring clang-tidy back to Travis CI
We have dropped Python 2 job from Travis CI. I think we have a room to bring clang-tidy back.

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #8048
Reverts #6682

### CODE REVIEW

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
@niboshi Could you check Jenkins failure?

**Comment by niboshi** [comment]
PTAL.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
