### PR TITLE
Improve iDeep version checking

### PR DESCRIPTION
**Pull request by kmaehashi**
Improve documentation and environment check for ideep (see #5592).

### CODE REVIEW

**Comment by toslunar** [comment]
Is it ok to backport `>=2.0.0.post3`, which will require updating ideep4py if an older version is installed?

**Comment by kmaehashi** [comment]
Ok, I'll make a separate PR for v4 (which requires `>=2.0.0.post1`).

**Comment by toslunar** [comment]
> for v4

for v5

Jenkins, test this please.

**Comment by kmaehashi** [comment]
Ah, I noticed that `_optional_dependencies` was finally not backported to v5. Anyway I'll send separate PR for docs to v5.

**Comment by toslunar** [comment]
The Jenkins failures are unrelated to the PR.

**Pull request merged**
