### PR TITLE
Remove ideep mixed dtype workaround in `F.batch_normalization`

### PR DESCRIPTION
**Pull request by niboshi**
See: https://github.com/chainer/chainer/pull/8175#pullrequestreview-295345169

I cannot replicate the error after the PR was merged to master.

### CODE REVIEW

**Comment by emcastillo** [comment]
Might be because of #8164?

**Comment by niboshi** [comment]
>Might be because of #8164

That's the case 😋.
(#8164 also targets `chainer_tests`.)

**Comment by niboshi** [comment]
Taken over by #8216.

**Comment by toslunar** [comment]
The combinations to replicate the error are
```
param_shape=(3,)
ndim=1
eps=*
xdtype=float64
dtype=float32
c_contiguous=True
running_statistics=*
```
https://github.com/chainer/chainer/blob/8ba9d150dbab9d4baf970e4f054b6543396cb449/tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py#L68-L76

Note that `_as_noncontiguous_array` in the file turns `ideep4py.mdarray` into `numpy.ndarray`.

**Pull request closed without merging**
