### PR TITLE
Optimize Huber loss by simpler calculation

### PR DESCRIPTION
**Pull request by grafi-tt**
Forward and backward computations of Huber loss function are optimized.

* `xp.abs` is used instead of `abs`,
* `out` arguments are aggressively used for efficient memory access,
* `chainer.function.clip` is used for the backward computation.

CUDA kernel would achieve better performance, but it is out of scope of this PR.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for the improvement!

In my benchmark, backward is faster but forward is not.
Could you check forward computation?

master
```
forward             :    55.284 us   +/- 6.720 (min:   51.980) us
backward            :   248.941 us   +/- 3.165 (min:  245.336) us         

forward             :    56.646 us   +/- 6.633 (min:   53.218) us
backward            :   254.573 us   +/-20.623 (min:  246.579) us        

forward             :    55.700 us   +/- 7.059 (min:   51.902) us
backward            :   320.981 us   +/-35.906 (min:  251.722) us
```                                                                                            

This PR
```
forward             :    59.320 us   +/- 5.454 (min:   57.041) us
backward            :   235.110 us   +/- 4.020 (min:  231.728) us

forward             :    57.420 us   +/- 4.797 (min:   55.432) us
backward            :   234.781 us   +/-21.002 (min:  226.693) us

forward             :    59.093 us   +/- 5.345 (min:   56.486) us
backward            :   238.777 us   +/- 4.667 (min:  235.268) us
```

**Comment by grafi-tt** [comment]
@niboshi Thank you for your performance evaluation! I conducted a benchmark on my Linux machine, but this PR consistently perform better than the master branch both on CPU and GPU. Could you share your benchmark?

Tested software versions are Python 3.6, CuPy 4.0.0 and CUDA 9.0. The machine has Core i5-3550 and GTX 1080Ti. My (arguably sloppy) benchmark script is as below.

```
import chainer
import cupy
import numpy
import time


def bench_gpu():
    x0 = cupy.arange(1024 * 1024, dtype=cupy.float32).reshape(1024, 1024)
    x1 = cupy.arange(1024 * 1024, dtype=cupy.float32).reshape(1024, 1024)
    time.sleep(1)

    start = cupy.cuda.Event()
    end = cupy.cuda.Event()
    start.record()
    l = chainer.functions.huber_loss(x0, x1, delta=1.)
    end.record()
    end.synchronize()
    t = cupy.cuda.get_elapsed_time(start, end)
    print(t)


def bench_cpu():
    x0 = numpy.arange(1024 * 1024, dtype=numpy.float32).reshape(1024, 1024)
    x1 = numpy.arange(1024 * 1024, dtype=numpy.float32).reshape(1024, 1024)

    start = time.perf_counter()
    l = chainer.functions.huber_loss(x0, x1, delta=1.)
    end = time.perf_counter()
    t = end - start
    print(t)


with chainer.no_backprop_mode():
    print("gpu")
    for i in range(10):
        bench_gpu()
    print("cpu")
    for i in range(10):
        bench_cpu()
```

**Comment by niboshi** [comment]
Ah, I'm sorry, I was benchmarking with very small arrays.
Now I tested with large arrays as in your benchmark, and confirmed both forward and backward computation are improved.

master
```
forward             :  8629.765 us   +/-784.995 (min: 8297.305) us
backward            : 12835.636 us   +/-1123.289 (min:12338.551) us
```
This PR (original)
```
forward             :  7343.509 us   +/-729.469 (min: 6985.093) us
backward            :  5949.416 us   +/-588.071 (min: 5639.520) us
```
This PR (https://github.com/chainer/chainer/pull/4775#issuecomment-389757286)
```
forward             :  7365.982 us   +/-662.457 (min: 7063.958) us
backward            :  5873.546 us   +/-667.226 (min: 5477.769) us
```
(I repeated measurements, and it seems this PR (original) is slightly but consistently faster than https://github.com/chainer/chainer/pull/4775#issuecomment-389757286).

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM, Thank you!

**Pull request merged**
