### PR TITLE
Add float16 and float 64 to `F.group_normalization` test

### PR DESCRIPTION
**Pull request by crcrpar**
This PR aims to complete `F.group_normalization` tests by adding np.float16 and np.float64.

Tolerance for fp16 is the same as that of `F.batch_normalization` test.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by crcrpar** [comment]
@toslunar Can I add one more commit that removes redundant empty lines in `F.group_normalization` and `L.GroupNormalization`?

**Comment by toslunar** [comment]
> @toslunar Can I add one more commit that removes redundant empty lines in `F.group_normalization` and `L.GroupNormalization`?

:+1:

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by crcrpar** [comment]
> `float16` tests are failing in an environment. Could you make `_simple_group_normalization` return an array with correct dtype? Old `numpy.sqrt` has a bug. See e.g. [#2302 (comment)](https://github.com/chainer/chainer/pull/2302#issuecomment-323258697)

I didn't know this. Thank you for pointing out.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
