### PR TITLE
Implement time trigger

### PR DESCRIPTION
**Pull request by unnonouno**
I implemented a trigger that is invoked periodically.

### CODE REVIEW

**Comment by okuta** [comment]
What happens when serialized?

**Comment by toslunar** [comment]
Why don't you use `Trainer.elapsed_time`?

**Comment by unnonouno** [comment]
@toslunar That sounds good

**Comment by okuta** [comment]
LGTM except test.
Cloud you add test?

**Comment by unnonouno** [comment]
updated

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
