### PR TITLE
[backport] Relax float16 tolerances in `F.batch_inv` test

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #7971

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
Please check CIs.

**Comment by niboshi** [comment]
Please undo the changes to `check_double_backward_options`.

**Comment by emcastillo** [comment]
Fixed, run 1000 times without issues now.

**Comment by niboshi** [comment]
Thanks
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
