### PR TITLE
Fix broken `skip` condition

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Test runs successfully, let me trigger test for #8606 first as it is a blocker for CuPy v8/v9 support.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
