### PR TITLE
Exclude eps from `running_var` of `F.batch_renormalization`

### LINKED ISSUE #7506: `eps` is doubly added to variance in inference of `L.BatchRenormalization`
- `runninng_var` learns variances with `eps`
- `train=False` mode uses `running_var + eps`

### Conditions
I tested with Chainer versions: `3.0.0`, `4.5.0`, `5.4.0`, `7.0.0a1`

### Code to reproduce
```python
import chainer
import numpy as np
np.random.seed(0)

brn = chainer.links.BatchRenormalization(3, eps=1.)
for _ in range(1000):
    x = np.random.randn(1000, 3).astype('f')
    brn(x)

x = np.random.randn(1000, 3).astype('f')

y = brn(x)
print(y.array.var(axis=0))

with chainer.using_config('train', False):
    y = brn(x)
print(y.array.var(axis=0))
```

### Error messages, stack traces, or logs
```
[0.51281106 0.49953052 0.48790243]
[0.3506052  0.33283928 0.31892547]
```

Here, the "normalized" variance is around 1/(1+eps) if train, whereas it's around 1/(1+2 eps) otherwise.

### PR DESCRIPTION
**Pull request by toslunar**
Fix #7506.

The statistics tests were unexpectedly passing because they didn't test with large `eps`.

Split from #7104.

### CODE REVIEW

**Comment by toslunar** [comment]
Done.

**Comment by toslunar** [comment]
> The statistics tests were unexpectedly passing because they didn't test with large `eps`.

Not really passing.  The test failures were buried because of other flaky tests (and `retry(3)`).  For example, https://travis-ci.org/chainer/chainer/jobs/546576170 failed:
```
_________________________ TestPopulationStatistics_param_0_{nx=10, ny=10}.test_statistics_cpu __________________________
../../../virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/parameterized.py:89: in new_method
    utils._raise_from(e.__class__, s.getvalue(), e)
../../../virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/utils/__init__.py:106: in _raise_from
    six.raise_from(new_exc.with_traceback(orig_exc.__traceback__), None)
../../../virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/parameterized.py:78: in new_method
    return base_method(self, *args, **kwargs)
../../../virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/condition.py:80: in wrapper
    fail()
../../../virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/condition.py:51: in fail
    instance.fail(msg)
E   AssertionError: Parameterized test failed.
E   
E   Base test method: TestPopulationStatistics.test_statistics_cpu
E   Test parameters:
E     nx: 10
E     ny: 10
E   
E   
E   (caused by)
E   AssertionError: 
E   Fail: 3, Success: 0
E   
E   The first error message:
E   Traceback (most recent call last):
E     File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/array.py", line 27, in assert_allclose
E       x, y, atol=atol, rtol=rtol, verbose=verbose)
E     File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/numpy/testing/_private/utils.py", line 1452, in assert_allclose
E       verbose=verbose, header=header, equal_nan=equal_nan)
E     File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
E       raise AssertionError(msg)
E   AssertionError: 
E   Not equal to tolerance rtol=0.0001, atol=1e-05
E   
E   (mismatch 33.33333333333333%)
E    x: array([0.466337, 0.150953, 0.096771], dtype=float32)
E    y: array([0.466359, 0.150975, 0.096793], dtype=float32)
E   
E   During handling of the above exception, another exception occurred:
E   
E   Traceback (most recent call last):
E     File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/condition.py", line 60, in <lambda>
E       lambda: f(ins, *args[1:], **kwargs),
E     File "/home/travis/build/chainer/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py", line 152, in test_statistics_cpu
E       self.check_statistics(self.x, self.y)
E     File "/home/travis/build/chainer/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py", line 142, in check_statistics
E       testing.assert_allclose(unbiased_var, self.link.avg_var)
E     File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/chainer/testing/array.py", line 59, in assert_allclose
E       raise AssertionError(f.getvalue())
E   AssertionError: 
E   Not equal to tolerance rtol=0.0001, atol=1e-05
E   
E   (mismatch 33.33333333333333%)
E    x: array([0.466337, 0.150953, 0.096771], dtype=float32)
E    y: array([0.466359, 0.150975, 0.096793], dtype=float32)
E   
E   assert_allclose failed: 
E     shape: (3,) (3,)
E     dtype: float32 float32
E     i: (2,)
E     x[i]: 0.09677109122276306
E     y[i]: 0.09679330885410309
E     relative error[i]: 0.00022953684674575925
E     absolute error[i]: 2.2217631340026855e-05
E   x: [0.4663368  0.15095286 0.09677109]
E   y: [0.46635902 0.15097508 0.09679331]
```

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
