### PR TITLE
Add `chainerx.softplus`

### PR DESCRIPTION
**Pull request by aksub99**
Add `chainerx.softplus`.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you so much!
Jenkins, test this please

**Comment by niboshi** [comment]
The test seems to be failed with overflow in NumPy reference implementation.
Could you fix it?

**Comment by aksub99** [comment]
Sorry, I am not able to understand why `254` is the output instead of `inf`. Could you please elaborate a bit @niboshi ? Thanks.

**Comment by niboshi** [comment]
@aksub99 
As the input value in the parameterization is `-2` and the input dtype is `uint8`, the "actual" input value passed to `Softplus()` is `254` (`uint8` bit representation of `-2`).

From the [definition of softplus](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.softplus.html), the limit of `Softplus(x, beta)` (x → ∞) is `x`, i.e. `254`. This is the expected return value.

In your numpy reference implementation, the subexpression `numpy.exp(self.beta * a)` overflows as `inf`, which should be avoided. In order to avoid that, probably you have to write the same way as in `chainerx::Softplus()`.

**Comment by aksub99** [comment]
Thanks for your detailed explanation @niboshi . I have modified the implementation similar to `chainer::Softplus` and have reduced the range of tested `beta` values to `(1, 2)` similar to the `chainer` tests for `softplus`.

**Comment by aksub99** [comment]
The failed travis tests seem to be caused by `Power` which is unrelated to this PR.

**Comment by niboshi** [comment]
Thank you for the fix.
Yes please include negative values (but not zero), as softplus is well-defined for negative beta.

**Comment by niboshi** [comment]
Please omit beta around zero. It will be unstable.

**Comment by aksub99** [comment]
Is this alright @niboshi ?

**Comment by niboshi** [comment]
Thanks! Jenkins, test this please

**Pull request merged**
