### PR TITLE
Support for float16 dtype to ChainerX linalg routines

### PR DESCRIPTION
**Pull request by IvanYashchuk**
LAPACK and cuSOLVER does not support fp16 input. NumPy raises an error as well.
With this PR, fp16 input is supported in ChainerX linalg via casting the input to fp32.

Ref. #6764

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
Travis failure is not related:
```
=============================================== short test summary info ================================================
FAIL tests/chainerx_tests/unit_tests/routines_tests/test_misc.py::test_Minimum_param_133_{is_module=False, in_dtypes=('float16', 'float16'), input_lhs='random', input_rhs='random', in_shapes=((3, 1), (2, 1, 4)), out_dtype='float16'}[native:0]
[31m[1m========================= 1 failed, 88767 passed, 84435 skipped, 41 xfailed in 1292.45 seconds =========================[0m
```

**Comment by hvy** [comment]
Thanks for the PR. The PR is conflicting and needs to be resolved but it's probably better to resolve the flaky solver routines first before introducing this change (included in this list https://github.com/chainer/chainer/issues/6903).

**Comment by hvy** [comment]
All routines in https://github.com/chainer/chainer/issues/6764 are implemented now and the flaky issues have been fixed, so it's okay to continue working on this PR!

**Comment by hvy** [comment]
For reference, CuPy is now working towards dropping fp16 support in some linalg routines to be consistent with NumPy https://github.com/cupy/cupy/issues/2553 It might reasonably apply to ChainerX as well. Do you have any comments @IvanYashchuk ?

**Comment by IvanYashchuk** [comment]
Have you seen https://github.com/numpy/numpy/issues/11690 ? and there is (not merged) PR https://github.com/numpy/numpy/pull/11697

**Comment by hvy** [comment]
Thank you for the reference, I was not aware of those ticket and it now makes sense to keep this PR open.

**Comment by Saanidhyavats** [comment]
Is this issue open? I want to contribute on this issue?

**Pull request closed without merging**
