### PR TITLE
Create links.rnn and functions.rnn

### PR DESCRIPTION
**Pull request by himkt**
Unify RNN related functionalities in (i) `functions.activation` and `links.connection`,
(ii) `functions.activation` and `functions.connection`.

issue: https://github.com/chainer/chainer/issues/7677

### CODE REVIEW

**Comment by himkt** [comment]
Jenkins, test this please.

**Comment by himkt** [comment]
Jenkins, test this please.

**Comment by himkt** [comment]
Jenkins, test this please.

**Comment by himkt** [comment]
It seems that test modules should have unique names.
Updated.

https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1576/TEST=CHAINERX_chainer-py3,label=mn1-p100/console

<details>

```
08:47:55 E   py._path.local.LocalPath.ImportMismatchError: ('test_n_step_rnn', '/repo/tests/chainer_tests/functions_tests/rnn_tests/test_n_step_rnn.py', local('/repo/tests/chainer_tests/links_tests/rnn_tests/test_n_step_rnn.py'))
08:47:55 _ ERROR collecting tests/chainer_tests/links_tests/rnn_tests/test_n_step_rnn.py _
08:47:55 import file mismatch:
08:47:55 imported module 'test_n_step_rnn' has this __file__ attribute:
08:47:55   /repo/tests/chainer_tests/functions_tests/rnn_tests/test_n_step_rnn.py
08:47:55 which is not the same as the test file we want to collect:
08:47:55   /repo/tests/chainer_tests/links_tests/rnn_tests/test_n_step_rnn.py
08:47:55 HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

</details>

**Comment by himkt** [comment]
Jenkins, test this please.

**Comment by himkt** [comment]
@emcastillo 
I revise my PR.

I'm not sure failures of jenkins are related to this PR.
Could you please take a look?

**Comment by emcastillo** [comment]
Jenkins errors are unrelated.
Will merge after release.

**Pull request merged**
