### PR TITLE
Fix `F.negative_sampling` output dtype in CPU mode

### LINKED ISSUE #5607: F.negative_sampling outputs float32 loss for any input dtypes, only in CPU mode
Version: current master b9e9267237d60b76211f42d13f80938d1b926e74

### Code to reproduce
```py
import chainer
import chainer.functions as F
import numpy
import cupy

batch_size = 2
in_size = 5
n_classes = 3
sample_size = 4

def func(xp, in_dtype, reduce):
    def sampler(shape):
        return xp.ones(shape, xp.int32)

    x_arr = xp.ones((batch_size, in_size), in_dtype)
    w_arr = xp.ones((n_classes, in_size), in_dtype)
    t_arr = xp.ones((batch_size,), numpy.int32)
    x = chainer.Variable(x_arr)
    w = chainer.Variable(w_arr)
    t = chainer.Variable(t_arr)

    y = F.negative_sampling(x, t, w, sampler, sample_size, reduce=reduce)
    print(in_dtype.__name__, ' -> ', y.dtype)


for reduce in ('sum', 'no'):
    print('*** reduce: ', reduce)
    for xp in (numpy, cupy):
        print('xp: ', xp.__name__)
        for in_dtype in (numpy.float16, numpy.float32, numpy.float64):
            func(xp, in_dtype, reduce)
    print()
```

### Result
```
*** reduce:  sum
xp:  numpy
float16  ->  float32
float32  ->  float32
float64  ->  float32
xp:  cupy
float16  ->  float16
float32  ->  float32
float64  ->  float64

*** reduce:  no
xp:  numpy
float16  ->  float16
float32  ->  float32
float64  ->  float64
xp:  cupy
float16  ->  float16
float32  ->  float32
float64  ->  float64
```

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #5607

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The failure (in the last run of Jenkins) below is unrelated to the PR.
`tests.chainer_tests.functions_tests.connection_tests.test_convolution_2d.TestConvolution2DFunction_param_25.test_forward__use_cuda_true__use_cudnn_always__cudnn_deterministic_true__autotune_true__use_ideep_never__cudnn_fast_batch_normalization_false`

**Comment by toslunar** [comment]
LGTM

**Pull request merged**
