### PR TITLE
Add hacking 1.1.0 style check to appveyor

### PR DESCRIPTION
**Pull request by toslunar**
After #4864, we will have to check OpenStack style manually.

It seemed Chainer was incompatible with hacking==1.1.0, but it seems not.  The compatibility problem between the style checkers would be solved by installing either one to each of environments.

### CODE REVIEW

**Comment by niboshi** [comment]
What's the compatibility issue?

**Comment by toslunar** [comment]
`hacking==1.1.0` and `autopep8` require incompatible versions of `pycodestyle`.
`hacking==1.0.0` requires `pep8` instead.  `pep8` has been renamed to `pycodestyle` but  these two can be `pip install`ed without any warnings.

FYI, I run `pipdeptree`:
```
autopep8==1.3.5
  - pycodestyle [required: >=2.3, installed: 2.4.0]
```
```
hacking==1.1.0
  - flake8 [required: >=2.6.0,<2.7.0, installed: 2.6.2]
    - mccabe [required: >=0.2.1,<0.6, installed: 0.2.1]
    - pycodestyle [required: >=2.0,<2.1, installed: 2.4.0]
    - pyflakes [required: >=0.8.1,<1.3,!=1.2.2,!=1.2.1,!=1.2.0, installed: 0.8.1]
  - pbr [required: >=2.0.0,!=2.1.0, installed: 4.0.2]
  - six [required: >=1.10.0, installed: 1.11.0]
```
```
hacking==1.0.0
  - flake8 [required: >=2.5.4,<2.6.0, installed: 2.5.5]
    - mccabe [required: >=0.2.1,<0.5, installed: 0.2.1]
    - pep8 [required: >=1.5.7,!=1.6.2,!=1.6.1,!=1.6.0, installed: 1.5.7]
    - pyflakes [required: >=0.8.1,<1.1, installed: 0.8.1]
  - mccabe [required: ==0.2.1, installed: 0.2.1]
  - pbr [required: >=1.8, installed: 4.0.2]
  - pep8 [required: ==1.5.7, installed: 1.5.7]
  - pyflakes [required: ==0.8.1, installed: 0.8.1]
  - six [required: >=1.9.0, installed: 1.11.0]
```

**Comment by toslunar** [comment]
Related: #4731?

**Comment by niboshi** [comment]
I see. Thank you.

But we have decided to not rely on hacking (at least tentatively).
Requing hacking could break something some day.

**Comment by kmaehashi** [comment]
I agree with niboshi-san.
Also related to #4852, I'm opposed to add misc. things on AppVeyor. It should focus on finding issues on Windows.

**Comment by toslunar** [comment]
I got it.

**Pull request closed without merging**
