### PR TITLE
skip MultiprocessIterator finalization at exit

### PR DESCRIPTION
**Pull request by grafi-tt**
Finalization routine of `MultiprocessIterator` hangs when uncaught exception is triggered. Tested with Python 3.6.6 on Linux x86_64. Even though `with` statement is generally recommended, the hang is undesirable. This PR workaround the issue by skipping `MultiprocessIterator` finalization after `atexit` hook execution.

Such type of a hang occurs if `iterator.__del__` is called when the interpreter finalizing itself. In the following program, probably the traceback held by the exception object defers `__del__` call until the interpreter finalization.

```python
import chainer

class Dataset(chainer.dataset.DatasetMixin):
    def __len__(self):
        return 100

    def get_example(self, i):
        return i

def main():
    dataset = Dataset()
    iterator = chainer.iterators.MultiprocessIterator(dataset, 16, repeat=False, shuffle=False, n_processes=8)
    for batch in iterator:
        raise RuntimeError("Err")

main()
```

### CODE REVIEW

**Comment by niboshi** [comment]
Just a cosmetic point, but I think it's better to add some comment on the declaration of `_finalized` that it should not be assigned `False` as an instance attribute (that would make the class attribute ignored).

**Comment by grafi-tt** [comment]
@niboshi Thanks. I added comments.

**Comment by Crissman** [comment]
Jenkins, test this please

**Comment by kuenishi** [comment]
I'm afraid this workaround causes regression of https://github.com/chainer/chainer/pull/4137 in case of custom loop. With Trainer it'd be ok as it finalizes iterators.

**Comment by grafi-tt** [comment]
@kuenishi Thanks. I think removing `__del__` on a major release is fine provided appropriate documents are added. It is a design choice to be made by the core team, so I couldn't make a decision.

I believe many Jupyter users create `MultiprocessIterator` instances without `with` statement just because it is faster, even though those who seriously care resource leak should already have used something like `with` statement. I think we should make enough notice if we get rid of `__del__`.

**Comment by Crissman** [comment]
LGTM. Merging.

**Comment by Crissman** [comment]
Reverted the merge to allow for discussion about removing __del__ as opposed to this fix.

**Comment by Crissman** [comment]
Discussing with the Chainer team. Will either revert this, or remove `__del__` depending on the decision. Thanks!

**Pull request merged**
