### PR TITLE
Simplify pooling with cuDNN

### PR DESCRIPTION
**Pull request by okuta**
Please merge cupy/cupy#1735 first.

### CODE REVIEW

**Comment by takagi** [comment]
Would you check CI failure on flake8?

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Would you omit 49ba65c2fb25d0f4a5653fd5a9e42fe9c1f2812f from this branch to perform CI without merging https://github.com/cupy/cupy/pull/1734 before?

**Comment by okuta** [comment]
I dropped a commit.

**Comment by takagi** [comment]
Jenkins, test this please.

**Pull request merged**
