### PR TITLE
Add `chainerx::Absolute` device implementation

### PR DESCRIPTION
**Pull request by asi1024**
Depends on #7298.

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please check the test.

**Comment by asi1024** [comment]
Fixed.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please check the test once again.

**Comment by niboshi** [comment]
Hmm, why is the last fix needed?
I think it may be slower than `std::abs`.
I didn't check the last error. How about implementing in type-dependent way?

**Comment by asi1024** [comment]
PTAL.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
I can't press the merge button...

clip

**Comment by niboshi** [comment]
Oh, now I can.

**Pull request merged**
