### PR TITLE
[backport] Fix test failure in cuDNN v7.5

### PR DESCRIPTION
**Pull request by hvy**
Backport of #6710

### CODE REVIEW

**Comment by hvy** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
`chainer.backends.cuda.libcudnn ` should be `chainer.backends.cuda.cupy.cuda.cudnn` in v5...

**Comment by hvy** [comment]
Fixed accordingly. PTAL.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
