### PR TITLE
Forbid calling empty `Sequential`

### LINKED ISSUE #6303: Empty Sequential has different semantics than other cases
As you can see from below, an empty `chainer.Sequential()` has different semantics: it wraps an argument with a tuple and return it. If at least one built-in links or functions exist, it returns a single `Variable` object.

I think it's better to forbid calling an empty `Sequential`.

#### Code
```py
import numpy
import chainer
from chainer import functions as F

x = numpy.array([1, 2], numpy.float32)
seq = chainer.Sequential()
ret = seq(x)

print(ret)
print(type(ret))
print(type(ret[0]))
print()

seq = chainer.Sequential(F.tanh)
ret = seq(x)
print(type(ret))
```
#### Result
```
(array([1., 2.], dtype=float32),)
<class 'tuple'>
<class 'numpy.ndarray'>

<class 'chainer.variable.Variable'>
```

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #6303

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
Sorry, I forgot `Test` prefix (it seems it doesn't matter, though).
Please retrigger jenkins.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
