### PR TITLE
Support device specifiers in ImageNet data parallel example

### PR DESCRIPTION
**Pull request by hvy**
Part of #6661.

~`MultiprocessParallelUpdater` does not support the new devices it seems and need to be fixed for this example to work.~ Fixed by https://github.com/chainer/chainer/pull/7245

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
This PR fixes #7291.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by hvy** [comment]
Sorry I forgot to put the `to-be-backported` label so I just did. Could you create a backport?

**Pull request merged**
