### PR TITLE
[backport] Support all float dtypes in `F.connectionist_temporal_classification`

### PR DESCRIPTION
**Pull request by takagi**
Backport of #5680

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
#5680 is followed by #5727 to fix the parameterized test that causes this CI failure, so I will make a backport PR of #5727 so that it will include the change in #5680.

**Comment by takagi** [comment]
#5680 is followed by #5727 to fix the parameterized test that causes the CI failure. I backport #5727 in this PR as well as #5680.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure seems unrelated to the PR.

**Comment by takagi** [comment]
I'll make a backport of #5928 shortly.

**Comment by toslunar** [comment]
It has been backported as #6035.

**Comment by takagi** [comment]
Okay, I saw an outdated page.

**Pull request merged**
