### PR TITLE
Add OpenMP option for cuSOLVER

### PR DESCRIPTION
**Pull request by hvy**
Fixes https://github.com/chainer/chainer/issues/7815.

### CODE REVIEW

**Comment by hvy** [comment]
@toslunar could you verify this fix locally you think?

**Comment by toslunar** [comment]
> @toslunar could you verify this fix locally you think?

Done. The fix worked in my environment.

**Comment by toslunar** [comment]
CIs, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
