### PR TITLE
[backport] Provide a cleaner way to collect threads and processes in MultiprocessIterator

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #4155

### CODE REVIEW

**Comment by kmaehashi** [comment]
Conflict for `examples/mnist/train_mnist_custom_loop.py` manually resolved. (#4470)

**Comment by okuta** [comment]
flake8
```
./examples/mnist/train_mnist_custom_loop.py:67:4: E901 IndentationError: unindent does not match any outer indentation level
./examples/mnist/train_mnist_custom_loop.py:67:70: E901 IndentationError: unindent does not match any outer indentation level
```

**Comment by okuta** [comment]
@kmaehashi Please fix style.

**Comment by kmaehashi** [comment]
@okuta ping

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
