### PR TITLE
[backport] Include platform information to `chainer.print_runtime_info()`

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #5163

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
#5271 should be backported after this PR has merged.

**Comment by okuta** [comment]
```
$ flake8
./chainer/_runtime_info.py:5:1: H306  imports not in alphabetical order (six, platform)```

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
