### PR TITLE
[WIP] Training utilities and examples using a custom training loop

### PR DESCRIPTION
**Pull request by bkvogel**
Add some training utilities for #2252. This PR currently contains a timer utility and a progress utility that can optionally display a progress bar (borrowing code with some duplication from the existing `ProgressBar`). Other utilities can be added later as separate PRs.

Additional examples of using custom training loops have been added for MNIST, CIFAR, and ptb examples.  These examples now contain both a Trainer version and a "custom training loop" version. These new examples also show how to use the new v2 `chainer.config.train` flag to disable train mode during model evaluation.

### CODE REVIEW

**Comment by delta2323** [comment]
"No compat" label is attached to this PR. But does it really break compatibility?

**Comment by bkvogel** [comment]
You are right, "no compat" was not needed so I removed it. I was initially considering to break compatibility but then decided against it.

**Comment by delta2323** [comment]
OK, thanks.

**Comment by bkvogel** [comment]
Since this did not make it into v2, I will close, update the PR and resubmit from a forked repo.

**Pull request closed without merging**
