### PR TITLE
Simplify `F.cast` test

### PR DESCRIPTION
**Pull request by hvy**
Part of https://github.com/chainer/chainer/issues/6071.

~Depends on a change in gradient check in #6621 . In particular https://github.com/chainer/chainer/pull/6621/files#diff-643267efb2f2b096c96a529d2818281dR1016~

### CODE REVIEW

**Comment by Crissman** [comment]
@hvy As I read #6071, this is no longer blocked by that PR, and ok to proceed with review and merge, correct?

**Comment by hvy** [comment]
I think the CI will fail, but haven't tested it for a while. It should depend on a change in the gradient check.

**Comment by hvy** [comment]
This PR is no longer blocked and ready for review, PTAL. Since the PR on which this PR used to depend was closed, I simply included the necessary changes in this PR instead.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
ImosCI has the same issue with `chainerx.testing`. Do we need to fix imosCI?

**Comment by hvy** [comment]
Hm, could you reproduce the same failure locally? It seems to fail only for certain environments.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Travis issue looks unrelated.

**Pull request merged**
