### PR TITLE
Add Dockerfiles for intel/chainer

### PR DESCRIPTION
**Pull request by mitmul**

### CODE REVIEW

**Comment by niboshi** [comment]
https://github.com/chainer/chainer/pull/4223/files#diff-7875ccd19cfb45549a123015e987ea60R59

We need to fix this after iDeep integration will be finished in Chainer.

**Comment by mitmul** [comment]
@niboshi Now should I progress this PR?

**Comment by niboshi** [comment]
@mitmul Yes, could you fix it?

**Comment by mitmul** [comment]
@niboshi Yes, I fiexd. Now I'm checking those Dockerfilies can correctly work.

**Comment by mitmul** [comment]
@niboshi How should I test these Dockerfile?

**Comment by niboshi** [comment]
Hmm, perhaps to run test of some function (that supports ideep) and check if `_forward_ideep` is actually called?
Btw, don't we have to install ideep4py?

**Comment by kmaehashi** [comment]
I think we just need a line of glog installation and `pip install ideep4py`.
I also think we can suspend this work as iDeep update that eliminates glog dependency and numpy version issue should be coming in near future.

**Comment by niboshi** [comment]
Let's wait for the next release of iDeep.

**Comment by niboshi** [comment]
@mitmul 
iDeep 1.0.3 has been released.
Can you update the installation script?

**Comment by niboshi** [comment]
FYI: dockerfiles in intel/ideep
https://github.com/intel/ideep/tree/ideep4py/docker

**Comment by kmaehashi** [comment]
I discussed with iDeep team in Chainer slack.

* Let's remove `centos` version of Dockerfile as it is quite similar to `ubuntu:16.04` one.
* They gave us the following simple version of Dockerfile. Let's use it.

```
FROM ubuntu:16.04
RUN apt-get update -y && \
   apt-get install -y --no-install-recommends \
   python python-pip python-dev
RUN pip install --upgrade pip setuptools
RUN pip install --default-timeout=10000 ideep4py chainer
```

I guess `--default-timeout=10000` is not needed, as download from PyPI to DockerHub infrastructure should be fast enough. I think we can remove this for now and append it later if needed (i.e. build failed on DockerHub).

**Comment by niboshi** [comment]
>I guess `--default-timeout=10000` is not needed, as download from PyPI to DockerHub infrastructure should be fast enough.

Does this apply to user environments?
I think these dockerfiles are also intended for end users.

**Comment by kmaehashi** [comment]
`--default-timeout` (equivalent to `--timeout`) is a timeout for the HTTP connection establishment , not timeout for whole download process. If we need that, we should append that to everywhere.

I think it is generally considered as internet connection issue (or pypi is down) if connection to pypi server failed for 15 seconds (the default value).

**Comment by kmaehashi** [comment]
@mitmul Shall I takeover this? I'd like to include this to the next RC.

**Comment by mitmul** [comment]
@kmaehashi Yes, please

**Comment by kmaehashi** [comment]
Moved to #4476

**Pull request closed without merging**
