### PR TITLE
Replace hacking with explicit requirements

### LINKED ISSUE #4610: Avoid hacking for coding style check
Now that contributors can install style-check tools with `pip install -e .[stylecheck]`, we no longer have to use `hacking` in order to fix the tool versions. We can have finer control over tool versions than `hacking`.

One problem of `hacking` is that it fixes to rather old versions, which means we're unable to benefit from recent bugfixes.

Another problem is that its dependency can conflict with other tools (e.g. the case in #4606).

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #4610.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Requirements are copied from https://github.com/openstack-dev/hacking/blob/1.0.0/requirements.txt

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The PR drops `Hnnn` checks:
```
% pip install -U -e '.[stylecheck]'
Obtaining file:///Users/tos/Documents/chainer
Requirement already up-to-date: filelock in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: numpy>=1.9.0 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: protobuf>=3.0.0 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: six>=1.9.0 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: autopep8 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: pbr>=1.8 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: pep8==1.5.7 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: pyflakes==0.8.1 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: flake8<2.6.0,>=2.5.4 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: mccabe==0.2.1 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from chainer==5.0.0a1)
Requirement already up-to-date: setuptools in /Users/tos/py3sandbox/lib/python3.6/site-packages (from protobuf>=3.0.0->chainer==5.0.0a1)
Requirement already up-to-date: pycodestyle>=2.3 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from autopep8->chainer==5.0.0a1)
Installing collected packages: chainer
  Running setup.py develop for chainer
Successfully installed chainer
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
% flake8 a.py
% pip install hacking
Collecting hacking
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/25/95/705a1afe3808a9fbd7dc28b5647bc9f2a1138689e47cbd9e1bd5399ded4b/hacking-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: pep8==1.5.7 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from hacking)
Requirement already satisfied: pyflakes==0.8.1 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from hacking)
Requirement already satisfied: mccabe==0.2.1 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from hacking)
Requirement already satisfied: six>=1.9.0 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from hacking)
Requirement already satisfied: flake8<2.6.0,>=2.5.4 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from hacking)
Requirement already satisfied: pbr>=1.8 in /Users/tos/py3sandbox/lib/python3.6/site-packages (from hacking)
Installing collected packages: hacking
Successfully installed hacking-1.0.0
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
% flake8 a.py
a.py:1:1: H104  File contains nothing but comments
a.py:1:3: H101  Use TODO(NAME)
% cat a.py
# TODO: todo
%
```

**Comment by niboshi** [comment]
Hmm, I confirmed, but after installing `hacking` and then `-e .[stylecheck]`, I got the errors...

```console
$ cat a.py                           
# TODO: foo                                         
$ pip install -U -e '.[stylecheck]'
...
$ flake8 a.py

$ pip install -U hacking
...
$ flake8 a.py
a.py:1:1: H104  File contains nothing but comments
a.py:1:3: H101  Use TODO(NAME)

$ pip install -U -e '.[stylecheck]'
...
$ flake8 a.py
a.py:1:1: H104  File contains nothing but comments
a.py:1:3: H101  Use TODO(NAME)
```

**Comment by toslunar** [comment]
The checks are in the `hacking` package. `H1nn` seems here: https://github.com/openstack-dev/hacking/blob/master/hacking/checks/comments.py

**Comment by niboshi** [comment]
Oh, `hacking` has its own checks...

**Comment by niboshi** [comment]
OK.
But we should leave hacking anyway.
We need an alternative.

**Comment by kmaehashi** [comment]
Thanks. I agree with that.

**Pull request closed without merging**
