### PR TITLE
Do not retain input on iDeep `F.relu`

### LINKED ISSUE #5866: iDeep F.relu retains input array unnecessarily
If iDeep is used, `F.relu` retains both of input and output during training, even though iDeep implementation of `F.leaky_relu` retains outputs only. This can cause memory exhaust.

Apart from the issue itself, it is questionable whether iDeep improves `F.relu` performance, because it is band-width limited and trivially written in NumPy. So it might be better to change

```python
intel64.should_use_ideep('>=auto')
```

to 

```python
intel64.should_use_ideep('==always')
```

### PR DESCRIPTION
**Pull request by grafi-tt**
Fixes #5866. Some refactoring of code style is done as well.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for the PR!
The test error indeed seems unrelated (issued: #5874).
I'll take a look at the changes soon.

**Comment by grafi-tt** [comment]
@niboshi Thank you for helpful feedback! I had left those codes conservatively because I wasn't confident there are unneeded. Following your feedback, I removed them.

**Comment by niboshi** [comment]
Thanks.
Jenkins, test this please.

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
