### PR TITLE
new style sqrt function

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR implements new `sqrt` function.

This PR needs to be rebased after merging #3603.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Rebased.

**Comment by niboshi** [comment]
It seems backward test is numerically unstable (dtype=float32). Please adjust tolerances.

**Comment by kmaehashi** [comment]
Thanks for reivew, but I can't reproduce the test failure, so I don't have any idea of how much to adjust.
(Jenkins is failing because of another test failure (numerically unstable))

**Comment by niboshi** [comment]
To check numerical stability of backward or double-backward test, it's helpful to put `@testing.condition.repeat(10000)` just before the test (e.g. `def test_backward_cpu()`) and run it.

**Comment by kmaehashi** [comment]
I tested with `repeat(10000)` and adjusted tolerance.
To achieve that, I also updated `unary_math_function_unittest` to accept tolerance parameters.

**Comment by takagi** [comment]
Would you rebase the master?

**Comment by kmaehashi** [comment]
Thansks, resolved conflict.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
