### PR TITLE
Fix caffe test with protobuf>=3.8

### PR DESCRIPTION
**Pull request by toslunar**
Takeover #7529.

### CODE REVIEW

**Comment by toslunar** [comment]
It seems `append` and `insert` are supported by more types of containers from protobuf 3.8.0-rc1.
https://github.com/protocolbuffers/protobuf/commit/d8c2501b43c1b56e3efa74048a18f8ce06ba07fe#diff-b10901d5df013ae758ed053d1b9b2a69

**Comment by toslunar** [comment]
To confirm the difference, run
```python
from chainer.links.caffe.caffe_function import caffe_pb

def _iter_init(param, data):
    print(type(param))
    print([n for n in dir(param) if not n.startswith('_') and callable(getattr(param, n, None))])
    print(data)
    print('----')
    if isinstance(data, list):
        for d in data:
            if hasattr(param, 'add'):
                param.add()
                if isinstance(d, (list, dict)):
                    _iter_init(param[-1], d)
                else:
                    param[-1] = d
            else:
                param.append(d)

    elif isinstance(data, dict):
        for k, d in data.items():
            if isinstance(d, (list, dict)):
                _iter_init(getattr(param, k), d)
            else:
                setattr(param, k, d)

    else:
        setattr(param, data)

data = {
    'layer': [
        {
            'name': 'l1',
            'type': 'Concat',
            'bottom': ['x', 'y'],
            'top': ['z'],
            'concat_param': {
                'axis': 2
            }
        }
    ]
}

param = caffe_pb.NetParameter()
_iter_init(param, data)
```
and get
```diff
--- (with protobuf 3.7.1)
+++ (with protobuf 3.8.0)
@@ -3,7 +3,7 @@
 {'layer': [{'name': 'l1', 'type': 'Concat', 'bottom': ['x', 'y'], 'top': ['z'], 'concat_param': {'axis': 2}}]}
 ----
 <class 'google.protobuf.pyext._message.RepeatedCompositeContainer'>
-['MergeFrom', 'add', 'extend', 'pop', 'remove', 'sort']
+['MergeFrom', 'add', 'append', 'extend', 'insert', 'pop', 'remove', 'sort']
 [{'name': 'l1', 'type': 'Concat', 'bottom': ['x', 'y'], 'top': ['z'], 'concat_param': {'axis': 2}}]
 ----
 <class 'caffe_pb2.LayerParameter'>
```

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
