### PR TITLE
Simplify `F.average` test

### PR DESCRIPTION
**Pull request by hikjik**
Simplifies test_average using testing.FunctionTestCase
Refer to [#6071](https://github.com/chainer/chainer/issues/6071)

### CODE REVIEW

**Comment by Crissman** [comment]
8 failures on these tests on my system. Please take a look.

https://gist.github.com/Crissman/5fdb1fd3fee5e6b2086557f3416e3402

**Comment by hikjik** [comment]
Seems like forward and forward _expected functions return data of different types. I have made some changes in the forward_expected function (added type casting). Could you please retest it in your system, as I am unable to reproduce errors you mentioned on my system.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Rerunning Jenkins. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins failure looks unrelated. Merging.

**Pull request merged**
