### PR TITLE
Fix error message of parameterized test

### PR DESCRIPTION
**Pull request by toslunar**
`testing.parameterize` needs the same fix as 630a2da1cd1b619560dcec015d6bbf9a345e537e.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure `tests.chainer_tests.functions_tests.activation_tests.test_elu.TestELU_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_1__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_0_{alpha_range=(-2.0,  0.0), dtype=<class 'numpy.float16'>, shape=(3,  2)}.test_double_backward` is unrelated to the PR, and its error message shows the correct parameter!
```
21:12:05 E           chainer.testing.function.FunctionTestError: Parameterized test failed.
21:12:05 E           
21:12:05 E           Base test method: TestELU_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_1__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_double_backward
21:12:05 E           Test parameters:
21:12:05 E             alpha_range: (-2.0, 0.0)
21:12:05 E             dtype: <class 'numpy.float16'>
21:12:05 E             shape: (3, 2)
21:12:05 E           
21:12:05 E           
21:12:05 E           (caused by)
21:12:05 E           FunctionTestError: double backward is not implemented correctly
21:12:05 E           
21:12:05 E           (caused by)
21:12:05 E           AssertionError: check_double_backward failed (eps=0.001 atol=0.0001 rtol=0.001)
21:12:05 E           input[0]:
21:12:05 E           [[ 0.0868 -0.4434]
21:12:05 E            [-0.151   0.6895]
21:12:05 E            [-0.9907 -0.757 ]]
21:12:05 E           grad_output[0]:
21:12:05 E           [[ 0.3416  0.652 ]
21:12:05 E            [-0.7266  0.1501]
21:12:05 E            [ 0.7827 -0.5815]]
21:12:05 E           grad_grad_input[0]:
21:12:05 E           [[-0.6294 -0.783 ]
21:12:05 E            [-0.5605  0.957 ]
21:12:05 E            [ 0.6235 -0.6562]]
21:12:05 E           
21:12:05 E           check_backward failed (eps=0.001 atol=0.0001 rtol=0.001)
21:12:05 E           inputs[0]:
21:12:05 E           [[ 0.0868 -0.4434]
21:12:05 E            [-0.151   0.6895]
21:12:05 E            [-0.9907 -0.757 ]]
21:12:05 E           inputs[1]:
21:12:05 E           [[ 0.3416  0.652 ]
21:12:05 E            [-0.7266  0.1501]
21:12:05 E            [ 0.7827 -0.5815]]
21:12:05 E           grad_outputs[0]:
21:12:05 E           [[-0.6294 -0.783 ]
21:12:05 E            [-0.5605  0.957 ]
21:12:05 E            [ 0.6235 -0.6562]]
21:12:05 E           directions[0]:
21:12:05 E           [[-0.12530578 -0.30720573]
21:12:05 E            [-0.01662964 -0.32910971]
21:12:05 E            [ 0.1762803  -0.17049192]]
21:12:05 E           directions[1]:
21:12:05 E           [[ 0.00417008 -0.63966631]
21:12:05 E            [ 0.01400885  0.39202264]
21:12:05 E            [-0.39498257 -0.04595117]]
21:12:05 E           gradients (numeric):  -0.025336154248142947
21:12:05 E           gradients (backward): -0.02567347824660285
21:12:05 E           
21:12:05 E           
21:12:05 E           Not equal to tolerance rtol=0.001, atol=0.0001
21:12:05 E           
21:12:05 E           Mismatch: 100%
21:12:05 E           Max absolute difference: 0.00033732
21:12:05 E           Max relative difference: 0.01313901
21:12:05 E            x: array(-0.025336)
21:12:05 E            y: array(-0.025673)
21:12:05 E           
21:12:05 E           assert_allclose failed: 
21:12:05 E             shape: () ()
21:12:05 E             dtype: float64 float64
21:12:05 E             i: (0,)
21:12:05 E             x[i]: -0.025336154248142947
21:12:05 E             y[i]: -0.02567347824660285
21:12:05 E             relative error[i]: 0.01313900653506259
21:12:05 E             absolute error[i]: 0.00033732399845990205
21:12:05 E           x: -0.02533615
21:12:05 E           y: -0.02567348
```

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
