### PR TITLE
Remove test_get_dummy_device_for_empty_array

### PR DESCRIPTION
**Pull request by okuta**
An empty array will has actual device id in cupy/cupy#946 .

### CODE REVIEW

**Comment by niboshi** [comment]
How about adding TODO to check `assert cuda.get_device_from_array(x) == cuda.Device(0)`?

**Comment by okuta** [comment]
I added.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please make it a TODO, instead of actually checking.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
>How about adding TODO to check `assert cuda.get_device_from_array(x) == cuda.Device(0)`?

How about this?
We should fix as such as soon as cupy/cupy#946 will be merged.

**Comment by okuta** [comment]
OK.

**Comment by niboshi** [comment]
No, I mean to write TODO as a comment.

**Comment by okuta** [comment]
oh,ok. I will

**Comment by niboshi** [comment]
LGTM. Thanks.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
@niboshi Is this PR needs to be labeled as `no-compat`?

**Comment by niboshi** [comment]
@kmaehashi 
I think so. This PR reflects the change of exposed behavior.
I'm not sure if it has been documented, but it affects existing user code.

**Comment by kmaehashi** [comment]
I discussed with @niboshi. As https://github.com/cupy/cupy/pull/946 is not merged yet, this PR itself does not break anything. I raised another issue #5113 for documenting this behavior change (its corresponding PR should be marked as no-compat)

**Pull request merged**
