### PR TITLE
Improve docs of sigmoid_cross_entropy

### PR DESCRIPTION
**Pull request by naoto0804**
This is PR for improving docs of functions/links. Related issue: #2182

Modified functions/links:
 - chainer/functions/loss/sigmoid_cross_entropy

### CODE REVIEW

**Comment by naoto0804** [comment]
[Screen Shot 2017-10-14 at 18.21.02.pdf](https://github.com/chainer/chainer/files/1384540/Screen.Shot.2017-10-14.at.18.21.02.pdf)

**Comment by naoto0804** [comment]
[screen_shot.pdf](https://github.com/chainer/chainer/files/1384541/screen_shot.pdf)

**Comment by naoto0804** [comment]
screen_shot

**Comment by naoto0804** [comment]
Could you review this? (In travis CI, it seems that one test not relavant to this PR is failing.)

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
