### PR TITLE
Rewrite ChainerX activation tests

### PR DESCRIPTION
**Pull request by niboshi**
Part of #6401

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Can you check the Travis time-out failures?

**Comment by hvy** [comment]
The ReLU test gets stuck in an infinite loop trying to generate differentiable points. You need to make `generate_inputs` stochastic. How about simply using `numpy.random.uniform`?

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins and AppVeyor failures seem unrelated but Travis is raising a NumPy error for tests including shapes with dimensions of length 0, e.g. `(5, 0)` on the numerical gradient computation.

**Comment by niboshi** [comment]
Fixed.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Hm, CI is failing. Can you take a look?

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
CI is still failing.

**Comment by hvy** [comment]
I'd like to rerun the tests after https://github.com/chainer/chainer/pull/6599.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
CI failures seem unrelated. LGTM!

**Pull request merged**
