### PR TITLE
Add `Device.name` property

### PR DESCRIPTION
**Pull request by niboshi**
I think it's useful.

This PR also improves backend device tests.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Do you think the attribute name `name` is appropriate? I think we're currently calling it `device specifier`.
https://docs.chainer.org/en/latest/reference/generated/chainer.get_device.html?highlight=get_device#chainer.get_device

**Comment by niboshi** [comment]
"Device specifier" is more general. It can be `int`, for example.
`Device.name` is meant to be more like unique identifiers.

C.f. `chainerx.Device` also has the same attribute.
```
>>> dev = chainerx.get_device('native')
>>> dev.name
'native:0'
```

**Comment by kmaehashi** [comment]
OK, that makes sense.
Jenkins, test this please.

**Comment by kmaehashi** [comment]
@niboshi Could you resolve conflicts?

**Comment by niboshi** [comment]
Resolved.

**Comment by hvy** [comment]
Seems to be conflicting again.

**Comment by niboshi** [comment]
Resolved.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
