### PR TITLE
Fix test instability for trigonometric functions

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by hvy** [comment]
@kmaehashi thanks for this fix. 

Running 10k repetitions, Arcsin's `forward_gpu` still seems a bit unstable. Could you fix this too?

**Comment by kmaehashi** [comment]
Thanks!
To adjust forward tolerance I added forward_options to unary_math_function_test decorator.
Confirmed forward 10k repeats.

**Comment by hvy** [comment]
LGTM! Will merge after tests!

**Comment by kmaehashi** [comment]
jenkins test this please

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
