### PR TITLE
`LinkTestCase` to simplify link tests

### PR DESCRIPTION
**Pull request by hvy**
Squashed https://github.com/chainer/chainer/pull/6187 and kept history of `function.py` and its corresponding test.

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, tset this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by hvy** [comment]
Hm, NumPy 1.9.3 (Py2) fails on mismatched dtypes for the float16 tests. 🤔

**Comment by hvy** [comment]
Fixed the above failure. PTAL.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by crcrpar** [comment]
NumPy 1.9 has a bug in `sqrt`. See https://github.com/chainer/chainer/pull/2302#issuecomment-323258697

I think it'd be better to specify dtype in `numpy.sqrt`.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
@crcrpar 
Thank you for the comment!
I think both ways are fine. I'm gonna prioritize the merge at this moment.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
