### PR TITLE
[backport] Fix lazy init of `BatchNormalization` link

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #6369

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by hvy** [comment]
This is not a trivial backport since `generate_array` doesn't accept a `device` argument nor does the `Link` have a `device` attribute.

**Comment by hvy** [comment]
Should we fix those problems in this backport? We can also create a separate PR/issue to address it.

**Comment by niboshi** [comment]
@hvy Fixed. Please check.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
