### PR TITLE
Refactor Travis script

### PR DESCRIPTION
**Pull request by niboshi**
Follow-up of #5858.

Simply separates Travis sequences as a file.

### CODE REVIEW

**Comment by hvy** [comment]
Sorry I have not caught up with the motivation of this PR but is `run-tests.sh` meant to be reused or is it more about keeping `.travis.yml` minimal?

**Comment by niboshi** [comment]
I want to add other checks like clang-tidy and cpplint.

**Comment by hvy** [comment]
Ah, I assume you're referring to https://github.com/chainer/chainer/pull/5867 . Thanks for the clarification.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
