### PR TITLE
Avoid fallback for ChainerX in `F.accuracy`

### PR DESCRIPTION
**Pull request by niboshi**
Split from #7393

Implements `chainerx_forward` in `F.accuracy`.
The base class is now `FunctionNode` instead of `Function` in order to support `chainerx_forward`.

### CODE REVIEW

**Comment by niboshi** [comment]
ping

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by niboshi** [comment]
Resolved conflict.
PTAL

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
