### PR TITLE
Remove Travis macOS Py34 job

### LINKED ISSUE #6132: Travis macOS Py34 is failing
The Travis job for macOS (runs only with the `master` branch) is failing when NumPy is used with the Accelerate backend in `numpy.polynomial.polynomial.polfit` in the gradient check. It is confirmed that this failure does not occur with Python 3.5.1, nor with NumPy with OpenBLAS.

### PR DESCRIPTION
**Pull request by hvy**
Fixed #6132 .

### CODE REVIEW

**Comment by hvy** [comment]
Installing NumPy with OpenBLAS instead of Accelerate seems to get around the problem. Specifically, a memory allocation failed in `polyfit` in the gradient check.

**Comment by hvy** [comment]
This workaround is not necessary for Python 3.5.1. Since Python 3.4 reaches end-of-life by 2018-03-16, it might be okay to drop this build from the test matrix entirely. https://devguide.python.org/#status-of-python-branches

**Comment by hvy** [comment]
Removed the build from the matrix as a part of https://github.com/chainer/chainer/issues/6131 (dropping Py34 support).

**Comment by hvy** [comment]
Travis failures seem unrelated.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins failure is irrelevant

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
