### PR TITLE
Simplify `CreateSubgraph`

### LINKED ISSUE #8050: `chainer.grad` is broken with ChainerX backend
As reported by @hvy, `chainerx.grad` called by `chainer.grad` seems broken with macOS clang.  https://travis-ci.org/chainer/chainer/builds/577696208 
```
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_0_{extend_graph_x=False, extend_graph_y=False}::test_double_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_0_{extend_graph_x=False, extend_graph_y=False}::test_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_2_{extend_graph_x=True, extend_graph_y=False}::test_double_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_2_{extend_graph_x=True, extend_graph_y=False}::test_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_1_{extend_graph_x=False, extend_graph_y=True}::test_double_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_1_{extend_graph_x=False, extend_graph_y=True}::test_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_3_{extend_graph_x=True, extend_graph_y=True}::test_double_grad
FAIL tests/chainer_tests/test_function_node.py::TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_3_{extend_graph_x=True, extend_graph_y=True}::test_grad
```
```
_ TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_0_{extend_graph_x=False, extend_graph_y=False}.test_grad _
self = <chainer.testing._bundle.TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None...t_batch_normalization_false__use_ideep_never_param_0_{extend_graph_x=False, extend_graph_y=False} testMethod=test_grad>
backend_config = <BackendConfig use_chainerx=True chainerx_device='native:0' use_cuda=False cuda_device=None use_cudnn='never' cudnn_deterministic=False autotune=False cudnn_fast_batch_normalization=False use_ideep='never'>
    def test_grad(self, backend_config):
        if self.loss_scale and backend_config.xp is chainerx:
            pytest.skip('chainerx.grad does not support loss_scale')
        self.use_device(backend_config.device)
>       self.check_grad()
tests/chainer_tests/test_function_node.py:970: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/chainer_tests/test_function_node.py:959: in check_grad
    testing.assert_allclose(self._get_value(a), self._get_value(e))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = array([  6., -14., -32.], dtype=float32), y = array([  2.,  -4., -48.], dtype=float32), atol = 1e-05, rtol = 0.0001
verbose = True
    def assert_allclose(x, y, atol=1e-5, rtol=1e-4, verbose=True):
        """Asserts if some corresponding element of x and y differs too much.
    
        This function can handle both CPU and GPU arrays simultaneously.
    
        Args:
            x: Left-hand-side array.
            y: Right-hand-side array.
            atol (float): Absolute tolerance.
            rtol (float): Relative tolerance.
            verbose (bool): If ``True``, it outputs verbose messages on error.
    
        """
        x = backend.CpuDevice().send(utils.force_array(x))
        y = backend.CpuDevice().send(utils.force_array(y))
        try:
            numpy.testing.assert_allclose(
                x, y, atol=atol, rtol=rtol, verbose=verbose)
        except AssertionError as e:
            f = six.StringIO()
            f.write(str(e) + '\n\n')
            f.write(
                'assert_allclose failed: \n' +
                '  shape: {} {}\n'.format(x.shape, y.shape) +
                '  dtype: {} {}\n'.format(x.dtype, y.dtype))
            if x.shape == y.shape:
                xx = numpy.atleast_1d(x)
                yy = numpy.atleast_1d(y)
                err = numpy.abs(xx - yy)
    
                tol_rtol = rtol * numpy.abs(yy).astype(numpy.float64)
                tol_err = atol + tol_rtol
    
                i = numpy.unravel_index(
                    numpy.argmax(err.astype(numpy.float64) - tol_err), err.shape)
    
                if yy[i] == 0:
                    rel_err = 'inf'
                else:
                    rel_err = err[i] / numpy.abs(yy[i])
    
                f.write(
                    '  i: {}\n'.format(i) +
                    '  x[i]: {}\n'.format(xx[i]) +
                    '  y[i]: {}\n'.format(yy[i]) +
                    '  relative error[i]: {}\n'.format(rel_err) +
                    '  absolute error[i]: {}\n'.format(err[i]) +
                    '  relative tolerance * |y[i]|: {}\n'.format(tol_rtol[i]) +
                    '  absolute tolerance: {}\n'.format(atol) +
                    '  total tolerance: {}\n'.format(tol_err[i]))
    
            opts = numpy.get_printoptions()
            try:
                numpy.set_printoptions(threshold=10000)
                f.write('x: ' + numpy.array2string(x, prefix='x: ') + '\n')
                f.write('y: ' + numpy.array2string(y, prefix='y: ') + '\n')
            finally:
                numpy.set_printoptions(**opts)
>           raise AssertionError(f.getvalue())
E           AssertionError: Parameterized test failed.
E           
E           Base test method: TestGradComplex_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_grad
E           Test parameters:
E             extend_graph_x: False
E             extend_graph_y: False
E           
E           
E           (caused by)
E           AssertionError: 
E           Not equal to tolerance rtol=0.0001, atol=1e-05
E           
E           Mismatch: 100%
E           Max absolute difference: 16.
E           Max relative difference: 2.5
E            x: array([  6., -14., -32.], dtype=float32)
E            y: array([  2.,  -4., -48.], dtype=float32)
E           
E           assert_allclose failed: 
E             shape: (3,) (3,)
E             dtype: float32 float32
E             i: (2,)
E             x[i]: -32.0
E             y[i]: -48.0
E             relative error[i]: 0.3333333432674408
E             absolute error[i]: 16.0
E             relative tolerance * |y[i]|: 0.0048000000000000004
E             absolute tolerance: 1e-05
E             total tolerance: 0.00481
E           x: [  6. -14. -32.]
E           y: [  2.  -4. -48.]
../../../.pyenv/versions/3.5.1/lib/python3.5/site-packages/chainer/testing/array.py:68: AssertionError
------------------------------------------------- Captured stdout call -------------------------------------------------
xs  : array([ 1.,  1., -1.], shape=(3,), dtype=float32, device='native:0'), array([ 2.,  3., -2.], shape=(3,), dtype=float32, device='native:0')
gxs : array([ 0., -3., -4.], shape=(3,), dtype=float32, device='native:0'), array([-2.,  0., -4.], shape=(3,), dtype=float32, device='native:0')
gys : array([ 2., -3.,  5.], shape=(3,), dtype=float32, device='native:0'), array([-1.,  2.,  4.], shape=(3,), dtype=float32, device='native:0')
gxs (actual)  : array([  6., -14., -32.], shape=(3,), dtype=float32, device='native:0'), array([ 2., -6., -4.], shape=(3,), dtype=float32, device='native:0')
gxs (expected): array([  2.,  -4., -48.], shape=(3,), dtype=float32, device='native:0'), array([ 0., -2., -4.], shape=(3,), dtype=float32, device='native:0')
```

### PR DESCRIPTION
**Pull request by toslunar**
`forward_op_nodes` does not have to know whether a node is in `outputs`.  

Close #8050.  See also #8049.

### CODE REVIEW

**Comment by toslunar** [comment]
#8049 fixed the bug.

**Comment by toslunar** [comment]
See https://github.com/chainer/chainer/pull/8310/files/cebcf15ba8436c41827dec27c8b4a8b75dcd34a8 for the diff without the indentation changes.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Thanks, LGTM!

**Pull request merged**
