### PR TITLE
Support all float dtypes in `F.n_step_rnn` and `F.n_step_birnn`

### PR DESCRIPTION
**Pull request by takagi**
Resubmit of #5125.

This PR is a part of #4582, generalize `F.n_step_rnn` and `F.n_step_birnn` to support all float dtypes.

### CODE REVIEW

**Comment by takagi** [comment]
@kmaehashi Would you continue to review this PR after some commits after e914be4?

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
I will merge the master to pass CI.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
@kmaehashi Would you merge this?

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by crcrpar** [comment]
bump

**Comment by kmaehashi** [comment]
@takagi Could you resolve conflicts?

**Comment by takagi** [comment]
Sure!

**Comment by kumasento** [comment]
Hi @takagi I'm really looking forward to using your nice contribution in this PR! Is there anything that I can help with to make it work and merged? Thanks!

**Comment by takagi** [comment]
@kumasento Thanks for your mention. `F.n_step_rnn` and `F.n_step_birnn` actually work in FP16 mode on v6 as far as you don't use them with cuDNN. It would be nice if you would make them run on your environment to find if they would work well. Now I'm working on making it run in FP16 mode with cuDNN, and it will finish soon. If possible, I would like you to test on your environment as well after I will push it.

**Comment by kumasento** [comment]
Thanks @takagi I didn't know that FP16 actually works (w/o cuDNN). I will try that asap

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
I've resolved the conflict. This PR is ready for review, though it depends on #https://github.com/cupy/cupy/pull/2442 . Please review and merge it first.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by crcrpar** [comment]
???

**Comment by kmaehashi** [comment]
I'm unsure why this has caused... Resubmitting as https://github.com/chainer/chainer/pull/8078 anyway.

**Comment by kmaehashi** [comment]
GitHub support told that it was a bug in Github and they fixed the issue right now. Closing #8078 and reopening it to keep the discussion in one place.

**Comment by crcrpar** [comment]
Thanks kmaehashi

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
