### PR TITLE
Test statistics of initializers

### PR DESCRIPTION
**Pull request by toslunar**
Test `scale` arg of `chainer.initializers`.

This PR adds statistical tests ~and fixes bias of sign of `Orthogonal` initializer~.

### CODE REVIEW

**Comment by toslunar** [comment]
@sunaemon Could you review the math part of this PR?

**Comment by toslunar** [comment]
This PR can be backported because the change to `Orthogonal` is moved to #5615.

**Comment by mitmul** [comment]
Will you make the test case for the orthogonal initializer stricter by removing `abs` over the sample values after this PR is merged and backported for v5? Or isn't it necessaliry be such a strict condition for testing the orthogonal initializer?

**Comment by toslunar** [comment]
#5615 makes the test stricter by removing `abs`.

**Comment by sunaemon** [comment]
@toslunar 
The statistical tests for orthogonal initializer seem verifies a necessary condition!

Sorry for the delay.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
A test (with `alpha=0.05` and `repeat_with_success_at_least(5, 3)`) fails with probability 0.001158125.  This seems too large to have parameterized tests.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by okuta** [comment]
@mitmul Test was passed.

**Pull request merged**
