### PR TITLE
Make it possible to be fine-tuning with NStepLSTM and NStepBiLSTM

### PR DESCRIPTION
**Pull request by massongit**
(Related to #1816)
I added `initial_model` parameter to `__init__` methods of `NStepLSTM` and `NStepBiLSTM` so that fine-tuning can. A value of this parameter is `NStepLSTM` or `NStepBiLSTM`, and this parameter is used to initialize weights and biases.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for PR!
In order to copy a link including its weights, you can write as `copy.deepcopy(link)`, by using Python's builtin `copy` module.
Does that achieve this purpose?

**Comment by massongit** [comment]
@niboshi Thank you for your review!
I achieved your purpose.

**Comment by massongit** [comment]
@niboshi Thank you for your review!
I achieved your purpose.

**Comment by niboshi** [comment]
I'm sorry for being unclear. I meant you could use `copy.deepcopy` to duplicate a `NStepLSTM` link itself, including its weights, instead of `initial_model`.
How do you think?

**Comment by massongit** [comment]
@niboshi I understand that you said that we have only to copy `NStepLSTM` link deeply when we do fine-tuning.
I think so, so I would like to close PR.

**Comment by niboshi** [comment]
OK. Thank you for making a suggestion!

**Pull request closed without merging**
