### PR TITLE
Avoid unnecessary copy in `ndarray.astype`

### PR DESCRIPTION
**Pull request by toslunar**
This would improve the performance.

### CODE REVIEW

**Comment by toslunar** [comment]
This PR does not fix difficult ones like `xp.random.normal(...).astype(...)`, which could be fixed in other ways.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by beam2d** [comment]
LGTM

**Pull request merged**
