### PR TITLE
Fix array indexing in `create_multi_node_evaluator`

### LINKED ISSUE #8546: Unable to run mnist dual parallel example
Python version: 3.7
OS/Platform: Red Hat 7.6

I am unable to run the chainermn dual parallel example (chainer/examples/chainermn/mnist/train_mnist_dual_parallel.py) with chainer version `7.1.0`. I was able to run this example previously with chainer version `6.2.0`.

The error I get is

```
  File "chainer/chainermn/mnist/train_mnist_dual_parallel.py", line 156, in <module>
    main()
  File "chainer/chainermn/mnist/train_mnist_dual_parallel.py", line 152, in main
    trainer.run()
  File "/opt/chainer/chainer/training/trainer.py", line 376, in run
    six.reraise(*exc_info)
  File "/opt/chainer/six.py", line 703, in reraise
    raise value
  File "/opt/chainer/chainer/training/trainer.py", line 346, in run
    entry.extension(self)
  File "/opt/chainer/chainer/training/extensions/evaluator.py", line 180, in __call__
    result = self.evaluate()
  File "/opt/chainer/chainermn/extensions/multi_node_evaluator.py", line 229, in new_evaluate
    array0 = list(local_mean_dict.values())[0]
IndexError: list index out of range
```

I noticed that since release 6.2.0 some modification has been made to multi_node_evaluator.py, specifically the addition of the following lines
```
        # ChainerX support:
        # We need convert chainerx ndarray to Native array because
        #   (1) allreduce_obj is used to compute global mean values, since
        #       a simple allreduce operation cannot be applied in evaluation.
        #   (2) allreduce_obj calls mpi4py.allreduce, which pickles the object
        #   (3) chainerx.ndarray preserves CUDA device internally when pickled
        #   (4) An error will occur when an ndarray is unpickled in another
        #       process
        array0 = list(local_mean_dict.values())[0]
        xp = backend.get_array_module(array0)
        if xp == chx and array0.device.backend.name == 'cuda':
            # Results of evaluation is fairly small, so
            # the ndarray is transferred to CPU and allreduce()-ed.
            # NOTE: Matrices for evaluation are transferred to the host memory
            # and sent via MPI instead of NCCL. Although evaluation matrices
            # are small in most cases, this is a potential performance issue.
            local_mean_dict = {
                name: chx.to_numpy(value)
                for name, value in local_mean_dict.items()
            }
```
I have also installed ChainerX  but I still get the same error. The Data Parallel (`train_mnist.py`) and Model Parallel (`train_mnist_model_parallel.py`) examples are able to run successfully.

### PR DESCRIPTION
**Pull request by emcastillo**
Closes #8546

In some cases `local_mean_dict.values()` is empty. For example in the above issue, it is empty for the rank 1 since the example explicitly creates an empty dataset for this rank. 

https://github.com/chainer/chainer/blob/8b9e9c014716077366845fdb5bf780644c067952/examples/chainermn/mnist/train_mnist_dual_parallel.py#L124-L126

Also metrics are not reported for rank 1.

https://github.com/chainer/chainer/blob/8b9e9c014716077366845fdb5bf780644c067952/examples/chainermn/mnist/train_mnist_dual_parallel.py#L107-L110

### CODE REVIEW

**Comment by keisukefukuda** [comment]
pfnci, test this please.

**Comment by emcastillo** [comment]
Yes, tests has been failing in PfnCI for a while due to out of memory errors, 
We have to fix this 🙇‍♂️.
Jenkins worked fine and the errors are not related to the PR so I think it is safe to merge.

Sorry and thank you again.

**Comment by emcastillo** [comment]
All the CI issues were fixed, the current failing job is due to having the env variables set on job creation so it can't be overridden with the new values unless the CIs are kicked again ☹️

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test  this please

**Comment by emcastillo** [comment]
@keisukefukuda we fixed the CIs and now all test passed  :D

**Pull request merged**
