### PR TITLE
Simplify `F.deconvolution_nd.py` tests

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies `test_deconvolution_nd` using `testing.FunctionTestCase`

Solves part of issue #6071

### CODE REVIEW

**Comment by ishanrai05** [comment]
@Crissman Can you please review this?

**Comment by Crissman** [comment]
Tests passed increased from 160 to 440. Is that necessary?

**Comment by ishanrai05** [comment]
@Crissman  The tests passed have increased probably because of several devices introduced in the backend tests.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Retesting: Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins is showing issues with the deconvolution_nd tests. Please take a look.

**Comment by Crissman** [comment]
Restesting since previous results not available. Jenkins, test this please.

**Pull request closed without merging**
