### PR TITLE
[backport] Relax tolerances in old cuDNN convolution tests

### LINKED ISSUE #7693: Flaky test: tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1497/TEST=chainer-py2,label=mn1-p100/testReport/junit/tests.chainer_tests.links_tests.connection_tests.test_deconvolution_2d/TestDeconvolution2DParameterShapePlaceholder_param_16_%7Buse_cudnn='always',%20nobias=True,%20deconv_args=((None,%202,%203,%202,%201),%20%7B%7D)%7D/test_backward_gpu/

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #7942
Fixes #7693

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
