### PR TITLE
[RFC] Fix on flake8 3.5.0

### PR DESCRIPTION
**Pull request by kuenishi**
Current master doesn't pass flake8 version 3.5.0 test. Most of new errors are E741, where PEP8 discourages single-letter variable such as 'l', 'L' and 'O'. This is a suggested change to fix it, with single exception which I don't have good idea on its new name. Please feel free to comment on current fix for better naming, or to push further commit to `fix-flake8-350` branch. 

c.f
- https://pep8.readthedocs.io/en/latest/_modules/pycodestyle.html .
- https://github.com/chainer/chainermn/pull/150 

After:
```
$ flake8 --version && flake8
3.5.0 (ProxyChecker: 0.0.1, hacking.core: 0.0.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.3 on Linux
./tests/chainer_tests/functions_tests/loss_tests/test_ctc.py:20:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_ctc.py:179:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_ctc.py:193:14: E741 ambiguous variable name 'l'
```

Before:
```
$ flake8 --version && flake8                                                                                                                
3.5.0 (ProxyChecker: 0.0.1, hacking.core: 0.0.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.3 on Linux                                              
./chainer/links/connection/tree_lstm.py:188:17: E741 ambiguous variable name 'l'                                                                                         
./chainer/links/model/vision/resnet.py:517:13: E741 ambiguous variable name 'l'
./chainer/functions/array/pad_sequence.py:47:17: E741 ambiguous variable name 'l'
./chainer/functions/array/pad_sequence.py:48:20: E741 ambiguous variable name 'l'
./chainer/training/extensions/plot_report.py:167:17: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:297:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:346:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:373:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:387:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:403:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:499:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:500:17: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:790:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/test_link.py:793:25: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/connection_tests/test_inceptionbn.py:25:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/connection_tests/test_inception.py:24:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py:141:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py:152:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py:167:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/loss_tests/test_black_out.py:48:13: E741 ambiguous variable name 'l'
./tests/chainer_tests/links_tests/loss_tests/test_black_out.py:51:17: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_black_out.py:59:13: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_black_out.py:62:17: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py:374:9: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_ctc.py:20:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_ctc.py:179:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/functions_tests/loss_tests/test_ctc.py:193:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/function_hooks_tests/test_cupy_memory_profile.py:41:14: E741 ambiguous variable name 'l'
./tests/chainer_tests/function_hooks_tests/test_timer.py:39:14: E741 ambiguous variable name 'l'
./examples/imagenet/nin.py:3:32: E741 ambiguous variable name 'I'
./examples/imagenet/googlenet.py:49:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:50:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:51:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:52:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:59:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:60:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:61:9: E741 ambiguous variable name 'l'
./examples/imagenet/googlenet.py:62:9: E741 ambiguous variable name 'l'
./examples/sentiment/train_sentiment.py:113:18: E741 ambiguous variable name 'l'
./examples/word2vec/train_word2vec.py:15:32: E741 ambiguous variable name 'I'
./examples/word2vec/train_word2vec.py:17:30: E741 ambiguous variable name 'O'
```

### CODE REVIEW

**Comment by kmaehashi** [comment]
Do you use `flake8` from `hacking` package?

> To check your code, use autopep8 and flake8 command installed by hacking package:

```
$ pip install autopep8 hacking
$ autopep8 --global-config .pep8 path/to/your/code.py
$ flake8 path/to/your/code.py
```

https://docs.chainer.org/en/stable/contribution.html

**Comment by niboshi** [comment]
Even though we are using `hacking` and thus E741 is not a mandatory rule, the reasoning behind this rule is understandable.

I think we should still review and merge this PR.

**Comment by kuenishi** [comment]
Thanks for the comment. To continue this work, I have two questions. I took a glance at documentation of hacking but found no mention in E741 and not sure whether it has a way to make E741 mandatory.

Also, renaming `l` in this case is not obvious to me:
```python
class CTCTestBase(object):

    def setUp(self):
        self.x = numpy.random.uniform(-1, 1, (4, 2, 3)).astype(numpy.float32)
        self.t = numpy.array([[0, 1], [1, 0]]).astype(numpy.int32)
        self.l = numpy.array([[2, 0, 2, 1, 2],
                              [2, 1, 2, 0, 2]]).astype(numpy.int32)
        self.blank_symbol = 2
        self.x_length = numpy.full((len(self.x[0]),), len(self.x), dtype='i')
        self.l_length = numpy.full((len(self.t),), len(self.t[0]), dtype='i')
        self.use_length = True
        if self.reduce == 'mean':
            self.gy = numpy.random.uniform(-1, 1, ()).astype(numpy.float32)
        else:
            self.gy = numpy.random.uniform(-1, 1, (2,)).astype(numpy.float32)
```
Possibly in this case `l` is just a letter in some equation but now sure what it comes from.

**Comment by kuenishi** [comment]
So I found further facts, that the latest flake8 (3.5.0) uses [pycodestyle (2.3.1) which includes E741 check since 2.1.0](https://pypi.python.org/pypi/pycodestyle). On the other hand flake8 with hacking forces flake8 to be old [(2.5.5) that uses *pep8*](https://gitlab.com/pycqa/flake8/blob/2.5.5/setup.py) . pep8 is not maintained any more and renamed to pycodestyle this October. So possible options could be:
* Ask hacking to update its fixed dependencies, esp pep8 to pycodestyle
* Remove hacking from dependency and keep up-to-date at the cost of additional checks by hacking

I'm not sure how much hacking is actively maintained, but last release is this September and could be said either.

**Comment by kmaehashi** [comment]
Related to #4606, we need to rethink how we ask contributors to apply style checking.
(Update the guide, or, migrate to `flake8` instead of `hacking` and disable some rules manually.)

**Comment by niboshi** [comment]
Also related to #4610.

**Pull request closed without merging**
