### PR TITLE
Use pytest-warnings to set warnings configuration

### PR DESCRIPTION
**Pull request by unnonouno**
I fix setup.cfg to use pytest-warnings instead of changing PYTHONWARNINGS environment variable.

### CODE REVIEW

**Comment by unnonouno** [comment]
merge #3717 first

**Comment by okuta** [comment]
I merged #3717. Please resolve conflicts.

**Comment by okuta** [comment]
Please fix tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py

**Comment by unnonouno** [comment]
fixed

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
