### PR TITLE
Fix a minior bug of resnet.py

### PR DESCRIPTION
**Pull request by t-abe**
`n_layers` argument for `ResNetLayers` was missing.

### CODE REVIEW

**Comment by mitmul** [comment]
Now it results in a weird error at a Jenkins test job. Investigating it.

**Comment by mitmul** [comment]
Doc test is still failing due to a error, but it must not be related to this PR. So LGTM

**Comment by mitmul** [comment]
I'm sorry, I wrongly merged this PR. The doctest error should have been fixed before merging this.

**Comment by kiyukuta** [comment]
I think we do not need `n_layers` here.

Although base `ResNetLayer.__init__` needs `n_layers`, `ResNetXXXLayers.__init__` does not and  `convert_caffemodel_to_npz ` is called only from specific `ResNetXXLayers` classes.
https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/resnet.py#L699-L706

**Comment by kiyukuta** [comment]
Sorry, never mind, I noticed #3062 will solve this.

**Comment by mitmul** [comment]
@kiyukuta Thank you for pointing out it. I agree with that. Can I revert this PR, @t-abe ?

**Pull request merged**
