### PR TITLE
[backport] fix doctest failure in trainer tutorial

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #3810

### CODE REVIEW

**Comment by hvy** [comment]
#3886 should fix this issue (as well as other similar ones). Do we still need this PR merged?

**Comment by niboshi** [comment]
As you say, eventually we will remove this fix. But I think it's better to keep it consistent between master and stable branches.

**Comment by hvy** [comment]
I agree. Thanks for the quick response!

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
