### PR TITLE
Code clean up for `routines/indexing.h`

### PR DESCRIPTION
**Pull request by niboshi**
Including https://github.com/chainer/chainer/pull/8281#discussion_r333466640

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I think we can close this one.
Thanks!

**Comment by niboshi** [comment]
Some subtle fixes are still applicable.
I'll update the PR.

**Comment by niboshi** [comment]
PTAL

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
