### PR TITLE
Add Synchronized Iterator

### PR DESCRIPTION
**Pull request by levelfour**
## Overview

In some situations of distributed machine learning, it is preferable to

1. synchronize iterator seed: to preserve batch order among each process.
2. use private random number generator: to avoid interfering other random number generation, such as dropout.

In this PR, I added create_synchronized_iterator, which extends Chainer SerialIterator to synchronize the seed and make private random number generators during initialization.

## Note

This PR is a porting from chainer/chainermn#185.

### CODE REVIEW

**Comment by levelfour** [comment]
Even though the test for the last commit fails, the other parts that do not have anything to do with this PR seem to cause the test failure.

**Comment by kuenishi** [comment]
Jenkins, test this please.

**Comment by kuenishi** [comment]
Jenkins, test this please.

**Comment by kuenishi** [comment]
Jenkins, test this please.

**Comment by kuenishi** [comment]
I'm not sure how to fix Travis error here but in #6345 I succeeded. This PR will be superseded.

**Pull request closed without merging**
