### PR TITLE
Fix ArgMax of CUDA when all values are negative

### PR DESCRIPTION
**Pull request by hvy**
Fixes https://github.com/chainer/chainer/issues/6742

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Let me rerun Jenkins since it was interrupted.

**Comment by asi1024** [comment]
Jenkins failure seems unrelated to this PR. LGTM.

**Pull request merged**
