### PR TITLE
[backport]Fix doctest

### PR DESCRIPTION
**Pull request by unnonouno**
#3641

### CODE REVIEW

**Comment by kmaehashi** [comment]
jenkins test this please

**Comment by takagi** [comment]
This backport seems to lose some change on `extension.rst` in the original PR.

https://github.com/chainer/chainer/pull/3641/files#diff-cbcaba2532e9f3a72ff2b0588ef31a40

Actually `extension.rst`'s backport (#3646) is not merged to v3 yet. I have made another backport PR for #3641 and it should work.

Can I close this PR?

**Comment by okuta** [comment]
This PR fixes other than `extension.rst`. We need this backport PR.

**Comment by takagi** [comment]
Okay.

**Pull request merged**
