### PR TITLE
Add support for fp16 and fp64 to cudnn RNN

### PR DESCRIPTION
**Pull request by crcrpar**
This PR enables `NStepRNN`s to handle inputs of float16/float64.

- [x] fix TestNStepBiLSTM of test_n_step_lstm.py

### CODE REVIEW

**Comment by crcrpar** [comment]
Should I wait for https://github.com/chainer/chainer/pull/5303?

**Comment by hvy** [comment]
I'm not aware of the status of #5303 but it at a quick glance looks like they could be worked on independently? This PR modified an existing function while #5303 is introducing a new one.

**Comment by crcrpar** [comment]
I was concerned that that PR seems to be limiting inputs to float32.

**Comment by crcrpar** [comment]
@hvy Could you take a look at this if you have the time?

**Comment by hvy** [comment]
Rephrasing this comment https://github.com/chainer/chainer/pull/6150#issuecomment-476290566.

**Comment by crcrpar** [comment]
OK.

**Comment by crcrpar** [comment]
Seems a dup of https://github.com/chainer/chainer/pull/5808/ going to be merged.

**Comment by crcrpar** [comment]
Let me close.

**Pull request closed without merging**
