### PR TITLE
Changes citation to new KDD paper

### PR DESCRIPTION
**Pull request by prabhatnagarajan**
Changes the bibtex and citation to use the new KDD 2019 paper.

### CODE REVIEW

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by prabhatnagarajan** [comment]
@toslunar I think it's fine to keep both. Though presumably you would want to keep share the bibtex of the paper that you would prefer to cite, right? I think keeping both references is fine but maybe the bibtex should only be for the latest paper?

**Comment by Crissman** [comment]
@prabhatnagarajan Keeping both ok?

**Comment by prabhatnagarajan** [comment]
Yeah, I'll make the changes.

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by Crissman** [comment]
Testing errors look unrelated. Merging.

**Pull request merged**
