### PR TITLE
Bump python version for RTD build

### LINKED ISSUE #8573: Fix readthedocs build failures
Currently master branch doc build failing with 

```
  File "/tmp/easy_install-98_shk88/numpy-1.19.0/setup.py", line 30, in <module>
    'protobuf>=3.0.0',
RuntimeError: Python version >= 3.6 required.
```

https://readthedocs.org/projects/chainer/builds/11381309/

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #8573

### CODE REVIEW

**Comment by kmaehashi** [comment]
I've enabled RTD pull-request build test.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
