### PR TITLE
Optimize ctc

### PR DESCRIPTION
**Pull request by unnonouno**
I optimized logsumexp in ctc by using a custom kernel. It is about 10% faster than the original.

### CODE REVIEW

**Comment by hvy** [comment]
Thank you for this PR! 

It seems like the cpu-only builds are failing because of the unconditioned usage of cupy but I guess you are on it already. Could you share some code for running the benchmarks?

**Comment by unnonouno** [comment]
Here is a test code:
```
import time

import chainer
import cupy

xs = [chainer.Variable(cupy.zeros((32, 256), 'f')) for _ in range(50)]
t = chainer.Variable(cupy.zeros((32, 20), 'i'))
cupy.cuda.Stream.null.synchronize()
begin = time.time()
for i in range(50):
    chainer.functions.connectionist_temporal_classification(xs, t, 1)
cupy.cuda.Stream.null.synchronize()
end = time.time()
print('%f sec' % (end - begin))
```

Original:
```
3.284915 sec
```

This pr:
```
2.508997 sec
```

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM! And thank you for the reproduction code also!

**Pull request merged**
