### PR TITLE
Support Soft Nearest Neighbor Loss

### PR DESCRIPTION
**Pull request by tohmae**
This PR is proposal for supporting soft nearest neighbor loss.
Deteil is here.
https://arxiv.org/abs/1902.01889
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/loss.py

### CODE REVIEW

**Comment by Crissman** [comment]
Thanks for the PR! Please add tests and add the documentation as well. Let me know if you have questions about how to do that.

**Comment by tohmae** [comment]
Thank you for your comment.
Please give me some time to modify tests and to add documentation.

**Comment by Crissman** [comment]
Thanks for the work on this PR. Is it ready for review? If so, please remove [WIP] from the title.

**Comment by tohmae** [comment]
Thank you for your comment.
I add tests, but do not add documentation.
Please give me some time to add documentation.
Please review source code and test code.

**Comment by tohmae** [comment]
Please review it.  🙏

**Comment by tohmae** [comment]
I add documentation.
Please review documentation too.

**Comment by emcastillo** [comment]
Sorry, as we have ceased to add new functionalities to chainer, we are now closing PRs that do not explicitly address bugs or severe issues.
Thanks for your contribution and sorry for the inconvenience.

**Pull request closed without merging**
