### PR TITLE
Print installed packages in pytest

### PR DESCRIPTION
**Pull request by niboshi**
To make investigation easier.

### CODE REVIEW

**Comment by niboshi** [comment]
Introduced `CHAINER_CI`.
Packages are printed only when its value is non-empty.

PTAL

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Required CI failure on ChainerX Cholesky, essentially unrelated to this PR.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
LGTM!

**Comment by niboshi** [comment]
Thanks!

**Pull request merged**
