### PR TITLE
Fix iterator syntax in MNIST custom loop example

### PR DESCRIPTION
**Pull request by niboshi**
For consistency with other examples.

### CODE REVIEW

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Related to: #4155, #5519

**Comment by mitmul** [comment]
LGTM

**Comment by niboshi** [comment]
@mitmul Can you make a backport PR?

**Comment by kmaehashi** [comment]
I made a backport.

**Pull request merged**
