### PR TITLE
chmod 644 *.py

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by niboshi** [comment]
Maybe we should remove those shebangs?

**Comment by niboshi** [comment]
Or maybe we should keep executable bits for example scripts.

**Comment by kmaehashi** [comment]
+1 to keep it as is for examples, unless there is a strong motivation to do so.
At least one user invoking the script directly. http://pongsuke.hatenadiary.jp/entry/2017/03/14/132907

**Comment by toslunar** [comment]
I reverted the changes in examples.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
