### PR TITLE
Support Rollaxis in ONNX-Chainer

### PR DESCRIPTION
**Pull request by tkanmae**
This Pull Request is intend to add support of Rollaxis in ONN-Chainer (#8427).

### CODE REVIEW

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Comment by tkanmae** [comment]
@take-cheeze Hi, I see that the CI test failed. Can you point me to where to look at? I skimmed through [the Jenkins build page](https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2498/), but could not figure out what went wrong.

**Comment by take-cheeze** [comment]
@tkanmae 
Thank you for the contribution.
Basically the jenkins failure is due to our CI environment and onnchainer* should be what we need to care.
I'll merge this when jenkins passes.
Thank you again for the PR!

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Pull request merged**
