### PR TITLE
Fix BatchNormalization with lazy initialization fail on GPU #5682

### LINKED ISSUE #5682: BatchNormalization with lazy initialization fail on GPU
# Problem description

```python
import chainer
import numpy as np

x = np.arange(12).reshape(4, 3).astype(np.float32) ** 2
x = chainer.cuda.to_gpu(x)
x = chainer.Variable(x)

# lazy initialization by not providing size
bn = chainer.links.BatchNormalization(axis=0)
bn.to_gpu()

bn(x)
```

This fails with following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-3375da8069af> in <module>()
----> 1 bn(x)

/usr/local/lib/python3.6/dist-packages/chainer/link.py in __call__(self, *args, **kwargs)
    240         if forward is None:
    241             forward = self.forward
--> 242         out = forward(*args, **kwargs)
    243 
    244         # Call forward_postprocess hook

/usr/local/lib/python3.6/dist-packages/chainer/links/normalization/batch_normalization.py in forward(self, x, **kwargs)
    297             ret = functions.batch_normalization(
    298                 x, gamma, beta, eps=self.eps, running_mean=self.avg_mean,
--> 299                 running_var=self.avg_var, decay=decay, axis=self.axis)
    300         else:
    301             # Use running average statistics or fine-tuned statistics.

/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py in batch_normalization(x, gamma, beta, **kwargs)
    830 
    831     return BatchNormalization(eps, running_mean, running_var, decay,
--> 832                               axis).apply((x, gamma, beta))[0]
    833 
    834 

/usr/local/lib/python3.6/dist-packages/chainer/function_node.py in apply(self, inputs)
    261                 outputs = static_forward_optimizations(self, in_data)
    262             else:
--> 263                 outputs = self.forward(in_data)
    264 
    265         # Check for output array types

/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py in forward(self, inputs)
    222                 x_desc.value, x.data.ptr, x_desc.value,
    223                 y.data.ptr, derivedBnDesc.value, gamma.data.ptr,
--> 224                 beta.data.ptr, factor, running_mean.data.ptr,
    225                 running_var.data.ptr, self.eps,
    226                 self.mean.data.ptr, self.inv_std.data.ptr)

AttributeError: 'memoryview' object has no attribute 'ptr'
```

Environment

```
Platform: Linux-4.14.65+-x86_64-with-Ubuntu-18.04-bionic
Chainer: 5.0.0
NumPy: 1.14.6
CuPy:
  CuPy Version          : 5.0.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9020
  CUDA Driver Version   : 9020
  CUDA Runtime Version  : 9020
  cuDNN Build Version   : 7201
  cuDNN Version         : 7201
  NCCL Build Version    : 2213
iDeep: Not Available
```

# Reason for failure

The problem was that `running_mean` was numpy array where it should've been a cupy array.

I figured out the problem lies in BatchNormalization's initializer. https://github.com/chainer/chainer/blob/v5.0.0/chainer/links/normalization/batch_normalization.py#L323

```python
def _init_array(initializer, default_value, size, dtype):
    if initializer is None:
        initializer = default_value
    initializer = initializers._get_initializer(initializer)
    return initializers.generate_array(initializer, size, numpy, dtype=dtype)
```

As you can see, `numpy` is hard coded in initializer.

I will send a pull request shortly.

### PR DESCRIPTION
**Pull request by koreyou**
Fix #5682 . I have done test but I was not able to do multi-GPU test.

### CODE REVIEW

**Comment by toslunar** [comment]
Thanks for your contribution.  Are you interested in adding a testcase that failed before the PR?

**Comment by koreyou** [comment]
Sure. Would probably do that on the weekend.

**Comment by koreyou** [comment]
Hi. I implemented the test. 

It (correctly) fails on the BatchNormalization before the fix. It is, of course, OK after the fix was introduced.
Could you review the test because I am not so familiar with chainer testing conventions.

Running test on code before the fix:

```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /content/chainer, inifile: setup.cfg
collected 402 items                                                            

tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py . [  0%]
..........s......s......s......s......s......s......s......s......s..... [ 18%]
.s......s......s......s......s......s......s......s......s......s......s [ 36%]
......s......s......s......s......s......s......s......s......s......s.. [ 53%]
....s......s......s......s......s......s......s......s......s......s.... [ 71%]
..s......s.................s.......s.......s.......s.......s.......s.... [ 89%]
...s.......s...............F....F....F...                                [100%]

=================================== FAILURES ===================================
_____________ TestChannalSizeInference_param_0.test_inference_gpu ______________
/usr/local/lib/python3.6/dist-packages/chainer/testing/parameterized.py:60: in wrap
    six.raise_from(e_new.with_traceback(e.__traceback__), None)
/usr/local/lib/python3.6/dist-packages/chainer/testing/parameterized.py:43: in wrap
    return method(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py:80: in wrapper
    fail()
/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py:51: in fail
    instance.fail(msg)
E   AssertionError: Parameterized test failed.
E   
E   Base test method: TestChannalSizeInference.test_inference_gpu
E   Test parameters:
E     shape: (5, 4, 3, 2)
E     axis: (0, 2, 3)
E   
E   AssertionError: 
E   Fail: 3, Success: 0
E   
E   The first error message:
E   Traceback (most recent call last):
E     File "/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py", line 60, in <lambda>
E       lambda: f(ins, *args[1:], **kwargs),
E     File "/content/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py", line 478, in test_inference_gpu
E       bn(cuda.to_gpu(self.x))
E     File "/usr/local/lib/python3.6/dist-packages/chainer/link.py", line 242, in __call__
E       out = forward(*args, **kwargs)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/links/normalization/batch_normalization.py", line 299, in forward
E       running_var=self.avg_var, decay=decay, axis=self.axis)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py", line 836, in batch_normalization
E       axis).apply((x, gamma, beta))[0]
E     File "/usr/local/lib/python3.6/dist-packages/chainer/function_node.py", line 263, in apply
E       outputs = self.forward(in_data)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py", line 226, in forward
E       beta.data.ptr, factor, running_mean.data.ptr,
E   AttributeError: 'memoryview' object has no attribute 'ptr'
_____________ TestChannalSizeInference_param_1.test_inference_gpu ______________
/usr/local/lib/python3.6/dist-packages/chainer/testing/parameterized.py:60: in wrap
    six.raise_from(e_new.with_traceback(e.__traceback__), None)
/usr/local/lib/python3.6/dist-packages/chainer/testing/parameterized.py:43: in wrap
    return method(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py:80: in wrapper
    fail()
/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py:51: in fail
    instance.fail(msg)
E   AssertionError: Parameterized test failed.
E   
E   Base test method: TestChannalSizeInference.test_inference_gpu
E   Test parameters:
E     shape: (5, 4)
E     axis: 0
E   
E   AssertionError: 
E   Fail: 3, Success: 0
E   
E   The first error message:
E   Traceback (most recent call last):
E     File "/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py", line 60, in <lambda>
E       lambda: f(ins, *args[1:], **kwargs),
E     File "/content/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py", line 478, in test_inference_gpu
E       bn(cuda.to_gpu(self.x))
E     File "/usr/local/lib/python3.6/dist-packages/chainer/link.py", line 242, in __call__
E       out = forward(*args, **kwargs)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/links/normalization/batch_normalization.py", line 299, in forward
E       running_var=self.avg_var, decay=decay, axis=self.axis)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py", line 836, in batch_normalization
E       axis).apply((x, gamma, beta))[0]
E     File "/usr/local/lib/python3.6/dist-packages/chainer/function_node.py", line 263, in apply
E       outputs = self.forward(in_data)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py", line 226, in forward
E       beta.data.ptr, factor, running_mean.data.ptr,
E   AttributeError: 'memoryview' object has no attribute 'ptr'
_____________ TestChannalSizeInference_param_2.test_inference_gpu ______________
/usr/local/lib/python3.6/dist-packages/chainer/testing/parameterized.py:60: in wrap
    six.raise_from(e_new.with_traceback(e.__traceback__), None)
/usr/local/lib/python3.6/dist-packages/chainer/testing/parameterized.py:43: in wrap
    return method(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py:80: in wrapper
    fail()
/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py:51: in fail
    instance.fail(msg)
E   AssertionError: Parameterized test failed.
E   
E   Base test method: TestChannalSizeInference.test_inference_gpu
E   Test parameters:
E     shape: (5, 4, 3)
E     axis: (0, 1)
E   
E   AssertionError: 
E   Fail: 3, Success: 0
E   
E   The first error message:
E   Traceback (most recent call last):
E     File "/usr/local/lib/python3.6/dist-packages/chainer/testing/condition.py", line 60, in <lambda>
E       lambda: f(ins, *args[1:], **kwargs),
E     File "/content/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py", line 478, in test_inference_gpu
E       bn(cuda.to_gpu(self.x))
E     File "/usr/local/lib/python3.6/dist-packages/chainer/link.py", line 242, in __call__
E       out = forward(*args, **kwargs)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/links/normalization/batch_normalization.py", line 299, in forward
E       running_var=self.avg_var, decay=decay, axis=self.axis)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py", line 836, in batch_normalization
E       axis).apply((x, gamma, beta))[0]
E     File "/usr/local/lib/python3.6/dist-packages/chainer/function_node.py", line 263, in apply
E       outputs = self.forward(in_data)
E     File "/usr/local/lib/python3.6/dist-packages/chainer/functions/normalization/batch_normalization.py", line 226, in forward
E       beta.data.ptr, factor, running_mean.data.ptr,
E   AttributeError: 'memoryview' object has no attribute 'ptr'
============== 3 failed, 349 passed, 50 skipped in 37.97 seconds ===============
```

**Comment by koreyou** [comment]
I removed the retry decorator from the newly added test.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
