### PR TITLE
Use `_has_chainerx_array` in `Variable`

### PR DESCRIPTION
**Pull request by okuta**
This PR is performance improvement that relates #6016.

### CODE REVIEW

**Comment by okapies** [comment]
It seems great but these kind of fix was once reverted based on the discussion in https://github.com/chainer/chainer/pull/6016#pullrequestreview-196876021. How do you think? @niboshi

**Comment by niboshi** [comment]
@okapies 
I thought it's not worthwhile when it's viewed as performance optimization, but now I feel it's ok because this can be seen as refactoring (`_has_chainerx_array` is more straightforward to distinguish chainerx arrays than `xp is chainerx`).

**Comment by niboshi** [comment]
In that sense I'd put `cat:code-fix` rather than `cat:performance`.

**Comment by okuta** [comment]
Thank you for your advice. I added the label.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
