### PR TITLE
fix undocumented functions and links

### LINKED ISSUE #4038: Some functions and links are undocumented
I found that followings are not documented. Maybe we should automate this check.

Functions:

* chainer.functions.f1_score()
* chainer.functions.precision()
* chainer.functions.recall()
* chainer.functions.decov()
* chainer.functions.absolute()
* chainer.functions.batch_det()
* chainer.functions.det()
* chainer.functions.zoneout()
* chainer.functions.batch_renormalization()
* chainer.functions.fixed_batch_renormalization()
* chainer.functions.unpooling_nd()

Links:

* chainer.links.StatefulMGU
* chainer.links.StatelessMGU
* chainer.links.Parameter
* chainer.links.BatchRenormalization

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #4038

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Some of these functions are missing actual docs (incl. summaries, meaning that the rightmost column is blank in the docs). Should we address those in a different PR?

**Comment by kmaehashi** [comment]
@hvy OK, I'll add docs for them first, in separate PR.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
