### PR TITLE
[backport] Check optional dependencies at runtime

### PR DESCRIPTION
**Pull request by takagi**
Backport of #5425

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
Another thing to point out is that this implementation depends on `setuptools`, which is not a standard library  (although chainer has already been depending on `setuptools` via `chainer.testing.helper`.)

**Comment by kmaehashi** [comment]
@niboshi 

> Is it ok to backport this PR?
> Change of dependency is not a trivial change.
> Some existing system which (perhaps incorrectly) rely on this dependency will break with this.

I consider this case as a bug rather than just an enhancement, as behavior described in #5425 is obviously unwanted for users.
I'd like to know if you have any concrete use-case that is affected by this change.

> Another thing to point out is that this implementation depends on setuptools, which is not a standard library (although chainer has already been depending on setuptools via chainer.testing.helper.)

I think we can assume use of `setuptools` is safe because it is a common convention to use it for package installation. (note that it's already required in Chainer installation and no one claims it https://github.com/chainer/chainer/blob/7565ecb1a49a396118527fe0db87bdba1d4c4680/setup.py#L7)

**Comment by niboshi** [comment]
> I'd like to know if you have any concrete use-case that is affected by this change.

Yes.
In a team I belong to, CI system stopped working by this change.
In that system CuPy is first installed without dependency followed by Chainer.
The fault was the incorrectly written CI script, but that's what happened to us and could happen to external users as well.

>I think we can assume use of `setuptools` is safe because it is a common convention to use it for package installation.

Discussed with @beam2d and the dependency itself is OK, but we should explicitly write it in `requirements` in `setup.py` as well as documentation.

**Comment by kmaehashi** [comment]
> The fault was the incorrectly written CI script, but that's what happened to us and could happen to external users as well.

OK. In addition, as users are now required to manually update CuPy after updating Chainer, this may be a bit large change for users. I'd avoid backporting this.

> Discussed with @beam2d and the dependency itself is OK, but we should explicitly write it in requirements in setup.py as well as documentation.

I also feel it makes sense, will work on separate PR.

**Pull request closed without merging**
