### PR TITLE
Improve example tests (2)

### PR DESCRIPTION
**Pull request by niboshi**
This is yet another implementation of example test improvement (the earlier one is #7277).

>- Some examples have `--test` argument, which is irrelevent to ordinary readers and often confusing. This PR eliminates the necessity of it by altering script files on the fly.
>- Moves the test logic from https://github.com/chainer/chainer-test to the chainer repository, to make it easier to maintain.
>
>This is also preparation of #6094 (see #7280)

Instead of generating test example script on-the-fly using template comments, in this PR both example scripts (for users and for test) are version-controlled. Difference between them is marked by marker comments (`# BEGIN ADDITIONAL TEST CODE` and `# END ADDITIONAL TEST CODE`) and consistency of non-marked part is checked in the test runner.

### CODE REVIEW

**Comment by niboshi** [comment]
@kmaehashi ping

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
