### PR TITLE
New style swapaxis function

### PR DESCRIPTION
**Pull request by okuta**
Please see #3147.

### CODE REVIEW

**Comment by okuta** [comment]
Do I need to add a double backward test?
I think this `backward` function is same as forward pass. And, code is clear and simple.
Thus, test is not so necessary IMO.

**Comment by niboshi** [comment]
This is black-box test, so it doesn't depend on what the implementation is like.

**Comment by okuta** [comment]
I added test

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
