### PR TITLE
Add `.mergify.yml`

### PR DESCRIPTION
**Pull request by niboshi**
Integrating [Mergify](https://mergify.io/) for automatic merge.

https://doc.mergify.io/index.html

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Added ChainerCV CIs as requirements.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
