### PR TITLE
Add doctest and document generation to CI

### PR DESCRIPTION
**Pull request by imos**
Examples of execution results:
- https://ci.preferred.jp/chainer.docs/13528/
  - This generates the following page as specified at the end of the execution log:
     https://storage.googleapis.com/chainer-artifacts-pfn-public-ci/13528/index.html
- https://ci.preferred.jp/chainer.doctest/13529/

### CODE REVIEW

**Comment by imos** [comment]
Jenkins, test this please.

**Comment by imos** [comment]
Friendly ping @kmaehashi

**Comment by toslunar** [comment]
Resolved the merge conflicts.

**Comment by kmaehashi** [comment]
Will merge after following tests success.
https://ci.preferred.jp/chainer.docs/52197/
https://ci.preferred.jp/chainer.doctest/52198/
After merging this PR webhook needs to be configured.

**Pull request closed without merging**
