### PR TITLE
Fix flake8 error

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix error introduced in #7622

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Hm, massive CI failure. Is it related?

**Comment by asi1024** [comment]
All CI failures seem unrelated to this PR.
I confirmed that flake8 turned success. Can I merge this PR?

**Comment by toslunar** [comment]
It has been backported as 5cacbf938f44c5d1b5799c0a967e0cd3640b688f (in #7659).

**Pull request merged**
