### PR TITLE
let stalebot ignore issues labelled with roadmap

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by hvy** [comment]
LGTM!

**Comment by hvy** [comment]
No need to backport? `stale.yml` isn't created in the stable branch.

**Comment by kmaehashi** [comment]
Ah yes, no need to backport, as config in the default branch (`master` in this repos) is effective. 
https://github.com/apps/stale

**Comment by hvy** [comment]
Thanks for the quick response!

**Pull request merged**
