### PR TITLE
Op registration: connection

### PR DESCRIPTION
**Pull request by niboshi**
Part of #6692

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
@asi1024 Fixed.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failure seems unrelated to this PR. LGTM.

**Comment by hvy** [comment]
Removing `to-be-backported` as we decided not to backport non-critical PRs.

**Pull request merged**
