### PR TITLE
Fix occasional test failure of `l2normalize` with float16

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
ping? @takagi

**Comment by takagi** [comment]
LGTM!

**Comment by toslunar** [comment]
Thanks!

**Pull request merged**
