### PR TITLE
Remove stable version section from README

### PR DESCRIPTION
**Pull request by niboshi**
Related: #7948

I don't know how this section would be useful.

### CODE REVIEW

**Comment by kmaehashi** [comment]
I think we need to leave it as is for users. Without it, there's no explicit link for v6 branch; v6 users cannot find the codebase and examples.

**Comment by Hakuyume** [comment]
In the README, `Examples` is linked to master branch, where `Docs`, `Install Guide`, and `Concepts` are linked to stable. How about changing `Examples` to refer stable examples? With this modification, we can remove stable version section, I think.

**Comment by kmaehashi** [comment]
> In the README, Examples is linked to master branch, where Docs, Install Guide, and Concepts are linked to stable. How about changing Examples to refer stable examples? With this modification, we can remove stable version section, I think.

Thanks for pointing that issue out. However I still think it's unreasonable to reduce information only to cut our cost to bump the version after major release.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

As v7 is now the only stable version, I agree with removing this.

**Pull request merged**
