### PR TITLE
Add ChainerX CUDA float16

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Compilation failed on Jenkins.
```
19:28:01     /tmp/pip-req-build-x87j82cc/chainerx_cc/chainerx/cuda/float16.cuh(45): error: more than one conversion function from "__half" to a built-in type applies:
19:28:01                 function "__half::operator float() const"
19:28:01                 function "__half::operator short() const"
19:28:01                 function "__half::operator unsigned short() const"
19:28:01                 function "__half::operator int() const"
19:28:01                 function "__half::operator unsigned int() const"
19:28:01                 function "__half::operator long long() const"
19:28:01                 function "__half::operator unsigned long long() const"
19:28:01                 function "__half::operator __nv_bool() const"
```

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Merge #6171 first.

**Comment by asi1024** [comment]
Rebased. Jenkins, test this please.

**Comment by niboshi** [comment]
`test_conv[float16-cuda:0-True-x_shape5-w_shape5-b_shape5-1-0]`
>E       chainerx.ChainerxError: CUDNN_STATUS_ARCH_MISMATCH

Also there're errors in clang-format and cpplint.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
`TestNonparameterizedLinear_use_chainerx_true__chainerx_device_cuda:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_0_{W_dtype=<class 'numpy.float16'>, c_contiguous=True, nobias=True, x_dtype=<class 'numpy.float16'>, x_shape={'n_batch_axes': 1, 'data_shape': (3,)}}.test_backward `

>E   chainerx.ChainerxError: CUBLAS_STATUS_NOT_SUPPORTED

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins failure is irrelevant.

**Comment by niboshi** [comment]
Please fix the conflict.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
