### PR TITLE
Op registration: array members

### PR DESCRIPTION
**Pull request by niboshi**
Part of #6692

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Fixed test failures.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failure is unrelated to this PR.

**Comment by hvy** [comment]
Removing `to-be-backported` as we decided not to backport non-critical PRs.

**Pull request merged**
