### PR TITLE
Partially output_grad support on fake_as_funcnode

### PR DESCRIPTION
**Pull request by disktnk**
Current `fake_as_funcnode` (`@as_funcnode`) does not set backward function, and occur error when exporting with `output_grad=True`. This PR enables `output_grad` option partially. When the target function returns `chainer.Variable`(s), `fake_as_funcnode` (`WrappedFunctionNode` class more correctly) returns gradients on backward.

### CODE REVIEW

**Comment by shinh** [comment]
I'm fairly sure this has some flaw, though I have confirmed nothing yet. I doubt `chainer.grad` works with this logic or `WrappedFunctionNode.backward` would compute gradients outside the graph. Let me see..

**Comment by shinh** [comment]
Sent a PR for this PR: https://github.com/disktnk/chainer/pull/1

**Comment by disktnk** [comment]
Merge, I could check the logic, thx!

**Comment by shinh** [comment]
Jenkins, test this please!

**Comment by shinh** [comment]
Jenkins, test this please!

**Comment by shinh** [comment]
Flaky?

Jenkins, test this please!

**Pull request merged**
