### PR TITLE
Fix SGEMV error

### LINKED ISSUE #3428: Double backprop exception
A simple double-backprop operation fails with an exception.
Tested on v3.0.0rc1 on Windows and Linux.

The forward pass runs successful, but the exception is thrown on the backward pass.

* Conditions
  - Chainer v3.0.0rc1
  - CuPy 1.0.3
  - Debian stretch/sid x86_64
  - CUDA v8.0, cuDNN 8.0 v6.0

* Code to reproduce (`problem.py`)

```python
import chainer
import chainer.functions as F
import chainer.links as L
from chainer import optimizers

import numpy as np

print chainer.__version__

class GFunc(chainer.Chain):
    def __init__(self, d, dim_hidden=32):
        super(GFunc, self).__init__(
            l0 = L.Linear(d, dim_hidden),
            l1 = L.Linear(dim_hidden, dim_hidden),
            l2 = L.Linear(dim_hidden, d)
        )
        self.d = d

    def __call__(self, x):
        h1 = F.relu(self.l0(x))
        h2 = F.relu(self.l1(h1))
        h3 = self.l2(h2)

        return h3

class LDGEObjective(chainer.Chain):
    def __init__(self, G):
        super(LDGEObjective, self).__init__(
            G = G
        )

    def __call__(self, x):
        batchsize = x.shape[0]
        g = self.G(x)
        obj = F.sum(g*g)/batchsize

        # Compute gradient term
        gsum = F.sum(g)
        gx = chainer.grad((gsum,), (x,), enable_double_backprop=True)
        xgrad = gx[0]
        obj += 2.0*F.sum(xgrad)/batchsize

        return obj

G = GFunc(1)
ldge = LDGEObjective(G)

x = np.random.normal(size=(3,1)).astype(np.float32)
x = chainer.Variable(x)

obj = ldge(x)
print obj.data

obj.backward()
```

* Error messages, stack traces, or logs

```
$ python ./problem.py
3.0.0rc1
-0.602684617043
Traceback (most recent call last):
  File "./problem.py", line 54, in <module>
    obj.backward()
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/variable.py", line 852, in backward
    self._backward_main(retain_grad)
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/variable.py", line 953, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/function_node.py", line 487, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/functions/connection/linear.py", line 53, in backward
    gW = linear(gy.T, x.T)
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/functions/connection/linear.py", line 108, in linear
    y, = LinearFunction().apply(args)
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/function_node.py", line 221, in apply
    outputs = self.forward(in_data)
  File "/mnt/nfs/users/senowozi/local/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/functions/connection/linear.py", line 37, in forward
    y = x.dot(W.T).astype(x.dtype, copy=False)
ValueError: On entry to SGEMV parameter number 8 had an illegal value
```

### PR DESCRIPTION
**Pull request by niboshi**
Add workaround code for SGEMV error (fixes #3428 and #2744).

### CODE REVIEW

**Comment by okuta** [comment]
Please add test.

**Comment by niboshi** [comment]
Added tests.
Also added `1 in x.shape` to the conditions.

**Comment by okuta** [comment]
How about using `x.astype(x.dtype, order='A', copy=False)`?

**Comment by niboshi** [comment]
Note that arrays are always non-contiguous. In that case, `ascontiguousarray` does exactly the same as `astype`, but it expresses the intent more directly.

**Comment by okuta** [comment]
OK, I understand.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
