### PR TITLE
Improve version embedding

### PR DESCRIPTION
**Pull request by okuta**
Current Chainer requires installed state.
This fix relaxing limitation of environment. For example, [Pyinstaller.](http://www.pyinstaller.org/)

### CODE REVIEW

**Comment by takagi** [comment]
Please fix flake8.

**Comment by niboshi** [comment]
The same comment as https://github.com/cupy/cupy/pull/639: how about `imp.load_source`?

**Comment by niboshi** [comment]
Please update to use `imp.load_source`.

Also please rebase to master (otherwise we would have to wait for Travis for a while)

**Comment by okuta** [comment]
I fixed.

**Comment by niboshi** [comment]
Please fix test errors.

**Comment by takagi** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
