### PR TITLE
Update style check tools

### PR DESCRIPTION
**Pull request by niboshi**
Fix: #4610
Related: #4674

### CODE REVIEW

**Comment by niboshi** [comment]
@kmaehashi @beam2d Can you merge this?

**Comment by toslunar** [comment]
The Jenkins failure (`links_tests.normalization_tests.test_batch_renormalization.BatchRenormalizationTest_param_9.test_forward_multi_gpu`) is irrelevant to the PR.

**Comment by kmaehashi** [comment]
## Context behind this PR

* We are planning to stop using ``hacking`` in v5 final release. The motivation is to make version of each tool under our control, so that we can use the latest tools (ie, which includes the latest bug fixes) as early as possible.
* As a first step, we substituted ``hacking`` package with explicit tool requirements with version specified. **Please note that this is currently under the trial phase; we may revise this later.**
* This PR does not intend to change our coding style.
* The `ignore` rules are adjusted so that code that passes check with toolset installed via ``hacking==1.0.0`` should be able to pass check with toolset installed via new dependencies proposed in this PR. However, the reverse may not be true; it will be confirmed during the trial period.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
