### PR TITLE
Pass raw arrays to the loss function in `MultiprocessParallelUpdater`

### LINKED ISSUE #2811: `MultiprocessParallelIUpdater` does not pass raw arrays to the loss function
Chainer v2 introduced a change that raw arrays are passed to the loss function by the updater:
http://docs.chainer.org/en/stable/upgrade.html#updater-and-evaluator-pass-raw-data-arrays-to-the-loss-function

`MultiprocessParallelUpdater` does not follow this change, which is inconsistent:
https://github.com/chainer/chainer/blob/master/chainer/training/updaters/multiprocess_parallel_updater.py#L236

### PR DESCRIPTION
**Pull request by tkerola**
Fixes #2811

### CODE REVIEW

**Comment by delta2323** [comment]
Thank you for your PR. Could you add unit tests for checking the behavior?

**Comment by tkerola** [comment]
Hi, I added a unit test.

**Comment by delta2323** [comment]
@tkerola Thank you!

@mitmul Can you check the PR as you assigned yourself as a reviewer?

**Comment by mitmul** [comment]
@tkerola The test code is also run when NCCL is not installed. So, it causes error raised from MultiprocessingParallelUpdater, and the Jenkins test job fails. We need to address this problem before merging it.

The error the Jenkins job shows is the below:

```
22:58:26 ======================================================================
22:58:26 ERROR: test_update_uses_raw_array (test_multiprocess_parallel_updater.TestRawArray)
22:58:26 ----------------------------------------------------------------------
22:58:26 Traceback (most recent call last):
22:58:26   File "chainer/tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py", line 168, in test_update_uses_raw_array
22:58:26     iters, optimizer, devices=devices)
22:58:26   File "chainer/chainer/training/updaters/multiprocess_parallel_updater.py", line 116, in __init__
22:58:26     'NCCL is not enabled. MultiprocessParallelUpdater '
22:58:26 Exception: NCCL is not enabled. MultiprocessParallelUpdater requires NCCL.
22:58:26 Please reinstall chainer after you install NCCL.
22:58:26 (see https://github.com/pfnet/chainer#installation).
```

**Comment by tkerola** [comment]
Hi, I disabled the test when NCCL is not installed.

**Comment by mitmul** [comment]
@tkerola Thanks! LGTM

**Pull request merged**
