### PR TITLE
Use more precise timer in funciton_hooks/timer.py

### PR DESCRIPTION
**Pull request by crcrpar**
time.time() of python2.7 on Windows is 16 milliseconds precision.

## change
- use more precise timer
- use assert not self.assert*

ref: https://stackoverflow.com/questions/1938048/high-precision-clock-in-python
rel: https://github.com/chainer/chainer/pull/5842#issuecomment-452553988

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
@toslunar can we assign you on this ticket?

**Comment by toslunar** [comment]
Windows tests are failing because the timer in the test is less precise than the new timer.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
AppVeyor passed in https://ci.appveyor.com/project/pfnet/chainer/builds/21623212

**Pull request merged**
