### PR TITLE
[backport] Document `chainer.testing.LinkTestCase`

### PR DESCRIPTION
**Pull request by toslunar**
Backport of #6895

### CODE REVIEW

**Comment by toslunar** [comment]
[automatic post] Jenkins, test this please.

**Comment by hvy** [comment]
Let me merge this backport as it seems straight forward. However, it looks like the section isn't rendered correctly (master). Let me address that in a separate PR. https://docs.chainer.org/en/latest/reference/check.html

**Comment by hvy** [comment]
LGTM!

**Comment by crcrpar** [comment]
Hmm, the documentation was correctly rendered in my local environment.

Sorry to bother you.

**Comment by hvy** [comment]
It rendered correctly in my environment too. Actually it seems like the build on readthedocs is failing (because of ChainerX).

**Comment by crcrpar** [comment]
Ah, I see.

Thank you for the info.

**Pull request merged**
