### PR TITLE
Improve function reference and documentation

### PR DESCRIPTION
**Pull request by kmaehashi**
Related to #4052.

### CODE REVIEW

**Comment by niboshi** [comment]
It misses two requirements pointed out in https://github.com/chainer/chainer/pull/4052#issuecomment-350364224?

**Comment by toslunar** [comment]
Yes.  I'd like to have something like the following:
1. "to backprop through the Link, the output of activation function should be a Variable whose gradient  is `backward`-ed to a gradient of the input"
2. "parameters in the activation function are not caught by the Link"

**Comment by kmaehashi** [comment]
Thanks for comments!

> 1. "to backprop through the Link, the output of activation function should be a Variable whose gradient is backward-ed to a gradient of the input"

Fixed by saying: `Returned value must be a Variable derived from the input Variable to perform backpropagation on the variable.`

> 2. "parameters in the activation function are not caught by the Link"

Sorry, I couldn't get the point of this comment. What kind of mistakes are expected without this description?

**Comment by toslunar** [comment]
>> 2.

`MLPConvolution2D(..., activation=chainer.links.PReLU)` is a mistake.

**Comment by kmaehashi** [comment]
Thanks, I understood the concerns. I added

```
            It should not be an
            :doc:`activation functions with parameters </reference/links>`
            (i.e., :class:`~chainer.Link` instance).
```

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
