### PR TITLE
Fix fp16 issue in batch normalization

### PR DESCRIPTION
**Pull request by anaruse**
This PR aims to fix a fp16 related issue of batch normalization layer, resulting in NaN.

When dtype of x is fp16 and cudnn is used, "output cache" memory for cudnn is allocated as fp16 array now, but it must be allocated as fp32 array. 

imagenet example, resnet50, fp16
```
w/o this PR
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
1           32          nan         nan                   0              0                         0.01
2           64          nan         nan                   0              0                         0.01
3           96          nan         nan                   0              0                         0.01
```
```
with this PR
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
1           32          4.375       143.375               0.0476074      0.028244                  0.01
2           64          3.83398     17.2188               0.0866699      0.085083                  0.01
3           96          3.41992     3.54102               0.118896       0.121948                  0.01
```

This is related to https://github.com/chainer/chainer/issues/6168

### CODE REVIEW

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by anaruse** [comment]
I've fixed the PR so that arrays for cuDNN output cache are allocated in CuPy rather than Chainer.
Please note that, this PR depends on https://github.com/cupy/cupy/pull/2060 now.

**Comment by takagi** [comment]
Now cupy/cupy#2060 is merged.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
LGTM! The CI failure is not relevant to this change.

**Pull request merged**
