### PR TITLE
Check lengths of args of `chainer.grad`

### LINKED ISSUE #6579: `chainer.grad` does not check `len(outputs) == len(grad_outputs)`
What is worse, default grad for each output is 1.

* Code to reproduce
```python
import chainer
import numpy as np
x1 = chainer.Variable(np.array(2, np.float32))
x2 = chainer.Variable(np.array(3, np.float32))
y1, y2 = chainer.functions.identity(x1, x2)
print(chainer.grad([y1, y2], [x1, x2], None))
print(chainer.grad([y1, y2], [x1, x2], [None]))
print(chainer.grad([y1, y2], [x1, x2], [None, None]))
```

* Error messages, stack traces, or logs
```
[variable(1.), variable(1.)]
[variable(1.), None]
[variable(1.), variable(1.)]
```

### PR DESCRIPTION
**Pull request by toslunar**
Fix #6579.

### CODE REVIEW

**Comment by toslunar** [comment]
- The change is not really safe to be backported.
- No upgrade guide is needed because the error messages are clear.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
