### PR TITLE
Improve docs of links/connection/linear

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
This is PR for improving docs of functions/links. Related issue: #2182

Modified functions/links:

- links/connection/linear.py

### CODE REVIEW

**Comment by mitmul** [comment]
@keisuke-umezawa Could you rebase it to the current master?

**Comment by keisuke-umezawa** [comment]
@mitmul I rebased this branch.

**Comment by keisuke-umezawa** [comment]
@mitmul I rebased it.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
LGTM

**Pull request merged**
