### PR TITLE
Allow comma separated keys in `testing.product`

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
This PR allows pytest-style parameter destruction in `chainer.testing.product`, like
```py
chainer.testing.product({
    'param1,param2': [
        (value1_1, value2_1),
        (value1_2, value2_2),
        (value1_3, value2_3),
    ],
    'param3': [param3_1, param3_2],
})
```

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Travis failure seems unrelated. Need to verify Jenkins results.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
CI failures seem unrelated. LGTM!

**Pull request merged**
