### PR TITLE
[backport] Remove some CI requirements

### PR DESCRIPTION
**Pull request by okuta**
Backport of #5865

### CODE REVIEW

**Comment by okuta** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
I think we don't have to backport this fix.

**Comment by okuta** [comment]
OK.

**Comment by niboshi** [comment]
How about restricting to `pytest-cov<=2.6.0` instead?
We should be careful about changing requirements (even removal) in the stable branch.
pytest-cov 2.6.1 was released just a day ago, so it should be relatively safer to change `pytest-cov` to `pytest-cov<=2.6.0`.

...But as they're requirements for `travis` and `appveyor`, it's unlikely that any third-party depend on it.
So it's not a strong opinion.

**Comment by niboshi** [comment]
#5968 has been merged.

**Pull request closed without merging**
