### PR TITLE
Make weight standardization faster

### PR DESCRIPTION
**Pull request by gwtnb**
Make weight standardization faster by using group normalization. Group normalization is fast on GPU because Chainer uses the batch normalization function in cuDNN.

Using [the cifar example](https://github.com/chainer/chainer/blob/e0d92fe68a5285287d0b4e150abdca1c5b2a9198/examples/cifar/train_cifar.py) with following modification
```diff
% git diff
diff --git a/examples/cifar/models/VGG.py b/examples/cifar/models/VGG.py
index 45935f0c2..301320f7c 100644
--- a/examples/cifar/models/VGG.py
+++ b/examples/cifar/models/VGG.py
@@ -1,6 +1,7 @@
 import chainer
 import chainer.functions as F
 import chainer.links as L
+import chainer.link_hooks
 
 
 class Block(chainer.Chain):
@@ -24,8 +25,8 @@ class Block(chainer.Chain):
         super(Block, self).__init__()
         with self.init_scope():
             self.conv = L.Convolution2D(None, out_channels, ksize, pad=pad,
-                                        nobias=True)
-            self.bn = L.BatchNormalization(out_channels)
+                                        nobias=True).add_hook(chainer.link_hooks.WeightStandardization())
+            self.bn = L.GroupNormalization(32)
 
     def forward(self, x):
         h = self.conv(x)
```

With this PR
```
%  python train_cifar.py -g 0 -e 1
...
...
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           2.52634     2.30258               0.101003       0.100119                  46.6895       
```

Without this PR
```
% python train_cifar.py -g 0 -e 1                                                                                                                                                                                                                             
...
...
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           2.51579     2.21687               0.105978       0.166899                  73.358        

```

### CODE REVIEW

**Comment by crcrpar** [comment]
Just dropping a reference.
Use of cuDNN batch normalization for speed was mentioned in the first PR of WeightStandardization. https://github.com/chainer/chainer/pull/6678#pullrequestreview-219966111

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
@toslunar do you have any comments on this speed-memory trade-off?

**Comment by gwtnb** [comment]
On a layer with 2048 channels, it costs just 2 * 4 * 2048 = 16 KB when the dtype is float32. It looks small.

**Comment by hvy** [comment]
That makes sense.

I then guess that `chainer.functions.normalization._standardize` is no longer needed?

**Comment by gwtnb** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM, Jenkins test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Pull request merged**
