### PR TITLE
Support all float dtypes in `F.normalize`

### PR DESCRIPTION
**Pull request by takagi**
This PR follows #4582 to support all float dtypes in `F.normalize`.

### CODE REVIEW

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
You mean, computing L2 norm without using `numpy.linalg.norm` to keep `float16` at least for old numpy environment? (Or just casting back to FP16 in such case is enough?)

**Comment by toslunar** [comment]
I'd like to compare with `numpy.linalg.norm` in the tests.  Therefore I prefer casting back to `float16`.

**Comment by takagi** [comment]
Okay, I got.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Pull request merged**
