### PR TITLE
Simplify 'F.exp', 'F.log' test

### PR DESCRIPTION
**Pull request by hikjik**
Simplifies test_exponential using testing.FunctionTestCase
Refer to [#6071](https://github.com/chainer/chainer/issues/6071)

### CODE REVIEW

**Comment by hikjik** [comment]
The CI failures are probably unrelated

**Comment by Crissman** [comment]
LGTM. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins tests not run. Travis error looks unrelated. Jenkins, test this please.

**Comment by Crissman** [comment]
Test failures look unrelated. Merging.

**Pull request merged**
