### PR TITLE
New style AveragePoolingND/MaxPoolingND/UnpoolingND

### PR DESCRIPTION
**Pull request by rezoo**
Related to #2745. This PR aims to update `AveragePoolingND`, `MaxPoolingND`, and `UnpoolingND` to support double back propagations.
After merging this PR, I would like to integrate `Pooling2D` and `PoolingND` (it includes the support of `cover_all=True` in AveragePoolingND).

(This is a re-submission of #4131)

### CODE REVIEW

**Comment by rezoo** [comment]
I've finished implementation.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by rezoo** [comment]
Happy new year!
@mitmul Hi, is there any progress?

**Comment by mitmul** [comment]
@rezoo Sorry for my late reaction. I'll review it soon.

**Comment by rezoo** [comment]
@mitmul Hi, I'd be glad if you could proceed to review.

**Comment by mitmul** [comment]
I think it's better to have a consistency regression test for the double backward of ND poolings. How do you think of it, @rezoo @beam2d ?

**Comment by mitmul** [comment]
From offline discussion, it turns out to be unnecessary to add consistency regression tests for double backwards between ND poolings with N=2 and 2D poolings. Because if forward results of ND with N=2 and 2D are same and backward results are also same, the double backward results can not be different. So, LGTM!

**Comment by hvy** [comment]
@rezoo @mitmul Do you think we should backport this PR?

**Comment by mitmul** [comment]
Yes, I think so. Because all the other PRs for new-style functions have been backported so far.

**Pull request merged**
