### PR TITLE
[backport] Fix decorrelated batch normalization when groups ≠ 1

### PR DESCRIPTION
**Pull request by hvy**
Backport of #7707

### CODE REVIEW

**Comment by hvy** [comment]
[automatic post] Jenkins, test this please.

**Comment by hvy** [comment]
We need to backport this PR first https://github.com/chainer/chainer/pull/7226 ?

**Comment by toslunar** [comment]
> #7226

`chainer.backend.copyto` is relevant but `Variable.copydata` is not.

**Comment by toslunar** [comment]
I've not understood the difference between
https://github.com/chainer/chainer/blob/397fb99d501846687d9c4601b3766f9ffec5086d/chainer/serializers/npz.py#L180-L182
and
https://github.com/chainer/chainer/blob/397fb99d501846687d9c4601b3766f9ffec5086d/chainer/backend.py#L53-L54

**Comment by hvy** [comment]
The former indeed seems broken https://github.com/chainer/chainer/issues/7829

**Comment by niboshi** [comment]
TODO: Backport #7828 after this.

**Comment by hvy** [comment]
> chainer.backend.copyto is relevant but Variable.copydata is not.

Are there concerns with backporting https://github.com/chainer/chainer/pull/7226 ? I'd like to do so otherwise.

**Comment by niboshi** [comment]
ping

**Comment by toslunar** [comment]
I made #7934.  Whether to backport the other part of #7226 might be discussed later.

**Comment by niboshi** [comment]
#7934 merged.

**Comment by hvy** [comment]
@toslunar could you take another look at this backport now that your PR has been merged?

**Comment by toslunar** [comment]
Jenkins & flexCI, test this please.

**Pull request merged**
