### PR TITLE
[backport] Insert missing spaces between concatenated string literals

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #7930

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
I force-pushed. Please retrigger the CIs manually >reviewer

**Comment by toslunar** [comment]
Jenkins & flexCI, test this please.

**Comment by toslunar** [comment]
The Jenkins failure is unrelated to the PR.

**Pull request merged**
