### PR TITLE
Fix AdamW docstring

### PR DESCRIPTION
**Pull request by crcrpar**
Part of #7124

### CODE REVIEW

**Comment by crcrpar** [comment]
Why `needs-discussion`?

This PR aims at fixing the wrong description of default weight_decay_rate and the order of `eps`, `weight_decay_rate`, and `eta` that is inconsistent with other Adam optimizers.

**Comment by niboshi** [comment]
@crcrpar Oh, sorry it was my misunderstanding.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Thanks!

**Pull request merged**
