### PR TITLE
Add scripts for Docker base images for Chainer CI

### PR DESCRIPTION
**Pull request by imos**
This PR adds scripts to create base images used for Chainer CI. Chainer CI targets build Docker images using scripts out of Chainer repository.

This PR creates new 4 CI targets "chainer.docker.(py37|py27and35).(test|push)", but they will not be trigger automatically mainly because they take about ten minutes.

### CODE REVIEW

**Comment by hvy** [comment]
@imos Thanks for the PR! The old targets seems to work correctly and LGTM but I'm not sure how to test the new ones. Did you verify that they work? Was also wondering how to trigger these new targets. Do we need to raise issues (maybe in the CuPy repository?) to address it?

**Comment by imos** [comment]
You can run those targets manually on the web (e.g., https://ci.preferred.jp/chainer.docker.py37.push/), and I'll remove old targets (chainer-ci-prep.*) in the future. In the next meeting, I would ask some opinions about whether we should trigger the target with CuPy's master push.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Comment by hvy** [comment]
@imos I guess we have to backport this PR?

**Comment by imos** [comment]
> @imos I guess we have to backport this PR?

No, the CI targets will refer to only the master branch and backporting should not affect anything.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
@imos 
>  I'll remove old targets (chainer-ci-prep.*) in the future.

How is the progress of this new architecture? Currently I'm facing an issue that tests of Chainer v6 branch tests running against CuPy master branch. Currently CuPy master is no longer compat with Py2, but we need to test Chainer v6 with Py2.

If `chainer.docker.*` migration does not happen soon, I will fix `chainer-ci-prep.*` to build separate images for each branch.

**Comment by kmaehashi** [comment]
I talked with imos-san. The configuration is now ready.
* `chainer-ci-prep.*` projects are now removed.
* https://ci.preferred.jp/chainer.docker.py25and35.push/ and https://ci.preferred.jp/chainer.docker.py37.push/ are used to build `chainer-ci-prep` docker images; we no longer have to trigger them manually as they will be triggered via webhook from cupy repos.

I already activated webhook of cupy repos for `master` branch. After https://github.com/chainer/chainer/pull/8350 got merged, I'll enable it for `v6` branch as well.

**Pull request merged**
