### PR TITLE
Use `_` for private classes under `chainer.dataset.tabular`

### PR DESCRIPTION
**Pull request by Hakuyume**
e.g. `chainer.dataset.tabular.slice.Slice` -> `chainer.dataset.tabular._slice._Slice`

### CODE REVIEW

**Comment by Hakuyume** [comment]
jenkins, test this please.

**Comment by okapies** [comment]
@beam2d Someone pointed out in today's meeting that it doesn't need to prefix the classes instead of the functions. Any idea?

**Comment by Hakuyume** [comment]
I personally prefer adding prefix because I want users not to use these classes directly.

**Comment by Hakuyume** [comment]
The failure of jenkins seems not related to this PR.

**Comment by beam2d** [comment]
Basically, private names only need at least one name in the module path prefixed with `_`, so `chainer.dataset.tabular._slice.Slice` should also be treated as a private name (using it requires to import a module prefixed with `_`, which is not "public"). Whether to also prefix `Slice` with `_` or not is a matter of taste (I don't have any preference here).

**Comment by Hakuyume** [comment]
> Whether to also prefix Slice with _ or not is a matter of taste (I don't have any preference here).

So, is this PR ok?

**Comment by beam2d** [comment]
Yes, it looks good to me.

**Pull request merged**
