### PR TITLE
[backport] New style Gaussian

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3759, will be rebased after #4021 merged.

### CODE REVIEW

**Comment by hvy** [comment]
Will merge after rebase and test.

**Comment by hvy** [comment]
Could you rebase the backport since #4021 has been is merged?

**Comment by takagi** [comment]
Merged the latest `v3` branch!

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
