### PR TITLE
Add Travis matrix for macOS ChainerX tests

### PR DESCRIPTION
**Pull request by niboshi**
Adds a new Travis matrix: macOS x ChainerX.

Only the native backend will be tested.

Note: Error fixes can be done in separate PRs I think. Specifically #5776 will be required.

### CODE REVIEW

**Comment by hvy** [comment]
#5776 is now merged but we're getting an error trying to uninstall `oclint` when it's not available. 🤔

**Comment by hvy** [comment]
Could you take a look at this new Travis failure?

**Comment by hvy** [comment]
I'll try to reproduce it locally.

**Comment by hvy** [comment]
Reproduced it. I'll take a look.

**Comment by hvy** [comment]
Seems like `RuntimeError` is raised instead of the expected `chainerx.ChainerxError` 🤔

**Comment by hvy** [comment]
This is only an issue when building with setuptools (e.g. pip install or python setup.py) so it's probably about some option that's not configured.

**Comment by hvy** [comment]
This happens both when installing via setuptools and directly with cmake.

**Comment by hvy** [comment]
Can you fix the conflicts?

**Comment by hvy** [comment]
The above failure should be fixed by https://github.com/chainer/chainer/pull/5936.

**Comment by asi1024** [comment]
Rebased.

**Comment by hvy** [comment]
Temporarily tested with Python 3.5.6 since 3.5.1 failed on `types.overload` (unrelated to this PR) and it seems to pass CI.

**Comment by asi1024** [comment]
Checked that macos tests have passed.
https://travis-ci.org/chainer/chainer/builds/476670316

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
It seems that the current change does not add a matrix?

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkinst, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
