### PR TITLE
Enable optimizer model setup with instantiation

### PR DESCRIPTION
**Pull request by Crissman**
Code to close issue #3211 .

Allow models to be passed as an argument to an optimizer, so
```
optimizer = chainer.optimizers.SGD()
optimizer.setup(model)
```
becomes:
```
optimizer = chainer.optimizers.SGD(model)
```

Change added to all `optimizers`. Old two-line method also still valid.

Tested by running new one-line method and old method on SGD, then running new method on all `optimizers` after changing code.

### CODE REVIEW

**Comment by mitmul** [comment]
@Crissman Check the travis-ci's test errors and please fix them.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
LGTM

**Comment by niboshi** [comment]
Note that this code does not work, because the first argument of `SGD` is `lr`.
```
optimizer = chainer.optimizers.SGD(model)
```
I think it's better to make `model` a keyword-only argument.

**Comment by Crissman** [comment]
@niboshi Correct. `model` should be a keyword argument. I've updated my comment above accordingly.

**Comment by kmaehashi** [comment]
Removed `to-be-backported` (as discussed in #3936)

**Pull request merged**
