### PR TITLE
New style hstack

### PR DESCRIPTION
**Pull request by hvy**
New style hstack function to support double backprop.

I am unsure whether accessing `self.inputs`, i.e. the `VariableNode`s from within the `FunctionNode` is against practices. There is no need to retain the inputs since we only want to know the shapes.

### CODE REVIEW

**Comment by hvy** [comment]
Seems like the CI failed on tests that aren't relevant to this PR.

**Comment by niboshi** [comment]
It seems double-backward test is numerically unstable (for float16).
Can you adjust tolerances?

Tips: you can put `@testing.condition.repeat(10000)` just before `def test_double_backward_cpu()`, for example, to check its stability.

**Comment by hvy** [comment]
Thank, for the comment. I'll all add an option for tests with low precision. And thank you for the tip!

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
LGTM! Thank you!

**Pull request merged**
