### PR TITLE
Fix ChainerMN Step-by-Step Troubleshooting

### PR DESCRIPTION
**Pull request by shu65**
The content was old so I fixed it.

### CODE REVIEW

**Comment by keisukefukuda** [comment]
Jenkins, test please.

**Comment by keisukefukuda** [comment]
Jenkins, test this please.

**Comment by keisukefukuda** [comment]
Maybe we should add a note that some tests are only activated when `comm.size > 1` or `comm.size == 2` etc.

**Comment by shu65** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Checks look fine. Ok to merge?

**Comment by shu65** [comment]
Yes!

**Comment by keisukefukuda** [comment]
I viewed it again. LGTN too. I will merge it.

**Pull request merged**
