### PR TITLE
[backport] Fix text_classification example fails on Python 3 (#5590)

### PR DESCRIPTION
**Pull request by takagi**
Backport of #5591

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
Will merge after https://github.com/chainer/chainer-test/pull/472.

**Comment by takagi** [comment]
chainer/chainer-test#472 has been merged!

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
I've rebased this on the latest `v5` branch so that it passes the CI.

**Comment by kmaehashi** [comment]
Thank you! Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
