### PR TITLE
Do not ignore FutureWarning other than experimental features

### PR DESCRIPTION
**Pull request by toslunar**
This PR changes only tests, while defining `class ExperimentalWarning(FutureWarning): pass` might resolve some other issues.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Merge #5950 first.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Comment by toslunar** [comment]
It seems there remain uncaught `FutureWarning`s.  I'll fix the issue.

**Pull request merged**
