### PR TITLE
Check deprecation warining in Travis

### PR DESCRIPTION
**Pull request by unnonouno**
I changed warnings configuration to check DeprecationWarnings. Note that some `ignore` configurations are required because Python itself shows DeprecationWarnings.

### CODE REVIEW

**Comment by unnonouno** [comment]
merge #3363 before this pr.

**Comment by delta2323** [comment]
jenkins, test this please.

**Comment by delta2323** [comment]
jenkins, test this please

**Comment by delta2323** [comment]
jenkins, test this please.

**Comment by delta2323** [comment]
LGTM

**Comment by delta2323** [comment]
Should we backport this PR?

**Comment by unnonouno** [comment]
yes, please

**Comment by takagi** [comment]
This PR is missed to be backported. I have posted #3721 .

**Pull request merged**
