### PR TITLE
Split python binding math routines

### PR DESCRIPTION
**Pull request by emcastillo**
The python binding code for routines initialization has been split according to the code splitting in the routines/ package.

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
I think we should test `reciprocal` but it otherwise LGTM.

**Comment by emcastillo** [comment]
I will add the reciprocal test, I thought it was included, despite of the routine not being bound

**Comment by hvy** [comment]
Hm, can it be tested without being bound? 🤔 Thanks in any case. Can you do that in this PR?

**Comment by emcastillo** [comment]
> Hm, can it be tested without being bound? 🤔 Thanks in any case. Will you do that in this PR?

I thought there was a test for the C++ routine, I planned to use that one as a base, however there was no test neither for C++ or the python binding :(

**Comment by emcastillo** [comment]
@hvy test added!

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Seems the error is unrelated

**Comment by hvy** [comment]
Thanks, LGTM!

**Pull request merged**
