### PR TITLE
Add `F.arctanh`

### PR DESCRIPTION
**Pull request by muupan**
This function is intended to be used to model a Gaussian distribution squashed by tanh as described in https://arxiv.org/abs/1812.05905.

### CODE REVIEW

**Comment by niboshi** [comment]
Double-backprop test failed in travis. Could you check it?
```
FAIL tests/chainer_tests/functions_tests/math_tests/test_arctanh.py::TestArctanh_param_0_{dtype=float16, shape=(3, 2)}::test_double_backward_cpu
```

**Comment by muupan** [comment]
I set `eps=1e-3` for backward and double backward tests and locally confirmed that `pytest -m "not gpu" tests/chainer_tests/functions_tests/math_tests/test_arctanh.py` succeeded 100 times in a row.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM
Thank you!

**Pull request merged**
