### PR TITLE
Simplify `F.batch_normalization` test

### PR DESCRIPTION
**Pull request by crcrpar**
Solves part of #6071.

### CODE REVIEW

**Comment by Crissman** [comment]
Tests reduced from 556 to 196. Can you comment on the change?

**Comment by crcrpar** [comment]
The reason would be that I removed the parameterization of `'contiguous'` because `testing.FunctionTestCase` set `'contiguous'` attribute `None`, or non-contiguous by default.

**Comment by Crissman** [comment]
LGTM. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins showing errors on batch_normalization. Please take a look.

**Comment by crcrpar** [comment]
Thank you for your reminding.

**Comment by crcrpar** [comment]
Hmm, some failures are terrible.

https://ci.preferred.jp/chainer.py37.gpu/3357/#
```
2019-04-18 18:42:22.088123 STDOUT 2482] | E       Base test method: TestFixedBatchNormalization_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__us
-- | --
2019-04-18 18:42:22.088135 STDOUT 2482] | e_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_true__use_ideep_never.test_forward
2019-04-18 18:42:22.088145 STDOUT 2482] | E       Test parameters:
2019-04-18 18:42:22.421614 STDOUT 2482] | E         dtype: <class 'numpy.float32'>
2019-04-18 18:42:22.421676 STDOUT 2482] | E         eps: 2e-05
2019-04-18 18:42:22.421684 STDOUT 2482] | E         ndim: 0
2019-04-18 18:42:22.421692 STDOUT 2482] | E         param_shape: (3,)
2019-04-18 18:42:22.421699 STDOUT 2482] | E
2019-04-18 18:42:22.421706 STDOUT 2482] | E
2019-04-18 18:42:22.421716 STDOUT 2482] | E       (caused by)
2019-04-18 18:42:22.421724 STDOUT 2482] | E       FunctionTestError: Outputs do not match the expected values.
2019-04-18 18:42:22.421731 STDOUT 2482] | E       Indices of outputs that do not match: 0
2019-04-18 18:42:22.421738 STDOUT 2482] | E       Expected shapes and dtypes: (5, 3):float32
2019-04-18 18:42:22.421770 STDOUT 2482] | E       Actual shapes and dtypes:   (5, 3):float32
2019-04-18 18:42:22.421806 STDOUT 2482] | E
2019-04-18 18:42:22.421814 STDOUT 2482] | E
2019-04-18 18:42:22.421821 STDOUT 2482] | E       Error details of output [0]:
2019-04-18 18:42:22.421828 STDOUT 2482] | E
2019-04-18 18:42:22.421835 STDOUT 2482] | E       Not equal to tolerance rtol=0.001, atol=0.0001
2019-04-18 18:42:22.421841 STDOUT 2482] | E
2019-04-18 18:42:22.421847 STDOUT 2482] | E       Mismatch: 66.7%
2019-04-18 18:42:22.421854 STDOUT 2482] | E       Max absolute difference: 2.1074407
2019-04-18 18:42:22.421861 STDOUT 2482] | E       Max relative difference: 22.353071
2019-04-18 18:42:22.421868 STDOUT 2482] | E        x: array([[ 0.098943, -0.322484, -0.924886],
2019-04-18 18:42:22.421875 STDOUT 2482] | E              [-0.970273, -0.558061,  0.467827],
2019-04-18 18:42:22.421882 STDOUT 2482] | E              [-0.789855, -0.204201,  0.518881],...
2019-04-18 18:42:22.421904 STDOUT 2482] | E        y: array([[ 0.098943,  1.32542 ,  0.255577],
2019-04-18 18:42:22.421911 STDOUT 2482] | E              [-0.970273,  1.138316,  1.614404],
2019-04-18 18:42:22.421917 STDOUT 2482] | E              [-0.789855,  1.419365,  1.664215],...
2019-04-18 18:42:22.421924 STDOUT 2482] | E
2019-04-18 18:42:22.421931 STDOUT 2482] | E       assert_allclose failed:
2019-04-18 18:42:22.421937 STDOUT 2482] | E         shape: (5, 3) (5, 3)
2019-04-18 18:42:22.421944 STDOUT 2482] | E         dtype: float32 float32
2019-04-18 18:42:22.421952 STDOUT 2482] | E         i: (4, 1)
2019-04-18 18:42:22.421958 STDOUT 2482] | E         x[i]: -2.555821657180786
2019-04-18 18:42:22.421964 STDOUT 2482] | E         y[i]: -0.4483809471130371
2019-04-18 18:42:22.421971 STDOUT 2482] | E         relative error[i]: 4.7001118659973145
2019-04-18 18:42:22.421977 STDOUT 2482] | E         absolute error[i]: 2.107440710067749
2019-04-18 18:42:22.421983 STDOUT 2482] | E       x: [[ 0.09894272 -0.3224843  -0.92488617]
2019-04-18 18:42:22.421990 STDOUT 2482] | E           [-0.9702735  -0.55806124  0.4678272 ]
2019-04-18 18:42:22.421996 STDOUT 2482] | E           [-0.78985536 -0.20420137  0.5188807 ]
2019-04-18 18:42:22.422004 STDOUT 2482] | E           [-0.46940023 -1.8804028  -0.31354263]
2019-04-18 18:42:22.422011 STDOUT 2482] | E           [-1.2186993  -2.5558217  -0.8982011 ]]
2019-04-18 18:42:22.422019 STDOUT 2482] | E       y: [[ 0.09894273  1.3254204   0.25557706]
2019-04-18 18:42:22.755225 STDOUT 2482] | E           [-0.9702735   1.1383162   1.6144036 ]
2019-04-18 18:42:22.755281 STDOUT 2482] | E           [-0.78985536  1.4193652   1.6642151 ]
2019-04-18 18:42:22.755294 STDOUT 2482] | E           [-0.46940023  0.08806241  0.8520457 ]
2019-04-18 18:42:22.755304 STDOUT 2482] | E           [-1.2186995  -0.44838095  0.28161287]]
```

**Comment by Crissman** [comment]
Can you take a look at the errors? Do you need help with this PR?

**Comment by crcrpar** [comment]
@Crissman Sorry for being late.

I tried this with chainer/cupy==7.0.0b1, but no failures occurred in my environment.

**Comment by Crissman** [comment]
Ok. Let's try again. Jenkins, test this please.

**Comment by crcrpar** [comment]
Ah... this indicates my environment is broken...

**Comment by crcrpar** [comment]
After a while, I couldn't point out the cause.

Could you take a look?

**Pull request closed without merging**
