### PR TITLE
Fix float16 and TensorCore related issue in ChainerX

### PR DESCRIPTION
**Pull request by anaruse**
This PR aims to fix the issue below.
* "CUDNN_STATUS_BAD_PARAM" occurs when ChainerX and float16 are used in the imagenet example due to improper setting of cudnn convolution math type.

### CODE REVIEW

**Comment by asi1024** [comment]
Thank you for the PR! I added the test which reproduces the error in #7203 and confirmed that this PR fixes the error.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failure is unrelated to this PR. LGTM!

**Comment by anaruse** [comment]
Thank you for your prompt response!

**Pull request merged**
