### PR TITLE
[chainerx] add softmax

### PR DESCRIPTION
**Pull request by tohmae**
Add softmax.
Reference: #6423

### CODE REVIEW

**Comment by hvy** [comment]
Thanks for the PR. The implementation basically LGTM but could you resolve the conflicts?

**Comment by hvy** [comment]
For the record, we probably want to implement softmax using cuDNN's `cudnnSoftmaxForward` for CUDA but that can be addressed in a later PR.

**Comment by tohmae** [comment]
Thank you for comment. I rebased.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Sorry for the delayed merge. LGTM!

**Comment by hvy** [comment]
Renamed the PR title for style and release note rendering.

**Pull request merged**
