### PR TITLE
added get_fashion_mnist helper

### PR DESCRIPTION
**Pull request by kashif**
Helper for the fashion-mnist

### CODE REVIEW

**Comment by hanxiao** [comment]
the error comes from 
```
FAIL: test_double_backward_cpu (test_log_softmax.transplant_class.<locals>.C)  parameter: {'shape': (2, 2, 2, 3), 'dtype': <class 'numpy.float16'>}
```
seems not related to this PR

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Thank you for sending us this PR to use your dataset!

Is it possible to rebase this PR on top of the current master and maybe write a test for it.
For reference, there exists a test for the [CIFAR-10 helper](https://github.com/chainer/chainer/blob/master/tests/chainer_tests/datasets_tests/test_cifar.py).

**Comment by kashif** [comment]
sure will do!

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
@kashif Thank you for the quick response. The call to `_preprocess_mnist ` is however currently missing a positional argument `rgb_format ` and will thus cause an error. 

https://github.com/chainer/chainer/blob/96753116c96e26d33e4d747673114b06b86ebb6b/chainer/datasets/mnist.py#L59-L60

On the other hand, I am not sure if we want to reuse a private function that belongs to a different module. Should we make it public (i.e. removing the leading underscore) or maybe move this code into the MNIST module? @niboshi

**Comment by kashif** [comment]
@hvy ok ready for another review. Regarding the private function I am using 2 of them... so I can change it to public if you want?

**Comment by niboshi** [comment]
Yes, in priciple, you shoudn't use private entities of other modules.
OTOH, it's better not to expose these functions to users, because they're for internal implementation.

How about making a private module such as `chainer.datasets._mnist_helper` and put them into it (without `_` prefix)?

**Comment by hvy** [comment]
@niboshi @kashif Thank you for the feedback. Yes I think that's okay. 

This is not a strong opinion but I would ideally reorganize `chainer/datasets`, as it currently contains both reusable classes and concrete datasets in the same hierarchy. But I guess that's another topic.

**Comment by hvy** [comment]
@kashif Would it be possible to refactor the code according to the feedback above? Sorry for repeatedly coming back to you.

**Comment by kashif** [comment]
sure @hvy, I was a bit confused as to which of the feedback to follow now. Can you kindly write it down in the comment concretely and I will do it 🙇

**Comment by hvy** [comment]
Sorry for the ambiguity. Reorganizing `chainer.datasets` will probably be a future topic. What I meant was this.

> How about making a private module such as chainer.datasets._mnist_helper and put them into it (without _ prefix)?

More concretely, could you please create a module `chainer.datasets._mnist_helper` and move the two functions `_preprocess_mnist ` and `_make_npz ` there, but without the prepending `_` to that module. Then change the current Fashion MNIST helper, as well as the MNIST helper to use those functions instead.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
@kashif Again, thank you for the changes. I noticed when running the tests locally that they failed because of the mock module. I fixed it in this PR, could you merge this one into your fork/branch? https://github.com/kashif/chainer/pull/1

**Comment by kashif** [comment]
@hvy ah thanks! done

**Comment by hvy** [comment]
@kashif Thank you for the quick response. LGTM (to us).

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please

**Comment by hvy** [comment]
FYI, caching logic tests might be unified into a single test instead of running them for each separate dataset, in which case this test will be affected. However, the helper itself should not be.

**Pull request merged**
