### PR TITLE
[v6] Add missing FlexCI configurations

### PR DESCRIPTION
**Pull request by kmaehashi**
* Copy configuration from master branch.
* Activate `chainer.py2.cv`, `chainer.py2.cv.gpu`, `chainer.py2.cv.examples` configurations (copy configuration from the default config) and enable `include_dot_git` for https://github.com/chainer/chainercv/pull/935 .
* Disable onnx-chainer related tests to avoid invoking them in v6.

See also: https://github.com/cupy/cupy/pull/2591

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
[INVALID_ARGUMENT] failed to parse config.pbtxt: line 213: expected "key", "value", or "}", found "configs"

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Sorry, #8401 got merged by mistake. Will make a fix in this PR.

**Comment by kmaehashi** [comment]
/test

PTAL (removed `st:test-and-merge`)

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
