### PR TITLE
[backport] Use float division instead of `__future__.division` for Python2

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #6562

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
Please merge #6561 first.

**Comment by niboshi** [comment]
LGTM

**Comment by toslunar** [comment]
The AppVeyor failure (`TestTriplet_param_31.test_double_backward_cpu`) is unrelated to the PR.

**Pull request merged**
