### PR TITLE
Make standard deviations available via LogReport

### PR DESCRIPTION
**Pull request by okapies**
This patch adds functionality to select statistics provided by specifying `init_stats` argument in `LogReport`. It also adds `MeanStats` and `StdDevStats` class instead of `DictSummary`.

This fix is suggested by @ktns.

Usage:
```python
trainer.extend(extensions.LogReport(init_stats=reporter.StdDevStats))
```

Output example:

```json
[
    {
        "main/loss": 0.18992580644320697,
        "main/loss.std": 0.19250075864959096,
        "main/accuracy": 0.9421666692197322,
        "main/accuracy.std": 0.05971576333672585,
        "validation/main/loss": 0.08225996830442454,
        "validation/main/loss.std": 0.0,
        "validation/main/accuracy": 0.9739000046253204,
        "validation/main/accuracy.std": 0.0,
        "epoch": 1,
        "iteration": 600,
        "elapsed_time": 26.420904844999313
    },
    {
        "main/loss": 0.0745212121346655,
        "main/loss.std": 0.045783321075002194,
        "main/accuracy": 0.9770833432674408,
        "main/accuracy.std": 0.015275029362245526,
        "validation/main/loss": 0.08226964094443247,
        "validation/main/loss.std": 0.0,
        "validation/main/accuracy": 0.9755000072717667,
        "validation/main/accuracy.std": 0.0,
        "epoch": 2,
        "iteration": 1200,
        "elapsed_time": 54.302615933993366
    },
    ...
]
```

### CODE REVIEW

**Comment by hvy** [comment]
This change basically LGTM but did you have the time to do some benchmarking?

**Comment by okapies** [comment]
## Benchmark
### Summary
`make_statistics()` is 2-3 times slower than `compute_mean()`, but I think it has actually no impact on the performance (about 0.015 ms/epoch).

### Result
number: `100000`

| Method | Processing Time (sec) |
|:--|:--|
| s.compute_mean() | 0.18963855504989624 |
| s.make_statistics() | 0.4698130157776177 |
| s_cpu.compute_mean() | 0.20775226410478354 |
| s_cpu.make_statistics() | 0.5885013220831752 |
| s_gpu.compute_mean() | 0.20731235714629292 |
| s_gpu.make_statistics() | 0.5891663557849824 |
| s_chx_cpu.compute_mean() | 0.2113188481889665 |
| s_chx_cpu.make_statistics() | 0.5834914911538363 |
| s_chx_gpu.compute_mean() | 0.21123537002131343 |
| s_chx_gpu.make_statistics() | 0.5860745450481772 |

### Script
```python
import timeit

setup = """
from chainer.reporter import Summary
import numpy as np
import cupy
import chainerx as chx

s = Summary()
s.add(0.5)
s_cpu = Summary()
s_cpu.add(np.float32(0.5))
s_gpu = Summary()
s_gpu.add(cupy.float32(0.5))
s_chx_cpu = Summary()
s_chx_cpu.add(chx.float32(0.5, device=chx.get_device("native:0")))
s_chx_gpu = Summary()
s_chx_gpu.add(chx.float32(0.5, device=chx.get_device("cuda:0")))
"""

number = 100000

print("s.compute_mean():            " + str(timeit.timeit("s.compute_mean()", setup=setup, number=number)))
print("s.make_statistics():         " + str(timeit.timeit("s.make_statistics()", setup=setup, number=number)))
print("s_cpu.compute_mean():        " + str(timeit.timeit("s_cpu.compute_mean()", setup=setup, number=number)))
print("s_cpu.make_statistics():     " + str(timeit.timeit("s_cpu.make_statistics()", setup=setup, number=number)))
print("s_gpu.compute_mean():        " + str(timeit.timeit("s_gpu.compute_mean()", setup=setup, number=number)))
print("s_gpu.make_statistics():     " + str(timeit.timeit("s_gpu.make_statistics()", setup=setup, number=number)))
print("s_chx_cpu.compute_mean():    " + str(timeit.timeit("s_chx_cpu.compute_mean()", setup=setup, number=number)))
print("s_chx_cpu.make_statistics(): " + str(timeit.timeit("s_chx_cpu.make_statistics()", setup=setup, number=number)))
print("s_chx_gpu.compute_mean():    " + str(timeit.timeit("s_chx_gpu.compute_mean()", setup=setup, number=number)))
print("s_chx_gpu.make_statistics(): " + str(timeit.timeit("s_chx_gpu.make_statistics()", setup=setup, number=number)))
```

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Thanks for the report. I think it's okay in the most general cases too but it assumes that `trigger` passed to log report is quite rarely fired, e.g. per epoch and not per iterations. I'm not sure it's a good idea to change the default behavior and that it'd be better to add an additional argument to log report to control whether std should be computed or not. What do you think?

**Comment by okapies** [comment]
Hmm. I think this is a fully backward-compatible way because this patch simply adds keys suffixed with `".std"` for each corresponding metrics. I'm afraid the filtering feature increases complexity of the API. What kind of cases do you think the users will be confused?

**Comment by hvy** [comment]
I'm thinking of users firing this log report in e.g. each iteration. Wouldn't the performance impact be quite noticeable to them? I do agree of course agree that the API complexity shouldn't be increased unless necessary.

**Comment by okapies** [comment]
It makes sense. It's just an idea, but how about making `_init_summary` injectable through the constructor like the following?

An advantage is that the users can replace it with more powerful implementation such like supporting quantiles.

```Python
class LogReport(extension.Extension):
    def __init__(self, keys=None, trigger=(1, 'epoch'), postprocess=None,
                 filename=None, init_summary=reporter.DictSummary, **kwargs):
        # init_summary is a callable object (like constructor, function or lambda)
        self._init_summary = init_summary
        ...

    def __call__(self, trainer):
        ...
        if self._trigger(trainer):
            # output the result
            stats = self._summary.make_statistics()
            ...
            # reset the summary for the next output
            self._init_summary()
```

If we go with it, need to discuss the followings:

1. Capability of the default `DictSummary` (just compute mean?)
2. A name of the default `DictSummary` (like `MeanDictSummary` and `StdDictSummary`)
3. The spec of `make_statistics()`
    - It states *"returns a single dictionary that holds mean and standard deviation values..."* in the document
    - Add another method and deprecate the old one?

What do you think?

**Comment by hvy** [comment]
That sounds like a future proof approach. A concern might be that we'll have to define a new class for each combination of statistics, once they get many, if they'll ever do.

**Comment by okapies** [comment]
@hvy I'm very sorry for the late response. I tried to add and use new `Stats` and `StatsDict` (the name is borrowed from [Guava](https://static.javadoc.io/com.google.guava/guava/28.1-jre/com/google/common/math/Stats.html) library) in place of `Summary`. Could you check and give a comment for these new APIs? Thanks.

**Pull request closed without merging**
