### PR TITLE
[backport] backends subpackage

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #3974

### CODE REVIEW

**Comment by kmaehashi** [comment]
For record: the following conflicts has been manually resolved:

```
        both modified:   chainer/__init__.py
        both modified:   chainer/cuda.py
        deleted by us:   chainer/functions/array/scatter_add.py
        deleted by us:   chainer/functions/math/cumsum.py
        deleted by us:   chainer/functions/noise/gumbel_softmax.py
```

as some features are not backported in v3: TensorCore, `chainer.cuda.fuse`, CuPy to use default memory pool, new functions.

**Comment by niboshi** [comment]
Jenkins has failed.
This is minimized code to reproduce the error.
(All of 3 test fixtures must be run.)

It seems CuPy's memory pool has some problem.

```
import pkgutil
import unittest

import numpy

import chainer
from chainer import cuda
from chainer import functions
from chainer import function_hooks
from chainer.testing import attr

# Extracted from chainer_tests/test_init_docstring.py
def test_load_modules():
    root = chainer.__path__
    for loader, modname, ispkg in pkgutil.walk_packages(root):
        if modname == 'backends' or modname == 'backends.cuda':
            loader.find_module(modname).load_module(modname)
            pass


# Extracted from chainer_tests/function_hooks_tests/test_cupy_memory_profile.py
@attr.gpu
class TestCupyMemoryProfileReport(unittest.TestCase):

    def setUp(self):
        self.h = function_hooks.CupyMemoryProfileHook()
        self.f1 = functions.Exp()
        self.f2 = functions.ReLU()
        self.x = numpy.random.uniform(-0.1, 0.1, (3, 5)).astype(numpy.float32)
        x = cuda.to_gpu(self.x)
        cuda.memory_pool.free_all_blocks()
        print(len(cuda.memory_pool._free))
        with self.h:
            self.f1.apply((chainer.Variable(x),))
            self.f1.apply((chainer.Variable(x),))
            self.f2.apply((chainer.Variable(x),))
            self.f2.apply((chainer.Variable(x),))

    def test_call_history(self):
        self.assertEqual(4, len(self.h.call_history))

    def test_total_acquired_bytes(self):
        self.assertNotEqual(0, self.h.total_acquired_bytes())
```

**Comment by sonots** [comment]
jenkins, test this please

**Comment by sonots** [comment]
With print debug as below:

```
diff --git a/cupy/cuda/memory.pyx b/cupy/cuda/memory.pyx
index 18f73f0..ce5944d 100644
--- a/cupy/cuda/memory.pyx
+++ b/cupy/cuda/memory.pyx
@@ -848,11 +848,13 @@ cdef class MemoryPool(object):
             ~cupy.cuda.MemoryPointer: Pointer to the allocated buffer.

         """
+        print('malloc', self)
         mp = <SingleDeviceMemoryPool>self._pools[device.get_device_id()]
         return mp.malloc(size)

     cpdef free_all_blocks(self):
         """Release free blocks."""
+        print('free_all_blocks', self)
         mp = <SingleDeviceMemoryPool>self._pools[device.get_device_id()]
         mp.free_all_blocks()
```

I get:

```
('free_all_blocks', <cupy.cuda.memory.MemoryPool object at 0x7f4f91f6a710>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
.('free_all_blocks', <cupy.cuda.memory.MemoryPool object at 0x7f4f91f6a710>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
('malloc', <cupy.cuda.memory.MemoryPool object at 0x7f4fb9fdb6a0>)
```

So, it looks the memory pool object using at `x = cuda.to_gpu(self.x)` and the `cuda.memory_pool` are now different objects.

**Comment by sonots** [comment]
It looks

```
from chainer.backends import cuda
from chainer.backends import cuda
```

does not load `chainer/backends/cuda` twice or more, but `loader.find_module(modname).load_module(modname)` loads twice or more.

**Comment by niboshi** [comment]
TODO: re-test after  #4094 will be merged

**Comment by kmaehashi** [comment]
After merging this, I need to fix `chainer/functions/connection/dilated_convolution_2d.py` that introduced `from chainer import cuda`. (it was already removed in master, so not part of this backport)

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
