### PR TITLE
[WIP] Rewrite AdaDelta with CuPy Fusion

### PR DESCRIPTION
**Pull request by asi1024**
~Merge cupy/cupy#1594 first.~
Merge cupy/cupy#1817 and cupy/cupy#1832 first.

- ElementwiseKernel
```
[100.00%] ··· Running optimizers.ada_delta.AdaDelta.time_update                                                                                                                    ok
[100.00%] ····
               ========= =============== ===============
               --                     dtype
               --------- -------------------------------
                backend   numpy.float32   numpy.float64
               ========= =============== ===============
                  gpu        44.81ms         44.56ms
                  cpu        497.86ms         1.05s
               ========= =============== ===============
```

- Fusion
```
[100.00%] ··· Running optimizers.ada_delta.AdaDelta.time_update                                                                                                                    ok
[100.00%] ····
               ========= =============== ===============
               --                     dtype
               --------- -------------------------------
                backend   numpy.float32   numpy.float64
               ========= =============== ===============
                  gpu        41.74ms         42.63ms
                  cpu        500.93ms         1.05s
               ========= =============== ===============
```

### CODE REVIEW

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
Resolved the merge conflicts.

Jenkins, test this please.

**Comment by toslunar** [comment]
Tests with ideep are failing.

**Comment by asi1024** [comment]
Rebased.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failures in `TEST=CHAINERX_chainerx-py3` seem unrelated to the PR.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request closed without merging**
