### PR TITLE
Add FromFile, FromString, FromStream creation routines to ChainerX.

### PR DESCRIPTION
**Pull request by sierreis**
These routines follow their counterparts in NumPy, except, FromStream
is a convenience for C++. This PR also contains tests.

I'm not sure how much documentation is being put into the C++ API, but I can also contribute in that area if requested.

Reference: https://github.com/chainer/chainer/issues/6423

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for the PR!
Please wait until I will review.

**Comment by niboshi** [comment]
Could you resolve conflict?

**Comment by sierreis** [comment]
Done.

**Comment by niboshi** [comment]
It seems clang-tidy check fails.
Could you check by yourself?

(And I'm sorry this documentation is not updated: please run `make clang-tidy` from within **the build directory**).
https://docs.chainer.org/en/latest/chainerx/contribution.html#lint-checking

**Comment by sierreis** [comment]
Alright, I'll try and get that resolved. It seems like it's generating a lot of errors which aren't related to the changes. I think clang-tidy is selecting a different version of gcc than I expected. I'll see if I can isolate the issue.

**Comment by sierreis** [comment]
So I tried to fix the `clang-tidy` errors but it seems there are still some issues. I am using a `docker` container with the following version:

|Software|Version|
|-----------|----------|
|ubuntu|16.04|
|gcc|5.4.0|
|g++|5.4.0|
|clang-tidy|3.8.0|
|clang-format|3.8.0|
|cmake|3.5.1|

Upon running `make clang-tidy` from the `build` folder, I get the following errors among others:

```
Error parsing /src/build/../chainerx_cc/.clang-tidy: Invalid argument
YAML:16:19: error: unknown key 'WarningsAsErrors'
WarningsAsErrors: '*'
                  ^~~
Error parsing /src/chainerx_cc/.clang-tidy: Invalid argument
1 error generated.
Error while processing /src/build/../chainerx_cc/chainerx/array_repr.cc.
          ^
/usr/include/wchar.h:39:11: error: 'stdarg.h' file not found [clang-diagnostic-error]
# include <stdarg.h>
          ^
```

The contents of the `.clang-tidy` file should be unmodified and are pasted here:

```
Checks: "-*,\
boost-*,\
bugprone-*,\
cert-*,\
cppcoreguidelines-*,\
-cppcoreguidelines-pro-bounds-pointer-arithmetic,\
clang-analyzer-*,\
google-*,\
-google-runtime-references,\
misc-*,\
modernize-*,\
-modernize-use-auto,\
performance-*,\
readability-*,\
"
WarningsAsErrors: '*'
HeaderFilterRegex: '^chainerx/chainerx/.*'
AnalyzeTemporaryDtors: false
```

Do you have an idea where the problem might stem from?

**Comment by niboshi** [comment]
Oh,I'm sorry, I overlooked that the problem has been resolved.
Could you resolve the conflict?

**Pull request closed without merging**
