### PR TITLE
Improve code sample appearance in docs

### PR DESCRIPTION
**Pull request by niboshi**
- Removes weird blank lines
- Adds line numbers

### CODE REVIEW

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by toslunar** [comment]
On blank lines, do you have an idea to keep maintainability?  See https://github.com/chainer/chainer/pull/5316#issuecomment-420489939

**Comment by niboshi** [comment]
Oh, I didn't notice it has already discussed.

I know it's less maintainable and I can't find any better way, but for me, current appearance is simply not acceptable. I would have the impression that this documentation is poorly written, which in turn means Chainer itself is poorly maintained.

**Comment by kmaehashi** [comment]
Using `start-after` and `lines` may be (a bit) better option.

> Changed in version 1.6: With both start-after and lines in use, the first line as per start-after is considered to be with line number 1 for lines.

http://www.sphinx-doc.org/en/1.8/usage/restructuredtext/directives.html?highlight=literalinclude#directive-literalinclude

**Comment by niboshi** [comment]
Thank you for suggestion.

If we're going to add line numbers, the maintenance cost is same: we need both the starting line number and the number of lines to show.

And I think it's better to show line numbers: (1) it's easier to view code and text in parallel (2) it implies the code fragments are extracts from external code (for those who missed the "The code below is from..." statement).

**Comment by niboshi** [comment]
How do you think? I want to fix the appearance before v5 release.

**Comment by toslunar** [comment]
How about adding some comments to `examples/glance/glance.py`?
```
# This example is referred by "Chainer at a Glance".
# If the file is modified, please update `docs/source/glance.rst`.
```

**Comment by niboshi** [comment]
I think that's helpful :+1:

**Comment by niboshi** [comment]
PTAL.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
