### PR TITLE
implement floordiv and rfloordiv

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR implements `floordiv` / `rfloordiv` operation for Variable.

### CODE REVIEW

**Comment by okuta** [comment]
Please resolve conflicts.
jenkins, test this please.

**Comment by kmaehashi** [comment]
Rebased to the master.
Jenkins test this please

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
