### PR TITLE
Fix code style for long expressions

### PR DESCRIPTION
**Pull request by niboshi**
* Backslashes for breaking long lines should be discouraged (https://www.python.org/dev/peps/pep-0008/#maximum-line-length).

* Positions of new lines should reflect the structure of expressions.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure
```
TestConvolutionND_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_backward
```
is unrelated to the PR.

**Pull request merged**
