### PR TITLE
Drop support for Python 2.7

### PR DESCRIPTION
**Pull request by kmaehashi**
Re-submit of #7766 for v7.0.0b3 release.

### CODE REVIEW

**Comment by kmaehashi** [comment]
CuPy counterpart: https://github.com/cupy/cupy/pull/2343

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
All the test failures are unrelated.

**Pull request merged**
