### PR TITLE
Fix backslashes

### PR DESCRIPTION
**Pull request by unnonouno**
We need to use double backslashes in str literals.

### CODE REVIEW

**Comment by niboshi** [comment]
For reference: http://www.sphinx-doc.org/en/stable/ext/math.html

>Keep in mind that when you put math markup in Python docstrings read by autodoc, you either have to double all backslashes, or use Python raw strings (r"raw").

As for  ``` :class:`~chainer.Link`\s ```, how about ``` :class:`~chainer.Link`\ s ``` instead? (http://www.sphinx-doc.org/en/stable/rest.html)

>it must be separated from surrounding text by non-word characters. Use a backslash escaped space to work around that: `thisis\ *one*\ word`.

**Comment by unnonouno** [comment]
updated

**Comment by niboshi** [comment]
Ah, double slash is for escaping Python string literals. I understand it now.
So we need to write ``` :class:`~chainer.Link`\\ s ``` as in your fix.

**Comment by niboshi** [comment]
AppVeyor has failed (HTTP connection time out?).
How can we redo the test?

**Comment by unnonouno** [comment]
I don't know, but i think other results are enough.

**Comment by niboshi** [comment]
OK, LGTM

**Pull request merged**
