### PR TITLE
 Put comments in `FindCuDNN.cmake`

### PR DESCRIPTION
**Pull request by niboshi**
~Depends on #7418~

* Put comments
* tabs -> spaces for consistency.

### CODE REVIEW

**Comment by niboshi** [comment]
I think #7418 and this PR can be reviewed altogether.
I'll close #7418.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Comment by hvy** [comment]
Failure is unrelated.

**Pull request merged**
