### PR TITLE
Support `TabularDataset` in iterators

### PR DESCRIPTION
**Pull request by Hakuyume**
~merge after #7428~

### CODE REVIEW

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by okapies** [comment]
Jenkins, test this please.

**Comment by okapies** [comment]
@Hakuyume I'm very, very sorry for the late response. I checked your patch and it seems great, but could you merge the latest `master` to pass the test?

**Comment by okapies** [comment]
Jenkins, test this please.

**Comment by okapies** [comment]
Jenkins, test this please.

**Comment by okapies** [comment]
Jenkins, test this please.

**Pull request closed without merging**
