### PR TITLE
Split reduction routines from math.cc

### PR DESCRIPTION
**Pull request by asi1024**
Part of #7143.
Depends on #7269.

### CODE REVIEW

**Comment by hvy** [comment]
#7269 has now been merged.

**Comment by asi1024** [comment]
Rebased.

**Comment by niboshi** [comment]
Please fix the Travis test failure.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please resolve the conflict.

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request merged**
