### PR TITLE
Fix AttributeError in WrappedFunctionNode.forward

### PR DESCRIPTION
**Pull request by msakai**
This PR fixes `AttributeError` in `onnx_chainer.replace_func.WrappedFunctionNode.forward`.
The `self.name` is not defined and I assume that this is a mistake of `self.custom_function_node_name`.

### CODE REVIEW

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Comment by msakai** [comment]
> (but the line is over 79 char..?)

Oops, Sorry. I didn't noticed that because I made the PR on browser :sweat_smile:.
Shall I add a commit to fold the line?

**Comment by take-cheeze** [comment]
Hmm strange.
Seems CI isn't checking onnx-chainer code: https://github.com/chainer/chainer/blob/b35ce749b900e55117c18aec072a49c30c8ca4b6/scripts/ci/travis/steps.sh#L118-L126

**Comment by take-cheeze** [comment]
Should be checked with: https://github.com/chainer/chainer/pull/8400

**Comment by take-cheeze** [comment]
Checked the code under onnx_chainer/ with CI and now correctly found:
https://travis-ci.org/chainer/chainer/jobs/609149881#L391
Sorry to bother but could you fix it and make travis green?

**Comment by msakai** [comment]
Sure!

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Comment by take-cheeze** [comment]
Jenkins, test this please

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Pull request merged**
