### PR TITLE
Drop Python 2 PFN CI configuration

### PR DESCRIPTION
**Pull request by niboshi**
Takes over #8015

Part of #8005

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Thanks, LGTM! I just want to mention/verify with @yuyu2172 and @Hakuyume that we're also stopping the tests for ChainerCV with this change.

**Comment by Hakuyume** [comment]
In ChainerCV, we also dropped CI configuration for Py2 + Chainer master.

**Pull request merged**
