### PR TITLE
Fix copy

### LINKED ISSUE #3047: Add order='C' option to `cupy.copy` calls using default order value.
Merge https://github.com/cupy/cupy/pull/159 first.

In https://github.com/cupy/cupy/pull/159, the default value of `cupy.copy`'s `order` argument is changed with breaking compatibility. We need to add `order='C'` option to `cupy.copy` calls with default `order` value in Chainer so that Chainer can work as currently it does.

`cupy.ndarray.copy` is not affected by https://github.com/cupy/cupy/pull/159, so it needs nothing.

### PR DESCRIPTION
**Pull request by okuta**
Fix #3047

### CODE REVIEW

**Comment by takagi** [comment]
LGTM! I also checked the lines where `cupy.copy` is used with `grep "\.copy("`.

**Comment by takagi** [comment]
When and how to merge this PR: https://github.com/cupy/cupy/pull/159

**Comment by okuta** [comment]
@takagi This PR do not break compatibility. Therefore, please merge this.

**Comment by okuta** [comment]
I resolved conflict.

**Comment by takagi** [comment]
Merged!

**Pull request merged**
