### PR TITLE
[backport] Infer input size in batchnorm using aggregate axes

### PR DESCRIPTION
**Pull request by delta2323**
Backport of #4673

### CODE REVIEW

**Comment by delta2323** [comment]
[automatic post] Jenkins, test this please.

**Comment by delta2323** [comment]
According to @niboshi, this PR should be merged in the same release as the backport of #5017. Should we wait to merge it until the backport for #5017?

**Comment by niboshi** [comment]
We should merge in this order.
1. #5017
2. This PR (#5050)
3. Backport of #5017

1\. should be in v5b3.
2\. and 3. should be in the same (corresponding) releases.

**Comment by toslunar** [comment]
Without a backport of #4266, the inference of parameter sizes seems difficult.
🤔

**Comment by delta2323** [comment]
I tried and was able to make the backport PR of #4266 (#5060). But it is a different question if we do merge it.

**Comment by delta2323** [comment]
When I merged the original PR (#4266), I didn't make a backport PR as it was addition of new features. But I also think it is OK to do so. How do you think? @niboshi @toslunar

**Comment by toslunar** [comment]
I'd rather not backport #4266.

BTW, lazy initialization of persistent arrays is new.  This backport PR (of #4673) itself is somewhat dangerous.

**Comment by niboshi** [comment]
I don't fully understand the detail of related PRs. I'm going to leave the decision to both of you.

So it's better to skip backporting?

**Comment by delta2323** [comment]
@toslunar Actually, I also think we do not have to backport #4266 and #4673 unless there is strong need for it because they modify the internal structure of `L.BatchNormalization` too much. Then, let's close the backport PRs.

**Comment by delta2323** [comment]
Please reopen the PR if you have some comments or requests.

**Pull request closed without merging**
