### PR TITLE
[backport] New style forget

### PR DESCRIPTION
**Pull request by hvy**
Backport of #3792

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Comment by kmaehashi** [comment]
LGTM!

**Comment by hvy** [comment]
Thank you for the verification 🙇

**Pull request merged**
