### PR TITLE
Add "copy and set item"

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by okuta** [comment]
@bkvogel @beam2d Is `copied_set_item` ok?
Another ideas are `copied_setitem`  `setitem_with_copy`.

**Comment by toslunar** [comment]
How about adding `set_item(x, slices, rhs, *, inplace=True)` and supporting only `inplace=False` in this PR.

**Comment by okuta** [comment]
@beam2d How about this design?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
@beam2d Please check API design.

**Pull request closed without merging**
