### PR TITLE
[backport] Support custom initializer in links.CRF1d

### PR DESCRIPTION
**Pull request by hvy**
Backport of #5807

### CODE REVIEW

**Comment by hvy** [comment]
[automatic post] Jenkins, test this please.

**Comment by okuta** [comment]
Please check travis result.

**Comment by hvy** [comment]
Probably because this PR isn't backported. https://github.com/chainer/chainer/pull/5624

**Comment by hvy** [comment]
@okuta could you review the backport as well? https://github.com/chainer/chainer/pull/5926

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Thanks for reviewing the dependency PR, now at least travis looks green.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
