### PR TITLE
Fix grammatical errors in documentation

### PR DESCRIPTION
**Pull request by niboshi**
It is recommended to ... -> It is recommended that you ...

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins test this please.

**Comment by hvy** [comment]
I'd personally write `We recommend you to ...` for to me a more natural way to put it but it's not strictly better in but rather a preference so let me merge this PR as is. As a side not, I also discussed this change with another native speaker but `recommended to` is not "wrong" by any sense it seemed.

**Comment by hvy** [comment]
Jenkins test this please.

**Comment by hvy** [comment]
Jenkins test this please.

**Comment by niboshi** [comment]
There are many materials out there that indicate "recommend [person] to <verb>" is incorrect.

* https://english.stackexchange.com/questions/35953/recommend-you-to-vs-recommend-that-you
* http://www.nativespeakeronline.com/typical-mistakes-in-english/i-recommend-you-to
* https://www.myhappyenglish.com/free-english-lesson/2014/01/28/how-to-use-suggest-recommend-english-grammar-lesson/

This historical plotting is also interesting:
* https://english.stackexchange.com/questions/56993/recommend-you-to-do-something-or-recommend-to-you-to-do-something

**Comment by hvy** [comment]
This was new to me (and indeed quite difficult), thanks for the references.

**Comment by niboshi** [comment]
Shouldn't it be backported?

**Pull request merged**
