### PR TITLE
ResultType

### LINKED ISSUE #6336: Prepare type promotion API

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #6336 

* If arrays and scalars are mixed, only arrays are considered.
* If float dtypes and other dtypes are mixed, only float dtypes are considered.
* If unsigned and signed integers are mixed, and the widest one is unsigned, a signed dtype with one level wider is chosen.

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins and Travis failures seem unrelated.

**Comment by hvy** [comment]
LGTM(us @asi1024 )!

**Pull request merged**
