### PR TITLE
Delete deprecated communicators 

### PR DESCRIPTION
**Pull request by keisukefukuda**
This PR removes deprecated communicators from ChainerMN.
Removed communicators are `TwoDimensional`, `Hierarchical`, `SingleNode`. 

They were implemented when NCCL only supports intra-node communication and combination of MPI's allreduce and NCCL's allredcue was necessary. However, NCCL supports inter-node communication on its own and there is no longer a need for such hybrid communicator classes.

NOTE: the removed communicators has been marked as `deprecated` in Chainer v6.

### CODE REVIEW

**Comment by keisukefukuda** [comment]
pfnci, test this please.

**Comment by belldandyxtq** [comment]
Can you also delete the following lines? 

https://github.com/chainer/chainer/blob/57c8e85359d288dad51fcc4433be1dfdba228351/chainermn/communicators/__init__.py#L24
to
https://github.com/chainer/chainer/blob/57c8e85359d288dad51fcc4433be1dfdba228351/chainermn/communicators/__init__.py#L28

https://github.com/chainer/chainer/blob/57c8e85359d288dad51fcc4433be1dfdba228351/chainermn/communicators/__init__.py#L65

**Comment by belldandyxtq** [comment]
Those in tests

https://github.com/chainer/chainer/blob/57c8e85359d288dad51fcc4433be1dfdba228351/tests/chainermn_tests/communicator_tests/test_communicator.py#L937
to the end

**Comment by belldandyxtq** [comment]
in the examples

```
examples/chainermn/seq2seq/seq2seq_mp1.py:344:    parser.add_argument('--communicator', default='hierarchical',
examples/chainermn/seq2seq/seq2seq_mp1.py:358:        comm = chainermn.create_communicator('hierarchical')
examples/chainermn/seq2seq/seq2seq.py:325:    parser.add_argument('--communicator', default='hierarchical',
examples/chainermn/seq2seq/seq2seq.py:339:        comm = chainermn.create_communicator('hierarchical')
examples/chainermn/imagenet/train_imagenet.py:130:    parser.add_argument('--communicator', default='hierarchical')
examples/chainermn/dcgan/train_dcgan.py:24:                        default='hierarchical', help='Type of communicator')
examples/chainermn/mnist/train_mnist.py:36:                        default='hierarchical', help='Type of communicator')
examples/chainermn/mnist/train_mnist_dual_parallel.py:81:        comm = chainermn.create_communicator('hierarchical')
examples/chainermn/mnist/train_mnist_model_parallel.py:81:        comm = chainermn.create_communicator('hierarchical')
examples/chainermn/mnist/train_mnist_checkpoint.py:39:                        default='hierarchical', help='Type of communicator')
examples/chainermn/parallel_convolution/train.py:37:        comm = chainermn.create_communicator('hierarchical')
```

**Comment by belldandyxtq** [comment]
in docs
```
docs/source/chainermn/model_parallel/example1_simple_mlp.rst:12:        comm = chainermn.create_communicator('hierarchical')
```

**Comment by keisukefukuda** [comment]
I removed all occurence of the removed communicators.

**Comment by belldandyxtq** [comment]
pfnci, test this please.

**Comment by belldandyxtq** [comment]
pfnci, test this please.

**Comment by belldandyxtq** [comment]
LGTM

**Pull request merged**
