### PR TITLE
add autosummary check to documents

### PR DESCRIPTION
**Pull request by kmaehashi**
I added functionality to check autosummary automatically, by reverse-generating a list of exported features.
Now we can catch the documentation error when adding new feature.

I started with Functions and Links, but if this idea is acceptable, I can just add another modules.

By #4037 and this PR,

```
$ SPHINXOPTS= make check-html
```

will print:

```
chainer/docs/source/_autosummary_check.rst:75: WARNING: unknown document: reference/generated/chainer.functions.f1_score
chainer/docs/source/_autosummary_check.rst:76: WARNING: unknown document: reference/generated/chainer.functions.precision
chainer/docs/source/_autosummary_check.rst:77: WARNING: unknown document: reference/generated/chainer.functions.recall
chainer/docs/source/_autosummary_check.rst:86: WARNING: unknown document: reference/generated/chainer.functions.decov
chainer/docs/source/_autosummary_check.rst:100: WARNING: unknown document: reference/generated/chainer.functions.absolute
chainer/docs/source/_autosummary_check.rst:106: WARNING: unknown document: reference/generated/chainer.functions.batch_det
chainer/docs/source/_autosummary_check.rst:107: WARNING: unknown document: reference/generated/chainer.functions.det
chainer/docs/source/_autosummary_check.rst:151: WARNING: unknown document: reference/generated/chainer.functions.zoneout
chainer/docs/source/_autosummary_check.rst:154: WARNING: unknown document: reference/generated/chainer.functions.batch_renormalization
chainer/docs/source/_autosummary_check.rst:155: WARNING: unknown document: reference/generated/chainer.functions.fixed_batch_renormalization
chainer/docs/source/_autosummary_check.rst:166: WARNING: unknown document: reference/generated/chainer.functions.unpooling_nd
chainer/docs/source/_autosummary_check.rst:191: WARNING: unknown document: reference/generated/chainer.links.StatefulMGU
chainer/docs/source/_autosummary_check.rst:192: WARNING: unknown document: reference/generated/chainer.links.StatelessMGU
chainer/docs/source/_autosummary_check.rst:202: WARNING: unknown document: reference/generated/chainer.links.Parameter
chainer/docs/source/_autosummary_check.rst:219: WARNING: unknown document: reference/generated/chainer.links.BatchRenormalization
```

Currently missing Functions and Links are listed in #4038.

I'd like to use `make check-html` in chainer-test.

### CODE REVIEW

**Comment by niboshi** [comment]
I feel it's not very straight-forward way.
Isn't it possible to implement this check using sphinx events, perhaps [autodoc-process-docstring](http://www.sphinx-doc.org/en/stable/ext/autodoc.html#event-autodoc-process-docstring) and [build-finished](http://www.sphinx-doc.org/en/stable/extdev/appapi.html#event-build-finished)?

**Comment by kmaehashi** [comment]
Thank you for the suggestion! I'll try that.

**Comment by kmaehashi** [comment]
I rewrote the check it using Sphinx events.

This check is enabled only when `CHAINER_DOCS_CHECK_UNDOCUMENTED_ENTITY=1` is defined and another error is not occurred during build. The test is disabled by default, because `autodoc-process-docstring` is not emitted if build tree is already built (i.e., without `make clean`, it does not work as expected)

```
$ CHAINER_DOCS_CHECK_UNDOCUMENTED_ENTITY=1 make clean html
```

now displays:

```
...

Warning, treated as error:
Undocumented entities found.
(Note: be sure to use `make clean html` to run this check):

chainer.functions.f1_score
chainer.functions.precision
chainer.functions.recall
chainer.functions.decov
chainer.functions.absolute
chainer.functions.batch_det
chainer.functions.det
chainer.functions.zoneout
chainer.functions.batch_renormalization
chainer.functions.fixed_batch_renormalization
chainer.functions.unpooling_nd
chainer.links.StatefulMGU
chainer.links.StatelessMGU
chainer.links.Parameter
chainer.links.BatchRenormalization
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 1
```

as expected.

**Comment by niboshi** [comment]
I'm sorry for late review.
I've come up with another idea: how about directly checking existence of generated document files (*.rst?), from e.g. `build-finished` event?
I'm sorry for completely different suggestion, but in that way you would not need an environment variable.

**Comment by kmaehashi** [comment]
Thanks! That sounds much better. Fixed, and found that `chainer.functions.shift` is undocumented.

**Comment by niboshi** [comment]
This PR needs a fix to `chainer.functions.shift` first.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
