### PR TITLE
Simplify to_gpu in RNN tests

### PR DESCRIPTION
**Pull request by unnonouno**
I replaced to_gpu in RNN tests.
related to #4045

### CODE REVIEW

**Comment by niboshi** [comment]
`cuda.to_gpu` now supports lists and `None`. You can simply use it like `cuda.to_gpu(self.xs)`.

**Comment by unnonouno** [comment]
Does it support nested lists?

**Comment by niboshi** [comment]
Oh, I see. It does not.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
