### PR TITLE
Update VariableNode.data if new data is assigned 

### LINKED ISSUE #3868: VariableNode's dtype mismatch if Variable.data is manually assigned
If `Variable.data` is assigned manually, `node.dtype` and `node.data.dtype` can indicate different values.
This has caused "Dtype of data and grad mismatch" error in `gradient_check.check_double_backward`.
### Code
```
import chainer
import numpy
from chainer import functions as F

x = chainer.Variable(numpy.array([3, 2], dtype=numpy.float32))
y = F.sin(x)
x.data = numpy.array([4, 2], dtype=numpy.float64)

print(x.node.dtype)
print(x.node.data.dtype)
```

### Output
```
float64                                             
float32
```

Current master: 5683281c854fd2e47b68a3461b8e3e7e3c69f227

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #3868

### CODE REVIEW

**Comment by unnonouno** [comment]
Do you have a test for it?

**Comment by niboshi** [comment]
OK, I'll add.

**Comment by niboshi** [comment]
Done.

**Comment by unnonouno** [comment]
In setter of `data`, `_data` is already set. Is this fix only required in `__init__`?

**Comment by niboshi** [comment]
`VariableNode._set_data_type` is also called from `Variable.array.setter` and `Variable.data.setter`.

**Comment by unnonouno** [comment]
I see

**Comment by unnonouno** [comment]
If so, `_set_data` is more appropriate for this method, isn't it?

**Comment by niboshi** [comment]
Hmm, you're right, but `self._data` is only updated if it was not `None` previously.
I didn't come up with a good name...

**Comment by niboshi** [comment]
@unnonouno Do you think I need to rename the method?

**Comment by unnonouno** [comment]
I think so. Or, make another method.

**Comment by niboshi** [comment]
I see. Another method is not an option, because the previous one would be unused.

How about `_update_data_metadata`? Or how about `_udpate_data_info`?

**Comment by unnonouno** [comment]
`_udpate_data_info` is simple

**Comment by niboshi** [comment]
OK, updated. Also added a comment.

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
