### PR TITLE
[WIP] Call forward_postprocess with output values if the hook impl supports

### PR DESCRIPTION
**Pull request by belltailjp**
This is an initial attempt to fix https://github.com/chainer/chainer/issues/6250

In order to keep backward compatibility, it checks signature of the specified hook.
In case the hook has only one argument, it calls without output values.
If it has 2, it calls with output value, and if it has more, an error is raised.

Although it's still work-in-progress, I want to hear opinions about the feature design.

TODO
* Code quality
* Tests and documentation

----
- Read [our contribution guide](https://docs.chainer.org/en/stable/contribution.html).
  - Does your code conform to our coding guidelines?
  - Did you write sufficient test code?
  - Did you write sufficient documentation?
- Also, take a look at [our compatibility policy](https://docs.chainer.org/en/stable/compatibility.html).

### CODE REVIEW

**Comment by tkerola** [comment]
By offline discussion, we considered that `inspect` might be heavy to call each forward pass, and might be replaced by wrapping `self.function_hook` once instead in the `FunctionHook` constructor.

**Comment by belltailjp** [comment]
This PR checks hook signature in every `FunctionNode` call but it turns out that cost of `inspection` is not trivial.
(ResNet50+GTX1080Ti case, it takes 4.46% of time just for inspection cost, which is a bit too heavy)

**Comment by niboshi** [comment]
The inspection could be done on hook registration (`FunctionNode.add_hook`) as well.
I think it's better because it's less trickier (no need to replace `FunctionHook.forward_postprocess`).
Also doing that in the constructor would break existing hook that do not call `super().__init__` (none of the existing built-in hooks do that).

Another comment is that if possible, I'd like to change the "new" interface to something similar to link hooks, to prevent future compatibility issues.

**Comment by belltailjp** [comment]
Thanks for the suggestion! I've changed the implementation to do inspection in hook registration time (both for global hook and FunctionNode individual hook).

> I'd like to change the "new" interface to something similar to link hooks,

Does this mean redesigned arguments of forward_postprocess (and others) like `forward_postprocess(func, name, args, kwargs, out)`?

**Comment by niboshi** [comment]
@belltailjp 
>Does this mean redesigned arguments of forward_postprocess (and others) like `forward_postprocess(func, name, args, kwargs, out)`?

No, I want to change so that arguments would be bundled in a single object. The signature would be `forward_postprocess(args)` and callback implementation would use `arg` like `arg.function`, `arg.in_data` and so on. That way we would be able to introduce new arguments in the future, without breaking user code.

**Comment by belltailjp** [comment]
> (func, name, args, kwargs, out)
Oh, yes I somehow misunderstood that they are formed into one `args`.
Let me try that, but it would require big changes, so should take time quite a bit.

**Comment by niboshi** [comment]
@belltailjp 
The team discussed and the following is the current conclusion.

* Inspecting the signature might not be robust and better avoided. For example, it won't work for C-implemented functions.
* It's better to make a new interface: say, `FunctionNodeHook`.
  * `FunctionNodeHook` might be a bit too long... but might be more precise because it works with `FunctionNode`.
* OK to bundle arguments like `LinkHook`.

How do you think? Any opinions and/or suggestions are of course welcome!

**Comment by niboshi** [comment]
What's the status of this PR?

**Pull request closed without merging**
