### PR TITLE
[backport] Reorganize tutorial & add new contents

### PR DESCRIPTION
**Pull request by hvy**
Backport of #3241

### CODE REVIEW

**Comment by hvy** [comment]
There might be quite a few conflict, including broken links.

**Comment by hvy** [comment]
Open for discussion whether this need to be backported or not.

**Comment by kmaehashi** [comment]
I think it is difficult to include this fix for the next release.

**Comment by hvy** [comment]
Thank you for the input. Is it okay to close this backport @niboshi ?

**Comment by niboshi** [comment]
@hvy OK.

**Comment by hvy** [comment]
Closed due to above mentioned concerns.

**Pull request closed without merging**
