### PR TITLE
Tentative fix: pytest<3.8

### PR DESCRIPTION
**Pull request by toslunar**
I cannot run the tests with `pytest==3.8.0`.

### CODE REVIEW

**Comment by toslunar** [comment]
> pytest-dev/pytest#3251: Warnings are now captured and displayed during test collection.

https://docs.pytest.org/en/latest/changelog.html

I found this issue in https://ci.appveyor.com/project/pfnet/chainer/build/12203/job/trqdumv8pfisunoc :
```
============================= test session starts =============================
platform win32 -- Python 3.5.2, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: C:\projects\chainer, inifile: setup.cfg
plugins: timeout-1.2.1, cov-2.6.0
timeout: 60.0s method: thread
collected 51638 items / 2 errors / 28907 deselected
=================================== ERRORS ====================================
 ERROR collecting tests/chainer_tests/testing_tests/test_unary_math_function_test.py 
tests\chainer_tests\testing_tests\test_unary_math_function_test.py:37: in <module>
    is_linear=True)
chainer\testing\unary_math_function_test.py:202: in unary_math_function_unittest
    warnings.warn('is_linear option is deprecated', DeprecationWarning)
E   DeprecationWarning: is_linear option is deprecated
 ERROR collecting tests/chainer_tests/testing_tests/test_unary_math_function_test.py 
tests\chainer_tests\testing_tests\test_unary_math_function_test.py:37: in <module>
    is_linear=True)
chainer\testing\unary_math_function_test.py:202: in unary_math_function_unittest
    warnings.warn('is_linear option is deprecated', DeprecationWarning)
E   DeprecationWarning: is_linear option is deprecated
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!
================= 28907 deselected, 2 error in 37.24 seconds ==================
```

**Comment by toslunar** [comment]
The issue with Python<=3.6 is fixed by #5307.

**Comment by toslunar** [comment]
The current status of this issue:
```
platform darwin -- Python 3.7.0, pytest-3.8.2, py-1.5.4, pluggy-0.7.1
rootdir: /Users/tos/GitHub/chainer, inifile: setup.cfg
plugins: cov-2.6.0
collecting 10126 items / 2 errors                                                                                                                                                                                                                                             ^C
== ERRORS ==
__ ERROR collecting tests/chainer_tests/exporters_tests/test_caffe.py __
tests/chainer_tests/exporters_tests/test_caffe.py:7: in <module>
    from chainer.exporters import caffe
chainer/exporters/__init__.py:1: in <module>
    from chainer.exporters import caffe  # NOQA
chainer/exporters/caffe.py:11: in <module>
    from chainer.links.caffe.protobuf3 import caffe_pb2 as caffe_pb
chainer/links/caffe/__init__.py:1: in <module>
    from chainer.links.caffe.caffe_function import CaffeFunction  # NOQA
chainer/links/caffe/caffe_function.py:10: in <module>
    from chainer.links.caffe.protobuf3 import caffe_pb2 as caffe_pb
chainer/links/caffe/protobuf3/caffe_pb2.py:9: in <module>
    from google.protobuf import reflection as _reflection
../../.pyenv/versions/3.7.0/envs/n/lib/python3.7/site-packages/protobuf-3.6.1-py3.7.egg/google/protobuf/reflection.py:58: in <module>
    from google.protobuf.internal import python_message as message_impl
../../.pyenv/versions/3.7.0/envs/n/lib/python3.7/site-packages/protobuf-3.6.1-py3.7.egg/google/protobuf/internal/python_message.py:62: in <module>
    from google.protobuf.internal import containers
../../.pyenv/versions/3.7.0/envs/n/lib/python3.7/site-packages/protobuf-3.6.1-py3.7.egg/google/protobuf/internal/containers.py:340: in <module>
    collections.MutableSequence.register(BaseContainer)
../../.pyenv/versions/3.7.0/lib/python3.7/collections/__init__.py:52: in __getattr__
    DeprecationWarning, stacklevel=2)
E   DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

**Comment by toslunar** [comment]
#5514 supersedes this PR.

**Comment by kmaehashi** [comment]
Thanks! Closing as #5514 got merged.

**Pull request closed without merging**
