### PR TITLE
[backport] Fix `chainer.links.NStepRNN` and its variants

### PR DESCRIPTION
**Pull request by toslunar**
Backport of #6415

### CODE REVIEW

**Comment by toslunar** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
>AttributeError: module 'chainer' has no attribute 'using_device'

`using_device` has not been backported. Can you rewrite?

**Comment by toslunar** [comment]
OK, I will.

**Comment by toslunar** [comment]
> > AttributeError: module 'chainer' has no attribute 'using_device'
> 
> `using_device` has not been backported. Can you rewrite?

Done!

**Comment by niboshi** [comment]
Thanks.
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
