### PR TITLE
Add additional special methods in class template

### PR DESCRIPTION
**Pull request by niboshi**
These are mainly used in:
- Datasetes
- Iterators
- Variable and Parameter

### CODE REVIEW

**Comment by delta2323** [comment]
I tried this PR and generated the document in my local environment. But I could not confirm the change. For example, `DictDataset.__len__` is not appeared in the document although it is implemented.

**Comment by niboshi** [comment]
Thank you for testing.
Hmm, below is a screenshot from my build.
Probably you didn't clear `generated/` directories under `sources/`:

```
rm -rf **/generated/
```

screenshot from 2017-06-13 14-25-23

**Comment by niboshi** [comment]
Maybe it should be written in `clean` target in `Makefile`.
`**/generated/` above is an extended syntax of bash, so we will need to use `find` command to do the same.

**Comment by niboshi** [comment]
Added to `make clean` rule. You should be able to use it to build correctly.

**Comment by delta2323** [comment]
OK, it works. Thank you.

**Comment by delta2323** [comment]
LGTM

**Pull request merged**
