### PR TITLE
Fix broken notations in `F.linear` docs

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix screen shot 2018-06-26 at 20 44 22
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.linear.html

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM, but I'm wondering whether we should remove the parenthesis too. What do you think?

**Comment by kmaehashi** [comment]
Do you mean parenthesis after these two 
> The other dimensions are handled as concatenated one dimension whose size must be
and 
> Weight variable of shape (M,N), where
? I think that makes sense.

**Comment by hvy** [comment]
Indeed, I meant those two. They simply look like conditions that must hold true, rather than explaining shapes. But let's leave it as is if you think it looks okay (and since the've been written in that way since before).

**Comment by hvy** [comment]
Removed `to-be-backported` since https://github.com/chainer/chainer/pull/4204 wasn't.

**Pull request merged**
