### PR TITLE
iDeep: optimizers.SGD and optimizers.MomentumSGD

### PR DESCRIPTION
**Pull request by niboshi**
iDeep support in optimizers.SGD and optimizers.MomentumSGD (Separated from #3865. Based on #4278.)

### CODE REVIEW

**Comment by kmaehashi** [comment]
LGTM, but I'll revisit after rebase. (e.g., `is_ideep_available` is no longer needed for type checks after rebase)

**Comment by niboshi** [comment]
Partially rebased (but still depends on #4278)

Also, fixed this point:
>LGTM, but I'll revisit after rebase. (e.g., `is_ideep_available` is no longer needed for type checks after rebase)

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
@niboshi Could you please rebase?

**Comment by niboshi** [comment]
Rebased.

**Comment by niboshi** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM! (jenkins pass, waiting for appveyor)

**Pull request merged**
