### PR TITLE
Raise appropriate error when `Adam.lr` is evaluated before updating starts

### PR DESCRIPTION
**Pull request by niboshi**
It's often reported that Adam optimizer raises division by zero error (#3214, #3921).
This PR aims to provide more friendly error message for such cases.

### Code
```
import chainer
a = chainer.optimizers.Adam()
a.lr
```

### Error message (This PR)
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    a.lr
  File "/data/work/w/repos/chainer/chainer/optimizers/adam.py", line 138, in lr
    return _learning_rate(self.hyperparam, self.t)
  File "/data/work/w/repos/chainer/chainer/optimizers/adam.py", line 19, in _learning_rate
    'Can\'t determine the learning rate of Adam optimizer '
RuntimeError: Can't determine the learning rate of Adam optimizer because the update steps have not been started.
```

### CODE REVIEW

**Comment by niboshi** [comment]
I'm not sure if the term "learning rate" is appropriate here, because `alpha` is called "learning rate" in all other major frameworks.

**Comment by niboshi** [comment]
Related: #4056

**Comment by bkvogel** [comment]
As I understand it, the value returned by `lr` corresponds to `alpha_t` in the paper, which can be interpreted as a learning rate or modified `alpha`. Maybe I don't understand why a user would need to access it, but since this seems to be happening, I agree it is good to add a check as you have done. Maybe we could consider removing this property in the future if there is no good reason to access in user code? Until then, I think this is a good solution.

**Comment by bkvogel** [comment]
I think the suggestion in my previous comment can wait to be consider at some point in the future, so LGTM.

**Pull request merged**
