### PR TITLE
Replace optional-lite with abseil

### LINKED ISSUE #7645: Replace optional-lite with abseil
Related: #7502

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #7645 

~Depends on  #7643~

### CODE REVIEW

**Comment by niboshi** [comment]
Rebased

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Ah, `absl::optional<int64_t (or something else that's trivially copyable?)>` is trivially copyable and should thus not be moved (but copied). Could you fix these occurrences? (It was not the case for `nonstd::optional`? 🤔 )

**Comment by niboshi** [comment]
Fixed.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Sorry could you resolve the conflicts?

**Comment by niboshi** [comment]
Fixed.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Failure seem unrelated. LGTM!

**Pull request merged**
