### PR TITLE
Calculate `beta` with `static_code` on `F.BatchNormalization.forward`

### LINKED ISSUE #8324: static_graph with batch_norm use_beta false error -  'NoneType' object is not subscriptable
When beta is set to false in batchnorm...

```
L.BatchNormalization(64, use_beta=False)
```

static_graph raises a type error

```
TypeError: 'NoneType' object is not subscriptable
```

```
Platform: Linux-4.15.0-47-generic-x86_64-with-debian-buster-sid
Chainer: 7.0.0rc1
ChainerX: Available
NumPy: 1.17.3
CuPy:
  CuPy Version          : 7.0.0rc1
  CUDA Root             : /xx/cuda/10.1
  CUDA Build Version    : 10010
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10010
  cuDNN Build Version   : 7500
  cuDNN Version         : 7604
  NCCL Build Version    : 2402
  NCCL Runtime Version  : 2402
iDeep: 2.0.0.post3
None
```

### PR DESCRIPTION
**Pull request by emcastillo**
Closes #8324 

When using `static_graph`, if the `Link.forward` allocates some intermediate array constant (zeros) and the associated function does not retain this input, the static graph fails when calling forward, as this input won't be correctly retrieved.

Solves this issue by allocating beta inside of a `static_code` function as described by:
https://docs.chainer.org/en/stable/reference/static_graph_design.html

An alternative could be to retain `beta` in the function forward, but `beta` is not being used in gradient calculation, hence it does not respect the semantics of `retain_inputs`.

Minimum example to reproduce
```python
import chainer
import chainer.links as L
import numpy


class TestBN(chainer.Chain):
    def __init__(self):
        super(TestBN, self).__init__()
        with self.init_scope():
            self.link = L.BatchNormalization(64, use_beta=False)

    @chainer.static_graph
    def __call__(self, x):
        self.link(x)


x = numpy.random.uniform(
    -1, 1, (10, 64)).astype(numpy.float32)
x = chainer.Variable(x)

chain = TestBN()
chain(x)
```

### CODE REVIEW

**Comment by hvy** [comment]
Does this apply to `gamma` as well and if so, should we fix it in this same PR?

**Comment by emcastillo** [comment]
gamma is actually retained so it doesnt fail 😂

**Comment by hvy** [comment]
Do you think we should test this?

**Comment by emcastillo** [comment]
What do you think of adding a BatchNormalization layer to  the MLPs in `tests/chainer_tests/graph_optimization_tests/test_static_graph_models.py`

**Comment by hvy** [comment]
I was thinking of a test for this particular link, but that's okay too. That might better align with existing tests actually.

**Comment by emcastillo** [comment]
Actually is not testing links other than `Linear`, so maybe these tests should be reworked somehow

**Comment by hvy** [comment]
It's documented in `static_graph.py` that the static graph optimization is an experimental feature still, so I'm not sure how much effort we want to put into working on the coverage. If there's a high demand we might want to stabilize the API of this feature (or else, adding to the existing test file as you suggested sounds fine to me.)

**Comment by emcastillo** [comment]
I added a specific for `BatchNormalization` and also gamma is now static_code as you initially suggested! sorry I missed it.
the test unveiled a case where it was needed.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Thanks for prompt review 🙇‍♂️

**Pull request merged**
