### PR TITLE
Use `filename` in PlotReport example

### LINKED ISSUE #6875: Use `filename` argument in `PlotReport` code example
https://docs.chainer.org/en/latest/reference/generated/chainer.training.extensions.PlotReport.html

`file_name` is still used.

### PR DESCRIPTION
**Pull request by crcrpar**
resolves  #6875.

### CODE REVIEW

**Comment by Crissman** [comment]
LTGM. Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Merging.

**Pull request merged**
