### PR TITLE
Fix ChainerX fallback for replaced optimizer state

### LINKED ISSUE #6207: `Optimizer` runs unnecessary state array conversion
#6171 has been introduced for the specific `Optimizer` which replaces its state arrays such as `SMORMS3`. But it is also executed for every `Optimizer` which have `states` attribute (e.g. `Adam`) and generates additional overhead.

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #6207

### CODE REVIEW

**Comment by niboshi** [comment]
Hmm, this failure is not reproduced in my local environment.
```
E           AssertionError: Parameterized test failed.
E           
E           Base test method: TestNonparameterizedLinear_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_forward
E           Test parameters:
E             nobias: False
E             x_shape: {'data_shape': (3, 5), 'n_batch_axes': 3}
E             c_contiguous: False
E             W_dtype: <class 'numpy.float64'>
E             x_dtype: <class 'numpy.float64'>
E           
E           
E           (caused by)
E           AssertionError: 
E           Not equal to tolerance rtol=0.01, atol=0.001
E           
E           (mismatch 3.125%)
E            x: array([ 0.4578 ,  1.37   ,  0.093  , -0.1694 ,  1.024  ,  0.1527 ,
E                   0.1287 , -0.01268,  1.027  ,  0.6665 , -0.8145 , -1.387  ,
E                   1.936  ,  0.555  ,  1.062  ,  0.671  ,  0.9507 , -0.2325 ,...
E            y: array([ 0.4578 ,  1.37   ,  0.0913 , -0.1697 ,  1.026  ,  0.1531 ,
E                   0.1292 , -0.01123,  1.028  ,  0.667  , -0.8154 , -1.388  ,
E                   1.935  ,  0.555  ,  1.062  ,  0.672  ,  0.9507 , -0.2325 ,...
E           
E           assert_allclose failed: 
E             shape: (4, 2, 2, 2) (4, 2, 2, 2)
E             dtype: float16 float16
E             i: (0, 1, 1, 1)
E             x[i]: -0.0126800537109375
E             y[i]: -0.01123046875
E             relative error[i]: 0.1290283203125
E             absolute error[i]: 0.0014495849609375
```

**Comment by niboshi** [comment]
Well, the test passed after a retry.
It seems it was simply a problem of numeric tolerances.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins failures seem unrelated.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
