### PR TITLE
Avoid transferring from a native device to another in `Array::ToNative()`

### PR DESCRIPTION
**Pull request by niboshi**
Split from #7393.

Also added `Backend::IsNative()`.

### CODE REVIEW

**Comment by niboshi** [comment]
How to test this fix?
Parameterization in googletest is not easy...

**Comment by emcastillo** [comment]
Regarding the test, I think that an additional case on the array_to_device_test.cc is justified but maybe there is the need for a `ArrayToDeviceIncompatibleTest` fixture

**Comment by niboshi** [comment]
Wrote tests. PTAL

**Comment by emcastillo** [comment]
LGTM

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins tests has failures.

 /repo/chainerx_cc/chainerx/array_test.cc:1187:7: error: constructor does not initialize these fields: device_index_ [cppcoreguidelines-pro-type-member-init,-warnings-as-errors]
12:01:59 class ArrayToNativeTest : public ::testing::TestWithParam<::testing::tuple<std::string, int>> {

**Comment by niboshi** [comment]
Thank you. Fixed.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Error unrelated.

**Pull request merged**
