### PR TITLE
Improve performance of `using_config`

### PR DESCRIPTION
**Pull request by niboshi**
2.84 us -> 2.05 us

```py
with chainer.using_config('debug', False):
    pass
```

### CODE REVIEW

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Hmm, some Travis tests failed.

**Comment by niboshi** [comment]
@mitmul Sorry, I fixed the code.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
imosCI, test this please

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
