### PR TITLE
Add test for conveter device argument in Evaluator

### PR DESCRIPTION
**Pull request by niboshi**
Add test for the cupy backend.
ChainerX is not supported.

### CODE REVIEW

**Comment by okuta** [comment]
Please check test result.

**Comment by niboshi** [comment]
Fixed. PTAL

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure is unrelated to the PR.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
