### PR TITLE
ChainerX seq2seq example

### PR DESCRIPTION
**Pull request by niboshi**
Fixes the seq2seq example to enable ChainerX devices.

~Depends on #5832.~

### CODE REVIEW

**Comment by niboshi** [comment]
LGTM

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
chainer-example test failed. Fix needed.

**Comment by niboshi** [comment]
Requires #6126 and #6120.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
example-test fails.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins and Travis failures seem unrealted.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
