### PR TITLE
[backport] Ignore h5py is warned by Python 3.7

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #5691

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure (`tests.chainer_tests.functions_tests.pooling_tests.test_max_pooling_2d.TestMaxPooling2D_param_1.test_backward__use_cuda_true__use_cudnn_never__cudnn_deterministic_false__autotune_false__use_ideep_never__cudnn_fast_batch_normalization_false`) is unrelated to the PR.

**Pull request merged**
