### PR TITLE
New style fliplr

### PR DESCRIPTION
**Pull request by hvy**
New style fliplr to support double backprop.

### CODE REVIEW

**Comment by hvy** [comment]
Rebased on top of master.

**Comment by takagi** [comment]
Would you merge https://github.com/hvy/chainer/pull/1 to your repo, then I can merge this.

**Comment by hvy** [comment]
@takagi san, thank you for the tolerance adjustments. I merged the forked PR.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
