### PR TITLE
Check for mixed use of ndarrays

### PR DESCRIPTION
**Pull request by niboshi**
Checks input/output array types of forward operations.

This PR may be unsafe to backport, because existing functions may be mixing cupy and numpy arrays.
Also, some builtin functions will fail to pass this check. They need to be fixed before this PR.

### CODE REVIEW

**Comment by niboshi** [comment]
#4030 needs to be merged before this PR.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Comment by hvy** [comment]
Note: Not backported due to the fact that e.g. user-defined functions that are using mixed input/output backends will start to fail.

**Pull request merged**
