### PR TITLE
Show pytest summary in flexCI

### PR DESCRIPTION
**Pull request by niboshi**
Related: #6625

Applies in flexCI results as well.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Some of the CI errors 
`flag provided but not defined: -rfEX`

**Comment by niboshi** [comment]
https://github.com/chainer/xpytest/issues/14 is needed.

**Comment by emcastillo** [comment]
#8361 ?

**Comment by niboshi** [comment]
>#8361 ?

What do you mean?

**Comment by emcastillo** [comment]
Sorry, I just saw xpytest and thought it might be related 😅

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
