### PR TITLE
Remove ChainerX `CopyKernel`

### PR DESCRIPTION
**Pull request by kshitij12345**
As CopyKernel is a special case of AsTypeKernel.

https://github.com/chainer/chainer/projects/2#card-20163727

Have done reverse of what is mentioned on card as CopyKernel is subset of 
AsTypeKernel.

### CODE REVIEW

**Comment by asi1024** [comment]
Thank you for the PR!
Jenkins, test this please.

**Comment by hvy** [comment]
Hm, there is no value in emphasizing the words "copy" and/or "type" to communicate the intent of the operation to the reader?

**Comment by kshitij12345** [comment]
@hvy Good Point. Actually I believe there is. How about `using` keyword to alias them?
Somewhat like 
`using CopyKernel = AsTypeKernel`? However the `name()` function will return `AsType`. 
What do you think?

**Comment by hvy** [comment]
That sounds good to me. The `name` should basically not be visible to the average user so I think it's fine.

**Comment by hvy** [comment]
Still wondering if it's not better to keep the `CopyKernel` definition and make `AsType` an alias. The former sounds general enough to me and more common as a term. Not a strong argument. cc. @asi1024

**Comment by niboshi** [comment]
I don't think an alias makes sense.
Kernels are not for general users. API should be minimal.
I prefer `CopyKernel` as `As` implies a copy could be omitted.

**Comment by asi1024** [comment]
@kshitij12345 We discussed offline and decided to remove `AsTypeKernel` and not to create the alias as motivated here: https://github.com/chainer/chainer/pull/7522#issuecomment-502897321. Could you do that?

**Comment by kshitij12345** [comment]
Sure. Will update it by tomorrow.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM! Thank you for the PR!

**Comment by kshitij12345** [comment]
@asi1024 FYI, I have renamed the PR to be 

```
Remove ChainerX `AsTypeKernel`
```

**Comment by asi1024** [comment]
Thanks!

**Pull request merged**
