### PR TITLE
[backport] Suppot tuple for axis argument in average

### PR DESCRIPTION
**Pull request by knorth55**
backport of #3118 
it doesn't seem to be backported to `chainer-v2`.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for PR!
However, this is a new feature.
We add new features only into development branch (`master`).
Please wait until the next major version will be released.

**Comment by knorth55** [comment]
What do you mean by next release?
This feature won't be merged to v2?

**Comment by niboshi** [comment]
No, it won't.
We only merge bug-fixes and enhancements (those that do not change external behavior) to stable versions (currently v2).

**Comment by knorth55** [comment]
There will be no more new feature merged in `v2`?
That's really pity.

I'm satisfied with `v2` and I just want to use this new feature.
You mean I need to switch to `v3` in order to use the small feature.
I haven never used `v3`, but if there is as big difference between `v2` and `v3` as that between `v1` and `v2`, it is troublesome to switch to `v3`.

**Comment by knorth55** [comment]
by the way, i thought this is an enhancement, isn't it?

**Comment by niboshi** [comment]
Thank you for the precious feedback.
We discussed internally about this policy, and decided to loosen it.
From now on, we will backport minor feature addition like this one.

**Comment by niboshi** [comment]
I posted a new backport PR (https://github.com/chainer/chainer/pull/3264), because I could not reopen this one.

**Comment by knorth55** [comment]
Good decision! Thank you!

**Pull request closed without merging**
