### PR TITLE
Simplify  `F.deconvolution_2d` test

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies `test_deconvolution_2d` using `testing.FunctionTestCase`.

Solves part of issue #6071

### CODE REVIEW

**Comment by ishanrai05** [comment]
@Crissman  Can you please review this?

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins shows 10+ errors on the Deconvolution_2Dd tests, so we need to confirm whether relevant or not.

**Comment by ishanrai05** [comment]
@Crissman I think the tolerances need to be adjusted again.

**Comment by ishanrai05** [comment]
@Crissman I am unable to reproduce the errors on my system.

**Comment by Crissman** [comment]
Ok. Let's retest with Jenkins. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins still showing Deconvolution2D results off: 
` x: array(0.07680343490716937)`
`y: array(0.07691694685886355)`

Need to look to see the cause of discrepancy.

**Comment by ishanrai05** [comment]
@Crissman  I have added the tolerances for `backward_test` for `float64` and `float32` dtype since the tests that were failing were of these data types.
Also all the tests failing were on python2. Maybe that is why I was unable to produce the errors on my system.
Can you tests these again? :)

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Merging.

**Comment by Crissman** [comment]
Oops. Merged before clear on the error tolerances. Unmerging. 😓

**Comment by imos** [comment]
FYI, I found some flakiness in test_deconvolution_2d and test_deconvolution_nd tests:
https://ci.preferred.jp/chainer.py37.gpu/3525/
https://ci.preferred.jp/chainer.py37.gpu/3517/

**Pull request merged**
