### PR TITLE
ChainerX implementation of AMin and Min functions

### PR DESCRIPTION
**Pull request by Harshan01**
- AMax routines and AMax and Max functions are ndarray have been implemented in C++ for ChainerX.
- Docs have been updated.
- Python bindings and wrappers have been made.
- AMin device implementation has been been done.

### CODE REVIEW

**Comment by Harshan01** [comment]
The pull request is with reference to #6654

**Comment by Harshan01** [comment]
Ref issue: #6423

**Comment by hvy** [comment]
Thanks for the PR. LGTM although there are some code duplications. Let me check the CI.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by Harshan01** [comment]
I have updated _fallback_workaround.py to support the new AMin implementation

**Comment by hvy** [comment]
Good catch, thanks.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by Harshan01** [comment]
@hvy, Travis build succeeded for changes before commit e25f4cf except for Python static check which failed because of extra whitespace. After removing the whitespace, the Travis build failed for one test case although no other code was changed. Do you have suggestions on the matter?

**Comment by hvy** [comment]
Hm, indeed the Travis failures seem unrelated to this PR. Let me check if it persists.

**Comment by hvy** [comment]
Sorry but could you resolve the conflicts?

**Comment by Harshan01** [comment]
@hvy, Resolved conflicts

**Comment by Harshan01** [comment]
@hvy , I have removed the conflicts. Can you check it out?

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Thanks a lot. The changes look good and the CI failures are unrelated. Let me merge this PR.

**Pull request merged**
