### PR TITLE
[backport] Support ChainerX in word2vec example 

### PR DESCRIPTION
**Pull request by asi1024**
Backport of #6774

### CODE REVIEW

**Comment by asi1024** [comment]
[automatic post] Jenkins, test this please.

**Comment by asi1024** [comment]
Resolved two conflicts:
```py
 <<<<<<< HEAD
     if args.gpu >= 0:
         chainer.backends.cuda.get_device_from_id(args.gpu).use()
         cuda.check_cuda_available()

     print('GPU: {}'.format(args.gpu))
 =======
     device = chainer.get_device(args.device)
     device.use()

     if args.snapshot_interval is None:
         args.snapshot_interval = args.epoch
     args.snapshot_interval = min(args.snapshot_interval, args.epoch)

     print('Device: {}'.format(device))
 >>>>>>> 16aa002e9... Merge pull request #6774 from niboshi/chainerx-word2vec-example
```
```py
 <<<<<<< HEAD
     if args.gpu >= 0:
         model.to_gpu()
 =======
     model.to_device(device)
 >>>>>>> 16aa002e9... Merge pull request #6774 from niboshi/chainerx-word2vec-example
```

**Comment by niboshi** [comment]
Please fix test failure:
```
21:22:34 Running word2vec example
21:22:35 + echo 'Running word2vec example'
21:22:35 + coverage run -a --branch examples/word2vec/train_word2vec.py -e 1 -b 10 --test
21:22:35 Traceback (most recent call last):
21:22:35   File "examples/word2vec/train_word2vec.py", line 275, in <module>
21:22:35     main()
21:22:35   File "examples/word2vec/train_word2vec.py", line 189, in main
21:22:35     if args.snapshot_interval is None:
21:22:35 AttributeError: 'Namespace' object has no attribute 'snapshot_interval'
```

**Comment by asi1024** [comment]
Fixed. Jenkins, test this please.

**Pull request merged**
