### PR TITLE
use numbers for input check in roi_{average|max}_{pooling|align}_2d.py

### PR DESCRIPTION
**Pull request by knorth55**
~Merge after #5634 and #5635.~

use `numpy.issubdtype` instead of `isinstance` to check function args.
`numpy.issubdtype` supports `int, float` and `numpy.integer, numpy.floating`.

### CODE REVIEW

**Comment by knorth55** [comment]
waiting for #5635, not stale

**Comment by mitmul** [comment]
@knorth55 Could you fix the conflicts?

**Comment by knorth55** [comment]
I merged master branch and travis passed.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by knorth55** [comment]
@mitmul can you review this again ?

**Comment by knorth55** [comment]
@Hakuyume kindly ping.

**Comment by Hakuyume** [comment]
`numbers.Integral` can do similar thing and I think it is more simple.

```python
import numbers
import numpy as np

isinstance(int(0), numbers.Integral)  # True
isinstance(np.int32(0), numbers.Integral)  # True
isinstance(float(0), numbers.Integral)  # False
```

**Comment by knorth55** [comment]
@Hakuyume i update to use `numbers`.

**Comment by mitmul** [comment]
ChainerCI, test this please

**Comment by Hakuyume** [comment]
LGTM
It would be better to check float input causes exception.

**Comment by Hakuyume** [comment]
@mitmul I'm sorry for my slow review. Could you check and merge this PR?

**Comment by knorth55** [comment]
@mitmul can you check and merge this PR?

**Comment by Hakuyume** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
@knorth55 I'm very sorry for late reaction to your PRs... Could you fix the conflicts? Then I'll re-run the tests and merge this.

**Comment by knorth55** [comment]
@mitmul No problem. I resolved the conflict.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by knorth55** [comment]
The test exceeds in Python2.7.
Should I make the test ligheter?

**Comment by toslunar** [comment]
I'll rerun tests because the last two commits LGTM.

Jenkins, test this please.

**Comment by knorth55** [comment]
Jenkins test failed, but it is not related to this PR.

```
17:35:21 =================================== FAILURES ===================================
17:35:21 __________ test_TrilTriu_param_4_{k=1, shape=(4, 3)}[float16-cuda:0] ___________
17:35:21 
17:35:21 device = cuda:0, args = (), kwargs = {'float_dtype': 'float16'}
17:35:21 backend_config = <BackendConfig use_chainerx=True chainerx_device='cuda:0' use_cuda=False cuda_device=None use_cudnn='never' cudnn_deterministic=False autotune=False cudnn_fast_batch_normalization=False use_ideep='never'>
17:35:21 obj = <chainer.testing._bundle.TestTrilTriu_param_4_{k=1, shape=(4, 3)} object at 0x7f53f8b31908>
17:35:21 
17:35:21     @pytest.mark.parametrize_device(devices)
17:35:21     def entry_func(device, *args, **kwargs):
17:35:21         backend_config = _make_backend_config(device.name)
17:35:21     
17:35:21         # Forward test
17:35:21         obj = cls()
17:35:21         try:
17:35:21             obj.setup(*args, **kwargs)
17:35:21             obj.run_test_forward(backend_config)
17:35:21         finally:
17:35:21             obj.teardown()
17:35:21     
17:35:21         # If this is a NumpyOpTest instance, skip backward/double-backward
17:35:21         # tests if the forward test succeeds with acceptable errors.
17:35:21         if isinstance(obj, NumpyOpTest):
17:35:21             if obj.is_forward_successful_with_accept_errors:
17:35:21                 return  # success with expected errors
17:35:21     
17:35:21         # Backward test
17:35:21         obj = cls()
17:35:21         try:
17:35:21             obj.setup(*args, **kwargs)
17:35:21 >           obj.run_test_backward(backend_config)
17:35:21 
17:35:21 args       = ()
17:35:21 backend_config = <BackendConfig use_chainerx=True chainerx_device='cuda:0' use_cuda=False cuda_device=None use_cudnn='never' cudnn_deterministic=False autotune=False cudnn_fast_batch_normalization=False use_ideep='never'>
17:35:21 cls        = <class 'chainer.testing._bundle.TestTrilTriu_param_4_{k=1, shape=(4, 3)}'>
17:35:21 device     = cuda:0
17:35:21 kwargs     = {'float_dtype': 'float16'}
17:35:21 obj        = <chainer.testing._bundle.TestTrilTriu_param_4_{k=1, shape=(4, 3)} object at 0x7f53f8b31908>
17:35:21 
17:35:21 /repo/tests/chainerx_tests/op_utils.py:366: 
17:35:21 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
17:35:21 /repo/tests/chainerx_tests/op_utils.py:95: in run_test_backward
17:35:21     super(OpTest, self).run_test_backward(backend_config)
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/testing/function_link.py:255: in run_test_backward
17:35:21     do_check()
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/testing/function_link.py:244: in do_check
17:35:21     **self.check_backward_options)
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/contextlib.py:99: in __exit__
17:35:21     self.gen.throw(type, value, traceback)
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/testing/function_link.py:36: in raise_if_fail
17:35:21     cls.fail(message, e)
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/testing/function_link.py:27: in fail
17:35:21     utils._raise_from(cls, message, exc)
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/utils/__init__.py:106: in _raise_from
17:35:21     six.raise_from(new_exc.with_traceback(orig_exc.__traceback__), None)
17:35:21 <string>:3: in raise_from
17:35:21     ???
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/testing/function_link.py:34: in raise_if_fail
17:35:21     yield
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/testing/function_link.py:244: in do_check
17:35:21     **self.check_backward_options)
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/gradient_check.py:900: in check_backward
17:35:21     detect_nondifferentiable, is_immutable_params=False
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/gradient_check.py:464: in run
17:35:21     self._run()
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/gradient_check.py:507: in _run
17:35:21     self._compare_gradients(gx_numeric, gx_backward, directions)
17:35:21 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
17:35:21 
17:35:21 self = <chainer.gradient_check._CheckBackward object at 0x7f53f8b31748>
17:35:21 gx_numeric = array(-0.00447911, shape=(), dtype=float64, device='cuda:0')
17:35:21 gx_backward = array(-0.00457345, shape=(), dtype=float64, device='cuda:0')
17:35:21 directions = [array([[-0.19084183, -0.13525285, 0.24186938],
17:35:21        [0.38141085, -0.54487473, -0.3863876 ],
17:35:21        [-0.17815417, 0.04524124, -0.48183729],
17:35:21        [0.11480988, -0.03716954, 0.12087778]], shape=(4, 3), dtype=float64, device='cuda:0')]
17:35:21 
17:35:21     def _compare_gradients(self, gx_numeric, gx_backward, directions):
17:35:21         atol = self.atol
17:35:21         rtol = self.rtol
17:35:21         # Compare the gradients
17:35:21         try:
17:35:21             testing.assert_allclose(
17:35:21                 gx_numeric, gx_backward, atol=atol, rtol=rtol)
17:35:21         except AssertionError as e:
17:35:21             eps = self.eps
17:35:21             xs = self.xs
17:35:21             gys = self.gys
17:35:21             f = six.StringIO()
17:35:21             f.write('check_backward failed (eps={} atol={} rtol={})\n'.format(
17:35:21                 eps, atol, rtol))
17:35:21             for i, x in enumerate(xs):
17:35:21                 f.write('inputs[{}]:\n'.format(i))
17:35:21                 f.write('{}\n'.format(x))
17:35:21             for i, gy in enumerate(gys):
17:35:21                 f.write('grad_outputs[{}]:\n'.format(i))
17:35:21                 f.write('{}\n'.format(gy))
17:35:21             for i, d in enumerate(directions):
17:35:21                 f.write('directions[{}]:\n'.format(i))
17:35:21                 f.write('{}\n'.format(d))
17:35:21             f.write('gradients (numeric):  {}\n'.format(gx_numeric))
17:35:21             f.write('gradients (backward): {}\n'.format(gx_backward))
17:35:21             f.write('\n')
17:35:21             f.write('x: numeric gradient, y: backward gradient')
17:35:21             f.write(str(e))
17:35:21 >           raise AssertionError(f.getvalue())
17:35:21 E           chainer.testing.function_link.FunctionTestError: backward is not implemented correctly
17:35:21 E           
17:35:21 E           (caused by)
17:35:21 E           AssertionError: check_backward failed (eps=0.001 atol=1e-05 rtol=0.005)
17:35:21 E           inputs[0]:
17:35:21 E           array([[0.9765625 , 0.35913086, 0.16003418],
17:35:21 E                  [0.87304688, 0.41284180, 0.34838867],
17:35:21 E                  [0.61523438, 0.55126953, 0.71191406],
17:35:21 E                  [0.40600586, 0.0482788 , 0.73046875]], shape=(4, 3), dtype=float16, device='cuda:0')
17:35:21 E           grad_outputs[0]:
17:35:21 E           array([[-0.29565430, 0.82910156, -0.86621094],
17:35:21 E                  [0.45214844, -0.57568359, 0.51074219],
17:35:21 E                  [-0.91455078, -0.56347656, 0.04678345],
17:35:21 E                  [-0.18273926, 0.54541016, -0.71386719]], shape=(4, 3), dtype=float16, device='cuda:0')
17:35:21 E           grad_outputs[1]:
17:35:21 E           array([[-0.82617188, -0.45629883, -0.77978516],
17:35:21 E                  [0.63574219, -0.13049316, 0.2536621 ],
17:35:21 E                  [-0.75195312, -0.43554688, -0.35913086],
17:35:21 E                  [0.80859375, 0.69677734, 0.96728516]], shape=(4, 3), dtype=float16, device='cuda:0')
17:35:21 E           directions[0]:
17:35:21 E           array([[-0.19084183, -0.13525285, 0.24186938],
17:35:21 E                  [0.38141085, -0.54487473, -0.3863876 ],
17:35:21 E                  [-0.17815417, 0.04524124, -0.48183729],
17:35:21 E                  [0.11480988, -0.03716954, 0.12087778]], shape=(4, 3), dtype=float64, device='cuda:0')
17:35:21 E           gradients (numeric):  array(-0.00447911, shape=(), dtype=float64, device='cuda:0')
17:35:21 E           gradients (backward): array(-0.00457345, shape=(), dtype=float64, device='cuda:0')
17:35:21 E           
17:35:21 E           x: numeric gradient, y: backward gradient
17:35:21 E           Not equal to tolerance rtol=0.005, atol=1e-05
17:35:21 E           
17:35:21 E           Mismatch: 100%
17:35:21 E           Max absolute difference: 9.43329122e-05
17:35:21 E           Max relative difference: 0.02062621
17:35:21 E            x: array(-0.004479)
17:35:21 E            y: array(-0.004573)
17:35:21 E           
17:35:21 E           assert_allclose failed: 
17:35:21 E             shape: () ()
17:35:21 E             dtype: float64 float64
17:35:21 E             i: (0,)
17:35:21 E             x[i]: -0.004479114874565315
17:35:21 E             y[i]: -0.0045734477868034085
17:35:21 E             relative error[i]: 0.020626213884039273
17:35:21 E             absolute error[i]: 9.433291223809315e-05
17:35:21 E             relative tolerance * |y[i]|: 2.286723893401704e-05
17:35:21 E             absolute tolerance: 1e-05
17:35:21 E             total tolerance: 3.2867238934017044e-05
17:35:21 E           x: -0.00447911
17:35:21 E           y: -0.00457345
17:35:21 
17:35:21 atol       = 1e-05
17:35:21 d          = array([[-0.19084183, -0.13525285, 0.24186938],
17:35:21        [0.38141085, -0.54487473, -0.3863876 ],
17:35:21        [-0.17815417, 0.04524124, -0.48183729],
17:35:21        [0.11480988, -0.03716954, 0.12087778]], shape=(4, 3), dtype=float64, device='cuda:0')
17:35:21 directions = [array([[-0.19084183, -0.13525285, 0.24186938],
17:35:21        [0.38141085, -0.54487473, -0.3863876 ],
17:35:21        [-0.17815417, 0.04524124, -0.48183729],
17:35:21        [0.11480988, -0.03716954, 0.12087778]], shape=(4, 3), dtype=float64, device='cuda:0')]
17:35:21 eps        = 0.001
17:35:21 f          = <_io.StringIO object at 0x7f53f8b3c168>
17:35:21 gx_backward = array(-0.00457345, shape=(), dtype=float64, device='cuda:0')
17:35:21 gx_numeric = array(-0.00447911, shape=(), dtype=float64, device='cuda:0')
17:35:21 gy         = array([[-0.82617188, -0.45629883, -0.77978516],
17:35:21        [0.63574219, -0.13049316, 0.2536621 ],
17:35:21        [-0.75195312, -0.43554688, -0.35913086],
17:35:21        [0.80859375, 0.69677734, 0.96728516]], shape=(4, 3), dtype=float16, device='cuda:0')
17:35:21 gys        = (array([[-0.29565430, 0.82910156, -0.86621094],
17:35:21        [0.45214844, -0.57568359, 0.51074219],
17:35:21        [-0.91455078, -0....-0.43554688, -0.35913086],
17:35:21        [0.80859375, 0.69677734, 0.96728516]], shape=(4, 3), dtype=float16, device='cuda:0'))
17:35:21 i          = 0
17:35:21 rtol       = 0.005
17:35:21 self       = <chainer.gradient_check._CheckBackward object at 0x7f53f8b31748>
17:35:21 x          = array([[0.9765625 , 0.35913086, 0.16003418],
17:35:21        [0.87304688, 0.41284180, 0.34838867],
17:35:21        [0.61523438, 0.55126953, 0.71191406],
17:35:21        [0.40600586, 0.0482788 , 0.73046875]], shape=(4, 3), dtype=float16, device='cuda:0')
17:35:21 xs         = (array([[0.9765625 , 0.35913086, 0.16003418],
17:35:21        [0.87304688, 0.41284180, 0.34838867],
17:35:21        [0.61523438, 0.55126953, 0.71191406],
17:35:21        [0.40600586, 0.0482788 , 0.73046875]], shape=(4, 3), dtype=float16, device='cuda:0'),)
17:35:21 
17:35:21 /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/gradient_check.py:537: FunctionTestError
17:35:22 =============================== warnings summary ===============================
17:35:22 tests/chainerx_tests/unit_tests/routines_tests/test_explog.py::test_Erf_param_0_{shape=(2, 2), in_dtypes=('float16',), out_dtype='float16'}[float16-native:0]
17:35:22   /workspace/conda/envs/testenv/lib/python3.6/site-packages/chainer/functions/math/erf.py:36: PerformanceWarning: SciPy is not available. Forward computation of erf in CPU can be slow without SciPy.
17:35:22     chainer.warnings.PerformanceWarning)
17:35:22 
17:35:22 -- Docs: https://docs.pytest.org/en/latest/warnings.html
17:35:22 =========================== short test summary info ============================
17:35:22 FAIL ../../../repo/tests/chainerx_tests/unit_tests/routines_tests/test_creation.py::test_TrilTriu_param_4_{k=1, shape=(4, 3)}[float16-cuda:0]
17:35:22 = 1 failed, 165337 passed, 5907 skipped, 41 xfailed, 1 warnings in 2079.43 seconds =
17:35:38 Build step 'Execute shell' marked build as failure
```

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
