### PR TITLE
Simplify `F.max_pooling_2d` test

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies `test_max_pooling_2d` using `testing.FunctionTestCase`

Solves part of issue #6071

### CODE REVIEW

**Comment by toslunar** [comment]
CIs, test this please.

**Comment by toslunar** [comment]
Blocked by #6835.

**Comment by ishanrai05** [comment]
@toslunar I think #6835 can be merged.

**Comment by toslunar** [comment]
#6835 is merged.  Please merge (or rebase to) `master` .

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
