### PR TITLE
[WIP] Refactor `gradient_check` for `None` outputs

### PR DESCRIPTION
**Pull request by toslunar**
Moreover `numerical_grad` could unsupport `None` outputs because I don't come up with a case to utilize this feature (except for the internal use in `check_double_backward`).

### CODE REVIEW

**Comment by hvy** [comment]
@niboshi I think this is related to your recent changes, could you take a look?

**Comment by niboshi** [comment]
What's the status of this PR?

**Comment by toslunar** [comment]
The priority of the PR is low, because

- It's not nice to unsupport `None` after v6 is released.
- `_apply_grad_setter_func` will be removed by #5952.

**Comment by niboshi** [comment]
How about closing the PR (and perhaps create an issue), then?

**Comment by toslunar** [comment]
Again it happened that a feature was added to `gradient_check.check_backward` just because it's needed by `gradient_check.check_double_backward`.  I cannot believe my effort is welcomed.

refs: #6424, #7831.

**Comment by niboshi** [comment]
@toslunar Sorry, I don't understand what you are trying to say. I don't even understand the relationship between this PR and other PRs.
I suggested closing this PR simply because it had been WIP for quite a long time and you said the priority is low.

**Pull request closed without merging**
