### PR TITLE
Fix doctest

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by kmaehashi** [comment]
How about marking the doctest as SKIP (considering this behavior is tested in the unit test)?

```py
>>> dataset.concat_examples(w)  # doctest: +SKIP
```

Other solutions proposed in the document seems inappropriate for example codes. https://docs.python.org/3/library/doctest.html#warnings

**Comment by okuta** [comment]
I fixed.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
