### PR TITLE
Fix documentation of renamed arguments

### PR DESCRIPTION
**Pull request by niboshi**
Follow-up: https://github.com/chainer/chainer/pull/6928#pullrequestreview-226733858

Perhaps arguable:
* I made the mention of `file_name` much shorter: I felt the previous one was a bit too verbose. The mention of the case where both `filename` and `file_name` is also omitted.

### CODE REVIEW

**Comment by toslunar** [comment]
#5357 renamed arguments of three more functions.

**Comment by Crissman** [comment]
LGTM. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins failure seems unrelated. Merging.

**Comment by Crissman** [comment]
Oops. Please fix conflicting files.

**Comment by niboshi** [comment]
Resolved

**Comment by niboshi** [comment]
Fixed other arguments pointed out in https://github.com/chainer/chainer/pull/6932#issuecomment-483466812

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins failure unrelated.

**Pull request merged**
