### PR TITLE
Bugfix: `MultiNodeChainList` should not assume float32

### PR DESCRIPTION
**Pull request by toslunar**
This PR improves float16 support for model parallelization.  The bug was found in #6575.

### CODE REVIEW

**Comment by belldandyxtq** [comment]
pfnci, test this please

**Comment by toslunar** [comment]
pfnci, test this please.

**Comment by toslunar** [comment]
The Jenkins failure
```
test_Power_param_584_{in_dtypes=('float16', 'float16'), out_dtype='float16', in_shapes=((2, 3), (2, 3)), input_lhs=3, input_rhs=3.0, is_module=False}[native:0]
```
seems unrelated to the PR.

**Comment by belldandyxtq** [comment]
We are now having issues with tests. Once we get all the tests passed, I will merge it.

**Pull request merged**
