### PR TITLE
Avoid `# NOQA` in docstrings

### PR DESCRIPTION
**Pull request by toslunar**
https://github.com/chainer/chainer/pull/6182#issuecomment-460939096

This PR also fixes the link to `` :class:`~chainer.datasets.TupleDataset` ``

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
BTW, more `# NOQA` could be removed.

`H405` in the current `hacking` does not take `autodoc_docstring_signature` into account.  Since `hacking` is removed from CIs, we can wrap function signatures and remove `# NOQA`.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Pull request merged**
