### PR TITLE
Comment out extreme test of D.Categorical

### PR DESCRIPTION
**Pull request by YoshikawaMasashi**
I removed extreme test of `D.Categorical` temporarily.

### CODE REVIEW

**Comment by YoshikawaMasashi** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
This is a tentative fix until the test code is fixed to support SciPy 0.19. The test pass with SciPy 1.0 even when `extreme_values=True`.

**Comment by kmaehashi** [comment]
CI failures are not related to this PR.
I locally confirmed this fixed the issue with SciPy 0.19.

**Pull request merged**
