### PR TITLE
Fix to abort TestModeEvaluator and add resnet50.

### PR DESCRIPTION
**Pull request by yasunorikudo**
This PR will add ResNet50 for "train_imagenet_data_parallel.py". (related to #2644) 
This PR will also abort TestModeEvaluator to solve the following error. (related to #2186) 
```
$ python train_imagenet_data_parallel.py train.txt val.txt -a alex -g 0 1 2 3 -R imagenet
/home/ubuntu/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py:142: UserWarning: optimizer.lr is changed to 0.0025 by MultiprocessParallelUpdater for new batch size.
  format(optimizer.lr))
Traceback (most recent call last):
  File "train_imagenet_data_parallel.py", line 136, in <module>
    main()
  File "train_imagenet_data_parallel.py", line 112, in main
    trainer.extend(train_imagenet.TestModeEvaluator(val_iter, model,
AttributeError: module 'train_imagenet' has no attribute 'TestModeEvaluator'
```

### CODE REVIEW

**Comment by delta2323** [comment]
Thank you for reporting, it the latter change same as #2816?

**Comment by yasunorikudo** [comment]
As you said, the latter change is same as #2816 and I missed that PR.
Should I close this PR and send new PR which contain only the former change?

**Comment by delta2323** [comment]
No, you do not have to do that. The duplicated change is not harmful.

**Comment by delta2323** [comment]
Could you merge the master branch as #2816 is merged.

**Comment by yasunorikudo** [comment]
I rebased the master branch.

**Comment by delta2323** [comment]
Thanks. Could you add resnet50 to `train_imagenet_data_parallel.py` as well?

**Comment by yasunorikudo** [comment]
I have already done that.

**Comment by yasunorikudo** [comment]
Check c46cd965e587729fa7d8fdcd116be371560c6b58

**Comment by yasunorikudo** [comment]
I have added to resnet50 to ```train_imagenet_data_parallel.py```.

**Comment by delta2323** [comment]
Sorry, it was a stupid misdirection...

**Pull request merged**
