### PR TITLE
Create `chainer.optimizer_hooks` namespace and move hooks there.

### PR DESCRIPTION
**Pull request by delta2323**
This PR is continuation of #2943.

### CODE REVIEW

**Comment by okuta** [comment]
@delta2323 Cloud you resolve conflicts?

**Comment by delta2323** [comment]
@okuta I have rabased.

**Comment by okuta** [comment]
There are still conflicts.

**Comment by delta2323** [comment]
Sorry, I merged #4259, which made new conflicts. I resolved it.

**Comment by okuta** [comment]
Thanks!

**Comment by okuta** [comment]
flake8
```
.\tests\chainer_tests\test_optimizer.py:10:1: F401 'functions' imported but unused
.\tests\chainer_tests\test_optimizer.py:11:1: F401 'links' imported but unused
```

**Comment by kmaehashi** [comment]
Is it OK to deprecate these classes?
I feel it is inconsistent with what we did for updaters. https://github.com/chainer/chainer/pull/3037

**Comment by okuta** [comment]
flake8
```
./tests/chainer_tests/test_optimizer.py:10:1: F401 'functions' imported but unused
./tests/chainer_tests/test_optimizer.py:11:1: F401 'links' imported but unused
```

@kmaehashi Cloud you tell me more detail?

**Comment by kmaehashi** [comment]
We moved StandardUpdater and ParallelUpdater from `chainer.training` to `chainer.training.updaters` in #3037, but they does not raise DeprecationWarning (`chainer.training.StandardUpdater` is just a alias to `chainer.training.updaters.StandardUpdater`). The same rule applied for `chainer.cuda` v.s. `chainer.backends.cuda`.

I think we need to set policy regarding deprecations.

For me, immediately raising a DeprecationWarning just for internal refactoring (without explicit need to remove the API) is too aggressive.
How about leaving them as an alias and add comment like `# Following functions are kept for backward compatibility`?

**Comment by delta2323** [comment]
@kmaehashi I agree with you in that raising a deprecation warning is inconsistent with changes we have done with `StandardUpdater` or `chainer.backends.cuda`. On the other hand, if we are to remove old APIs in future, it might be better to have some mechanisms that promote users to move to recommended new APIs.

**Comment by okuta** [comment]
The document test was failed.
```
/home/user/.local/lib/python3.5/site-packages/chainer-4.0.0b4-py3.5.egg/chainer/optimizer_hooks/gradient_clipping.py:docstring of chainer.optimizer_hooks.GradientClipping:None: WARNING: more than one target found for cross-reference 'GradientClipping.timing': chainer.optimizer_hooks.GradientClipping.timing, chainer.optimizer.GradientClipping.timing
```

**Comment by kmaehashi** [comment]
@delta2323 One way to express our intension is to use Upgrade Guide, as done in `StandardUpdater` or `chainer.backends.cuda`.
https://docs.chainer.org/en/latest/upgrade.html

**Comment by delta2323** [comment]
jenkins test this please

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
