### PR TITLE
improve `F.elu` memory consumption by retaining output

### PR DESCRIPTION
**Pull request by grafi-tt**
When `alpha >= 0.0`, `F.elu` can modified to retain output. Gradient computation becomes easier.

It might degrade the precision of gradients, but it won't be worse than `F.sigmoid`, `F.tanh`, `F.swish` or `F.softplus`. [TF also computes gradients from the output.](https://github.com/tensorflow/tensorflow/blob/96237f7b7ae6b7b8a2cbcf6d64312906b96f060b/tensorflow/core/kernels/relu_op_functor.h#L149)

### CODE REVIEW

**Comment by hvy** [comment]
@toslunar can we assign you on this ticket?

**Comment by grafi-tt** [comment]
@toslunar Thanks. I modified test code to parameterize alpha with a positive random value, zero and a negative random value.

**Comment by toslunar** [comment]
LGTM.

Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure is unrelated to the PR.

**Pull request merged**
