### PR TITLE
Avoid numpy.stack which is supported in NumPy 1.10

### PR DESCRIPTION
**Pull request by niboshi**
numpy.stack is not supported until 1.10.

### CODE REVIEW

**Comment by hvy** [comment]
LGTM except that `stack` is also used in the seq2seq example https://github.com/chainer/chainer/blob/master/examples/seq2seq/seq2seq.py#L90. The example doesn't seem to document any NumPy particular version. Could we fix this occurrence as well?

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM except that the docs fail due to upgraded matplotlib version. Merging for now since it is unrelated to this PR.

**Comment by kmaehashi** [comment]
For record: this issue was introduced in #3551 (not backported)

**Pull request merged**
