### PR TITLE
[Backport] Add F.pad_sequence to the reference

### PR DESCRIPTION
**Pull request by delta2323**
Backport of #2863

### CODE REVIEW

**Comment by niboshi** [comment]
Please target `v2` branch, and I think you need to modify because we have changed the document style in `master` branch.

**Comment by delta2323** [comment]
I mistakenly made a PR on top of `master`. So I close it and re-submit another one.

**Comment by delta2323** [comment]
I noticed that as this PR is made on top of #2766, we have backport #2766 to merge this PR to v2 (in other words, if we backport this PR, #2766 will be automatically backported). Should we do that?

**Comment by niboshi** [comment]
In my opinion, it's better to simply add `F.pad_sequence` to `v2` branch in the old style.
Backporting #2766 is too cumbersome.

**Comment by delta2323** [comment]
I re-sent a PR (#2884)

**Pull request closed without merging**
