### PR TITLE
[backport] Add `chainer.get_device` to doc

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #6735

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
@niboshi Could you resolve conflicts?

**Comment by niboshi** [comment]
Resolved.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
