### PR TITLE
Simplify `F.clip` test

### PR DESCRIPTION
**Pull request by hikjik**
Simplifies test_clip using testing.FunctionTestCase
Refer to [#6071](https://github.com/chainer/chainer/issues/6071)

### CODE REVIEW

**Comment by hikjik** [comment]
The CI failures are probably unrelated

**Comment by Crissman** [comment]
LGTM. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins failure seems unrelated. Rerunning PFNCI tests.

**Comment by Crissman** [comment]
Failures on CI are on test_clip.py. Please see the details of the failed tests.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Retesting. Jenkins, test this please.

**Comment by Crissman** [comment]
Please take a look at the conflicts, thanks.

**Comment by Crissman** [comment]
Fixed merge conflict. Jenkins, test this please.

**Pull request closed without merging**
