### PR TITLE
Add 1d/3d aliases for convolution/pooling functions and links

### PR DESCRIPTION
**Pull request by kmaehashi**
This is based on #4025 by @mitmul, which is later reverted in #4475.
Fixed the code to work with the latest branch, and added tests.

### CODE REVIEW

**Comment by kmaehashi** [comment]
@niboshi Could you be an assignee for this PR?
The first commit (import #4025) is the same code as you have reviewed.

**Comment by kmaehashi** [comment]
Resolved conflicts.
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Resolved conflict.

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Welcome back! Jenkins, test this please

**Comment by mitmul** [comment]
LGTM

**Pull request merged**
