### PR TITLE
Document `chainer.testing.LinkTestCase`

### LINKED ISSUE #6894: No documentation for `LinkTestCase`
#6559 missed documentation.

### PR DESCRIPTION
**Pull request by crcrpar**
Resolves #6894.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Merging.

**Comment by toslunar** [comment]
v6 has #6559.

**Pull request merged**
