### PR TITLE
Improve docs of where

### PR DESCRIPTION
**Pull request by naoto0804**
This is PR for improving docs of functions/links. Related issue: #2182
Modified functions/links:
- functions/array/where

### CODE REVIEW

**Comment by naoto0804** [comment]
screenshot

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
