### PR TITLE
Add ChainerCV's tests to pfnCI

### PR DESCRIPTION
**Pull request by Hakuyume**
This PR adds ChainerCV's test cases to Chainer's CI. Chainer team can check a PR doesn't break backward-compatibility by using ChainerCV as a practical use case.

### CODE REVIEW

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Pull request merged**
