### PR TITLE
iDeep: F.max_pooling_2d

### PR DESCRIPTION
**Pull request by niboshi**
iDeep support in F.max_pooling_2d (Based on #4276.)

### CODE REVIEW

**Comment by niboshi** [comment]
Rebased.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test please

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
Please fix.
```
File "reference/generated/chainer.functions.upsampling_2d.rst", line ?, in default
Failed example:
    pooled_x.data
Expected:
    array([[[[ 8., 10., 12.],
             [20., 22., 24.],
             [32., 34., 36.]]]], dtype=float32)
Got:
    <Swig Object of type 'std::vector< mdarray >::value_type *' at 0x7fb87c83b848>
```

**Comment by niboshi** [comment]
Hmm, it seems difficult to fix in Chainer side....

**Comment by niboshi** [comment]
I disabled `use_ideep` config by default in #4337, so it should work now.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
