### PR TITLE
Add reference and warning to `F.swish` document

### PR DESCRIPTION
**Pull request by fiarabbit**
Improved documentation.
- Added reference to the original paper, because `F.swish` did not contain the reference.
- Added warning to use `L.Swish`, because Swish is an activation function which should be trained.

### CODE REVIEW

**Comment by Crissman** [comment]
Given the original paper had `beta` as a trainable variable, I think warning is appropriate here. @toslunar let's discuss.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
We discussed it offline:+1:

**Comment by Crissman** [comment]
Merging!

**Pull request merged**
