### PR TITLE
[backport] Fix `static_graph` docs code examples

### PR DESCRIPTION
**Pull request by Crissman**
Backport of #7875

### CODE REVIEW

**Comment by Crissman** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
@Crissman The line numbers need to be adjusted.

[master]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1780/TEST=chainer-doc,label=mn1-p100/artifact/chainer/docs/preview/reference/static_graph.html

[this PR]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1784/TEST=chainer-doc,label=mn1-p100/artifact/chainer/docs/preview/reference/static_graph.html

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
PTAL https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1892/TEST=chainer-doc,label=mn1-p100/artifact/chainer/docs/preview/reference/static_graph.html

**Comment by niboshi** [comment]
LGTM
(but please avoid triggering jenkins as a contributor just to check doc rendering!)

**Pull request merged**
