### PR TITLE
Enable `use_ideep` and `lazy_grad_sum` by default

### PR DESCRIPTION
**Pull request by niboshi**
They were introduced in v4.

### CODE REVIEW

**Comment by Crissman** [comment]
Need to add the documentation change for ideep default to `auto` to `configuration.rst`.

Similarly, documentation needs to be updated for the default value of ideep in `docs/source/tips.rst`.

**Comment by Crissman** [comment]
Discussed among team, and agreed to proceed with making `use_ideep` on by default.

**Comment by niboshi** [comment]
Conclusion:
* Make `config.use_ideep = 'auto'` by default
  * Currently `'auto'` is equivalent to `'always'`.
* Make `config.lazy_grad_sum = 'auto'` by default
  * If it is `'auto'`, the feature is enabled in CPU mode only and not in GPU mode, because in GPU mode memory consumption is more likely to be a problem than CPU.
  * Currently it takes `bool` values. They're mapped to `never` and `always` respectively.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins issues unrelated. Merging!

**Comment by niboshi** [comment]
@Crissman Oh, this PR at the current state does not reflect the discussion: https://github.com/chainer/chainer/pull/6127#issuecomment-465888560

Also, please refrain from self-merging!

**Comment by kmaehashi** [comment]
This PR has been reverted in #6794

**Pull request merged**
