### PR TITLE
Relax tolerances for FP16 `chainerx.where` test

### LINKED ISSUE #7241: `test_indexing` is flaky
- Failure example: https://jenkins.preferred.jp/job/chainer/job/chainer_pr/887/TEST=CHAINERX_chainerx-py3,label=mn1-p100/console
- Failiure test case: `test_Where_param_6_{condition_dtype='float32'}_param_11_{in_dtypes=('float16', 'float16'), out_dtype='float16'}_param_4_{cond_shape=(4, 5), x_shape=(3, 4, 1), y_shape=(1, 5)}[cuda:0]` (backward)
- Tolerance:
```
22:32:18 E           assert_allclose failed: 
22:32:18 E             shape: () ()
22:32:18 E             dtype: float64 float64
22:32:18 E             i: (0,)
22:32:18 E             x[i]: 0.21568901510230745
22:32:18 E             y[i]: 0.2169090419254323
22:32:18 E             relative error[i]: 0.005624601041501407
22:32:18 E             absolute error[i]: 0.001220026823124859
22:32:18 E           x: 0.21568902
22:32:18 E           y: 0.21690904
```

### PR DESCRIPTION
**Pull request by asi1024**
Fix #7241.

### CODE REVIEW

**Comment by asi1024** [comment]
PTAL.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Oops. Can you look at the conflict, please?

**Comment by asi1024** [comment]
It seems that the tolerances are already relaxed, because `TestWhere` was fixed in #7325 to use `math_utils.BinaryMathTestBase`, which uses a relaxed tolerance default. Can I close this PR?

**Pull request closed without merging**
