### PR TITLE
Avoid unnecessary `hasattr`

### PR DESCRIPTION
**Pull request by niboshi**
I replaced `hasattr` with normal attribute lookup.

IMO `hasattr` should be avoided, because

* It's slower. In my test, it's more than 3x times slower than `self.a is None`.
* Less readable. You cannot tell what attributes a class can have without reading the actual code.
* Look weird, especially to those from other programming languages.

### CODE REVIEW

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
I don't know why, but NegativeSampling raises an error.

**Comment by niboshi** [comment]
That's because `NegativeSamplingFunction.samples` is `del`ed in the test (https://github.com/chainer/chainer/pull/3952/commits/ec3b1ea4b6bf8f45ea8dea2a9559b6262678abb7#diff-91d435709d1f2973706d7b03fd776e40R94).

I reverted my change to this test, and added comment to state that this test needs a fix.

**Comment by unnonouno** [comment]
OK, thank you.

**Pull request merged**
