### PR TITLE
Warn users for Python 2

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Is this `no-compat`?

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by niboshi** [comment]
>Is this `no-compat`?

@kmaehashi ping

**Comment by kmaehashi** [comment]
OK to remove `no-compat` (but we shouldn't forget to mention it in the release note).

**Comment by kmaehashi** [comment]
The test passed.

**Comment by kmaehashi** [comment]
Let's backport the `docs/source/install.rst` part to stable branch as well.
(Warnings should not be raised in the stable branch.)

**Comment by niboshi** [comment]
I send a separate PR for v6: #7774
For v7,
* The note in the installation guide will not be needed by the release of v7.
* The wording in the upgrade guide should use the past (or past perfect) tense, not the future tense. I think the last sentense can also be omitted.

**Pull request merged**
