### PR TITLE
New style dstack

### PR DESCRIPTION
**Pull request by hvy**
New style dstack to support double backprop.

### CODE REVIEW

**Comment by hvy** [comment]
Rebased on top of master.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
