### PR TITLE
Simplify clip and clipped_relu

### PR DESCRIPTION
**Pull request by okuta**
`clip` covers `clipped_relu`.

### CODE REVIEW

**Comment by delta2323** [comment]
Should we treat this PR as `to-be-backported`?

**Comment by okuta** [comment]
No. Because `ClippedReLU` is deleted in this PR.

**Comment by niboshi** [comment]
Can we keep `ClippedReLU` as a thin wrapper or something? Otherwise it would break backward compatibility.

**Comment by okuta** [comment]
This change do not break backward compatibility based on Chainer's policy.
And, almost users do not use ClippedReLU directly.

**Comment by niboshi** [comment]
What do you mean?
In general, any identities not starting with `_` are considered "public" in the python convention, whether they're documented or not.

**Comment by okuta** [comment]
I read [this section](https://docs.chainer.org/en/stable/compatibility.html#documentation-error).
But, If this fixing is not user friendly, I propose a different way.

**Comment by niboshi** [comment]
I see.
Let's discuss with other members.

**Comment by delta2323** [comment]
IMO, I agree with keeping `ClippedReLU` if it is not costly and does not make the implementation complicated, as we do not need to dare to break compatibility.

**Comment by hvy** [comment]
@beam2d do you have any comments on this discussion?

I don't have any strong opinion but I see why we'd like to keep the class as it is. The maintenance cost is not that high and [`ClippedReLU`](https://github.com/chainer/chainer/blob/master/chainer/functions/activation/clipped_relu.py) has been reimplemented as a `FunctionNode`.  As for performance, both `clipped_relu` and `clip` are implemented with "optimized" grad computations so I'd image they are quite similar.

**Comment by okuta** [comment]
I updated.

**Comment by delta2323** [comment]
ping @beam2d

**Comment by beam2d** [comment]
Sorry for being late. I don't have any strong opinion on the backward compatibility of `ClippedReLU` class for the next major update, but since this name is imported to `chainer.functions`, I think it's safer to leave it. The implementation can be changed; e.g. `ClippedReLU` can be easily implemented by inheriting `Clip`. We can raise `DeprecationWarning` so that we will eventually remove them.

Btw, I think we should remove all the Function/FunctionNode implementations from `chainer/functions/__init__.py` at some point, and eventually make them look like not supported backward compatibility. (we may also need to rename all of them by prefixing by `_`).

**Comment by hvy** [comment]
@okuta san, do you have any opinions on this? 

I discussed with @beam2d san offline about the details and we said that maybe the class could be added back, throwing a warning in its `__init__` and we make sure to test both the new implementation and the deprecated (temporary) class implementation for the time being. I am not sure though when we should remove the warning/class completely.

**Comment by okuta** [comment]
OK, I will use `Clip`.

**Comment by okuta** [comment]
I fixed.

**Comment by hvy** [comment]
Sorry, could you rebase on the current master?

**Comment by okuta** [comment]
#4307 blocks this PR. So, I cannot rebase or merge this PR.
Is this PR really necessary?
In other words, I think it is necessary to discuss which functions of cuDNN to support.

**Comment by hvy** [comment]
I think it is okay to close this PR if that's okay with the PR author (@okuta) .

As for cuDNN function support, do we not under most circumstances want to support as many as possible?

**Comment by okuta** [comment]
OK, I close this PR.

**Pull request closed without merging**
