### PR TITLE
allow SerialIterator to use arbitrary random number generator

### PR DESCRIPTION
**Pull request by levelfour**
In some cases of distributed machine learning, it is needed to synchronize batch order of the iterator among multiple processes.
In order to achieve it, private random number generators are needed to avoid being interfered by other random number generation processes (e.g. dropout).
This PR alters `SerialIterator` to enable handling private RNG.
If no RNG is specified, it uses the numpy default RNG, which is compatible to the previous behavior.

For detail, please refer to chainer/chainermn#185.

### CODE REVIEW

**Comment by toslunar** [comment]
The test failure (`TestL2Normalization_param_3.test_backward_cpu` in AppVeyor) seems irrelevant to this PR.

**Comment by mitmul** [comment]
Is this related? https://github.com/chainer/chainer/pull/3429

**Comment by Crissman** [comment]
For testing purposes, can you provide an example of a private RNG?

**Comment by levelfour** [comment]
Thank you for the reply. Then I will reimplement after that the interface is fixed.

**Comment by hvy** [comment]
Fyi, https://github.com/chainer/chainer/pull/3429 has now been merged. Maybe you can use the new `ShuffleOrderSampler` taking a rng as constructor argument?

**Comment by hvy** [comment]
Talked offline with @levelfour and we agreed that we can close this PR. Please raise an issue if there are any issues using the `ShuffleOrderSampler`.

**Pull request closed without merging**
