### PR TITLE
Fix random for CuPy v8/v9

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
All test failures in `chainer-py3` are exceptions, except for https://github.com/chainer/chainer/pull/8607.
Failure of `chainer-py35` is as expected.
Failure of `CHAINERX_misc` is flake8 and was fixed in the above commit.

**Pull request merged**
