### PR TITLE
avoid using xp.stack in examples

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes https://github.com/chainer/chainer/pull/4003#issuecomment-348389484

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Comment by kmaehashi** [comment]
@lboloni Thank you for pointing that out. We'll fix the issue in #4117.

**Pull request merged**
