### PR TITLE
Add ignore option to NpzDeserializer

### PR DESCRIPTION
**Pull request by yuyu2172**
This PR adds an option to NpzDeserializer that ignores a subset of weights stored in the given npy file.

This is useful in the case when subset of parameters do not have the same shapes as those of the corresponding parameters in the file.
`strict` can ignore copying values in the case when corresponding parameters do not exist at all.
However, there is no easy way to deal with the situation when the corresponding parameters exist, but the shapes differ. Currently, shape mismatch error is raised.

This option is originally intended to solve the above problem. However, I made it a bit more general.
This way, a user can also ignore to copy some values even if their shapes match with the ones stored in the file.

### CODE REVIEW

**Comment by Hakuyume** [comment]
How about taking a callable in addition to a list of names? The callable takes a layer name and returns whether it is skipped or not. I want to use regular expressions to filter params.

**Comment by yuyu2172** [comment]
Nice suggestion. I updated the code.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
When a user misunderstand its specification and uses it with a list of callables, it shows no errors. How about supporting a list of callables? How do you think?

**Comment by yuyu2172** [comment]
Sure Good idea.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
