### PR TITLE
Fix n-step RNN docs

### LINKED ISSUE #6521: Slight inaccuracy in NStepGRU docs
in the part where the input dimension has been described , I think it should be L_t instead of L_i

### LINKED ISSUE #6810: Adding a usage example to NStepLSTM.
Adding an example would make NStepLSTM easier to understand.

### PR DESCRIPTION
**Pull request by toslunar**
Takeover #6808: fix #6521 and fix #6810.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
Only `../../../repo/tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_CholeskyFailing_param_7_{in_dtypes='float64', shape=(3, 3)}[cuda:0]` is failed (#8362).  Could you merge the PR?

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Pull request merged**
