### PR TITLE
Add support for importing and exporting Caffe Sigmoid layer

### PR DESCRIPTION
**Pull request by notogawa**
I implement Caffe Sigmoid layer.

### CODE REVIEW

**Comment by hvy** [comment]
Thanks for the PR. Would it make sense to also include tests for importing in `test_caffe_function.py` https://github.com/chainer/chainer/blob/master/tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py?

**Comment by notogawa** [comment]
Oh, missing that. I'll add.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, failure seems unrelated.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
