### PR TITLE
[backport] Update ChainerX contribution guide

### PR DESCRIPTION
**Pull request by hvy**
Backport of #6951

### CODE REVIEW

**Comment by hvy** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
