### PR TITLE
Simplify `F.log_softmax` test

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies `test_log_softmax` using `testing.FunctionTestCase`.
Fixes part of issue #6071

### CODE REVIEW

**Comment by Crissman** [comment]
Not sure what the cause is, but I don't think this test is testing anything:

``` % pytest -m 'not slow and not gpu and not cudnn and not ideep' test_log_softmax.py
======================================================= test session starts =======================================================
platform linux -- Python 3.5.2, pytest-4.3.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/crissman/chainer, inifile: setup.cfg
collected 18 items / 18 deselected                                                                                                

================================================== 18 deselected in 0.33 seconds ==================================================
crissman@GPCL-GPU102 ~/chainer/tests/chainer_tests/functions_tests/activation_tests
 % 
```

All tests are deselected. 🤔

**Comment by ishanrai05** [comment]
@Crissman  Fixed it. Should work now. Thanks a lot for reviewing. 

PS: sorry for the late reply. Had my midsem exams going on.

**Comment by Crissman** [comment]
LGTM. Good luck on your exams!

Jenkins, test this please.

**Comment by okuta** [comment]
imosci, test this please.

**Comment by ishanrai05** [comment]
@Crissman  I can't see why the tests are failing. Can you have a look please?

**Comment by Crissman** [comment]
Failures are unrelated. LGTM. Merging!

**Pull request merged**
