### PR TITLE
Add ConcatWithAsyncTransfer to the reference manual

### PR DESCRIPTION
**Pull request by beam2d**
Missed from #3336.

### CODE REVIEW

**Comment by hvy** [comment]
@beam2d san, thank you for this PR. At the moment the doc won't build since the module cannot be found. I think we need to import `ConcatWithAsyncTransfer ` under `chainer.dataset.__init__` to expose it, since the class is hidden under `chainer/dataset/convert`.

**Comment by beam2d** [comment]
Thank you for pointing that out. I have also noticed that after seeing the CI failure. Fixed it.

**Comment by hvy** [comment]
Thank you for the quick fix! 

Maybe you've noticed this too but now it seems to fail on the doctest.

```
10:16:48 File "reference/core/generated/chainer.dataset.ConcatWithAsyncTransfer.rst", line ?, in default
10:16:48 Failed example:
10:16:48     ...
10:16:48 Expected nothing
10:16:48 Got:
10:16:48     Ellipsis
10:16:48 
```

**Comment by beam2d** [comment]
Oops, ok, will take a look shortly.

**Comment by beam2d** [comment]
Fixed. Let's see if CI passes...

**Comment by hvy** [comment]
Great, LGTM! I also verified this locally so I'll merge this one.

**Pull request merged**
