### PR TITLE
Add workaround for cuSolver 10.2's new enums

### PR DESCRIPTION
**Pull request by take-cheeze**
Seems `CUSOLVER_STATUS_IRS_*` is added but can't be handled in current code

### CODE REVIEW

**Comment by niboshi** [comment]
How about using `#if` and `CUSOLVER_VERSION` to use new enum members?

**Comment by take-cheeze** [comment]
@niboshi I think it should be added when `cusolverDnIRS*` functions get supported.

**Comment by niboshi** [comment]
I don't really think we should, but this fix itself is OK.

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request merged**
