### PR TITLE
Fix visibility for pybind exception registration for macOS

### PR DESCRIPTION
**Pull request by hvy**
Fix that's required to correctly bind ChainerX custom exceptions on macOS (libc++).

More precisely, custom exceptions raised by the C++ code were treated as different types from the ones registered here https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/python/error.cc due to the default visibility configuration of pybind11 which is `hidden` and set here https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/common.h#L24. 

This PR changes the visibility to `default` and also includes changes to utilize `pybind11_add_module` which also seems to be required.

#### Reference
"Problems with C++ exceptions (please read!)" in https://gcc.gnu.org/wiki/Visibility

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
For the record, please refer to the exceptions section here https://gcc.gnu.org/wiki/Visibility.

**Comment by hvy** [comment]
jenkins failure seems unrelated.

**Comment by hvy** [comment]
Specify rpath so that ChainerX is correctly imported (`_core.so` finds `libchainerx.dylib`) when installed in a non-editable mode (e.g. via sdist).

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
