### PR TITLE
Remove unused parameter/serialization in test_manual_schedule_trigger.py

### PR DESCRIPTION
**Pull request by Hakuyume**
`initial_iteration` is no longer needed.

### CODE REVIEW

**Comment by mitmul** [comment]
LGTM

**Comment by Hakuyume** [comment]
updater serialization has no effect on tests of `ManualScheduleTrigger`

**Comment by Hakuyume** [comment]
I think this PR is not merged. Is there any problem?

**Comment by delta2323** [comment]
Sorry, we could not work on this PR to concentrate on the release of v2 tasks. @mitmul could you check the PR again?

**Comment by mitmul** [comment]
OK, sorry I'll check this again soon.

**Comment by mitmul** [comment]
Now master branch is broken, so please wait a little for master to be fixed.

**Pull request merged**
