### PR TITLE
Allow initialization of vision models by zeros

### PR DESCRIPTION
**Pull request by yuyu2172**
Currently, initializing vision models take long amount of time due to random.uniform of weights or copying of weights.
I added an option to the initialization functions to instantiate objects quickly by setting zeros to weights.
In my local environment, VGG speeded up from 5.6s to 0.1s.


This is a line by line profiling when initialized by random tensors.
```
Timer unit: 1e-06 s                                                                                                                                                        
                                                                                                                                                                           
Total time: 5.7949 s                                                                                                                                                       
File: /home/leus/install/chainer/chainer/links/model/vision/vgg.py                                                                                                         
Function: __init__ at line 80                                                                                                                                              
                                                                                                                                                                           
Line #      Hits         Time  Per Hit   % Time  Line Contents                                                                                                             
==============================================================                                                                                                             
    80                                               @do_line_profile()                                                                                                    
    81                                               def __init__(self, pretrained_model='auto'):                                                                         
    82         1            5      5.0      0.0          if pretrained_model:                                                                                              
    83                                                       # As a sampling process is time-consuming,                                                                    
    84                                                       # we employ a zero initializer for faster computation.                                                        
    85                                                       init = constant.Zero()                                                                                        
    86                                                       kwargs = {'initialW': init, 'initial_bias': init}                                                             
    87                                                   else:                                                                                                             
    88                                                       # employ default initializers used in the original paper                                                      
    89         1            5      5.0      0.0              kwargs = {                                                                                                    
    90         1           20     20.0      0.0                  'initialW': normal.Normal(0.01),                                                                          
    91         1           24     24.0      0.0                  'initial_bias': constant.Zero(),                                                                          
    92                                                       }                                                                                                             
    93         1            6      6.0      0.0          super(VGG16Layers, self).__init__(                                                                                
    94         1          920    920.0      0.0              conv1_1=Convolution2D(3, 64, 3, 1, 1, **kwargs),                                                              
    95         1         8095   8095.0      0.1              conv1_2=Convolution2D(64, 64, 3, 1, 1, **kwargs),                                                             
    96         1        14675  14675.0      0.3              conv2_1=Convolution2D(64, 128, 3, 1, 1, **kwargs),                                                            
    97         1        14356  14356.0      0.2              conv2_2=Convolution2D(128, 128, 3, 1, 1, **kwargs),                                                           
    98         1        16880  16880.0      0.3              conv3_1=Convolution2D(128, 256, 3, 1, 1, **kwargs),                                                           
    99         1        25879  25879.0      0.4              conv3_2=Convolution2D(256, 256, 3, 1, 1, **kwargs),                                                           
   100         1        25675  25675.0      0.4              conv3_3=Convolution2D(256, 256, 3, 1, 1, **kwargs),                                                           
   101         1        49397  49397.0      0.9              conv4_1=Convolution2D(256, 512, 3, 1, 1, **kwargs),                                                           
   102         1        97553  97553.0      1.7              conv4_2=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                           
   103         1        96978  96978.0      1.7              conv4_3=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                           
   104         1        96858  96858.0      1.7              conv5_1=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                           
   105         1        96835  96835.0      1.7              conv5_2=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                           
   106         1        97021  97021.0      1.7              conv5_3=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                           
   107         1      4222659 4222659.0     72.9              fc6=Linear(512 * 7 * 7, 4096, **kwargs),                                                                     
   108         1       740794 740794.0     12.8              fc7=Linear(4096, 4096, **kwargs),                                                                             
   109         1       190124 190124.0      3.3              fc8=Linear(4096, 1000, **kwargs),                                                                             
   110                                                   )                                                                                                                 
   111         1            2      2.0      0.0          if pretrained_model == 'auto':                                                                                    
   112                                                       _retrieve(                                                                                                    
   113                                                           'VGG_ILSVRC_16_layers.npz',                                                                               
   114                                                           'http://www.robots.ox.ac.uk/%7Evgg/software/very_deep/'                                                   
   115                                                           'caffe/VGG_ILSVRC_16_layers.caffemodel',                                                                  
   116                                                           self)                                                                                                     
   117         1            1      1.0      0.0          elif pretrained_model == 'zeros':                                                                                 
   118                                                       pass                                                                                                          
   119         1            1      1.0      0.0          elif pretrained_model:                                                                                            
   120                                                       npz.load_npz(pretrained_model, self)                                                                          
   121                                                                                                                                                                     
   122         1            2      2.0      0.0          self.functions = collections.OrderedDict([                                                                        
   123         1            2      2.0      0.0              ('conv1_1', [self.conv1_1, relu]),                                                                            
   124         1            2      2.0      0.0              ('conv1_2', [self.conv1_2, relu]),                                                                            
   125         1            1      1.0      0.0              ('pool1', [_max_pooling_2d]),                                                                                 
   126         1            2      2.0      0.0              ('conv2_1', [self.conv2_1, relu]),                                                                            
   127         1            2      2.0      0.0              ('conv2_2', [self.conv2_2, relu]),                                                                            
   128         1            1      1.0      0.0              ('pool2', [_max_pooling_2d]),                                                                                 
   129         1            1      1.0      0.0              ('conv3_1', [self.conv3_1, relu]),                                                                            
   130         1            1      1.0      0.0              ('conv3_2', [self.conv3_2, relu]),                                                                            
   131         1            1      1.0      0.0              ('conv3_3', [self.conv3_3, relu]),                                                                            
   132         1            2      2.0      0.0              ('pool3', [_max_pooling_2d]),                                                                                 
   133         1            1      1.0      0.0              ('conv4_1', [self.conv4_1, relu]),                                                                            
   134         1            2      2.0      0.0              ('conv4_2', [self.conv4_2, relu]),                                                                            
   135         1            1      1.0      0.0              ('conv4_3', [self.conv4_3, relu]),                                                                            
   136         1            1      1.0      0.0              ('pool4', [_max_pooling_2d]),                                                                                 
   137         1            1      1.0      0.0              ('conv5_1', [self.conv5_1, relu]),                                                                            
   138         1            1      1.0      0.0              ('conv5_2', [self.conv5_2, relu]),                                                                            
   139         1            1      1.0      0.0              ('conv5_3', [self.conv5_3, relu]),                                                                            
   140         1            1      1.0      0.0              ('pool5', [_max_pooling_2d]),                                                                                 
   141         1            2      2.0      0.0              ('fc6', [self.fc6, relu, dropout]),                                                                           
   142         1            1      1.0      0.0              ('fc7', [self.fc7, relu, dropout]),                                                                           
   143         1            2      2.0      0.0              ('fc8', [self.fc8]),                                                                                          
   144         1          105    105.0      0.0              ('prob', [softmax]),                                                                                          
   145                                                   ])                                                                                                                

```



This is a line by line profile when initialized by zeros.
```
Timer unit: 1e-06 s                                                                                                                                                                
                                                                                                                                                                                   
Total time: 0.102063 s                                                                                                                                                             
File: /home/leus/install/chainer/chainer/links/model/vision/vgg.py                                                                                                                 
Function: __init__ at line 80                                                                                                                                                      
                                                                                                                                                                                   
Line #      Hits         Time  Per Hit   % Time  Line Contents                                                                                                                     
==============================================================                                                                                                                     
    80                                               @do_line_profile()                                                                                                            
    81                                               def __init__(self, pretrained_model='auto'):                                                                                 
    82         1            2      2.0      0.0          if pretrained_model:                                                                                                      
    83                                                       # As a sampling process is time-consuming,                                                                            
    84                                                       # we employ a zero initializer for faster computation.                                                                
    85         1           10     10.0      0.0              init = constant.Zero()                                                                                                
    86         1            2      2.0      0.0              kwargs = {'initialW': init, 'initial_bias': init}                                                                     
    87                                                   else:                                                                                                                     
    88                                                       # employ default initializers used in the original paper                                                              
    89                                                       kwargs = {                                                                                                            
    90                                                           'initialW': normal.Normal(0.01),                                                                                  
    91                                                           'initial_bias': constant.Zero(),                                                                                  
    92                                                       }                                                                                                                     
    93         1            2      2.0      0.0          super(VGG16Layers, self).__init__(                                                                                        
    94         1          187    187.0      0.2              conv1_1=Convolution2D(3, 64, 3, 1, 1, **kwargs),                                                                      
    95         1          295    295.0      0.3              conv1_2=Convolution2D(64, 64, 3, 1, 1, **kwargs),                                                                     
    96         1          320    320.0      0.3              conv2_1=Convolution2D(64, 128, 3, 1, 1, **kwargs),                                                                    
    97         1          529    529.0      0.5              conv2_2=Convolution2D(128, 128, 3, 1, 1, **kwargs),                                                                   
    98         1          826    826.0      0.8              conv3_1=Convolution2D(128, 256, 3, 1, 1, **kwargs),                                                                   
    99         1         1531   1531.0      1.5              conv3_2=Convolution2D(256, 256, 3, 1, 1, **kwargs),                                                                   
   100         1         1566   1566.0      1.5              conv3_3=Convolution2D(256, 256, 3, 1, 1, **kwargs),                                                                   
   101         1         1616   1616.0      1.6              conv4_1=Convolution2D(256, 512, 3, 1, 1, **kwargs),                                                                   
   102         1         2730   2730.0      2.7              conv4_2=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                                   
   103         1         2823   2823.0      2.8              conv4_3=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                                   
   104         1         2664   2664.0      2.6              conv5_1=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                                   
   105         1         2641   2641.0      2.6              conv5_2=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                                   
   106         1         2650   2650.0      2.6              conv5_3=Convolution2D(512, 512, 3, 1, 1, **kwargs),                                                                   
   107         1        68176  68176.0     66.8              fc6=Linear(512 * 7 * 7, 4096, **kwargs),                                                                              
   108         1        10157  10157.0     10.0              fc7=Linear(4096, 4096, **kwargs),                                                                                     
   109         1         3224   3224.0      3.2              fc8=Linear(4096, 1000, **kwargs),                                                                                     
   110                                                   )                                                                                                                         
   111         1            1      1.0      0.0          if pretrained_model == 'auto':                                                                                            
   112                                                       _retrieve(                                                                                                            
   113                                                           'VGG_ILSVRC_16_layers.npz',                                                                                       
   114                                                           'http://www.robots.ox.ac.uk/%7Evgg/software/very_deep/'                                                           
   115                                                           'caffe/VGG_ILSVRC_16_layers.caffemodel',                                                                          
   116                                                           self)                                                                                                             
   117         1            1      1.0      0.0          elif pretrained_model == 'zeros':                                                                                         
   118         1            1      1.0      0.0              pass                                                                                                                  
   119                                                   elif pretrained_model:                                                                                                    
   120                                                       npz.load_npz(pretrained_model, self)                                                                                  
   121                                                                                                                                                                             
   122         1            2      2.0      0.0          self.functions = collections.OrderedDict([                                                                                
   123         1            2      2.0      0.0              ('conv1_1', [self.conv1_1, relu]),                                                                                    
   124         1            1      1.0      0.0              ('conv1_2', [self.conv1_2, relu]),                                                                                    
   125         1            1      1.0      0.0              ('pool1', [_max_pooling_2d]),                                                                                         
   126         1            1      1.0      0.0              ('conv2_1', [self.conv2_1, relu]),                                                                                    
   127         1            1      1.0      0.0              ('conv2_2', [self.conv2_2, relu]),                                                                                    
   128         1            1      1.0      0.0              ('pool2', [_max_pooling_2d]),                                                                                         
   129         1            1      1.0      0.0              ('conv3_1', [self.conv3_1, relu]),                                                                                    
   130         1            1      1.0      0.0              ('conv3_2', [self.conv3_2, relu]),                                                                                    
   131         1            1      1.0      0.0              ('conv3_3', [self.conv3_3, relu]),                                                                                    
   132         1            1      1.0      0.0              ('pool3', [_max_pooling_2d]),                                                                                         
   133         1            1      1.0      0.0              ('conv4_1', [self.conv4_1, relu]),                                                                                    
   134         1            1      1.0      0.0              ('conv4_2', [self.conv4_2, relu]),                                                                                    
   135         1            1      1.0      0.0              ('conv4_3', [self.conv4_3, relu]),                                                                                    
   136         1            1      1.0      0.0              ('pool4', [_max_pooling_2d]),                                                                                         
   137         1            1      1.0      0.0              ('conv5_1', [self.conv5_1, relu]),                                                                                    
   138         1            1      1.0      0.0              ('conv5_2', [self.conv5_2, relu]),                                                                                    
   139         1            1      1.0      0.0              ('conv5_3', [self.conv5_3, relu]),                                                                                    
   140         1            1      1.0      0.0              ('pool5', [_max_pooling_2d]),                                                                                         
   141         1            1      1.0      0.0              ('fc6', [self.fc6, relu, dropout]),                                                                                   
   142         1            1      1.0      0.0              ('fc7', [self.fc7, relu, dropout]),                                                                                   
   143         1            1      1.0      0.0              ('fc8', [self.fc8]),                                                                                                  
   144         1           85     85.0      0.1              ('prob', [softmax]),                                                                                                  
   145                                                   ])                                                                                                                        
                                                                                                                                                                                   

```

### CODE REVIEW

**Comment by yuyu2172** [comment]
Alternatively, we can add an argument to `__init__` that lets users to manually decide initialization methods for internal layers.

**Comment by delta2323** [comment]
How about passing an initializer (i.e. an instance of `Initializer`) like ordinal convolutions?

**Comment by yuyu2172** [comment]
Yeah, I think that is a better design.

**Comment by yuyu2172** [comment]
Updated.

**Comment by yuyu2172** [comment]
Sorry. I do not have time to finish this.

**Pull request closed without merging**
