### PR TITLE
Add `squared_difference` to chainerx

### PR DESCRIPTION
**Pull request by aksub99**
Add squared_difference to chainerx
Ref. #6423 
Depends on #6486

### CODE REVIEW

**Comment by aksub99** [comment]
Accommodated for Camel Case class name requirement as in issue #6505

**Comment by aksub99** [comment]
@hvy Could you please review?

**Comment by hvy** [comment]
Thanks for the PR. The implementation of the routine looks simple and good but could you fix the test? I don't think you're testing the actual binding introduced. The parameterizations that you've used covers edge cases and look good. But could you derive `op_utils.OpTest` similar to https://github.com/chainer/chainer/blob/master/tests/chainerx_tests/unit_tests/routines_tests/test_activation.py#L46 and override forward methods separately for chainerx and numpy?

**Comment by aksub99** [comment]
Sure! Will do. Thanks for the review.

**Comment by aksub99** [comment]
@hvy I have modified the tests as suggested. Could you please take a look?

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM, let me verify it with the CI.

**Comment by hvy** [comment]
CI failure looks unrelated so let me merge this PR. I noticed that the test could have been written with `op_utils.ChainerOpTest` which would have been better but that can be addressed in a separate PR (contribution-welcome).

**Pull request merged**
