### PR TITLE
New style exp

### PR DESCRIPTION
**Pull request by aonotas**
This PR depends on #3096, and is a part of #3147.
New style exp function for `Double backward support for v3`.

### CODE REVIEW

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
LGTM! Please rebase master.

**Comment by unnonouno** [comment]
This patch includes redundant commits. Please remove them or squash it.

**Comment by aonotas** [comment]
Oh...I'm sorry, please just a moment.

**Pull request closed without merging**
