### PR TITLE
Relax tolerance for float16 in `unary_math_function_unittest`

### PR DESCRIPTION
**Pull request by asi1024**
This PR fixes the occasional test failure in `test_erfc.py`.

### CODE REVIEW

**Comment by niboshi** [comment]
Are there any particular tests this PR is aimed for?

**Comment by asi1024** [comment]
This PR fixes the occasional test failure in `test_erfc.py` at least.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
