### PR TITLE
 Update examples and tests for chainer.backends.cuda 

### PR DESCRIPTION
**Pull request by vilyaair**
Update examples and tests in accordance with #3974 and #3981

### CODE REVIEW

**Comment by delta2323** [comment]
jenkins, test this please.

**Comment by delta2323** [comment]
@niboshi Could you take a look at the PR, as you designed and implemented the backend (if I remember correctly)?

**Comment by niboshi** [comment]
@delta2323 LGTM.
When backporting, please do not include the changes in documentation and examples.

**Comment by delta2323** [comment]
@niboshi OK, thanks.

**Comment by delta2323** [comment]
@vilyaair Could you resolve the conflict?

**Comment by kmaehashi** [comment]
@vilyaair Sorry, another conflict is happening as another PR (iDeep) got merged. Could you please resolve it?

**Comment by delta2323** [comment]
jenkins test this please.

**Comment by delta2323** [comment]
LGTM

**Comment by delta2323** [comment]
Thank you for your contribution!

**Pull request merged**
