### PR TITLE
Fix order of items in Reference section

### PR DESCRIPTION
**Pull request by kmaehashi**
~~Depends on #4488.~~ (merged)

### CODE REVIEW

**Comment by kmaehashi** [comment]
Rebased and ready for review.

**Comment by kmaehashi** [comment]
The intension of new order is:

```
// Basic data structures
variable

// Network components
functions
links
optimizers
initializers

// Trainer
training
datasets
iterators

// Utils
serializers
util
configuration

// Utils (for trouble shooting)
debug
graph

// Misc (maybe only limited number of users are interested in)
caffe
check
```

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Pull request merged**
