### PR TITLE
Simplify `F.bilinear` test

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies`test_bilinear` using `testing.FunctionTestCase`.

Solves part of issue #6071

### CODE REVIEW

**Comment by ishanrai05** [comment]
@Crissman Can you please review this?

**Comment by Crissman** [comment]
Tests passed dropped from 11 to 7. Can you take a look?

**Comment by ishanrai05** [comment]
@Crissman The tests passed dropped because `partial_forward`, `partial_backward` and `partial_double_backward` were not being tested. I managed to fix it by adding a flag `test_partial` and adjusting the code accordingly. Can you please take a look at the code again?

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins issues look unrelated. Merging.

**Pull request merged**
