### PR TITLE
[backport] New style negative_sampling

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3992, will be rebased after #4021 merged.

### CODE REVIEW

**Comment by hvy** [comment]
Could you rebase the backport since #4021 has been is merged?

**Comment by takagi** [comment]
Merged the latest `v3` branch!

**Comment by hvy** [comment]
It seems like `scatter_add` which this PR depends on is not backported. Do we still want to backport it?

**Comment by takagi** [comment]
Okay, then let's leave negative sampling not backported before any actual problem could happen.

**Comment by takagi** [comment]
Close because `scatter_add` #3442 is not introduced in `v3` as a backport.

**Pull request closed without merging**
