### PR TITLE
[WIP] Parallelize ChainerX tests in travis CI

### PR DESCRIPTION
**Pull request by niboshi**
Aims to solve the timeout issue.

### CODE REVIEW

**Comment by niboshi** [comment]
pytest-xdist cannot handle those tests parameterizing lambda functions.
They are rewritten using string parameterization.

**Comment by niboshi** [comment]
Observations so far:
* If the entire tests are run with xdist, it slows down at about 69% (no matter what the order tests are sorted), and finally causes timeout.
* If only half of the tests are run with xdist, any slowdown is not observed (in both the first and the second half of the tests), but the total run time (former + latter) is approximately the same as successful runs without xdist, meaning that it does not benefit at all from parallelization.
* If the test script is run locally by the following command, the above problems are not observed:
```sh
CHAINER_TRAVIS_TEST=chainer TRAVIS_BUILD_DIR="$PWD" \
bash scripts/ci/travis/run-tests.sh script
```

**Comment by emcastillo** [comment]
What are the specs of the travis vm?
maybe only one core?

**Comment by niboshi** [comment]
There are 2 cores: https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system

**Comment by emcastillo** [comment]
Yes, its weird to have the slowdown, maybe cpu affinity mask when running in travis? highly unlikely but I cant think of anything else.

**Comment by niboshi** [comment]
Seems like a memory issue?
### beginning
```
[2019-10-01 09:40:58] top - 09:41:03 up 6 min,  1 user,  load average: 1.85, 1.27, 0.58
[2019-10-01 09:41:03] Tasks: 103 total,   3 running,  63 sleeping,   0 stopped,   0 zombie
[2019-10-01 09:41:03] %Cpu(s): 66.7 us,  7.8 sy,  1.1 ni, 20.5 id,  3.9 wa,  0.0 hi,  0.0 si,  0.0 st
[2019-10-01 09:41:03] KiB Mem :  7652340 total,  4802328 free,   731984 used,  2118028 buff/cache
[2019-10-01 09:41:03] KiB Swap:        0 total,        0 free,        0 used.  6575684 avail Mem 
[2019-10-01 09:41:03] 
[2019-10-01 09:41:03]   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
[2019-10-01 09:41:03]  9180 travis    20   0  751364 266068  39976 R 10+sleep 5
6.7  3.5   0:14.33 /home/travis/virtualenv/python3.5.6/bin/python -u +
[2019-10-01 09:41:03]  9177 travis    20   0  751072 265528  39576 R 100.0  3.5   0:14.27 /home/travis/virtualenv/python3.5.6/bin/python -u +
[2019-10-01 09:41:03]     1 root      20   0   37724   5724   3956 S   0.0  0.1   0:01.70 /sbin/init
[2019-10-01 09:41:03]     2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [kthreadd]
[2019-10-01 09:41:03]     4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 [kworker/0:0H]
[2019-10-01 09:41:03]     5 root      20   0       0      0      0 I   0.0  0.0   0:00.79 [kworker/u4:0]
[2019-10-01 09:41:03]     6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 [mm_percpu_wq]
[2019-10-01 09:41:03]     7 root      20   0       0      0      0 S   0.0  0.0   0:00.10 [ksoftirqd/0]
[2019-10-01 09:41:03]     8 root      20   0       0      0      0 I   0.0  0.0   0:00.30 [rcu_sched]
[2019-10-01 09:41:03]     9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 [rcu_bh]
[2019-10-01 09:41:03]    10 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 [migration/0]
[2019-10-01 09:41:03]    11 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 [watchdog/0]
[2019-10-01 09:41:03]    12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [cpuhp/0]
```
### ending
```
[2019-10-01 09:59:41] top - 09:59:46 up 24 min,  1 user,  load average: 2.37, 2.42, 1.94
[2019-10-01 09:59:46] Tasks: 104 total,   3 running,  62 sleeping,   0 stopped,   0 zombie
[2019-10-01 09:59:46] %Cpu(s): 87.7 us,  5.6 sy,  0.3 ni,  5.3 id,  1.0 wa,  0.0 hi,  0.2 si,  0.0 st
[2019-10-01 09:59:46] KiB Mem :  7652340 total,   151500 free,  6377668 used,  1123172 buff/cache
[2019-10-01 09:59:46] KiB Swap:        0 total,        0 free,        0 used.   901396 avail Mem 
[2019-10-01 09:59:46] 
[2019-10-01 09:59:46]   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
[2019-10-01 09:59:46]  9180 travis    20   0 3165156 2.405g  48292 R 100.0 33.0  15:48.61 /home/travis/virtual+sleep 5
env/python3.5.6/bin/python -u +
[2019-10-01 09:59:46]  9177 travis    20   0 3199892 2.568g  46196 R  93.3 35.2  15:38.40 /home/travis/virtualenv/python3.5.6/bin/python -u +
[2019-10-01 09:59:46]     1 root      20   0   37724   5724   3956 S   0.0  0.1   0:01.71 /sbin/init
[2019-10-01 09:59:46]     2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [kthreadd]
[2019-10-01 09:59:46]     4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 [kworker/0:0H]
[2019-10-01 09:59:46]     5 root      20   0       0      0      0 I   0.0  0.0   0:02.08 [kworker/u4:0]
[2019-10-01 09:59:46]     6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 [mm_percpu_wq]
[2019-10-01 09:59:46]     7 root      20   0       0      0      0 S   0.0  0.0   0:00.15 [ksoftirqd/0]
[2019-10-01 09:59:46]     8 root      20   0       0      0      0 I   0.0  0.0   0:01.33 [rcu_sched]
[2019-10-01 09:59:46]     9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 [rcu_bh]
[2019-10-01 09:59:46]    10 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 [migration/0]
[2019-10-01 09:59:46]    11 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 [watchdog/0]
[2019-10-01 09:59:46]    12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [cpuhp/0]
```

**Pull request closed without merging**
