### PR TITLE
Cupy complex

### PR DESCRIPTION
**Pull request by boeddeker**
#1525

### CODE REVIEW

**Comment by delta2323** [comment]
Thank you for submitting PR! We will take a look to see if it is possible to include your work.

**Comment by bkvogel** [comment]
Would it be possible to consider splitting up your PR into several smaller PRs? This is not required, but it could make the reviewing process more manageable.

I understand you are currently running the latest CUDA version and are not able to test that your code will pass the build tests under older CUDA versions such as 6.5. Would it be possible for you to install Docker and NVIDA Docker? If so, we have a script that makes it easier to test your chainer code on older versions of CUDA without having to manually set up your environment for each one:

https://github.com/pfnet/chainer-test

Could this option work for you?

**Comment by boeddeker** [comment]
I can split the PR, but many thinks are coupled. I think some part from testing can splitted. Also some changes are already implemented (#1419). Currently there are also some Bugs witch I have to find.
Currently I have not the time to do this. I think next month I will continue.

Since I have no root acces to gpu-workstations I must ask my admin, who does not like to install more Software, especially when only one person requires this software.

**Comment by bkvogel** [comment]
We really appreciate your PR and do not want CUDA installation requirements to get in the way of further contributions. If it is difficult to get Docker installed, I think the Chainer team members can probably test your code on older versions of CUDA. 

If you have limited time, maybe fixing the bugs is more important than splitting into smaller PRs.

**Comment by boeddeker** [comment]
It seems that I do not get access to an computer with docker and nvidia-docker in the next months.
Therefore I will write and ask, when it is ready to test.

One Question: 
In the build process (install.build.check_cuda_version) of chainer the nvidia version number is known. Does anyone know how I get this number inside the cupy.core.core.pyx?

**Comment by bkvogel** [comment]
That sounds fine. 
You can get the version number from:
https://github.com/pfnet/chainer/blob/master/cupy/cuda/runtime.pyx#L140

**Comment by boeddeker** [comment]
I have now add a cupy_complex_available flag in core.pyx.
Now this branch should work with real numbers and an older cuda version. Can someone test it?

**Comment by bkvogel** [comment]
Thank you for the updates. Could you resolve the conflicts with master? We will then test. If you have time now to split into smaller PRs, that would be helpful, but is not required.

**Comment by boeddeker** [comment]
I know that I have changed many files, but after the first code was working, the idea was a test driven coding (Adding the dtypes for complex in the testcases). Therefore many code have to be changed, that the complex numbers in cupy have enough functions to be useful.

Ok, thanks, I have merged the master and solved all problems for travis.

**Comment by bkvogel** [comment]
Thanks for fixing the conflicts.

**Comment by okuta** [comment]
This feature will merge by cupy/cupy#232.

**Pull request closed without merging**
