### PR TITLE
Add `contains_nan`

### PR DESCRIPTION
**Pull request by toslunar**
The NaN check is not trivial so that Chainer could offer such a function.

The PR may supersede #4737.

### CODE REVIEW

**Comment by okuta** [comment]
Do you want to this as public method?

**Comment by toslunar** [comment]
OK, it's better to be private at the moment.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Comment by toslunar** [comment]
`_contains_nan` is private.

**Pull request merged**
