### PR TITLE
Allow mixing `testing.inject_backend_tests` and `testing.parameterize`

### PR DESCRIPTION
**Pull request by niboshi**
Follow-up #5893

With this fix, it will be possible to mix `inject_backend_tests` and `parameterize` any times in any order.

**no-compat**: With this change, it is no longer possible to inherit from a base class with `@inject_backend_tests` applied.

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
