### PR TITLE
Forbid fallback get/setitem for arrays with backprop required

### PR DESCRIPTION
**Pull request by niboshi**
`_setitem` and `_getitem` workarounds for ChainerX does not support backpropagation.
It's better to strictly prohibit them when the arrays have graphs.

### CODE REVIEW

**Comment by hvy** [comment]
Could you briefly document the motivation this PR?

**Comment by niboshi** [comment]
Done.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Discussed offline to prohibit this for now although it is strictly speaking not necessary to do so now.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Jenkins failure seems unrelated. LGTM!

**Comment by mingxiaoh** [comment]
This PR causes  about 10% performance regression on RNN Backward.


Small LSTM | batchsize | Type | P100 | skx-8180 | skx-8180/refs
-- | -- | -- | -- | -- | --
DS2 | 32 | Forward(sps) | 4.673 | 17.427 | 97.31%
Backward(sps) | 9.961 | 6.696 | 91.63%
Update(sps) | 179.61 | 1726.564 | 98.15%
Total(sps) | 31.256 | 49.778 | 96.19%
Big LSTM | 64 | Forward(sps) | 25.332 | 514.814 | 97.81%
Backward(sps) | 28.939 | 26.937 | 91.86%
Update(sps) | 365.437 | 98346.018 | 95.38%
Total(sps) | 13.026 | 25.591 | 92.16%
Small LSTM | 64 | Forward(sps) | 28.946 | 468.674 | 103.02%
Backward(sps) | 31.92 | 24.358 | 91.94%
Update(sps) | 373.042 | 102687.524 | 113.23%
Total(sps) | 14.587 | 23.15 | 92.50%

**Comment by niboshi** [comment]
@mingxiaoh 
Thank you for reporting. I made an issue: #7071

**Pull request merged**
