### PR TITLE
Check grads of inputs to test backward of collective communication

### PR DESCRIPTION
**Pull request by toslunar**
Before the PR, some tests use grads of outputs.

### CODE REVIEW

**Comment by shu65** [comment]
Jenkins, test this please

**Comment by shu65** [comment]
I will also perform unittests for chainermn

**Comment by toslunar** [comment]
The Jenkins failure
```
TestELU_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_1__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_0_{shape=(3, 2), dtype=<class 'numpy.float16'>, alpha_range=(-2.0, 0.0)}.test_double_backward
```
is unrelated to the PR.

**Comment by shu65** [comment]
I confirmed that the unittests for ChainerMN are passed.
I will merge this PR after passing test with travis.

**Comment by shu65** [comment]
The test case for chainerx has failed with travis. 
But, it is unrelated to the PR.
What should we do? @toslunar

**Comment by shu65** [comment]
I ignore this failure, because it is unrelated to the PR.

**Pull request merged**
