### PR TITLE
Support mixed indices in `TabularDataset.slice`

### PR DESCRIPTION
**Pull request by Hakuyume**
`numpy.ndarray` supports mixture of ints and bools as slice indices. This PR adds same functionality to `TabularDataset.slice`.

### CODE REVIEW

**Comment by Hakuyume** [comment]
jenkins, test this please.

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by beam2d** [comment]
Jenkins, test this please.

**Comment by beam2d** [comment]
LGTM. CI failure is not related.

**Comment by beam2d** [comment]
Oh the pfnCI also failed by timeout. I will retrigger.

**Comment by beam2d** [comment]
Reran pfnCI and it passed.

**Pull request merged**
