### PR TITLE
Remove obsolete assertions

### PR DESCRIPTION
**Pull request by niboshi**
Required in #6646

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Can you rebase now that mixed dtype BatchNorm has been merged?

**Comment by niboshi** [comment]
Rebased.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
CI failure seems unrelated. LGTM!

**Pull request merged**
