### PR TITLE
[backport] prefix class name to attributes in pydoc

### PR DESCRIPTION
**Pull request by hvy**
Backport of #4206

### CODE REVIEW

**Comment by hvy** [comment]
Might want to merge this one first https://github.com/chainer/chainer/pull/4207

**Comment by niboshi** [comment]
I guess it's opposite: this PR should be merged before #4207?

**Comment by hvy** [comment]
Ah, if this PR is still compatible we should of course prevent the error in the first place.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
