### PR TITLE
Relax test condition

### PR DESCRIPTION
**Pull request by unnonouno**
I changed test condition to pass.

### CODE REVIEW

**Comment by niboshi** [comment]
Why does directional differentiation require these relaxation, theoretically?

**Comment by unnonouno** [comment]
I'm not sure but in the previous implementation some gradients especially for array functions have the same direction to random vectors. I mean these functions returns an input vector itself and the previous implementation uses the input vector as a random vector. In the new implementation, they have different directions and it may causes calculation errors.

**Comment by unnonouno** [comment]
This PR will be replaced with #3652

**Comment by niboshi** [comment]
OK.

**Pull request closed without merging**
