### PR TITLE
Add test for `Parameter` initialization with device transfer and config dtype

### PR DESCRIPTION
**Pull request by hvy**
Separated from and depends on https://github.com/chainer/chainer/pull/8043.

This PR adds tests for a broken `Parameter` initialization scenario that is fixed via the above PR.

### CODE REVIEW

**Comment by hvy** [comment]
@toslunar I separated the tests as per your suggestion. The dtype is now also checked explicitly  since it's not tested by `assert_array_equal`.

**Comment by toslunar** [comment]
> title: Add test for `Parameter` initialization with device transfer and config dtype

The PR fixes `Constant` initializer.  It is (and should be) nothing to do with `Parameter`.  Otherwise please close #6116 first.

**Comment by hvy** [comment]
This PR is created on top of #8043 (that includes a fix) but this itself does not fix anything and merely adds a `Parameter` test.

**Comment by toslunar** [comment]
It's better to avoid testing `Constant` in `test_variable`, while I know there are such tests.  `Parameter(ndarray)` may be tested here, but `Parameter(Constant(_))` is not.

**Comment by hvy** [comment]
Let me close this issue as it's covered and fixed by https://github.com/chainer/chainer/pull/8089.

**Pull request closed without merging**
