### PR TITLE
Return exitcode of `make html` to Travis

### LINKED ISSUE #5767: Documentation build failure on Travis is not caught
https://github.com/chainer/chainer/blob/43947519131dc15586d2487ced976885b69f5280/.travis.yml#L89-L92

`pushd docs; make html; popd;` has exitcode `0` because `popd` succeeds.

### PR DESCRIPTION
**Pull request by toslunar**
Close #5767.

### CODE REVIEW

**Comment by toslunar** [comment]
Travis failed with
```
reading sources... [ 21%] reference/generated/chainer.AbstractSerializer        
Exception occurred:
  File "conf.py", line 400, in _is_parent_site_packages
    return os.path.dirname(path) in site.getsitepackages()
AttributeError: module 'site' has no attribute 'getsitepackages'
The full traceback has been saved in /tmp/sphinx-err-v0d14ofu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 2
make: Leaving directory '/home/travis/build/chainer/chainer/docs'
The command "if [[ $SKIP_CHAINERX != 1 ]]; then make -C docs html; else echo "Documentation build is skipped as ChainerX is not available."; fi" exited with 2.
```
as expected :tada:

Merge #5766 first.

**Comment by kmaehashi** [comment]
Retriggered travis.

**Comment by toslunar** [comment]
oops

**Comment by toslunar** [comment]
Travis succeeded :tada:

**Comment by kmaehashi** [comment]
LGTM!

**Comment by kmaehashi** [comment]
This does not need to be backported as `SKIP_CHAINERX` block is introduced for ChainerX.

**Pull request merged**
