### PR TITLE
Add `--test` option to seq2seq example

### PR DESCRIPTION
**Pull request by arisliang**
There's already a device allocation above the removed one.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks!
Jenkins, test this please.

**Comment by arisliang** [comment]
What's the best way to create multiple pull requests? I pushed another commit of the same file. It automatically combined in the previous pull request.

Should I change the name of the pull request to reflect it contains two merge? Or someway to separate the PR (but they're in the same file). What's the better way to do this?

**Comment by kmaehashi** [comment]
I think `--test` option is not needed for seq2seq example, as data is given from external file (i.e., unlike other examples using built-in dataset functions, users can control the size of data.)
If you need to experiment with small dataset, you can just use the first N lines of the source/target sentences. You can even create your own small dataset in the same format, like this: https://github.com/chainer/chainer-test/tree/master/data/seq2seq

**Comment by arisliang** [comment]
> use the first N lines of the source/target sentences

That's what I did with --test option. True, user can manipulate external data file, but it's just easier to toggle it with a switch.

**Comment by arisliang** [comment]
`Could you please split the PR?` To be honest, I'm not sure how to do it through github ui. Is it something I'd have to go through command line? If that's the case, maybe I'll try recreate the PR, might be easier.

**Comment by kmaehashi** [comment]
You cannot do that via Github UI. Feel free to close and recreate PRs!

**Comment by kmaehashi** [comment]
@arisliang ping? (I can takeover this fix if you don't have time.)

**Comment by arisliang** [comment]
@kmaehashi Yes, please, thank you.

**Comment by kmaehashi** [comment]
I'll revisit after #4782

**Comment by kmaehashi** [comment]
Redundant device allocation has been fixed in #4848.
As for ``--test`` argument, we should reconsider it as we now have `TextDataset` which does not load everything on memory.

**Pull request closed without merging**
