### PR TITLE
Improve concat_examples

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by Crissman** [comment]
Looks ok. What's WIP?

**Comment by okuta** [comment]
CuPy have not feature for this PR.

**Comment by niboshi** [comment]
What's the improved point?

**Comment by okapies** [comment]
It depends on cupy/cupy#2081. I'll work on it after it is merged.

**Comment by Crissman** [comment]
Status?

**Comment by okapies** [comment]
Still working but I think I should refactor `chainer._backend._convert_arrays()` for improving abstraction.

**Comment by okuta** [comment]
Please use #7823.

**Pull request closed without merging**
