### PR TITLE
Add `ignore::ImportWarning` to `setup.cfg`

### LINKED ISSUE #8123: Pytest fails when importing cupy
We found that pytest fails when trying to import cupy under the main directory of chainer after commit 406b198433ef9f4fd68b7d9baf57d4cdb05c51dc.

How to reproduce:

**Test File**
```
tianqi@host:chainer$ cat test.py
import cupy
```

**Versions**
```
pytest version 4.6.2
Python 3.7.2
```

**Errors with master**
```
tianqi@host:chainer$ git checkout master
Previous HEAD position was a75d9cd... Fix braced-scalar-init warning
Switched to branch 'master'
Your branch is up-to-date with 'original_repo/master'.
tianqi@host:chainer$ pytest test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: repository/chainer, inifile: setup.cfg
plugins: random-order-1.0.4
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 151, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 88, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 27, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/warnings.py", line 264, in _getcategory
INTERNALERROR>     m = __import__(module, None, None, [klass])
INTERNALERROR>   File "repository/tmp/chainer/chainer/__init__.py", line 96, in <module>
INTERNALERROR>     _environment_check.check()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 110, in check
INTERNALERROR>     _check_optional_dependencies()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 102, in _check_optional_dependencies
INTERNALERROR>     '''.format(name=name, pkgs=pkgs))
INTERNALERROR> UserWarning:
INTERNALERROR> --------------------------------------------------------------------------------
INTERNALERROR> Multiple installations of CuPy package has been detected.
INTERNALERROR> You should select only one package from from ['cupy-cuda101', 'cupy-cuda100', 'cupy-cuda92', 'cupy-cuda91', 'cupy-cuda90', 'cupy-cuda80', 'cupy'].
INTERNALERROR> Run `pip list` to see the list of packages currently installed, then
INTERNALERROR> `pip uninstall <package name>` to uninstall unnecessary package(s).
INTERNALERROR> --------------------------------------------------------------------------------

============================================================================ no tests ran in 2.48 seconds ============================================================================
tianqi@host:chainer$ 
```

**Errors with 406b198**
```
tianqi@host:chainer$ git checkout 406b198433ef9f4fd68b7d9baf57d4cdb05c51dc
HEAD is now at 406b198... Merge pull request #6653 from niboshi/warnings-as-errors
tianqi@host:chainer$ pytest test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: repository/chainer, inifile: setup.cfg
plugins: random-order-1.0.4
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 151, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 88, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 27, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/warnings.py", line 264, in _getcategory
INTERNALERROR>     m = __import__(module, None, None, [klass])
INTERNALERROR>   File "repository/tmp/chainer/chainer/__init__.py", line 96, in <module>
INTERNALERROR>     _environment_check.check()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 110, in check
INTERNALERROR>     _check_optional_dependencies()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 102, in _check_optional_dependencies
INTERNALERROR>     '''.format(name=name, pkgs=pkgs))
INTERNALERROR> UserWarning:
INTERNALERROR> --------------------------------------------------------------------------------
INTERNALERROR> Multiple installations of CuPy package has been detected.
INTERNALERROR> You should select only one package from from ['cupy-cuda101', 'cupy-cuda100', 'cupy-cuda92', 'cupy-cuda91', 'cupy-cuda90', 'cupy-cuda80', 'cupy'].
INTERNALERROR> Run `pip list` to see the list of packages currently installed, then
INTERNALERROR> `pip uninstall <package name>` to uninstall unnecessary package(s).
INTERNALERROR> --------------------------------------------------------------------------------

============================================================================ no tests ran in 2.43 seconds ============================================================================
tianqi@host:chainer$
```
**No Error with a75d9cd**
```
tianqi@host:chainer$ git checkout a75d9cde77e626bd10f74a8472795687109dcedb
Previous HEAD position was 406b198... Merge pull request #6653 from niboshi/warnings-as-errors
HEAD is now at a75d9cd... Fix braced-scalar-init warning
tianqi@host:chainer$ pytest test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: repository/chainer, inifile: setup.cfg
plugins: random-order-1.0.4
collected 0 items

============================================================================ no tests ran in 1.03 seconds ============================================================================
tianqi@host:chainer$
```

where, a75d9cde77e626bd10f74a8472795687109dcedb is the commit right before 406b198433ef9f4fd68b7d9baf57d4cdb05c51dc

### PR DESCRIPTION
**Pull request by shmurai**
~This will resolve #8123.~
This will resolve issues related to `import cupy` when testing Chainer with `pytest`. (#8138)

### CODE REVIEW

**Comment by niboshi** [comment]
Could you clarify where `ImportWarning` comes from, specifically, and how it is related to `chainer.warnings.PerformanceWarning`?

**Comment by shmurai** [comment]
`import cupy` itself can cause `ImportWarning`, which is ignored by default.
This can be verified by running `python` with `-W error` option:
```
>>> import cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "******/python3.7/site-packages/cupy/__init__.py", line 12, in <module>
    from cupy import core  # NOQA
  File "******/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "******/python3.7/site-packages/cupy/cuda/__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "******/python3.7/site-packages/cupy/cuda/compiler.py", line 12, in <module>
    from cupy.cuda import function
  File "cupy/cuda/memory.pxd", line 11, in init cupy.cuda.function
  File "cupy/cuda/memory.pyx", line 1, in init cupy.cuda.memory
  File "fastrlock/_lock.pxi", line 4, in init fastrlock.rlock
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

Chainer internally uses cupy, so `import chainer` or like also imports `cupy` as well. 
Therefore, `cupy` will be imported by `ignore::chainer.warnings.PerformanceWarning` in `setup.cfg`.
However, since `import cupy` causes an `ImportWarning`, which is to be regarded as an error (by `filterwarnings= error` in `setup.cfg`), this import stops halfway. This failure of import may cause failure of subsequent `import cupy` with different reason (not 100% confident).

To resolve this, we can simply make `ImportWarning` ignored. This is why I added `ignore::ImportWarning` to `setup.cfg`.
Also, the descriptions in `filterwarnings` look to be interpreted one by one (not 100% confident).
So, if we add `ignore::ImportWarning` after `ignore::chainer.warnings.PerformanceWarning`, `PerformanceWarning` is interpreted first and `import cupy` occurs before `ImportWarning` is made ignored. In this case, the error in `import cupy` persists. Therefore, we should add `ignore::ImportWarning` before `ignore::chainer.warnings.PerformanceWarning`.

**Comment by niboshi** [comment]
@shmurai Thank you for the detailed description.
Tentatively I made an issue on cupy: https://github.com/cupy/cupy/issues/2476

**Comment by niboshi** [comment]
@shmurai 
The `ImportWarning` comes from a Cython issue (https://github.com/cython/cython/issues/1720) and it seems we can do nothing directly. I think the fix in this PR is probably the best option we can take.
However, `ignore::ImportWarning` could be a bit more specific to limit the affected part. It seems this works: `ignore:can't resolve package from __spec__ or __package__, falling back on __name__ and __path__:ImportWarning`

Also please write a comment above the line. I think it's helpful to include the following information:
* The cause
* Link to a GitHub issue, perhaps https://github.com/cupy/cupy/issues/2476?
* The reason why it needs to be placed above `ignore::chainer.warnings.PerformanceWarning`

**Comment by kuenishi** [comment]
Just note: the issue to be fixed by this change blocks all other ChainerMN testing and development. I hope this get merged in priority (tagged as prio:high).

**Comment by niboshi** [comment]
I could merge this PR in the current state and handle the above requirements later by myself, if you prefer. @shmurai

**Comment by shmurai** [comment]
I'm working on the requested changes and I will update shortly.

**Comment by niboshi** [comment]
Thanks!
Jenkins, test this please

**Comment by niboshi** [comment]
Test failure is unrelated.

**Pull request merged**
