### PR TITLE
[WIP] Out-of-core training on V3

### PR DESCRIPTION
**Pull request by imaihal**
This PR enables us to run out-of-core training on V3. The out-of-core training realizes training of very large models whose memory usage goes above GPU memory by using CPU memory as swap area. This PR is a successor of #2027 (v1 OoC) and basic functions of this PR are ported from [@anaruse ’s branch for v2 OoC](https://github.com/anaruse/chainer/tree/OOC_chainer_v202)). I think they should credit to @anaruse and our contributions are as follows
- Ported automatic breakpoint insertion to split computational graph to V3
- Ported swap-in/out related functions to V3
- Enabled data parallel execution for OoC 
- Added enlarged models of GoogLeNet and ResNet and examples to use it

Please see examples (**_examples/imagenet/train_imagenet_OOC_ibm.py_** and _**examples/imagenet/train_imagenet_data_parallel_OOC_ibm.py**_) to run this function. As you can see in the examples, “with chainer.out_of_core_mode()” enables the out-of-core functions. Command line options of “—ooc” and “—insize” are added in the examples.  You don’t have to modify model files.

I created another PR to Cupy v2 ([Swap in/out between GPU and CPU memory #694](https://github.com/cupy/cupy/pull/694)) and this PR depends on it.

### CODE REVIEW

**Comment by mitmul** [comment]
@imaihal Hi, thank you for sending this PR. How's the progress? It seems to be still a "WIP" PR, but the next major version of Chainer is v5. I think a lot of code in this PR can work in v5 as is, but some conflicts have already happened. Could you resolve those conflicts and let us know the status and plans to finish this PR?

**Comment by imaihal** [comment]
@mitmul Sorry for late reply... Thank you for your comment. We've implemented this PR on Chainer V4, but not done on Chainer V5 yet. Unfortunately, as of now, we don't have plan to do it. However, we are interested in updating this PR. So, we would like to discuss what is the best way to merge official code at some point.

Should I close this PR for now?

**Comment by mitmul** [comment]
@imaihal I think it's OK to keep it open for making this easy-to-track by other committers. Then how about discusssing how to proceed this here or on the slack channel (https://chainer.slack.com)?

**Comment by imaihal** [comment]
@mitmul OK. Thanks. I think it is OK to discuss here.

**Comment by imaihal** [comment]
Hi, @lxqlxq21 , Thank you for trying this v3-ooc and the instruction in the blog.
Chainer v4-ooc and Cupy for v4-ooc are included in following links written in the blog. Have you already tried them?

- Cupy:  https://github.com/negiyas/cupy/tree/v4.0.0a3-ibm

- Chainer: https://github.com/negiyas/chainer/tree/v4.0.0a3-ibm

**Comment by lxqlxq21** [comment]
I tried it with pip install, but import chainer and import cupy both raise error. V3-OOC worked fine for me following the install instruction, but I can’t get any version of chainer and cupy installed after uninstall V3-OOC. It’s probably because I haven’t uninstall it correctly. Either I need to resolve that or is there anyway I can install it as a ready anacondas env? Would it be possible for you to create such an env?

**Comment by lxqlxq21** [comment]
>     * `pip uninstall` repeatedly
>       https://docs.chainer.org/en/stable/install.html#uninstall-chainer
>       http://docs-cupy.chainer.org/en/stable/install.html#uninstall-cupy
 
Done, this doesn't work.

>     * Run a script to clean up in the repository.
>       https://github.com/negiyas/cupy/blob/v4.0.0a3-ibm/clean.sh

under which dir should I run this? I ran it under my downloaded cupy dir. 

>     * Deleting cupy cache(default $HOME/.cupy) might be effective

Done, doesn't work.

>     * Delete build/ and dist/ directories in Chainer and Cupy

Done, doesn't work.

>     * `--no-cache-dir` option
>       `pip install cupy --no-cache-dir` and `pip install chainer --no-cache-dir` when reinstalling
>       http://docs-cupy.chainer.org/en/stable/install.html

Following is the error I see. Could you help me figure out what's going on?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a8430019ca35> in <module>()
      2 import glob
      3 import math, random
----> 4 import chainer
      5 from chainer import cuda, Function, gradient_check, report, training, utils, Variable
      6 from chainer import datasets, iterators, optimizers, serializers

/usr/local/lib/python2.7/dist-packages/chainer/__init__.py in <module>()
      6 import numpy
      7 
----> 8 from chainer import _version
      9 from chainer import backends  # NOQA
     10 from chainer import configuration  # NOQA

ImportError: cannot import name _version

**Pull request closed without merging**
