### PR TITLE
Support ellipsis in `Array::At` and `__getitem__`

### LINKED ISSUE #7560: Support ellipsis in `Array::At` and `__getitem__`
Depends on #7559 because `py::ellipsis` is supported from v2.3.0.

### PR DESCRIPTION
**Pull request by asi1024**
Resolve #7560.
~Depends on #7559.~
~Depends on #7614.~

### CODE REVIEW

**Comment by emcastillo** [comment]
Just a question.
It is possible to add some explicit tests on chainerx side? 

Or with just the chainer test suite should be enough

**Comment by asi1024** [comment]
@emcastillo I added python tests for chainerx now. Usually, we don't add chainerx test in C++ to avoid duplications.

**Comment by emcastillo** [comment]
There are some errors related to indexing on travis.
Might be an issue with the configuration on the CI after upgrading pybind?

**Comment by asi1024** [comment]
This line expects `IndexError` at the end of the loop, but `chainerx.ndarray` currently raises `DimensionError`. How should we fix it?
https://github.com/asi1024/chainer/blob/fb42f0a25106def7d74515eceddd0988f348aa2c/chainer/functions/loss/negative_sampling.py#L299

**Comment by hvy** [comment]
#7614 has now been merged.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Fails due to the flake8 issue a for which a PR is pending.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Unrelated error due to TestDeconvolutionND

**Pull request merged**
