### PR TITLE
[backport] Pass raw arrays to the loss function in `MultiprocessParallelUpdater`

### PR DESCRIPTION
**Pull request by mitmul**
This is a backport PR of #2817

### CODE REVIEW

**Comment by gwtnb** [comment]
@mitmul Test fails in travis. Is it harmful?

**Comment by okuta** [comment]
jenkins, test this plase

**Comment by okuta** [comment]
jenkins, test this plase

**Comment by okuta** [comment]
jenkins, test this plase

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
