### PR TITLE
Fix recomputation of `L.BatchRenormalization` 

### LINKED ISSUE #7255: `L.BatchRenormalization` does not recompute forward correctly
Batch Renormalization uses values of running mean and running variance in forward, unlike Batch Normalization just updates statistics.

To fix the issue, `L.BatchRenormalization.forward` should use the running statistics here: https://github.com/chainer/chainer/pull/5557/files#diff-d4ceca1eba0c30875cd23de80d438b78R71

### PR DESCRIPTION
**Pull request by toslunar**
Fix #7255.

The PR adds a private flag for forward of `F.forget`, in order to avoid consuming additional memory unless `F.forget` requires it.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Although this is considered as a bug, it will not be backported to v6 as it changes the existing behavior of `F.batch_renormalization` when `F.forget` is used.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
