### PR TITLE
[RFC]Fix progress bar

### LINKED ISSUE #3969: Progress bar exceeds 100% in some situation
In some situation, the progress bar in `progress_bar` extension exceeds 100%. We can find such situation in the PTB example. Where the default total epoch number (39) is not divisible by 7, the number epochs consumed in one iteration.

```
%(master)[]./train_ptb.py --test
#vocab = 10000
     total [#####################################################] 107.69%
this epoch [..................................................]  0.00%
         6 iter, 42 epoch / 39 epochs
  0.068392 iters/sec. Estimated time to finish: -1 day, 23:59:53.733622.
```

Detail discussion is found in #1384.

### PR DESCRIPTION
**Pull request by ankokumoyashi**
Fixes #3969
Recalculate epoch_length not to exceed 100%
before:
<pre>
[gen@localhost chainer]$ python3 examples/ptb/train_ptb.py --test
#vocab = 10000
     total [#####################################################] 107.69%
this epoch [..................................................]  0.00%
         6 iter, 42 epoch / 39 epochs
   0.10037 iters/sec. Estimated time to finish: -1 day, 23:59:55.730007.
</pre>
after:
<pre>
[gen@localhost chainer]$ python3 examples/ptb/train_ptb.py --test
#vocab = 10000
     total [##################################################] 100.00%
this epoch [..................................................]  0.00%
         6 iter, 42 epoch / 39 epochs
  0.099782 iters/sec. Estimated time to finish: 0:00:00.
</pre>

### CODE REVIEW

**Comment by okuta** [comment]
Sorry, late reply.

How about using `min`? I think it is more simple to understand.

**Comment by okuta** [comment]
@ankokumoyashi Do you have time to fix this PR?

**Comment by ankokumoyashi** [comment]
Sorry for my late reply.

Thank you for pointing it out.

How about this? Is it alright?

**Comment by okuta** [comment]
Thanks You are correct. I will check this.

jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
