### PR TITLE
Simplify `F.mean_absolute_error` test

### PR DESCRIPTION
**Pull request by aksub99**
Simplified F.mean_absolute_error test using testing.FunctionTestCase.
Ref. #6071

### CODE REVIEW

**Comment by crcrpar** [comment]
It seems that test_backward and test_double_backward of `F.mean_absolute_error` on ChainerX fail.  
Do you have any environment where ChainerX is enabled?
If you don't have any environment that supports ChainerX, could you check this [installation instruction](https://docs.chainer.org/en/latest/chainerx/install/index.html) and install ChainerX?

**Comment by aksub99** [comment]
Thanks @crcrpar . I did have some trouble enabling ChainerX locally. I'll try following the installation instructions.

**Comment by aksub99** [comment]
@crcrpar , it seems as though the error caused is probably not due to test_mean_absolute_error.py . The same error arises on running test_mean_squared_error.py as in PR  #5822 . I guess that this must be an issue with the definition of both losses. (In mean_absolute_error.py and mean_squared_error.py)

**Comment by aksub99** [comment]
The errors arising are due to lack of sign attribute in chainerx modules as in #6158 . This PR aims at simplifying test_mean_absolute_error.py using testing.FunctionTestCase to address #6071 . Could a separate PR be opened to fix #6158 ?

**Comment by Crissman** [comment]
How did you go with the ChainerX installation?

**Comment by okuta** [comment]
imosci, test this please.

**Comment by crcrpar** [comment]
@Crissman I found he said he succeeded to install ChainerX in chainer slack general).

**Comment by aksub99** [comment]
@Crissman @crcrpar Yes! I did manage to get chainerx working fine locally.

**Comment by Crissman** [comment]
@aksub99 To fix the tests failing at the `.sign()` function, please implement a work around in `chainerx/_fallback_workarounds.py` as mentioned in https://github.com/chainer/chainer/issues/6071

**Comment by aksub99** [comment]
Sorry for the delay in addressing the problem. @Crissman Please review the changes.

**Comment by Crissman** [comment]
The last commit to convert ChainerX back to chx looks unrelated to this PR. Is there a connection I'm missing?

**Comment by aksub99** [comment]
I got the following travis error after making the commit to implement the workaround.
https://travis-ci.org/chainer/chainer/jobs/503082003
Then I realized that PR #6312 converted `chainerx` to `chx` in `_fallback_workarounds.py` and this change wasn't being reflected in my branch even after pulling the changes to my forked repository's branch. So, I had to modify the file to the updated version.

**Comment by aksub99** [comment]
@Crissman Could you please review and let me know if there could be any modifications? Thanks in advance!

**Comment by aksub99** [comment]
I've rebased to remove the `chainerx` to `chx` commit. @Crissman Please review and let me know if any changes are to be made.

**Comment by aksub99** [comment]
@Crissman I tried to fix the above issue but mistakenly performed the above merge commits. I tried to undo these changes but am unsuccessful in doing so. Please suggest what I could do to solve this problem.

**Comment by toslunar** [comment]
@aksub99 Could you try the following steps?

1. `git rebase -i master` on your branch `simplify_mean_absolute_error_test`
2. leave your commits `pick`ed, remove lines for other commits, and then close the text editor
3. confirm `git diff master..` looks good
4. `git push --force-with-lease`

**Comment by aksub99** [comment]
@toslunar I had actually tried doing this. After removing lines for all the other commits and pushing, there was no difference that I could observe in removal of these other commits. Also, when I run `git log` now, It shows a history of commits that doesn't contain my commits anymore.

**Comment by toslunar** [comment]
Try `git reset HEAD^2`.  It seems the merged branch (i.e. the second parent) of the commit you'd like to undo is the original.

**Comment by aksub99** [comment]
fatal: ambiguous argument 'HEAD^2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]' 
I get this when I ran `git reset HEAD^2`.

**Comment by toslunar** [comment]
In my environment `git reset HEAD^2` worked.  I overwrote the branch.  Could you confirm if the branch is ok?  @aksub99

**Comment by aksub99** [comment]
Thanks @toslunar . The branch seems OK now. The only problem is that the changes from PR #6312 are not updated here and causes a travis error.

**Comment by toslunar** [comment]
I'll retry a Travis build.

**Comment by toslunar** [comment]
I recovered (the relevant part of) the commit 3c40c6c36441ed962142d129c8731f6f8d054eec as fc56f1421a73cfbc2b1c1220cafb09a9666c9146.

**Comment by aksub99** [comment]
@Crissman Could you please review and suggest possible modifications?

**Comment by Crissman** [comment]
Thank you both for working through this.

Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins doesn't seem to be feeling well. Let's try that again.

Jenkins, test this please.

**Comment by aksub99** [comment]
Is this ok to merge @Crissman ?

**Comment by Crissman** [comment]
LGTM. Merging!

**Pull request merged**
