### PR TITLE
Simplify `F.concat` test

### PR DESCRIPTION
**Pull request by niboshi**
Applies the function test case https://github.com/chainer/chainer/pull/3499.

### CODE REVIEW

**Comment by okuta** [comment]
Please check test result.

**Comment by niboshi** [comment]
Ah, this PR depends on #3499.

**Comment by niboshi** [comment]
Rebased and removed float16 skip.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
