### PR TITLE
 Improve error message of `gradient_check.check_double_backward`

### PR DESCRIPTION
**Pull request by niboshi**
Depends on #6424

### CODE REVIEW

**Comment by hvy** [comment]
Sorry could you rebase this PR?

**Comment by hvy** [comment]
Could you rebase this PR?

**Comment by niboshi** [comment]
Rebased

**Comment by hvy** [comment]
It seems a bit verbose but LGTM.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
(Travis failure seems unrelated.)

**Comment by hvy** [comment]
Could you fix the style error https://jenkins.preferred.jp/job/chainer/job/chainer_pr/155/TEST=CHAINERX_misc,label=mn1-p100/console ?

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Travis failure seems unrelated. Waiting for Jenkins.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
