### PR TITLE
Use new RNN implementation

### PR DESCRIPTION
**Pull request by unnonouno**
I fixed NStepRNNs to use new APIs defined in https://github.com/cupy/cupy/pull/1659

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Can you take a look at the segmentation faults in e.g. `tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py`?

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
Sorry, i found a bug: https://github.com/cupy/cupy/pull/1862

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
It seems like the Travis configuration isn't up to date. Could you rebase/merge with the current master?

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
