### PR TITLE
New style flipud

### PR DESCRIPTION
**Pull request by hvy**
New style flipud to support double backprop.

### CODE REVIEW

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Rebase on top of master.

**Comment by takagi** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
Would you merge https://github.com/hvy/chainer/pull/2 to your repo?

**Comment by hvy** [comment]
@takagi san, thank you for the adjustments. I merged your PR.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
