### PR TITLE
Fix AMSGrad with intel64 backend

### PR DESCRIPTION
**Pull request by toslunar**
AMSGrad's state `vhat` should be updated.  The intention of `out=vhat` (https://github.com/chainer/chainer/pull/4032#discussion_r169032555) was unclear, which led to an error in #6388 (2f05180c8a02b5651ff5d9b51324d6400be7bd04).

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Oh I overlooked flake8 error.
Please fix it.
>/home/travis/build/chainer/chainer/chainer/function_node.py:247:80: E501 line too long (83 > 79 characters)

**Comment by toslunar** [comment]
> > /home/travis/build/chainer/chainer/chainer/function_node.py:247:80: E501 line too long (83 > 79 characters)

Fixed in #7663.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
