### PR TITLE
chx.repeat (wip)

### PR DESCRIPTION
**Pull request by durswd**
I implemented F.repeat with ChainerX

### CODE REVIEW

**Comment by hvy** [comment]
I'm wondering if we can't simply the implementation by simply chaining calls of
1. `chx.reshape` - Add new axes at the positions after given `axis`
2. `chx.broadcast_to` - Broadcast new axes from 1 to the number of repeats for that axis
3. `chx.reshape` - To the final shape

**Comment by hvy** [comment]
Sorry for step 1., you can use `chainerx::ExpandDims`.

**Comment by durswd** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
Is it closed because of this one https://github.com/chainer/chainer/pull/7223? I'd be good to leave a record on why it was closed.

**Comment by durswd** [comment]
too much commits

**Pull request closed without merging**
