### PR TITLE
Add `TweakLink`: abstraction for weight normalization methods

### PR DESCRIPTION
**Pull request by crcrpar**
This LinkHook aims at easier, simpler, and unified implementation of SpectralNormalization (#5742) and WeightStandardization (#6678) and another usage of LinkHook.

cc: @toslunar @hitsgub 

Related to #6689.

### CODE REVIEW

**Comment by hvy** [comment]
@toslunar could you take a look?

**Comment by crcrpar** [comment]
just dropping a reference #6955

**Comment by toslunar** [comment]
It's ready for reviews.  #6678 was merged.

**Comment by crcrpar** [comment]
Just fixed conflicts.

**Pull request closed without merging**
