### PR TITLE
refactor `allreduce_grad()` and functions related with it

### PR DESCRIPTION
**Pull request by shu65**
This PR is one of PRs to solve https://github.com/chainer/chainer/issues/6670#issuecomment-505402604

### CODE REVIEW

**Comment by shu65** [comment]
Jenkins, test this please.

**Comment by shu65** [comment]
Jenkins, test this please.

**Comment by kuenishi** [comment]
Jenkins, test this please.

**Comment by kuenishi** [comment]
Code looks good to me. Waiting for CIs.

**Comment by kuenishi** [comment]
Test failure is not related to ChainerMN part

**Pull request merged**
