### PR TITLE
Improve browsability of API reference

### PR DESCRIPTION
**Pull request by niboshi**
This PR adopts NumPy-like documentation style

### CODE REVIEW

**Comment by delta2323** [comment]
LGTM. Although I like it, I would like the opinion of other members as I greatly changes the style of the document,

**Comment by mitmul** [comment]
LGTM. I feel it improves the browsability of documentation.

**Comment by delta2323** [comment]
@mitmul Thank you for your comment.

**Comment by beam2d** [comment]
LGTM. I have one comment; I feel the font size of the link texts in the tables is a bit small and difficult to look through. Can we enlarge the link texts? It might be rather the problem of CSS design; just changing the style of the links to symbols might be ok.

**Comment by niboshi** [comment]
Thank you for comments.
I fixed the text styles and doc generation of class member methods/attributes.
I did a bit tricky thing to render special methods (e.g. `__call__` and `__eq__`), 
as autosummary does not offer such flexibility.

**Comment by delta2323** [comment]
@beam2d Could you check the PR again?

**Comment by beam2d** [comment]
Will check soon

**Comment by beam2d** [comment]
Sorry for being late. Looks great!

**Comment by delta2323** [comment]
Should we backport this PR to v2?

**Pull request merged**
