### PR TITLE
Stabilize unit tests for F.Ceil and F.Floor

### PR DESCRIPTION
**Pull request by delta2323**
This PR changes the distribution from which inputs are sampled in TestCeil so that tests for the function are likely to pass more. Specifically, we sample less likely from discontinuous points (i.e. integer points).

### CODE REVIEW

**Comment by niboshi** [comment]
How about sampling repeatedly until an input with no value near integer point is obtained?
Tests must pass 100% of time.

**Comment by niboshi** [comment]
Also, please consider removing `retry`.

**Comment by niboshi** [comment]
`test_floor` has the same problem. Can you fix it too?

**Comment by delta2323** [comment]
I updated to the tests of `F.Ceil` and applied the same change to `F.Floor`. Also I change the PR title accordingly.

**Comment by niboshi** [comment]
Thanks!

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
