### PR TITLE
[backport] Edits Function Node docs.

### PR DESCRIPTION
**Pull request by Crissman**
Backport of #7622

### CODE REVIEW

**Comment by Crissman** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
After #7663 got merged, please add backport commit to this PR.

**Comment by kmaehashi** [comment]
@Crissman #7663 has been merged.

**Comment by Crissman** [comment]
Merged #7663. Jenkins, test this please.

**Pull request merged**
