### PR TITLE
 doc: Sort out navigation menu

### PR DESCRIPTION
**Pull request by niboshi**
Counterpart of CuPy PR: https://github.com/cupy/cupy/pull/444

**old**
old

**new**
new

### CODE REVIEW

**Comment by delta2323** [comment]
Is it `st:ready-for-review`?

**Comment by rezoo** [comment]
@niboshi LGTM. I would like to merge this one if you put `st:ready-for-review` label.

**Comment by niboshi** [comment]
@rezoo 
Status labels are supposed to be put/removed by reviewers, not authors.
(We confirmed later in an internal meeting. Sorry we didn't share that)

**Comment by rezoo** [comment]
OK. LGTM.

**Pull request merged**
