### PR TITLE
Add Chainer logo to README.md

### PR DESCRIPTION
**Pull request by niboshi**
[README.md](https://github.com/niboshi/chainer/blob/logo-readme/README.md)

### CODE REVIEW

**Comment by gwtnb** [comment]
Could you write in markdown instead of HTML?

**Comment by niboshi** [comment]
Hmm, it looks like GitHub-flavor Markdown does not support image resize nor centering.

**Comment by niboshi** [comment]
Removed the margin. (aligned with CuPy)

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
