### PR TITLE
Wrap platform specific operations and reduce macro usage

### LINKED ISSUE #6040: ChainerX platform specific logic should be cleaned up
Clean up platform specific branches under a new namespace such as `chainerx::crossplatform` and wrap platform specific functions such as `setenv`, `unsetenv`, `isnan`, `isinf`, `dlopen`, `dlclose`.

### PR DESCRIPTION
**Pull request by hvy**
Fixes #6040 .

### CODE REVIEW

**Comment by hvy** [comment]
Not entirely sure how we should test these functions since env related functions have side effects for instance. It might be fine skipping the tests for the current functions are they're covered by others.

**Comment by hvy** [comment]
CI should be updated to include Windows builds prior to merging this PR.

**Comment by niboshi** [comment]
We will not not set up CI for ChainerX on Windows at the moment.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
