### PR TITLE
Simplify `F.log1p` test

### PR DESCRIPTION
**Pull request by hikjik**
Simplifies test_logarithm_1p using testing.FunctionTestCase
Refer to [#6071](https://github.com/chainer/chainer/issues/6071)

### CODE REVIEW

**Comment by Crissman** [comment]
LGTM. Jenkins, test this please.

**Comment by Crissman** [comment]
pfnCI, please

**Comment by Crissman** [comment]
pfnCI, please

**Comment by Crissman** [comment]
pfnCI, please

**Comment by imos** [comment]
pfnCI, please

**Pull request merged**
