### PR TITLE
[backport] Avoid testing `F.cast` from negative floating-point to unsigned

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #7920

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
v6 had the old style testing for the function.
Should we refactor it to the new one in this backport too?
Thanks!

**Comment by niboshi** [comment]
I think the current code is OK.

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
