### PR TITLE
[backport] test: Stabilize upsampling_2d by adjusting tolerance

### PR DESCRIPTION
**Pull request by mitmul**
This backports test: Stabilize upsampling_2d by adjusting tolerance #3377

### CODE REVIEW

**Comment by niboshi** [comment]
Please rebase.

**Comment by niboshi** [comment]
TODO: Backport #3410 after this PR is merged.

**Comment by mitmul** [comment]
@niboshi Rebased.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
