### PR TITLE
Improve coding style

### PR DESCRIPTION
**Pull request by toslunar**
This PR fixes H238, H301, and H306 of OpenStack Style Guidelines.

### CODE REVIEW

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Resolved the conflict (with #5840).

Jenkins, test this please.

**Comment by toslunar** [comment]
If ChainerX are sure to drop support of Python 2, we don't have to fix `H238`.  Nevertheless I'd rather not mix the styles.
```
class ndarray(object):
```
in `chainerx/__init__.py`.

**Comment by hvy** [comment]
@mitmul can you merge if it looks okay to you?

**Comment by toslunar** [comment]
Then I'll fix H238 for new ChainerX examples.

**Comment by hvy** [comment]
Ah, there are more of them. Thanks.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
LGTM

**Pull request merged**
