### PR TITLE
Fix docs format in upgrade guide

### PR DESCRIPTION
**Pull request by hvy**
Added missing whitespace in docs.

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
