### PR TITLE
add group option value of Convolution2D to Caffe exporter

### PR DESCRIPTION
**Pull request by ohnabe**
Add group option value of Convolution2D to caffe exporter

### CODE REVIEW

**Comment by hvy** [comment]
Thanks a lot for this PR. Would it be possible to include tests for this as well? I'd assume in `tests/chainer_tests/exporters_tests/test_caffe.py`.

**Comment by ohnabe** [comment]
OK, I'll add.

**Comment by hvy** [comment]
Thanks for the quick fix. Please let me change the title of this PR to include "caffe" since that's what it's relevant to.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
The jenkins, failure seem unrelated.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
