### PR TITLE
Fix reinforcement_learning example to work with default dtype

### PR DESCRIPTION
**Pull request by takagi**
Rel #6168.

This PR fixes the reinforcement learning example to work with the default dtype feature.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
`CHAINER_DTYPE=float16 python ddpg_pendulum.py` overflows.  I'm investigating the issue.

**Comment by toslunar** [comment]
I'm running the example with larger `eps` for `Adam`.

**Comment by takagi** [comment]
As @toslunar says, I'll change the Adam's `eps` larger for numerical stability in FP16 mode.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
