### PR TITLE
doc: Add experimental warning in docstring

### PR DESCRIPTION
**Pull request by niboshi**
Currently, users cannot tell if a feature is experimental until they use it.

### CODE REVIEW

**Comment by niboshi** [comment]
Question:
`L.LayerNormalization` emits experimental warning, but `F.layer_normalization` does not. Shouldn't it emit, too?

**Comment by unnonouno** [comment]
Is it possible to check if experimental features have this warning?

**Comment by niboshi** [comment]
I think it's difficult.

To check whether experimental warning is emitted, we need to actually run the code (thus using unit test).
But there's no way to automatically check docstrings from unittest.

**Comment by unnonouno** [comment]
OK, LGTM

**Pull request merged**
