### PR TITLE
Fix create_mnbn_model() bug

### PR DESCRIPTION
**Pull request by shu65**
This PR solves https://github.com/chainer/chainer/issues/7717

ToDo:

- [x] fix a bug
- [x] add unittests

### CODE REVIEW

**Comment by ktns** [comment]
Due to #6053, it might not be sufficient to reproduce `chainer.Sequential._layers` because `chainer.Sequential._children` is dependent in what order links and functions are added. Wouldn't it better to reproduce `_children` also?

**Comment by ktns** [comment]
I've noticed that `chainer.Sequential.copy()` does not reproduce `_children` either. Maybe this  PR should be left as is and with a PR for #6053 should be compatible with this implementation.

**Comment by shu65** [comment]
Thank you for the comments. 
Does it mean that we should use this version https://github.com/chainer/chainer/pull/7718/commits/262357672321d9dbe5895c9420240c18adbfe02b instead of https://github.com/chainer/chainer/pull/7718/commits/3d5d943bd608e773828de75eff0303428c0ee5c8 ?

**Comment by ktns** [comment]
I think either will do. But I prefer 2623576 because it is similar to `chainer.Sequential.copy()`.

**Comment by kuenishi** [comment]
pfnci, test this please.

**Comment by kuenishi** [comment]
Test failure in Jenskin does not seem related. The code looks good to me. Testing multinode now...

**Comment by shu65** [comment]
pfnci, test this please.

**Pull request merged**
