### PR TITLE
Mixed dtype: dot

### PR DESCRIPTION
**Pull request by hvy**
Partially fixed https://github.com/chainer/chainer/issues/6436

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Hm, I don't know why Jenkins is failing.

**Comment by hvy** [comment]
Jenkins, test this please。

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Running jenkins to verify failure/fix that I cannot reproduce locally. Could be due to different gcc/nvcc version.

**Comment by hvy** [comment]
The above failure seems to be fixed (verified on Jenkins).

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
