### PR TITLE
Simplify RNN test that check if cuDNN is called

### PR DESCRIPTION
**Pull request by unnonouno**
I removed redundant test case class which check if cuDNN is called and simplify the test.

merge #4046 first
related to #4045

### CODE REVIEW

**Comment by niboshi** [comment]
#4046 has been merged.

**Comment by unnonouno** [comment]
I removed TestNStepRNNCudnnCall and merge it to TestNStepRNN. If this fix is OK, i'll apply the same fix to other tests.

**Comment by hvy** [comment]
Thank you for this PR.  I think we can go with this approach to get rid of some repetitions.

Just two considerations
1. I assume that TestCase members `batch`, `length`, etc. used to differ between cudnn and non-cudnn classes but that it's fine.
2. We could maybe reuse the [backend injection decorator](https://github.com/chainer/chainer/pull/3862) to test all cudnn configurations, but only if it is worth the effort.

**Comment by unnonouno** [comment]
Yes, IMO we need to refactor these test cases more and more. This PR only aims to merge two redundant test cases. I'll send another PR for these two points you suggests.

**Comment by hvy** [comment]
Okay, thank you very much. Then I think we should go with this approach for now!

**Comment by hvy** [comment]
For reference, https://github.com/chainer/chainer/pull/3499 also addresses the problem of repeated boilerplate code in our unit tests.

**Comment by unnonouno** [comment]
I fixed all RNN, GRU, and LSTM tests. Please review it.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
