### PR TITLE
ChainerX

### PR DESCRIPTION
**Pull request by beam2d**
ChainerX is a new ndarray+autograd implementation for Chainer. It aims at reducing Python overhead for host-heavy workloads, providing Python-free basis for application coding, and making device support pluggable.

This PR is to move the development to the main repository. It includes:

- C++ implementation of the new ndarray and related routines (`chainerx_cc`),
- Python binding of ChainerX (`chainerx_cc/python` and `chainerx`),
- Modifications on Chainer to support the new ndarray, and
- Documentation of ChainerX

We are planning to include this feature in the next beta release.

This PR is very big so that it's impossible to run review here, but we still use PR instead of silently merging it for visibility of changes included in the release. I'd like to merge it once CI is made ready and we confirm that this PR passes that.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by hvy** [comment]
LGTM

**Comment by mingxiaoh** [comment]
this PR will cause about 20% performance regression for DCGAN with small batchsize based on CPU-iDeep path, not check GPU yet, any comments here? @beam2d @niboshi

**Pull request merged**
