### PR TITLE
[backport] Use `LinkTestCase` for `L.GroupNormalization`

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #8343

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
There was a conflict but used #8343's version entirely.

**Comment by toslunar** [comment]
> There was a conflict but used #8343's version entirely. ([b64126b](https://github.com/chainer/chainer/commit/b64126bdb5799d8fc45f76cc102efb3d34119242))

:+1: because the conflict is just https://github.com/chainer/chainer/pull/8058/files#diff-8bd55391c2f2170bdb73f6c652d727c9.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
