### PR TITLE
Add path option for load_npz method

### PR DESCRIPTION
**Pull request by sergeant-wizard**
I came across a situation where I want to load the serialized parameters under a _certain path_.
If my understanding is correct, the only way to achieve the behavior is to write something like the following:

```py
serializers.NpzDeserializer(np.load('saved_model'))['path_of_interest'].load(obj)
```

which would produce quite a lot of the same code written in the `load_npz` method.
By applying the change I propose here, the user can obtain the same result by:

```py
serializers.load_npz('saved_model', obj, path='path_of_interest')
```

which I think is more straightforward.

### CODE REVIEW

**Comment by delta2323** [comment]
Could you add tests for verifying this feature?

**Comment by sergeant-wizard** [comment]
Sorry about the delay.
I think these tests should cover the feature that is added.
I found out that hdf5 currently doesn't support the path option so I omitted it for now.

**Comment by delta2323** [comment]
LGTM, I am running GPU tests.

**Comment by sergeant-wizard** [comment]
Oh I forgot to add docstring for the option. I am adding it now

**Comment by delta2323** [comment]
> Oh I forgot to add docstring for the option. I am adding it now

Good catch. Thank you.

**Comment by delta2323** [comment]
Test passed.

**Pull request merged**
