### PR TITLE
Fix handling of ndarray offsets

### PR DESCRIPTION
**Pull request by hvy**
When converting a ChainerX array into a CuPy array, the base pointer was incremented by the offset. This PR changes the behavior such that the base pointer is kept and the offset is specified via the "offset" parameter.

### CODE REVIEW

**Comment by okapies** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Fixed an error in `Stack` and `StackGrad` that became present due to this change (they've existed since before).

**Comment by okapies** [comment]
LGTM. I think they can be solved in the same PR because they are related to the handling of `offset`. Just rename the title is enough I think.

**Comment by hvy** [comment]
Okay, I'll do so.

**Comment by hvy** [comment]
Fixed the name to be a bit more "general".

**Comment by hvy** [comment]
Should be backported but after https://github.com/chainer/chainer/pull/7046.

**Comment by asi1024** [comment]
LGTM.

**Comment by asi1024** [comment]
I will create a backport PR after #7054 is merged.

**Pull request merged**
