### PR TITLE
Support double-backprop in `F.contrastive`

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR implements new style `contrastive` function

~~Merge this after #3735.~~ (done)
~~WIP: needs tolerance adjustments.~~ (done)

### CODE REVIEW

**Comment by takagi** [comment]
Would you resolve the conflicts?

**Comment by kmaehashi** [comment]
Resolved conflict.

**Comment by takagi** [comment]
LGTM, will merge after #3735!

**Comment by kmaehashi** [comment]
`F.repeat` is now merged. Resolved conflict.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by kmaehashi** [comment]
Fixed error in NumPy 1.9.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
