### PR TITLE
Fix `optimizer.use_fp32_update` on ChainerX model

### PR DESCRIPTION
**Pull request by y1r**
Current`optimizer.use_fp32_update` (for fp16 training) doesn't support ChainerX as following:
```
Traceback (most recent call last):
  File "training.py", line 323, in <module>
    main(parser.parse_args())
  File "training.py", line 316, in main
    trainer.run()
  File "SOME_DIRECTORY/chainer/chainer/training/trainer.py", line 376, in run
    six.reraise(*exc_info)
  File "~/.pyenv/versions/HOGEHOGE/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "SOME_DIRECTORY/chainer/chainer/training/trainer.py", line 343, in run
    update()
  File "SOME_DIRECTORY/chainer/chainer/training/updaters/standard_updater.py", line 240, in update
    self.update_core()
  File "SOME_DIRECTORY/chainer/chainer/training/updaters/standard_updater.py", line 253, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "SOME_DIRECTORY/chainer/chainermn/optimizers.py", line 33, in update
    self.actual_optimizer.update(None, *args, **kwds)
  File "SOME_DIRECTORY/chainer/chainer/optimizer.py", line 879, in update
    param.update()
  File "SOME_DIRECTORY/chainer/chainer/variable.py", line 1819, in update
    self.update_rule.update(self)
  File "SOME_DIRECTORY/chainer/chainer/optimizer.py", line 247, in update
    self.__update(param)
  File "SOME_DIRECTORY/chainer/chainer/optimizer.py", line 298, in __update
    param.array = fp32_param.array.astype(param.dtype)
  File "SOME_DIRECTORY/chainer/chainer/variable.py", line 884, in array
    'Cannot update the array of a Variable if either the '
ValueError: Cannot update the array of a Variable if either the existing or the new array requires backprop.
```

I think current ChainerX ndarray doesn't allow us to change its internal pointer thus I copy fp32 param to the corresponding array.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for the PR.
In order to understand the bug, could you provide a reproducing code, or write a unit test?  (test is needed anyway)

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by y1r** [comment]
@takagi What can I do to merge this PR? Should I merge current HEAD into this?

**Comment by takagi** [comment]
Thanks for your response. I'd like to merge this PR to the master but the required tests fail because of some reason that is not related to the change on this PR. Let me check it out and you don't need to make an action.

**Comment by takagi** [comment]
Ah, yes, would you merge the current HEAD if possible? (It may not make it work though)

**Comment by y1r** [comment]
@takagi I've updated this branch, so please check it.

**Comment by takagi** [comment]
Thanks!

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
