### PR TITLE
Suppress warnings in the document

### PR DESCRIPTION
**Pull request by unnonouno**
I fixed docstrings to suppress warnings in the document.

### CODE REVIEW

**Comment by niboshi** [comment]
Why did you exclude `FunctionHook`?

**Comment by unnonouno** [comment]
Sphinx raises a warning here. Maybe  because it is an alias.

**Comment by niboshi** [comment]
Hmm, I don't see any warning without excluding.
What kind of warning? What's the Python/sphinx version are you using?

**Comment by unnonouno** [comment]
I got this warning. I'm using sphinx 1.5.3 and python2
```
/home/unno/git/chainer/docs/source/reference/generated/chainer.function.FunctionHook.rst:: WARNING: document isn't included in any toctree
```

**Comment by niboshi** [comment]
Hmm, I think you didn't run `make clean`?
In my environment, there's `generated/chainer.FunctionHook.rst` but not `generated/chainer.function.FunctionHook.rst`.

Could you run `make clean`?

**Comment by unnonouno** [comment]
Oh, thank you. It works!

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
