### PR TITLE
[backport] Use rsqrt in batch_normalization

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #4612

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
