### PR TITLE
Document backend and device objects

### PR DESCRIPTION
**Pull request by niboshi**
Depends on #7099

Documents some newly introduced device-related objects.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Rebased to master.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Comment by kmaehashi** [comment]
This PR has been backported to v6 in #7152.

**Pull request merged**
