### PR TITLE
Rename `CHAINERX_REGISTER_OP_{NATIVE,CUDA}` to `CHAINERX_{NATIVE,CUDA}_REGISTER_OP`

### PR DESCRIPTION
**Pull request by hvy**
Fixes https://github.com/chainer/chainer/issues/6864

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please fix errors.

**Comment by hvy** [comment]
Sorry I forgot to push the changes. PTAL.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
Could you fix compilation error? https://ci.preferred.jp/chainer.py37/2338/

**Comment by hvy** [comment]
Rebased again. PTAL.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
