### PR TITLE
[backport] Use `filename` in PlotReport example

### PR DESCRIPTION
**Pull request by crcrpar**
Backport of #6880

### CODE REVIEW

**Comment by Crissman** [comment]
Strange. Are you using chainer/backport to create this? Usually, it would automatically run Jenkins when the PR is created.

Jenkins, test this please.

**Comment by crcrpar** [comment]
> Strange. Are you using chainer/backport to create this? Usually, it would automatically run Jenkins when the PR is created.

Yes, I'm using that repository. Ah, it might be due to the configuration of my GitHub token.

Can I trigger Jenkins even if I'm just a contributor?

**Comment by toslunar** [comment]
The labels were missing.

> > Strange. Are you using chainer/backport to create this? Usually, it would automatically run Jenkins when the PR is created.
> 
> Yes, I'm using that repository. Ah, it might be due to the configuration of my GitHub token.

I think so.

**Comment by Crissman** [comment]
Jenkins issue looks unrelated. Merging!

**Pull request merged**
