### PR TITLE
[backport] test: Stabilize roll_axis test by adjusting tolerance

### PR DESCRIPTION
**Pull request by mitmul**
This PR backports test: Stabilize roll_axis test by adjusting tolerance #3375

### CODE REVIEW

**Comment by niboshi** [comment]
Please rebase.

**Comment by mitmul** [comment]
@niboshi Rebased.

**Comment by niboshi** [comment]
Could you resolve conflict again?

**Comment by niboshi** [comment]
jenkins test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
