### PR TITLE
New style forget

### PR DESCRIPTION
**Pull request by hvy**
New style forget to support double backprop.

~It is quite inefficient at the moment during backprop since backward is called once to set the gradients of the variables invovled in the forgotten process, and then once again to get the backpropable gradients.~

### CODE REVIEW

**Comment by hvy** [comment]
Note, will continue working on this PR.

**Comment by hvy** [comment]
Rebased on top of current master.

**Comment by hvy** [comment]
Removed WIP and ready for review.

**Comment by mitmul** [comment]
LGTM

**Comment by mitmul** [comment]
Jenkins-san, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by mitmul** [comment]
LGTM

**Pull request merged**
