### PR TITLE
Simplify MultiprocessIterator

### PR DESCRIPTION
**Pull request by okuta**
This PR simplify MultiprocessIterator by using `multiprocessing.pool.Pool`.

### CODE REVIEW

**Comment by niboshi** [comment]
@okuta This conflicts with #3076. Can you check?

**Comment by okuta** [comment]
This PR fixes #2909 . But we use #3076 .

**Comment by grafi-tt** [comment]
Sorry, it seems I was too late to write my comments.

If I understand correctly, this PR just replaces of hand-written worker management by pool. But my PR is almost rewrites original implementation. So I don't think merging them makes sense. Notable differences are:

* Instated of polling-based queue management, my implementation uses conditional variables.
* In my implementation the prefetch thread runs independently from `__next__` call in the main thread. It may complicate reset implementation, but I think I managed to achieve a simple mechanism using a counter.

I honestly like my own implementation, but this PR can be reasonable conservative choice. If you find any flaws in my codes, I'm happy to fix those.

**Comment by okuta** [comment]
Thank you for your comment.

I am reviewing your PR. Your PR has good features.

**Pull request closed without merging**
