### PR TITLE
Improve docs of square, maximum and squared_difference

### PR DESCRIPTION
**Pull request by aksub99**
This is PR for improving docs of functions/links. Related issue: #2182

Modified functions/links:
- functions/math/square.py
- functions/math/maximum.py
- functions/math/squared_difference.py

### CODE REVIEW

**Comment by Crissman** [comment]
@aksub99 Take a look at the Travis error. There is an issue with the formatting for the docs. I usually do a `python setup.py build install > /dev/null; cd docs; make clean; SPHINXOPTS= make html` on my local machine to catch doc errors.

**Comment by aksub99** [comment]
Thanks @Crissman , I'll try doing the same!

**Comment by aksub99** [comment]
@Crissman After I run `make clean; SPHINXOPTS= make html`, the modifications I've made aren't being reflected in `docs/build/html/reference/functions.html`. Why could this be so?

**Comment by Crissman** [comment]
Did you do the first step of the test command listed above? `python setup.py build install > /dev/null;` This is necessary to update the functions that are not directly below the `docs/source` directory.

**Comment by aksub99** [comment]
Yes. I did run that too but wasn't able to observe the modifications in the html files after building.
I'm facing this issue only when the modifications are in the docstrings (In the python files).

**Comment by aksub99** [comment]
I assumed that the modifications I make in docstrings of `chainer/functions/math/square.py` will be reflected in `chainer/docs/build/html/reference/generated/chainer.functions.square.html`. Am I right in this?

**Comment by aksub99** [comment]
Managed to find the solution for the problem in this link.
https://docs.chainer.org/en/stable/contribution.html
Every time I modified the docstrings, I had to run `pip install -e .` before building the documentation. I was then able to view the modifications in the html files.

**Comment by aksub99** [comment]
@Crissman Please review :)

**Comment by aksub99** [comment]
@Crissman Could you please review?

**Comment by Crissman** [comment]
Verified! Jenkins, test this please.

**Comment by aksub99** [comment]
Is this ready to merge @Crissman ?

**Comment by Crissman** [comment]
Jenkins errors look unrelated. Merging!

**Pull request merged**
