### PR TITLE
Remove C++ routines tests

### PR DESCRIPTION
**Pull request by niboshi**
Follow-up of #6401 

There's no Python test for statistics routines. I only left a TODO comment.

### CODE REVIEW

**Comment by kshitij12345** [comment]
#6640 Adds tests for Mean and Var via Python Bindings.

**Comment by niboshi** [comment]
@kshitij12345
Oh, thank you so much!

**Comment by asi1024** [comment]
Could you resolve conflicts?

**Comment by niboshi** [comment]
Rebased.

**Comment by asi1024** [comment]
Could you resolve a conflict again?

**Comment by niboshi** [comment]
Rebased.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Rebased

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
