### PR TITLE
[backport] Allow `snapshot_object` have `condition` and `writer` option

### PR DESCRIPTION
**Pull request by kuenishi**
Manual backport of #6762 .

### CODE REVIEW

**Comment by niboshi** [comment]
The diff itself looks good to me.

@toslunar Do you think we should backport this feature?
I think this PR is a `feature` addition, not `enhancement`.

**Comment by toslunar** [comment]
While it's not usual to backport this, let me wait for the decision whether #6856 is backported to v6.

**Comment by niboshi** [comment]
@toslunar We agreed to backport #6856, so let's merge this.

Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Comment by kuenishi** [comment]
Thanks!

**Pull request merged**
