### PR TITLE
Make build_computational_graph accept single output

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
I'd like to hear your opinion whether to allow it or not.

cf.
- `chainer.grad` is strict.
- `check_backward` is not strict.

**Comment by okuta** [comment]
Please add test.

**Comment by toslunar** [comment]
Added.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
