### PR TITLE
Add get_variable_or_none to improve backward performance

### PR DESCRIPTION
**Pull request by okuta**
`get_variable` create `Variable` when `_variable` reference is dead.
But, some functions do not need temporary `Variable` object.

### CODE REVIEW

**Comment by beam2d** [comment]
I feel the name `get_raw_variable` is confusing a bit. How about an alternative name `get_variable_if_exist` or `get_variable_or_none`?

**Comment by okuta** [comment]
thanks, I will change

**Comment by okuta** [comment]
I fixed.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
