### PR TITLE
[backport] Update `F.roi_average_align_2d` doc to refer wrapper function

### PR DESCRIPTION
**Pull request by toslunar**
Backport of #5609

### CODE REVIEW

**Comment by toslunar** [comment]
[automatic post] Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by knorth55** [comment]
I thinks #5285 (add `roi_average_pooling_2d`) is not backported.

**Comment by toslunar** [comment]
@knorth55 Thanks for pointing it out.
I'd like to remove the reference to the class `functions.ROIPooling2D` anyway.

**Comment by kmaehashi** [comment]
I tweaked the PR title to fool the backport checker bot.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
