### PR TITLE
Make vision models copyable

### PR DESCRIPTION
**Pull request by gwtnb**
When one copies a vision model, `self.functions` is not correctly copied. This PR fixes the problem by making `functions` a property.

### CODE REVIEW

**Comment by delta2323** [comment]
Could you write unit tests that verifies that the problem is fixed?

**Comment by t-abe** [comment]
I noticed `BuildingBlock` in `resnet.py` has same problem.

**Comment by delta2323** [comment]
Jenkins failed due to the problem cupy/cupy#122. As it is solved, I am re-running GPU tests again. I will merge it after it.

**Comment by delta2323** [comment]
LGTM

**Pull request merged**
