### PR TITLE
[backport] Make ImportWarning just a warning in tests

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #8291

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Backport wasn't clean, please verify 🙂

**Comment by toslunar** [comment]
Because #6653 has not been backported to v6, this change to v6 has a different meaning: show `ImportWarning` which is ignored by default.  I am sorry that I was not aware of it.

**Comment by emcastillo** [comment]
@toslunar I guess it is safer to close this one then!😄

**Comment by toslunar** [comment]
I agree.

**Pull request closed without merging**
