### PR TITLE
Make `BatchNorm` states public

### PR DESCRIPTION
**Pull request by hvy**
If a user wants to call a device op without going through the routines, the concrete state classes for each backend must be public. This PR addresses this issue for BN.

_See also https://github.com/chainer/chainer/pull/6800#issuecomment-482001492_

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please fix cpplint error:
```
/home/travis/build/chainer/chainer/chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc:15:  "chainerx/cuda/cuda_device.h" already included at /home/travis/build/chainer/chainer/chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc:1  [build/include] [4]
Done processing /home/travis/build/chainer/chainer/chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
```

**Comment by hvy** [comment]
Thanks, fixed. PTAL.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Please resolve the conflict.

**Comment by hvy** [comment]
Resolved the conflicts. PTAL.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Comment by hvy** [comment]
Removing `to-be-backported` as we decided not to backport non-critical PRs.

**Pull request merged**
