### PR TITLE
Make Variable unhashable

### LINKED ISSUE #2670: Variable defines __hash__ but does not define __eq__
`Variable` defines `__hash__` but doesn't define `__eq__`:
```
class Variable(object):
    # ...

    def __eq__(self, other):
        raise NotImplementedError()

    # ...

    def __hash__(self):
        return super(Variable, self).__hash__()
```

But, the python documentation (https://docs.python.org/3.1/reference/datamodel.html#object.__hash__) says:
> If a class does not define an __eq__() method it should not define a __hash__() operation either;

Is there a reason `Variable` is designed like this?

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #2670 

Reopening https://github.com/chainer/chainer/pull/2727

### CODE REVIEW

**Comment by niboshi** [comment]
This PR will be affected by #2970. So please wait until it is merged.

**Comment by delta2323** [comment]
OK. Thank you for notifying it.

**Comment by niboshi** [comment]
Rebased to master.

Now we don't have to touch `chainer/computational_graph.py`, because `VariableNode` and `FunctionNode` are now used as graph nodes and they are both hashable.

**Comment by delta2323** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
(Jenkins has failed, but it's not a fault of this PR.)

**Comment by delta2323** [comment]
I ran the GPU test again.

**Comment by delta2323** [comment]
LGTM

**Pull request merged**
