### PR TITLE
Fix incorrect use of single backslashes in docstrings

### PR DESCRIPTION
**Pull request by niboshi**
`tests/chainer_tests/test_init_docstring.py` fails due to these backslashes in Python 3.

### CODE REVIEW

**Comment by kmaehashi** [comment]
What failure do you see in Python 3?
I can't reproduce it by running `tests/chainer_tests/test_init_docstring.py`.

**Comment by niboshi** [comment]
I got an error like this:
```
tests/chainer_tests/test_init_docstring.py:47: in test_init_docstring_empty
    mod = loader.find_module(modname).load_module(modname)
<frozen importlib._bootstrap_external>:399: in _check_name_wrapper
    ???
<frozen importlib._bootstrap_external>:823: in load_module
    ???
<frozen importlib._bootstrap_external>:682: in load_module
    ???
<frozen importlib._bootstrap>:265: in _load_module_shim
    ???
<frozen importlib._bootstrap>:684: in _load
    ???
<frozen importlib._bootstrap>:665: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:674: in exec_module
    ???
<frozen importlib._bootstrap_external>:781: in get_code
    ???
<frozen importlib._bootstrap_external>:741: in source_to_code
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
E     File "/data/work/w/repos/chainer/chainer/function_node.py", line 468
E       """
E        ^
E   SyntaxError: invalid escape sequence \
```

```
$ python --version
Python 3.6.3 :: Anaconda, Inc.
```

**Comment by niboshi** [comment]
Rebased and done additional fixes.

**Comment by kmaehashi** [comment]
@niboshi Thank you.
I still couldn't reproduce this, even with `python3` from Anaconda.

https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior says

> A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError, that will not be for several Python releases. (Contributed by Emanuel Barry in bpo-27364.)

So I think it is OK anyway to merge this.

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
