### PR TITLE
Fix initialization of random vectors in the test for RNNs

### PR DESCRIPTION
**Pull request by unnonouno**
I simplified initialization of random vectors in the NStepRNN's test.
merge #4047 first
related to #4045

### CODE REVIEW

**Comment by hvy** [comment]
#4047 has been merged. Is this PR still blocked?

**Comment by unnonouno** [comment]
No, i rebased it. Please review it. Currently it only fixed rnn test. If this fix is ok, i'll apply the same change to other tests for gru and lstm.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
