### PR TITLE
Fix the index page of datasets in documentation

### PR DESCRIPTION
**Pull request by mitmul**
Fix documentation

### CODE REVIEW

**Comment by kmaehashi** [comment]
LGTM, but the commit history seems strange? Could you try rebasing it?

**Comment by mitmul** [comment]
@kmaehashi Oops, I rebased it. Thanks

**Comment by mitmul** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
