### PR TITLE
[backport] Support device specifiers in MNIST model parallel example

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #7225

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
@niboshi Should we backport another PR first? CI seems to fail.

**Comment by niboshi** [comment]
@asi1024 Which is it?

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Could you check the CI failure?
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1852/TEST=chainer-example,label=mn1-p100/console

**Pull request closed without merging**
