### PR TITLE
Add `CHAINER_TEST_PAIRWISE_PARAMETERIZATION` and enable it only in Travis CI

### PR DESCRIPTION
**Pull request by niboshi**
See #8210

Adding `CHAINER_TEST_PAIRWISE_PARAMETERIZATION` environment variable and only set it to `always` in Travis CI.

### CODE REVIEW

**Comment by niboshi** [comment]
>- Could you fix the TODO comment on `_product_dict_orig` in `chainer/testing/parameterized.py`?  ("is patched by tests/conftest.py")

Fixed in ef3c7e271097c8cee0c7242d497b0795851a38d7.

>- I'd like to hear ChainerMN team's comment on the pairwise testing.

I don't think we should enable pairwise testing in `chainermn_tests`.
It only takes 1 minute in Travis CI.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins error might be related

**Comment by toslunar** [comment]
> > * I'd like to hear ChainerMN team's comment on the pairwise testing.
> 
> I don't think we should enable pairwise testing in `chainermn_tests`.
> It only takes 1 minute in Travis CI.

I don't think it's needed.  I meant that `tests/conftest.py` will enable it.
https://github.com/chainer/chainer/blob/3a184c8da03e160904c061a6796c3e6ec896ee84/tests/chainermn_tests/functions_tests/test_pseudo_connect.py#L13-L17

**Comment by niboshi** [comment]
@toslunar 
No, it's disabled by default.

**Comment by niboshi** [comment]
@emcastillo
The error should be fixed by #8217.

**Comment by toslunar** [comment]
> @toslunar
> No, it's disabled by default.

I see.  Could you fix `step_chainer_tests`, too?

**Comment by niboshi** [comment]
@toslunar 

>I see.  Could you fix `step_chainer_tests`, too?

Hm, do we need that?
Currently (only `chainerx_tests`) Travis takes 44 minutes, which has enough margin of 6 minutes.

Also if it were applied to `chainer_tests`, we wouldn't be able to test #8216.

**Comment by toslunar** [comment]
48 min 41 sec with macOS https://travis-ci.org/chainer/chainer/builds/592878722 where pairwise testing is applied to `chainer` and `chainerx`.  How about fixing #8073 first?

**Comment by niboshi** [comment]
@toslunar I see. That sounds good.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
