### PR TITLE
Improve `get_variable` performance

### PR DESCRIPTION
**Pull request by okuta**
`get_variable` is called many times.

### CODE REVIEW

**Comment by niboshi** [comment]
Please fix flake8 error:
```
/home/travis/build/chainer/chainer/chainer/variable.py:545:80: E501 line too long (80 > 79 characters)
```

**Comment by okuta** [comment]
I fixed.
jenkins, test this please.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
