### PR TITLE
Fix Caffe exporter to export eps of BatchNormalization layer

### LINKED ISSUE #4858: [chainer.exporters.caffe] Export eps param of BatchNormalization
I met a problem for exporting caffe model.
exporters.caffe don't export eps param of BatchNormalization. 
Chainer sets eps param to 2e-5 by default. however, Caffe sets eps param to 1e-5 by default.
The output value becomes very different in the regression task.

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes #4858.
I also improved tests to compare results between original link and re-imported link.

~Blocked by #4875.~(merged)

### CODE REVIEW

**Comment by kmaehashi** [comment]
Rebased to master.

**Comment by kmaehashi** [comment]
Rebased to master.

**Comment by okuta** [comment]
Thanks!

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
