### PR TITLE
fix F.convolution_2d and F.deconvolution_2d to work without cuDNN

### PR DESCRIPTION
**Pull request by kmaehashi**
Without cuDNN, `_cudnn_version` is undefined.
Related to #3494.

### CODE REVIEW

**Comment by niboshi** [comment]
I think you can define it with a single expression.

```
            use_cudnn = (
                chainer.should_use_cudnn('>=auto')
                and not self.cover_all
                and x.dtype == W.dtype
                and ((self.dy == 1 and self.dx == 1) or _cudnn_version >= 6000)
                and (self.group <= 0 or _cudnn_version >= 7000)
            )
````

(also it's better to split `x.dtype == W.dtype` in a separate line.)

**Comment by kmaehashi** [comment]
@niboshi Thanks! Fixed as suggested.

**Comment by kmaehashi** [comment]
Please merge this after #4078.

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by takagi** [comment]
Now #4078 is merged.

**Comment by kmaehashi** [comment]
Rebased.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
