### PR TITLE
Add missing doc entry for `CommunicatorBase.allgather`

### PR DESCRIPTION
**Pull request by beam2d**
I found that the method exists but the doc is missing.

### CODE REVIEW

**Comment by keisukefukuda** [comment]
Should it be backported to 6.x ?

**Comment by keisukefukuda** [comment]
Jenkins, test this please.

**Comment by beam2d** [comment]
I want it to be backported.

**Comment by keisukefukuda** [comment]
LGTM.
The failed test is not related to the PR. I will merge it.

**Pull request merged**
