### PR TITLE
Simplify batch normalization with cuDNN

### PR DESCRIPTION
**Pull request by okuta**
Please merge cupy/cupy#1737 first.

### CODE REVIEW

**Comment by takagi** [comment]
Would you resolve the conflict?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
Would you resolve the conflict?

**Comment by okuta** [comment]
@takagi I fixed.

**Comment by okuta** [comment]
I fixed.
jenkins, test this please.

**Comment by takagi** [comment]
Would you check another Travis failure on flake8?

**Comment by takagi** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Pull request merged**
