### PR TITLE
[backport] Raise an error when CUDA has been initialized before MultiprocessParallelUpdater is initialized

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #4717

### CODE REVIEW

**Comment by kmaehashi** [comment]
@mitmul Could you take a look on this backport?

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
By the way, is this a bugfix?

**Comment by niboshi** [comment]
Jenkins test has failed at ` <chainer_tests.training_tests.updaters_tests.test_multiprocess_parallel_updater.TestRawArray testMethod=test_update_uses_raw_array>`.

**Comment by kmaehashi** [comment]
https://github.com/chainer/chainer/pull/4801 needs to be merged first.

**Comment by kmaehashi** [comment]
> By the way, is this a bugfix?

I think it's not a bug. Relabeled to enhancement.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
