### PR TITLE
Improve docs of separate, select_item, and permutate

### PR DESCRIPTION
**Pull request by naoto0804**
This is PR for improving docs of functions/links. Related issue: #2182
Modified functions/links:
- chainer/functions/array/separate.py
- chainer/functions/array/select_item.py
- chainer/functions/array/permutate.py

### CODE REVIEW

**Comment by naoto0804** [comment]
select_item
separate
permutate

**Comment by naoto0804** [comment]
How can I avoid timeout in appveyor?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
