### PR TITLE
Fix warning filter for protobuf

### PR DESCRIPTION
**Pull request by toslunar**
This PR tries to address #7433.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The failures look unrelated to the PR.
```
FAIL repo/tests/chainerx_tests/unit_tests/routines_tests/test_trigonometric_hyperbolic.py::test_Arcsin_param_203_{contiguous='C', in_dtypes=('float64',), out_dtype='float64', input=-0.9, shape=(2, 3)}[cuda:0]
FAIL ../../repo/tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py::TestDecorrelatedBatchNormalization_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_24_{contiguous=None, dtype=float32, eps=2e-05, groups=1, n_channels=8, ndim=1}::test_forward
```

**Comment by emcastillo** [comment]
@toslunar should we backport?

**Comment by toslunar** [comment]
> @toslunar should we backport?

Yes.

**Pull request merged**
