### PR TITLE
Support unretained `Variable`s in `_check_grad_type`

### LINKED ISSUE #5608: Gradient dtype mismatch not detected if input array is not retained
Version: current master b9e9267237d60b76211f42d13f80938d1b926e74

### Code to reproduce
```py
import chainer
from chainer import functions as F
import numpy

dtype = numpy.float32
grad_dtype = numpy.float64
shape = (2, 3)

class Func(chainer.FunctionNode):
    def forward(self, xs):
        self.retain_inputs((0,))  # (!) Remove this line to make dtype mismatch undetected

        y = numpy.ones(shape, dtype)
        return y,

    def backward(self, input_indexes, grad_outputs):
        gy, = grad_outputs
        gx = F.cast(gy, grad_dtype)  # This line intentionally causes dtype mismatch
        return gx,

x_arr = numpy.ones(shape, dtype)
x = chainer.Variable(x_arr)

y, = Func().apply((x,))
y.grad = numpy.ones(shape, dtype)

y.backward()
```

### Result
If `(!)` line exists, gradient dtype mismatch is detected as expected:
```
Traceback (most recent call last):
  File "/home/niboshi/t/invalid-grad.py", line 27, in <module>
    y.backward()
  File "/data2/work/w/repos/chainer/chainer/variable.py", line 963, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/data2/work/w/repos/chainer/chainer/variable.py", line 1056, in _backward_main
    _check_grad_type(func, x, gx_elem.array)
  File "/data2/work/w/repos/chainer/chainer/variable.py", line 55, in _check_grad_type
    raise typ(detail + msg)
TypeError: Function `<property object at 0x7f0f29ac24f8>` (Func) has a bug.

Please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/chainer/chainer/issues/new.
Dtype of data and grad mismatch
grad: float64 != data: float32
```

### Result (no retain)
If `(!)` line is removed, the mismatch is not detected.
```
(no output)
```

### Related discussion on Slack
* https://chainer.slack.com/archives/C5P26TUR1/p1541049638005300

### PR DESCRIPTION
**Pull request by toslunar**
Close #5608.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Merge #5727 first.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
LGTM!

**Comment by takagi** [comment]
I'd like to leave this PR not backported to v5 because they contain some divergence on introducing ChainerX.

**Comment by toslunar** [comment]
Could you backport `master...21aea36`?

**Comment by takagi** [comment]
Sure!

**Comment by takagi** [comment]
I've made backport `master...7e2d137` since `21aea36` is also a merging commit.

**Pull request merged**
