### PR TITLE
Fix comparison with casting in hdf5 serializer test

### LINKED ISSUE #8181: flaky: `chainer_tests/serializers_tests/test_hdf5.py::TestHDF5Deserializer::test_deserialize_different_dtype_cpu`
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2114/TEST=chainer-py2,label=mn1-p100/console

`18:57:22 FAIL tests/chainer_tests/serializers_tests/test_hdf5.py::TestHDF5Deserializer::test_deserialize_different_dtype_cpu`

```
18:57:21 E                   AssertionError: 
18:57:21 E                   Arrays are not equal
18:57:21 E                   
18:57:21 E                   (mismatch 16.6666666667%)
18:57:21 E                    x: array([[ 0.272705, -0.590332,  0.962891],
18:57:21 E                          [-0.482178, -0.544922, -0.029999]], dtype=float16)
18:57:21 E                    y: array([[ 0.272705, -0.590332,  0.962891],
18:57:21 E                          [-0.481934, -0.544922, -0.029999]], dtype=float16)
```

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #8181 

Succeeded 100,000 times without a failure.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Py2 compat error detected.
Should we fix it until jenkins support can be dropped?

**Comment by niboshi** [comment]
@emcastillo This needs to be backported. I fixed the error.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Another related failure 😥

**Comment by niboshi** [comment]
`six.BytesIO` does not work in Python 2 for some reason.
I replaced with `tempfile.TemporaryFile` and it's fixed.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
