### PR TITLE
[backport] Print installed packages in pytest

### PR DESCRIPTION
**Pull request by takagi**
Backport of #8348

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
As #8211 is not backported and #8348 causes conflict to backport, I've manually implemented tests/conftest.py here.

**Comment by takagi** [comment]
I've added importing `print_function` for v6 series' Python 2 support.

**Comment by niboshi** [comment]
Oh, `flush` option was only introduced in Python 3.3.
I think it has to be rewritten using `sys.stdout.write()`/`flush()`?

**Comment by takagi** [comment]
Sure, I'll fix it!

**Comment by takagi** [comment]
Fixed, PTAL!

**Comment by niboshi** [comment]
LGTM

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request merged**
