### PR TITLE
Add SELU activation function

### PR DESCRIPTION
**Pull request by iwiwi**
This PR adds the SELU activation function, proposed in https://arxiv.org/abs/1706.02515. This is asked by @beam2d -san and Crissman-san.

### CODE REVIEW

**Comment by beam2d** [comment]
From the next time, could you make a PR from a fork instead of the main repository of chainer organization? Thanks!

**Comment by iwiwi** [comment]
Thanks for reviewing. I reflected the comment. Also, I will submit PRs from a fork repository from the next time.

FYI: I was advised to make PRs from a branch in the main repository by @unnonouno -san, as it can automatically invoke Jenkins tests. (Did you change the policy?)

**Comment by beam2d** [comment]
LGTM.

# Yes, we have changed our internal policy recently because we have started using "versioned branches" for stable versions which should be easy to find. We will basically not use branches of the central repository for our development to keep the list of branches clean and easy to explore (whereas the cleaning up is still on-going). PRs from organization members are automatically tested by our CI.

**Comment by iwiwi** [comment]
Got it, thanks!

**Comment by beam2d** [comment]
Jenkins, test this please

**Comment by beam2d** [comment]
Thank you!

**Pull request merged**
