### PR TITLE
Fix F632 (use ==/!= to compare str)

### LINKED ISSUE #6343: flake8 warns F632 (use ==/!= to compare str)
```
chainer/variable.py:1781:16: F632 use ==/!= to compare str, bytes, and int literals
chainer/variable.py:1783:18: F632 use ==/!= to compare str, bytes, and int literals
chainer/functions/math/sparse_matmul.py:27:12: F632 use ==/!= to compare str, bytes, and int literals
chainer/functions/math/sparse_matmul.py:29:14: F632 use ==/!= to compare str, bytes, and int literals
chainer/functions/math/sparse_matmul.py:102:8: F632 use ==/!= to compare str, bytes, and int literals
tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py:678:44: F632 use ==/!= to compare str, bytes, and int literals
```

### PR DESCRIPTION
**Pull request by toslunar**
Close #6343.

### CODE REVIEW

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
It seems other dependencies must be adjusted altogether.

```
+flake8 --version
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/flake8/plugins/manager.py", line 163, in load_plugin
    self._load()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/flake8/plugins/manager.py", line 140, in _load
    self._plugin = self.entry_point.load()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/entrypoints.py", line 86, in load
    obj = getattr(obj, attr)
AttributeError: module 'pycodestyle' has no attribute 'maximum_doc_length'
```

**Comment by kmaehashi** [comment]
imosCI, test this please.

**Comment by toslunar** [comment]
I checked the dependencies.  Excerpts from an output of `pipdeptree`:
```
autopep8==1.4.3
  - pycodestyle [required: >=2.4.0, installed: 2.5.0]
```
```
flake8==3.7.7
  - entrypoints [required: >=0.3.0,<0.4.0, installed: 0.3]
  - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
  - pycodestyle [required: >=2.5.0,<2.6.0, installed: 2.5.0]
  - pyflakes [required: >=2.1.0,<2.2.0, installed: 2.1.1]
```

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
