### PR TITLE
Use `LinkTestCase` for `L.GroupNormalization`

### LINKED ISSUE #6911: `test_group_normalization` is flaky
This is part of https://github.com/chainer/chainer/issues/6903 effort.

- Failure example: https://ci.preferred.jp/chainer.py27and35/2138/
- Failure test case: `GroupNormalizationTest_param_8_{dtype=float32, shape=(3, 8), groups=4}.test_backward_gpu_without_cudnn`
- Tolerance:
```
E   Not equal to tolerance rtol=0.01, atol=0.001
E   
E   Mismatch: 100%
E   Max absolute difference: 0.15960103
E   Max relative difference: 0.0476208
```

### PR DESCRIPTION
**Pull request by toslunar**
It seems `chainer.testing.LinkTestCase` supports backprop test with higher-prec `dtype` by overwriting parameters.  Use it and close #6911.

### CODE REVIEW

**Comment by toslunar** [comment]
It succeeded with `repeat(2000)`.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Oh, overlooked travis failure. Please fix it.
```
[2019-10-30 07:58:43] /home/travis/build/chainer/chainer/tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py:7:1: F401 'chainer.gradient_check' imported but unused
```

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request merged**
