### PR TITLE
Fix broken imagenet example

### LINKED ISSUE #5631: ChainerMN's ImageNet example is broken because of update in pickle module
* Conditions

  - Chainer >= 5.0.0

* Code to reproduce
The ImageNet example on Python >= 3.6

```
import multiprocessing
p = multiprocessing.Process(target=lambda *x: x, args=())
p.start()
```

* Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/home/kfukuda/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fb633f35e18>: attribute lookup <lambda> on __main__ failed
```
For details, see https://docs.python.org/3.6/library/pickle.html

```
The following types can be pickled:

* None, True, and False
* integers, floating point numbers, complex numbers
* strings, bytes, bytearrays
* tuples, lists, sets, and dictionaries containing only picklable objects
* functions defined at the top level of a module (using def, not lambda)
* built-in functions defined at the top level of a module
* classes that are defined at the top level of a module
* instances of such classes whose __dict__ or the result of calling __getstate__() is picklable (see section Pickling Class Instances for details).
```

Thus lambda is not pickable.

### PR DESCRIPTION
**Pull request by keisukefukuda**
This PR fixes #5631 by rewriting a dummy function from a lambda to an explicitly defined local function.

### CODE REVIEW

**Comment by keisukefukuda** [comment]
Jenkins, test please.

**Comment by keisukefukuda** [comment]
Jenkins, test this please

**Comment by shu65** [comment]
A dummy function is not used in ChinaerCV example.
https://github.com/chainer/chainercv/blob/3726368c49b5d9476eafdc3081d8cf7db607e06e/examples/classification/train_imagenet_multi.py#L89

We may not need the dummy function.

**Comment by shu65** [comment]
Jenkins, test this please

**Comment by shu65** [comment]
I confirmed that the unittests for chainermn were passed

**Pull request merged**
