### PR TITLE
Switch current directory in Jenkins tests

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by niboshi** [comment]
Please point the basis of this fix.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
As the commit message says, it'll fix an error in setting up conda in docker.
```
17:42:22 + docker build -t image1 --build-arg WORKSPACE_DIR=/workspace --build-arg WORK_DIR=/workspace/work --build-arg CONDA_DIR=/workspace/conda /tmp/tmp.sMfEaynh7a
```
...
```
17:42:23 Step 20/21 : RUN bash "$TEMP_DIR"/setup-conda.sh "$USER_TEMP_DIR"/conda "$CONDA_DIR"
```
...
```
17:42:42 Preparing transaction: ...working... done
17:42:43 Executing transaction: ...working... WARNING conda.core.envs_manager:register_env(46): Unable to register environment. Path not writable or missing.
17:42:44   environment location: /workspace/conda
17:42:44   registry file: /home/testuser/.conda/environments.txt
17:42:44 done
17:42:44 installation finished.
17:42:44 + bin_dir=/workspace/conda/bin
17:42:44 + /workspace/conda/bin/conda config --set changeps1 no
17:42:44 + /workspace/conda/bin/conda update -y -q conda
17:42:44 Collecting package metadata (current_repodata.json): ...working... done
17:42:46 Solving environment: ...working... done
17:42:47 
17:42:47 ## Package Plan ##
17:42:47 
17:42:47   environment location: /workspace/conda
17:42:47 
17:42:47   added / updated specs:
17:42:47     - conda
17:42:47 
17:42:47 
17:42:47 The following packages will be downloaded:
17:42:47 
17:42:47     package                    |            build
17:42:47     ---------------------------|-----------------
17:42:47     certifi-2019.6.16          |           py37_1         156 KB
17:42:47     chardet-3.0.4              |        py37_1003         173 KB
17:42:47     ------------------------------------------------------------
17:42:47                                            Total:         329 KB
17:42:47 
17:42:47 The following packages will be UPDATED:
17:42:47 
17:42:47   certifi                                  2019.6.16-py37_0 --> 2019.6.16-py37_1
17:42:47   chardet                                      3.0.4-py37_1 --> 3.0.4-py37_1003
17:42:47 
17:42:47 
17:42:47 Preparing transaction: ...working... done
17:42:47 Verifying transaction: ...working... done
17:42:47 Executing transaction: ...working... done
17:42:47 + /workspace/conda/bin/conda create -y -q --name testenv python=3.6 pip
17:42:47 Collecting package metadata (current_repodata.json): ...working... done
17:42:47 Solving environment: ...working... done
17:42:53 
17:42:53 [Errno 13] Permission denied: '/.cph_tmpvcwkmshg'
17:42:53 [Errno 13] Permission denied: '/.cph_tmpqm03zzdk'
17:42:53 [Errno 13] Permission denied: '/.cph_tmpuqjhnma5'
```
(taken from https://jenkins.preferred.jp/job/chainer/job/chainer_pr/TEST=CHAINERX_chainerx-c,label=mn1-p100/1705/console)

**Comment by toslunar** [comment]
The Jenkins failures
```
FAIL ../../../repo/tests/chainerx_tests/unit_tests/routines_tests/test_creation.py::test_TrilTriu_param_5_{k=1, shape=(2, 3, 4)}[float16-cuda:0]
```
and #7741 are unrelated to the PR.

**Pull request merged**
