### PR TITLE
Fix test of multiprocess_parallel_updater

### PR DESCRIPTION
**Pull request by niboshi**
`test_multiprocess_parallel_updater` does not specify appropriate test marks.

### CODE REVIEW

**Comment by okuta** [comment]
Thank you for your fixing.
I will check this.

**Comment by kmaehashi** [comment]
I think it is better to place the code string as a separate file, so that flake8 can be applied. (as long as there're no side effects)

**Comment by niboshi** [comment]
I agree, but we need a uniform convention to place such files.
e.g.
* What's the directory name / file name convention?
* What if .PNG files are required instead of .py files?

I think it's better to postpone to another issue.

**Comment by kmaehashi** [comment]
We already have `*.png` in https://github.com/chainer/chainer/tree/master/tests/chainer_tests/datasets_tests/image_dataset, but I think it's OK to do that in separate PR anyway.

**Comment by niboshi** [comment]
Oh, I see...
Then we can follow that in some way.
Anyway I'd like to seperate that in another PR, because it's essentially different topic (and the change is not trivial).

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM. I will merge soon.

**Pull request merged**
