### PR TITLE
Bug Fix: "copy" => "__deepcopy__" in ChainerMN "batch_normalization" & replace "to_gpu"

### PR DESCRIPTION
**Pull request by belldandyxtq**
This PR contains two fixes for ChainerMN to pass the CI tests.
1. A bug fix in the `batch_normalization`, from `copy` to use `__deepcopy__` to match the behavior of `chainer`.
2. Replace all the deprecated `to_gpu` to `to_device` in all the tests

### CODE REVIEW

**Comment by keisukefukuda** [comment]
pfnci, test please.

**Comment by keisukefukuda** [comment]
pfnci, test this please

**Comment by keisukefukuda** [comment]
The Jenkins error is not relevant to the PR.

**Comment by keisukefukuda** [comment]
@belldandyxtq Coudl you check the Python style check error?
```
[2019-09-27 10:05:08] /home/travis/build/chainer/chainer/tests/chainermn_tests/links_tests/test_multi_node_chain_list.py:2:1: F401 'chainer.backends.cuda' imported but unused
```

**Comment by belldandyxtq** [comment]
pfnci, test this please

**Comment by keisukefukuda** [comment]
LGTM

**Pull request merged**
