### PR TITLE
Relax tolerances in convolution nd function test

### PR DESCRIPTION
**Pull request by hvy**
Tried relaxing tolerances for failing py2 tests. I have however not verified this fail rate locally since I couldn't reproduce it.

### CODE REVIEW

**Comment by beam2d** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Let me rerun the test since one of them still failed.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Conv nd passed it seems.

**Comment by beam2d** [comment]
LGTM

**Pull request merged**
