### PR TITLE
Avoid unload module call in PureNcclCommunicator

### PR DESCRIPTION
**Pull request by okuta**
This is performance improvement PR.
`chainer.cuda.cupy.ElementwiseKernel` creates a function module for each function call.
`cuModuleLoadData` and `cuModule Unload` functions are blocking API call.

### CODE REVIEW

**Comment by keisukefukuda** [comment]
pfnci, test this please

**Comment by okuta** [comment]
pfnci, test this please

**Comment by okuta** [comment]
The test has failed for reasons unrelated to this PR.

**Comment by shu65** [comment]
Thank you for the PR. The PR has a bug with double buffering. 
I will new PR to fix it.

**Pull request closed without merging**
