### PR TITLE
Support ChainerX in POS-tagging example

### PR DESCRIPTION
**Pull request by hvy**
Part of https://github.com/chainer/chainer/issues/6661.

~It is incredibly slow with `'cuda:0'`, mostly because of `links.CRF1d`.~ With Debug build...

### CODE REVIEW

**Comment by hvy** [comment]
pos-tagging-prof

**Comment by hvy** [comment]
[forward_chainerx:371 (MulConstant.forward_chainerx)](https://github.com/chainer/chainer/blob/master/chainer/functions/math/basic_math.py#L371)

**Comment by hvy** [comment]
Sorted by "inclusive/cumulative" time.

pos-tagging-prof-incl

**Comment by hvy** [comment]
Need to investigate the slow training but in a separate issue/PR.

**Comment by hvy** [comment]
Sorry it used to be extremely slow (30-40 times slower) but I was actually running the ChainerX debug build. The release build is slow as well but not to the same extent (about 40% slower).

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
