### PR TITLE
Explain corresponding `Link`s

### PR DESCRIPTION
**Pull request by toslunar**
This PR explains hyperlinks from functions to their corresponding links.

I'd rather not warn as #6509.

### CODE REVIEW

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Oops. Wrong PR. This one not ready to test. 😅

**Comment by Crissman** [comment]
@toslunar Status?

**Comment by toslunar** [comment]
@Crissman 

- I'd like to fix docs of `connection` functions like this.
- As we discussed #6509, `activation` functions like `F.prelu` could be warned.

If it looks good to you, I'll edit the other files.

**Comment by Crissman** [comment]
Looks good. Please go ahead for the other files.

**Comment by Crissman** [comment]
@toslunar, should I merge this separately, or would you like to add the other files?

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins and Travis errors look unrelated.

**Comment by niboshi** [comment]
Shouldn't we make a backport?

**Pull request merged**
