### PR TITLE
Add BestValueTrigger to the document

### PR DESCRIPTION
**Pull request by beam2d**
`BestValueTrigger` was missing from the reference manual, so I added it.

### CODE REVIEW

**Comment by mitmul** [comment]
LGTM

**Comment by niboshi** [comment]
Please rebase master.
It has no conflict, but you should write in the new format using `autosummary`.

**Comment by mitmul** [comment]
@niboshi Fixed. Could you merge this?

**Comment by niboshi** [comment]
@mitmul OK

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
