### PR TITLE
Support for fp16 and mixed16 in `MultiNodeBatchNormalization` of ChainerMN

### PR DESCRIPTION
**Pull request by shu65**
This PR adds support for fp16 and mixed16 in `MultiNodeBatchNormalization` of ChainerMN.
Solved https://github.com/chainer/chainer/issues/6198 and https://github.com/chainer/chainer/issues/6457
Related to https://github.com/chainer/chainer/pull/6331

### CODE REVIEW

**Comment by shu65** [comment]
Jenkins, test this please.

**Comment by shu65** [comment]
Jenkins failure is unrelated.

**Comment by keisukefukuda** [comment]
Jenkins, test this please.

**Comment by keisukefukuda** [comment]
LGTM. will merge soon. :+1:

**Pull request merged**
