### PR TITLE
Update URL of PTB dataset

### PR DESCRIPTION
**Pull request by toslunar**
Docstrings can contain long URLs.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
How about changing the link to https://catalog.ldc.upenn.edu/LDC99T42?

**Comment by niboshi** [comment]
By the way, I like the commit message.

**Comment by kmaehashi** [comment]
> How about changing the link to https://catalog.ldc.upenn.edu/LDC99T42?

I think this URL is better.

**Comment by kmaehashi** [comment]
Thanks!
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
