### PR TITLE
Simplify scalar handling in `basic_math`

### PR DESCRIPTION
**Pull request by niboshi**
* Removed unnecessary preprocessing
* Use `math.log` in preference to `numpy.log` (`math` is faster)
* ~~Changed class names~~

### CODE REVIEW

**Comment by toslunar** [comment]
> Use math.log in preference to numpy.log (math is faster)

I confirmed:
```
In [8]: dtype
Out[8]: dtype('float32')

In [10]: %timeit np.log(2.0, dtype=dtype)
1.29 µs ± 17.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [12]: %timeit dtype.type(math.log(2.0))
451 ns ± 13.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by toslunar** [comment]
Please explain why you want to change the name of `FunctionNode`s.

- The names `*Const` were clearer than `*Scalar` in that the `FunctionNode`s don't take the corresponding operands.
- Prefixing `_` to the names is acceptable because they have `label` attributes.  (Otherwise I'd rather not.)

**Comment by niboshi** [comment]
I reverted class renames.

>- The names `*Const` were clearer than `*Scalar` in that the `FunctionNode`s don't take the corresponding operands.

I thought the opposite. These `FunctionNode`s takes only scalars, not other constants (ndarrays).

**Comment by niboshi** [comment]
If I can't rename the classes, can I rename `self.value` as `self.scalar`? It took me a while to understand they're actually scalars.

**Comment by okuta** [comment]
Please rebase this because I merged #5439 .

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
