### PR TITLE
Use stable CuPy v7 in ONNX test

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
The test passed.

**Comment by kmaehashi** [comment]
The error in the previous commit was due to API change issue between CUDA 10.1 / CUDA 10.1 Update 2.  @disktnk's image was using CUDA 10.1 so I recreated the image with exactly the same Dockerfile (but this time, the base image has been updated to CUDA 10.1 Update 2) and published it to Dockerhub.

**Pull request merged**
