### PR TITLE
Simplify `F.spatial_transformer_grid` test

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies `test_spatial_transformer_grid` using `testing.FunctionTestCase`
Solves part of issue #6071

### CODE REVIEW

**Comment by Crissman** [comment]
LTGM. Jenkins, test this please.

**Comment by Crissman** [comment]
Jenkins, test this please.

**Comment by Crissman** [comment]
Retesting. Jenkins, test this please.

**Comment by Crissman** [comment]
Not sure what the issue is. The simplified test ran ok on my local machine, but PFN CI is having issues with the tests. Please take a look at the error messages.

**Comment by Crissman** [comment]
Retesting. Jenkins, test this please.

**Comment by Crissman** [comment]
@ishanrai05 Can you look at these errors?

**Comment by ishanrai05** [comment]
@Crissman  I am getting an error 404 not found page when I try to look at jenkins tests results

**Comment by Crissman** [comment]
Ok. Let's retest. Jenkins, test this please.

**Comment by Crissman** [comment]
Retest. Jenkins, test this please.

**Pull request closed without merging**
