### PR TITLE
Add virtual destructor in CUDA `Allocator`

### PR DESCRIPTION
**Pull request by niboshi**
It's a virtual base class. Should have one.

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Comment by niboshi** [comment]
```
14:40:03 /repo/chainerx_cc/chainerx/cuda/memory_pool.h:44:7: error: class 'Allocator' defines a default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions,-warnings-as-errors]
14:40:03 class Allocator {
14:40:03       ^
```

`cppcoreguidelines-special-member-functions`:  https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html

How about setting `AllowSoleDefaultDtor = 1`?

**Comment by hvy** [comment]
It's not a strong opinion but I think it'd be cleaner to just define the remaining methods as we do in other abstract classes. I don't think this verbosity hurts.

**Comment by niboshi** [comment]
Added explicit definitions following the above comment, and [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types)

>Due to the risk of slicing, prefer to avoid providing a public assignment operator or copy/move constructor for a class that's intended to be derived from (and prefer to avoid deriving from a class with such members). If your base class needs to be copyable, provide a public virtual Clone() method, and a protected copy constructor that derived classes can use to implement it.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
