### PR TITLE
Simplify  `F.resize_image` test.

### PR DESCRIPTION
**Pull request by ishanrai05**
Simplifies `test_resize_image` using `testing.FunctionTestCase`

Solves part of issue #6071

### CODE REVIEW

**Comment by Crissman** [comment]
Passed tests reduced with this simplification from 20 tests to 12. Are there some important tests that are not covered by the rewrite?

**Comment by ishanrai05** [comment]
@Crissman, I checked all the individual tests rewrite. All seem to be working. 
On my system the passed test have increased for all the rewrites.
|Test |tests passed before rewrite |tests passed after rewrite
|---------------------------------------------------- |----|----|
| TestResizeImagesForwardIdentity        | 4  | 18 |
| TestResizeImagesForwardDownScale  | 9  | 2  |
| TestResizeImagesForwardUpScale      | 9  | 2  |
| TestResizeImagesBackward                 | 16 | 16 |

**Comment by ishanrai05** [comment]
@Crissman  Can you please review this again?

**Comment by Crissman** [comment]
You're correct. Tests increased.

Jenkins, test this please.

**Pull request merged**
