### PR TITLE
Adjust convolution_nd testing tolerance.

### PR DESCRIPTION
**Pull request by takagi**
Adjusting tolerance of backward test of `convolution_nd`.

### CODE REVIEW

**Comment by hvy** [comment]
Thank you for the fix. I ran the test locally but it seems like `test_backward_gpu_nobias` occasionally fails.

**Comment by takagi** [comment]
hum... would you tell the reasonable tolerance on your local?

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
I reran all tests with 10k repetitions and they all passed. I'll merge this PR after the test passes!

**Comment by hvy** [comment]
jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
