### PR TITLE
[chainerx] add `isfinite`

### PR DESCRIPTION
**Pull request by kshitij12345**
References : #6423

### CODE REVIEW

**Comment by hvy** [comment]
I'm wondering if we should skip introducing the `numeric.{h,cuh}` `IsFinite` since we can reuse existing ones in the kernels. There should be no difference in performance and it's less to maintain. What do you say?

**Comment by hvy** [comment]
It otherwise LGTM.

**Comment by kshitij12345** [comment]
> I'm wondering if we should skip introducing the `numeric.{h,cuh}` `IsFinite` since we can reuse existing ones in the kernels. There should be no difference in performance and it's less to maintain. What do you say?

My reasoning was that generally these functions have their peculiarities so I feel that it is safer to wrap library implementations. But if you feel that, it would be better to use existing ones then I will remove the definitions in `numeric`.

**Comment by hvy** [comment]
Thanks for the quick response. Do you have any concrete cases where either would behave unexpectedly? Wrapping is more robust to future changes but as for now, both approaches are basically logically identical.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by kshitij12345** [comment]
> Do you have any concrete cases where either would behave unexpectedly? Wrapping is more robust to future changes but as for now, both approaches are basically logically identical.

I guess, `isfinite` is not as hairy , I don't think there are any cases that this would misbehave.

**Comment by kshitij12345** [comment]
Do let me know, if anything is remaining. I tried to find is `isfinite` in `chainer.functions` but couldn't find it, so I assume we don't need to overload this one.

**Comment by hvy** [comment]
Then it LGTM 👍

**Pull request merged**
