### PR TITLE
add create_mnbn_model

### PR DESCRIPTION
**Pull request by shu65**
This PR adds function to replace BatchNorm by MultiNodeBatchNorm.

Solve https://github.com/chainer/chainer/issues/5786

### CODE REVIEW

**Comment by kuenishi** [comment]
imosCI, test this please.

**Comment by kuenishi** [comment]
Jenkins, test this please.

**Comment by shu65** [comment]
Jenkins, test this please.

**Comment by kuenishi** [comment]
Jenkins, test this please.

**Pull request merged**
