### PR TITLE
Use `enable_convert` in `StandardUpdater`

### PR DESCRIPTION
**Pull request by Hakuyume**
merge after #7599

### CODE REVIEW

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
reopen

**Comment by niboshi** [comment]
We're no longer merging feature PRs.
Let me close the PR.

**Pull request closed without merging**
