### PR TITLE
Refactor CUDA batch norm tensor descriptor

### PR DESCRIPTION
**Pull request by niboshi**
I feel `CudnnBNTensorDescriptor` was a bit obscure.
This PR makes it apparent that it's a "derived tensor descriptor".

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Sorry could you fix the conflicts?

**Comment by niboshi** [comment]
Resolved.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Hm, seems completely irrelevant it a test segfaulted 🤔 https://jenkins.preferred.jp/job/chainer/job/chainer_pr/267/TEST=chainer-py35,label=mn1-p100/console

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
