### PR TITLE
Make ChainerX loss functions raise `DtypeError` when non-float inputs are given

### LINKED ISSUE #8104: Parameters `in_dtypes` and `out_dtype` are unused in `test_loss.py`
`LossBase.generate_inputs` should cast input arrays in `tests/chainerx_tests/unit_tests/routines_tests/test_loss.py`

### PR DESCRIPTION
**Pull request by asi1024**
Loss functions in `chainer.functions` require input arrays which are of the same dtype. This PR make also ChainerX follow this dtype rule.

### CODE REVIEW

**Comment by niboshi** [comment]
Do they have to raise error in such cases?
That seems reasonable in a deep learning context, but these functions can be used for other purposes.
For example, `AbsoluteError` could be used to calculate a hamming distance of two bit sequences consisting of 0 or 1 integers.

**Comment by hvy** [comment]
Is there some context behind this PR? I agree that these routines could be useful for non-float arrays and that we don't necessarily have to align with Chainer, but maybe I'm missing the point.

**Comment by niboshi** [comment]
If they raise error, I'd want to make a namespace for such functions, something like `chainerx::loss::AbsoluteError`, or `chainerx::nn::AbsoluteError`.

**Comment by asi1024** [comment]
Current `test_loss.py` looks to say that ChainerX loss functions behave like as Chainer's ones even if mixed dtype inputs are taken, but actually it is not checked well (issue #8104). So I created this PR.
Now I agree that ChainerX loss routines could be useful for non-float arrays, so should we add mixed dtype test to PR #8141?

**Comment by niboshi** [comment]
I think the option in my comment above could be worth considering as well.

>If they raise error, I'd want to make a namespace for such functions, something like `chainerx::loss::AbsoluteError`, or `chainerx::nn::AbsoluteError`.

**Comment by hvy** [comment]
Do you want to define two versions e.g. `chainerx::loss::AbsoluteError` and `chainerx::AbsoluteError`, or just the former or them? We have been very conservative with introducing new namespaces and introducing one sounds like a topic that needs further discussions in any case. How about creating a separate issue for that?

IMHO, given that we have untested dtypes, I think we should proceed with https://github.com/chainer/chainer/pull/8141 adding mixed dtypes as suggested by @asi1024 until that is settled.

**Comment by niboshi** [comment]
I meant moving all the loss functions to `chainerx::loss` or `chainerx::nn` namespace.

Yes that needs discussion, but shouldn't we do that before implementing mixed dtype tests (which could end up with waste of time)?

**Comment by hvy** [comment]
Discussed with @niboshi and @asi1024. The conclusion is that we'll close this PR keeping the existing behavior, allowing mixed dtypes in the loss routines. There are several motivation including the fact that we allow mixed dtypes in other routines and it'd not be obvious why loss functions would behave differently. We imagine that it'd e.g. be easer for users if dtype behavior don't differ unnecessarily between routines. The discussion also gave rise to ideas such as prohibiting non-floats in DL routines, maybe placing them in a different namespace, but that should be addressed separately.

**Pull request closed without merging**
